// [Vue] Website Source Code/src/views/basic-py-3ai.vue
<template>
  <div class="basic-py3ai-container">
    <div class="basic-py3ai-banner">
      <div class="basic-py3ai-main-content">
        <h1 class="basic-py3ai-heading">CONTROL STRUCTURE</h1>
        <div class="basic-py3ai-container1">
          <router-link to="/basic-py-3ai" class="basic-py3ai-navlink button">
            Selection Statement
          </router-link>
          <router-link to="/basic-py-3aii" class="basic-py3ai-navlink1 button">
            Two-way Selectors
          </router-link>
          <router-link to="/basic-py-3aiii" class="basic-py3ai-navlink2 button">
            Multiple-way Selectors
          </router-link>
        </div>
        <div class="basic-py3ai-container2">
          <router-link to="/basic-py-3bi" class="basic-py3ai-navlink3 button">
            Counter-Controlled Loops
          </router-link>
          <router-link to="/basic-py-3bii" class="basic-py3ai-navlink4 button">
            Logically-Controlled Loops
          </router-link>
        </div>
        <div class="basic-py3ai-content-here">
          <div class="basic-py3ai-column">
            <h1 class="basic-py3ai-text">
              <span>Selection Statements</span>
              <br />
            </h1>
            <span class="basic-py3ai-text03">
              <span>
                In Python, the selection statements, also known as
                <span v-html="rawuu3i"></span>
              </span>
              <span class="basic-py3ai-text05">decision control statements</span>
              <span>
                or
                <span v-html="rawfwss"></span>
              </span>
              <span class="basic-py3ai-text07">branching statements</span>
              <span>
                allow a program to test several conditions and execute
                instructions based on whether those conditions are True or False.
                There are two primary selection statements in Python which are
                ‘if’ and ‘elif’ (short for ‘else if’).
              </span>
              <br />
              <br />
              <span>There are two general categories:</span>
              <br />
            </span>
            <div class="basic-py3ai-container3">
              <span class="basic-py3ai-text13">
                <span class="basic-py3ai-text14">a) Two-way selectors</span>
                <br />
              </span>
              <span class="basic-py3ai-text16">
                <span class="basic-py3ai-text17">b) Multiple-way selectors</span>
                <br />
              </span>
            </div>
            <div class="basic-py3ai-container4">
              <span class="basic-py3ai-text19">
                <span>    - if</span>
                <br />
                <span>    - if-else</span>
                <br />
                <span>    - nested if</span>
                <br />
                <span>    - if-elif else</span>
                <br />
              </span>
              <span class="basic-py3ai-text28">
                <span>    - nested IF structure</span>
                <br />
                <span>    - nested SWITCH structure</span>
                <br />
                <span>       =&gt; dictionary mapping</span>
                <br />
                <span>       =&gt; class</span>
                <br />
              </span>
            </div>
          </div>
          <span class="basic-py3ai-text37">
            <span>
              -
              <span v-html="raw5p9l"></span>
            </span>
            <span class="basic-py3ai-text39">Noor Alia Alisa</span>
          </span>
        </div>
      </div>
    </div>
    <div class="basic-py3ai-reference">
      <h1 class="basic-py3ai-text40">References</h1>
      <span class="basic-py3ai-text41">
        <br class="basic-py3ai-text42" />
        <span class="basic-py3ai-text43">
          Switch Case in Python (Replacement)
        </span>
        <span class="basic-py3ai-text44">
          . (2017, October 29). GeeksforGeeks.
        </span>
        <br class="basic-py3ai-text45" />
        <span class="basic-py3ai-text46">
                 
          <span v-html="raw8vly"></span>
        </span>
        <a
          href="https://www.geeksforgeeks.org/switch-case-in-python-replacement/"
          target="_blank"
          rel="noreferrer noopener"
          class="basic-py3ai-link"
        >
          https://www.geeksforgeeks.org/switch-case-in-python-replacement/
        </a>
        <br />
      </span>
    </div>
    <footer class="basic-py3ai-footer">
      <div class="basic-py3ai-container5">
        <router-link to="/strace" class="basic-py3ai-navlink5">
          STRACE
        </router-link>
      </div>
      <span class="basic-py3ai-text48">
        &quot;Making System Calls Cool Again&quot;
      </span>
      <div class="basic-py3ai-icon-group">
        <svg viewBox="0 0 877.7142857142857 1024" class="basic-py3ai-icon">
          <path
            d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
          ></path>
        </svg>
      </div>
    </footer>
    <app-header></app-header>
  </div>
</template>

<script>
import AppHeader from '../components/header'

export default {
  name: 'BasicPy3ai',
  props: {},
  components: {
    AppHeader,
  },
  data() {
    return {
      rawuu3i: ' ',
      rawfwss: ' ',
      raw5p9l: ' ',
      raw8vly: ' ',
    }
  },
  metaInfo: {
    title: 'Strace | Basic Python',
    meta: [
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ],
  },
}
</script>

<style scoped>
.basic-py3ai-container {
  width: 100%;
  display: flex;
  overflow: auto;
  min-height: 100vh;
  align-items: center;
  flex-direction: column;
  justify-content: flex-start;
  background-color: #f5f5f5;
}
.basic-py3ai-banner {
  width: 100%;
  height: 275px;
  display: flex;
  transition: 0.3s;
  align-items: center;
  flex-direction: column;
  background-size: cover;
  justify-content: center;
  background-image: url('https://marketplace.canva.com/EAD2962NKnQ/2/0/1600w/canva-rainbow-gradient-pink-and-purple-virtual-background-_Tcjok-d9b4.jpg');
}

.basic-py3ai-main-content {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: flex-start;
  background-color: #ffffff;
}
.basic-py3ai-heading {
  color: #ff0000;
  font-size: 3rem;
  align-self: center;
  text-align: center;
}
.basic-py3ai-container1 {
  flex: 0 0 auto;
  width: 100%;
  height: 100px;
  display: flex;
  align-items: flex-start;
}
.basic-py3ai-navlink {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py3ai-navlink:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py3ai-navlink1 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py3ai-navlink1:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py3ai-navlink2 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py3ai-navlink2:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py3ai-container2 {
  flex: 0 0 auto;
  width: 100%;
  height: 100px;
  display: flex;
  align-items: flex-start;
}
.basic-py3ai-navlink3 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py3ai-navlink3:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py3ai-navlink4 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py3ai-navlink4:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py3ai-content-here {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.basic-py3ai-column {
  flex: 1;
  width: auto;
  height: auto;
  display: flex;
  flex-direction: column;
}
.basic-py3ai-text03 {
  text-align: justify;
}
.basic-py3ai-container3 {
  flex: 0 0 auto;
  width: 395px;
  height: 100px;
  display: flex;
  align-items: flex-start;
  padding-top: 20px;
  flex-direction: column;
}
.basic-py3ai-container4 {
  flex: 0 0 auto;
  width: 395px;
  height: 100px;
  display: flex;
  align-items: flex-start;
  padding-top: 20px;
  flex-direction: column;
}
.basic-py3ai-reference {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #ffffff;
}
.basic-py3ai-footer {
  width: 100%;
  display: flex;
  max-width: var(--dl-size-size-maxwidth);
  align-self: center;
  align-items: center;
  padding-top: var(--dl-space-space-twounits);
  padding-left: var(--dl-space-space-threeunits);
  padding-right: var(--dl-space-space-threeunits);
  padding-bottom: var(--dl-space-space-twounits);
  justify-content: space-between;
}
.basic-py3ai-container5 {
  flex: 0 0 auto;
  width: auto;
  height: auto;
  display: flex;
  align-items: space-between;
  flex-direction: column;
}
.basic-py3ai-navlink5 {
  font-weight: 700;
  text-decoration: none;
}
.basic-py3ai-icon {
  width: 24px;
  height: 24px;
}
@media(max-width: 1600px) {
  .basic-py3ai-container {
    background-color: #f7f7f7;
  }
  .basic-py3ai-banner {
    height: auto;
    align-items: center;
    background-size: cover;
    justify-content: flex-start;
    background-image: url("/external/bgportrait-1500w.jpg");
  }
  .basic-py3ai-main-content {
    flex: 1;
    width: 1300px;
    height: auto;
    box-shadow: 0px 0px 10px 0px #d3d2d6;
    align-items: flex-start;
    padding-top: 100px;
    flex-direction: column;
    justify-content: flex-start;
    background-color: #ffffff;
  }
  .basic-py3ai-heading {
    color: rgb(255, 255, 255);
    width: 1200px;
    height: auto;
    font-size: 64px;
    font-style: normal;
    margin-top: 40px;
    font-family: Montserrat;
    font-weight: 700;
    line-height: 1.15;
    padding-top: 40px;
    border-radius: var(--dl-radius-radius-radius4);
    margin-bottom: 20px;
    padding-bottom: 40px;
    background-size: cover;
    background-image: url("/external/bglandscape-1200w.jpg");
    background-position: right;
  }
  .basic-py3ai-container1 {
    width: 700px;
    height: auto;
    align-self: center;
    margin-left: 50px;
    padding-top: 20px;
    margin-right: 50px;
    padding-bottom: 10px;
    justify-content: center;
  }
  .basic-py3ai-navlink {
    color: #A068FF;
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py3ai-navlink1 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py3ai-navlink2 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py3ai-container2 {
    width: 800px;
    height: auto;
    align-self: center;
    margin-left: 50px;
    padding-top: 10px;
    margin-right: 50px;
    padding-bottom: 20px;
    justify-content: center;
  }
  .basic-py3ai-navlink3 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py3ai-navlink4 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py3ai-content-here {
    width: 1200px;
    height: auto;
    align-items: flex-end;
    margin-left: 50px;
    padding-top: 50px;
    margin-right: 50px;
    padding-bottom: 50px;
  }
  .basic-py3ai-column {
    flex: 1;
    width: 100%;
    height: auto;
    align-items: flex-start;
  }
  .basic-py3ai-text {
    font-size: 36px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
    padding-top: 0px;
    padding-left: 0px;
    padding-right: 0px;
    padding-bottom: 30px;
  }
  .basic-py3ai-text03 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
  }
  .basic-py3ai-text05 {
    font-weight: 700;
  }
  .basic-py3ai-text07 {
    font-weight: 700;
  }
  .basic-py3ai-container3 {
    width: 100%;
    height: auto;
    padding-top: 25px;
    flex-direction: row;
    justify-content: flex-start;
  }
  .basic-py3ai-text13 {
    width: auto;
    font-size: 24px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-right: 90px;
  }
  .basic-py3ai-text14 {
    font-weight: 700;
  }
  .basic-py3ai-text16 {
    font-size: 24px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
  }
  .basic-py3ai-text17 {
    font-weight: 700;
  }
  .basic-py3ai-container4 {
    width: 100%;
    height: auto;
    padding-top: 25px;
    flex-direction: row;
    justify-content: flex-start;
  }
  .basic-py3ai-text19 {
    width: auto;
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-left: 15px;
    padding-right: 225px;
  }
  .basic-py3ai-text28 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-left: 15px;
  }
  .basic-py3ai-text37 {
    font-size: 18px;
    font-style: normal;
    font-family: Inter;
    font-weight: 500;
    padding-top: 25px;
  }
  .basic-py3ai-text39 {
    font-style: italic;
  }
  .basic-py3ai-reference {
    width: 1600px;
    height: auto;
    align-self: center;
    box-shadow: 0px -1px 15px 0px #ebebeb;
    align-items: flex-start;
    padding-top: 50px;
    padding-left: 200px;
    padding-right: 200px;
    flex-direction: column;
    padding-bottom: 50px;
    justify-content: flex-start;
  }
  .basic-py3ai-text40 {
    font-size: 32px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
  }
  .basic-py3ai-text41 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.25;
  }
  .basic-py3ai-text42 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py3ai-text43 {
    font-size: 16px;
    font-style: italic;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py3ai-text44 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py3ai-text45 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py3ai-text46 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py3ai-link {
    color: var(--dl-color-primary-300);
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    text-decoration: underline;
  }
  .basic-py3ai-footer {
    justify-content: space-between;
  }
  .basic-py3ai-navlink5 {
    font-size: 16px;
    font-family: Montserrat;
    font-weight: 700;
    text-decoration: none;
  }
  .basic-py3ai-text48 {
    font-size: 16px;
    font-style: normal;
    font-family: Montserrat;
    font-weight: 500;
  }
  .basic-py3ai-icon {
    margin-left: 50px;
  }
}
@media(max-width: 1200px) {
  .basic-py3ai-heading {
    color: rgb(255, 255, 255);
  }
}
@media(max-width: 479px) {
  .basic-py3ai-footer {
    align-self: center;
  }
  .basic-py3ai-icon-group {
    display: none;
  }
}
</style>

// [Angular] Website Source Code/src/app/pages/basic-py-3ai/basic-py-3ai.component.ts
import { Component } from '@angular/core'
import { Title, Meta } from '@angular/platform-browser'

@Component({
  selector: 'basic-py3ai',
  templateUrl: 'basic-py-3ai.component.html',
  styleUrls: ['basic-py-3ai.component.css'],
})
export class BasicPy3ai {
  rawo0un: string = ' '
  rawefxi: string = ' '
  raw40r0: string = ' '
  rawo2ry: string = ' '
  constructor(private title: Title, private meta: Meta) {
    this.title.setTitle('Strace | Basic Python')
    this.meta.addTags([
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ])
  }
}

<div class="basic-py3ai-container">
  <div class="basic-py3ai-banner">
    <div class="basic-py3ai-main-content">
      <h1 class="basic-py3ai-heading">CONTROL STRUCTURE</h1>
      <div class="basic-py3ai-container1">
        <a routerLink="/basic-py-3ai" class="basic-py3ai-navlink button">
          Selection Statement
        </a>
        <a routerLink="/basic-py-3aii" class="basic-py3ai-navlink1 button">
          Two-way Selectors
        </a>
        <a routerLink="/basic-py-3aiii" class="basic-py3ai-navlink2 button">
          Multiple-way Selectors
        </a>
      </div>
      <div class="basic-py3ai-container2">
        <a routerLink="/basic-py-3bi" class="basic-py3ai-navlink3 button">
          Counter-Controlled Loops
        </a>
        <a routerLink="/basic-py-3bii" class="basic-py3ai-navlink4 button">
          Logically-Controlled Loops
        </a>
      </div>
      <div class="basic-py3ai-content-here">
        <div class="basic-py3ai-column">
          <h1 class="basic-py3ai-text">
            <span>Selection Statements</span>
            <br />
          </h1>
          <span class="basic-py3ai-text03">
            <span>
              In Python, the selection statements, also known as
              <span [innerHTML]="rawo0un"></span>
            </span>
            <span class="basic-py3ai-text05">decision control statements</span>
            <span>
              or
              <span [innerHTML]="rawefxi"></span>
            </span>
            <span class="basic-py3ai-text07">branching statements</span>
            <span>
              allow a program to test several conditions and execute
              instructions based on whether those conditions are True or False.
              There are two primary selection statements in Python which are
              ‘if’ and ‘elif’ (short for ‘else if’).
            </span>
            <br />
            <br />
            <span>There are two general categories:</span>
            <br />
          </span>
          <div class="basic-py3ai-container3">
            <span class="basic-py3ai-text13">
              <span class="basic-py3ai-text14">a) Two-way selectors</span>
              <br />
            </span>
            <span class="basic-py3ai-text16">
              <span class="basic-py3ai-text17">b) Multiple-way selectors</span>
              <br />
            </span>
          </div>
          <div class="basic-py3ai-container4">
            <span class="basic-py3ai-text19">
              <span>    - if</span>
              <br />
              <span>    - if-else</span>
              <br />
              <span>    - nested if</span>
              <br />
              <span>    - if-elif else</span>
              <br />
            </span>
            <span class="basic-py3ai-text28">
              <span>    - nested IF structure</span>
              <br />
              <span>    - nested SWITCH structure</span>
              <br />
              <span>       =&gt; dictionary mapping</span>
              <br />
              <span>       =&gt; class</span>
              <br />
            </span>
          </div>
        </div>
        <span class="basic-py3ai-text37">
          <span>
            -
            <span [innerHTML]="raw40r0"></span>
          </span>
          <span class="basic-py3ai-text39">Noor Alia Alisa</span>
        </span>
      </div>
    </div>
  </div>
  <div class="basic-py3ai-reference">
    <h1 class="basic-py3ai-text40">References</h1>
    <span class="basic-py3ai-text41">
      <br class="basic-py3ai-text42" />
      <span class="basic-py3ai-text43">
        Switch Case in Python (Replacement)
      </span>
      <span class="basic-py3ai-text44">
        . (2017, October 29). GeeksforGeeks.
      </span>
      <br class="basic-py3ai-text45" />
      <span class="basic-py3ai-text46">
               
        <span [innerHTML]="rawo2ry"></span>
      </span>
      <a
        href="https://www.geeksforgeeks.org/switch-case-in-python-replacement/"
        target="_blank"
        rel="noreferrer noopener"
        class="basic-py3ai-link"
      >
        https://www.geeksforgeeks.org/switch-case-in-python-replacement/
      </a>
      <br />
    </span>
  </div>
  <footer class="basic-py3ai-footer">
    <div class="basic-py3ai-container5">
      <a routerLink="/strace" class="basic-py3ai-navlink5">STRACE</a>
    </div>
    <span class="basic-py3ai-text48">
      &quot;Making System Calls Cool Again&quot;
    </span>
    <div class="basic-py3ai-icon-group">
      <svg viewBox="0 0 877.7142857142857 1024" class="basic-py3ai-icon">
        <path
          d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
        ></path>
      </svg>
    </div>
  </footer>
  <app-header></app-header>
</div>
