// [Angular] Website Source Code/src/app/pages/basic-py-4ai/basic-py-4ai.component.ts
import { Component } from '@angular/core'
import { Title, Meta } from '@angular/platform-browser'

@Component({
  selector: 'basic-py4ai',
  templateUrl: 'basic-py-4ai.component.html',
  styleUrls: ['basic-py-4ai.component.css'],
})
export class BasicPy4ai {
  raw67nb: string = ' '
  rawqypn: string = ' '
  rawap3n: string = ' '
  raw0v86: string = ' '
  rawp6my: string = ' '
  raw4v5n: string = ' '
  rawqz7x: string = ' '
  rawgzhq: string = ' '
  rawni0s: string = ' '
  rawgh0m: string = ' '
  rawbi3e: string = ' '
  rawvmqg: string = ' '
  rawpvvg: string = ' '
  rawfa6j: string = ' '
  rawf357: string = ' '
  raw6pg2: string = ' '
  constructor(private title: Title, private meta: Meta) {
    this.title.setTitle('Strace | Basic Python')
    this.meta.addTags([
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ])
  }
}

<div class="basic-py4ai-container">
  <div class="basic-py4ai-banner">
    <div class="basic-py4ai-main-content">
      <h1 class="basic-py4ai-heading">SUBPROGRAMS</h1>
      <div class="basic-py4ai-container1">
        <a routerLink="/basic-py-4ai" class="basic-py4ai-navlink button">
          Fundamentals of Subprograms
        </a>
        <a routerLink="/basic-py-4aii" class="basic-py4ai-navlink1 button">
          Local Referencing Environments
        </a>
        <a routerLink="/basic-py-4bi" class="basic-py4ai-navlink2 button">
          Parameter-Passing Method
        </a>
        <a routerLink="/basic-py-4bii" class="basic-py4ai-navlink3 button">
          Indirect Subprograms Calling
        </a>
      </div>
      <div class="basic-py4ai-container2">
        <a routerLink="/basic-py-4biii" class="basic-py4ai-navlink4 button">
          Design Issues for Functions
        </a>
        <a routerLink="/basic-py-4biv" class="basic-py4ai-navlink5 button">
          Overloaded and Generic Subprograms
        </a>
        <a routerLink="/basic-py-4bv" class="basic-py4ai-navlink6 button">
          User-Defined Overloaded Operators
        </a>
      </div>
      <div class="basic-py4ai-content-here">
        <div class="basic-py4ai-column">
          <h1 class="basic-py4ai-text">
            <span>Fundamentals of Subprograms</span>
            <br />
          </h1>
          <div class="basic-py4ai-container3">
            <span class="basic-py4ai-text03">
              <span class="basic-py4ai-text04">
                Function in Python works just like any other programming
                languages and it
                <span [innerHTML]="raw67nb"></span>
              </span>
              <span class="basic-py4ai-text05">has the same properties</span>
              <span class="basic-py4ai-text06">
                but
                <span [innerHTML]="rawqypn"></span>
              </span>
              <span class="basic-py4ai-text07">different in syntax</span>
              <span class="basic-py4ai-text08">
                or the way you declare the function.
              </span>
              <br />
              <br />
              <span>
                We have to type
                <span [innerHTML]="rawap3n"></span>
              </span>
              <span class="basic-py4ai-text12">def</span>
              <span class="basic-py4ai-text13"> keyword</span>
              <span>
                (define) first when declaring a function/subprogram. After that,
                we
                <span [innerHTML]="raw0v86"></span>
              </span>
              <span class="basic-py4ai-text15">give it a name</span>
              <span>
                and also
                <span [innerHTML]="rawp6my"></span>
              </span>
              <span class="basic-py4ai-text17">arguments to pass</span>
              <span>
                . The
                <span [innerHTML]="raw4v5n"></span>
              </span>
              <span class="basic-py4ai-text19">
                function body has to be indented
              </span>
              <span>to show the compiler that its belong to the function.</span>
              <br />
              <br />
              <span>
                Lasty, we can
                <span [innerHTML]="rawqz7x"></span>
              </span>
              <span class="basic-py4ai-text24">return any values</span>
              <span>
                from the function but it is an
                <span [innerHTML]="rawgzhq"></span>
              </span>
              <span class="basic-py4ai-text26">optional</span>
              <span>
                step. If the function did not have a return, it is a void
                function.
              </span>
              <br />
            </span>
            <img
              alt="image"
              src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/4a%20Subprogram_Nabil/Function1.png?raw=true"
              loading="eager"
              class="basic-py4ai-image"
            />
          </div>
          <div class="basic-py4ai-container4">
            <div class="basic-py4ai-container5">
              <span class="basic-py4ai-text29">
                Arbitrary Arguments (*args)
              </span>
              <img
                alt="image"
                src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/4a%20Subprogram_Nabil/Function2.png?raw=true"
                loading="eager"
                class="basic-py4ai-image1"
              />
              <span class="basic-py4ai-text30">
                <span>
                  We can
                  <span [innerHTML]="rawni0s"></span>
                </span>
                <span class="basic-py4ai-text32">
                  pass more than one argument
                </span>
                <span>
                  into the function with only one formal parameter inside the
                  function header
                  <span [innerHTML]="rawgh0m"></span>
                </span>
                <span class="basic-py4ai-text34">
                  by adding asterisk &apos;*&apos; infront
                </span>
                <span>
                  of the
                  <span [innerHTML]="rawbi3e"></span>
                </span>
                <span class="basic-py4ai-text36">
                  formal parameter&apos;s name
                </span>
                <span>
                  and the function will receives the value in tuple/list type.
                </span>
              </span>
            </div>
            <div class="basic-py4ai-container6">
              <span class="basic-py4ai-text38">
                Arbitrary Keyword Arguments (**kwargs)
              </span>
              <img
                alt="image"
                src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/4a%20Subprogram_Nabil/Function3.png?raw=true"
                loading="eager"
                class="basic-py4ai-image2"
              />
              <span class="basic-py4ai-text39">
                <span>
                  Besides that, we also can
                  <span [innerHTML]="rawvmqg"></span>
                </span>
                <span class="basic-py4ai-text41">
                  pass more than one argument
                </span>
                <span>
                  into the function
                  <span [innerHTML]="rawpvvg"></span>
                </span>
                <span class="basic-py4ai-text43">
                  by adding two asterisks &apos;**&apos;
                </span>
                <span>
                  infront of the
                  <span [innerHTML]="rawfa6j"></span>
                </span>
                <span class="basic-py4ai-text45">
                  formal parameter&apos;s name
                </span>
                <span>
                  and the function will receives the value in dictionary type.
                </span>
              </span>
            </div>
          </div>
        </div>
        <span class="basic-py4ai-text47">
          <span>
            -
            <span [innerHTML]="rawf357"></span>
          </span>
          <span class="basic-py4ai-text49">Muhammad Ariff Ridzlan</span>
        </span>
      </div>
    </div>
  </div>
  <div class="basic-py4ai-reference">
    <h1 class="basic-py4ai-text50">References</h1>
    <span class="basic-py4ai-text51">
      <br />
      <span class="basic-py4ai-text53">Python Functions</span>
      <span>. (n.d.). W3Schools Online Web Tutorials.</span>
      <br />
      <span>
               
        <span [innerHTML]="raw6pg2"></span>
      </span>
      <a
        href="https://www.w3schools.com/python/python_functions.asp"
        target="_blank"
        rel="noreferrer noopener"
        class="basic-py4ai-link"
      >
        https://www.w3schools.com/python/python_functions.asp
      </a>
    </span>
  </div>
  <footer class="basic-py4ai-footer">
    <div class="basic-py4ai-container7">
      <a routerLink="/strace" class="basic-py4ai-navlink7">STRACE</a>
    </div>
    <span class="basic-py4ai-text57">
      &quot;Making System Calls Cool Again&quot;
    </span>
    <div class="basic-py4ai-icon-group">
      <svg viewBox="0 0 877.7142857142857 1024" class="basic-py4ai-icon">
        <path
          d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
        ></path>
      </svg>
    </div>
  </footer>
  <app-header></app-header>
</div>

// [Vue] Website Source Code/src/views/basic-py-4ai.vue
<template>
  <div class="basic-py4ai-container">
    <div class="basic-py4ai-banner">
      <div class="basic-py4ai-main-content">
        <h1 class="basic-py4ai-heading">SUBPROGRAMS</h1>
        <div class="basic-py4ai-container1">
          <router-link to="/basic-py-4ai" class="basic-py4ai-navlink button">
            Fundamentals of Subprograms
          </router-link>
          <router-link to="/basic-py-4aii" class="basic-py4ai-navlink1 button">
            Local Referencing Environments
          </router-link>
          <router-link to="/basic-py-4bi" class="basic-py4ai-navlink2 button">
            Parameter-Passing Method
          </router-link>
          <router-link to="/basic-py-4bii" class="basic-py4ai-navlink3 button">
            Indirect Subprograms Calling
          </router-link>
        </div>
        <div class="basic-py4ai-container2">
          <router-link to="/basic-py-4biii" class="basic-py4ai-navlink4 button">
            Design Issues for Functions
          </router-link>
          <router-link to="/basic-py-4biv" class="basic-py4ai-navlink5 button">
            Overloaded and Generic Subprograms
          </router-link>
          <router-link to="/basic-py-4bv" class="basic-py4ai-navlink6 button">
            User-Defined Overloaded Operators
          </router-link>
        </div>
        <div class="basic-py4ai-content-here">
          <div class="basic-py4ai-column">
            <h1 class="basic-py4ai-text">
              <span>Fundamentals of Subprograms</span>
              <br />
            </h1>
            <div class="basic-py4ai-container3">
              <span class="basic-py4ai-text03">
                <span class="basic-py4ai-text04">
                  Function in Python works just like any other programming
                  languages and it
                  <span v-html="rawg2kx"></span>
                </span>
                <span class="basic-py4ai-text05">has the same properties</span>
                <span class="basic-py4ai-text06">
                  but
                  <span v-html="raws7i7"></span>
                </span>
                <span class="basic-py4ai-text07">different in syntax</span>
                <span class="basic-py4ai-text08">
                  or the way you declare the function.
                </span>
                <br />
                <br />
                <span>
                  We have to type
                  <span v-html="rawojhg"></span>
                </span>
                <span class="basic-py4ai-text12">def</span>
                <span class="basic-py4ai-text13"> keyword</span>
                <span>
                  (define) first when declaring a function/subprogram. After that,
                  we
                  <span v-html="rawovnf"></span>
                </span>
                <span class="basic-py4ai-text15">give it a name</span>
                <span>
                  and also
                  <span v-html="raw1i7c"></span>
                </span>
                <span class="basic-py4ai-text17">arguments to pass</span>
                <span>
                  . The
                  <span v-html="raww5ej"></span>
                </span>
                <span class="basic-py4ai-text19">
                  function body has to be indented
                </span>
                <span>to show the compiler that its belong to the function.</span>
                <br />
                <br />
                <span>
                  Lasty, we can
                  <span v-html="rawygsm"></span>
                </span>
                <span class="basic-py4ai-text24">return any values</span>
                <span>
                  from the function but it is an
                  <span v-html="rawvl18"></span>
                </span>
                <span class="basic-py4ai-text26">optional</span>
                <span>
                  step. If the function did not have a return, it is a void
                  function.
                </span>
                <br />
              </span>
              <img
                alt="image"
                src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/4a%20Subprogram_Nabil/Function1.png?raw=true"
                loading="eager"
                class="basic-py4ai-image"
              />
            </div>
            <div class="basic-py4ai-container4">
              <div class="basic-py4ai-container5">
                <span class="basic-py4ai-text29">
                  Arbitrary Arguments (*args)
                </span>
                <img
                  alt="image"
                  src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/4a%20Subprogram_Nabil/Function2.png?raw=true"
                  loading="eager"
                  class="basic-py4ai-image1"
                />
                <span class="basic-py4ai-text30">
                  <span>
                    We can
                    <span v-html="rawjrz6"></span>
                  </span>
                  <span class="basic-py4ai-text32">
                    pass more than one argument
                  </span>
                  <span>
                    into the function with only one formal parameter inside the
                    function header
                    <span v-html="raw3gmc"></span>
                  </span>
                  <span class="basic-py4ai-text34">
                    by adding asterisk &apos;*&apos; infront
                  </span>
                  <span>
                    of the
                    <span v-html="rawctp0"></span>
                  </span>
                  <span class="basic-py4ai-text36">
                    formal parameter&apos;s name
                  </span>
                  <span>
                    and the function will receives the value in tuple/list type.
                  </span>
                </span>
              </div>
              <div class="basic-py4ai-container6">
                <span class="basic-py4ai-text38">
                  Arbitrary Keyword Arguments (**kwargs)
                </span>
                <img
                  alt="image"
                  src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/4a%20Subprogram_Nabil/Function3.png?raw=true"
                  loading="eager"
                  class="basic-py4ai-image2"
                />
                <span class="basic-py4ai-text39">
                  <span>
                    Besides that, we also can
                    <span v-html="rawyvbm"></span>
                  </span>
                  <span class="basic-py4ai-text41">
                    pass more than one argument
                  </span>
                  <span>
                    into the function
                    <span v-html="rawt7j2"></span>
                  </span>
                  <span class="basic-py4ai-text43">
                    by adding two asterisks &apos;**&apos;
                  </span>
                  <span>
                    infront of the
                    <span v-html="raw6lk0"></span>
                  </span>
                  <span class="basic-py4ai-text45">
                    formal parameter&apos;s name
                  </span>
                  <span>
                    and the function will receives the value in dictionary type.
                  </span>
                </span>
              </div>
            </div>
          </div>
          <span class="basic-py4ai-text47">
            <span>
              -
              <span v-html="rawob12"></span>
            </span>
            <span class="basic-py4ai-text49">Muhammad Ariff Ridzlan</span>
          </span>
        </div>
      </div>
    </div>
    <div class="basic-py4ai-reference">
      <h1 class="basic-py4ai-text50">References</h1>
      <span class="basic-py4ai-text51">
        <br />
        <span class="basic-py4ai-text53">Python Functions</span>
        <span>. (n.d.). W3Schools Online Web Tutorials.</span>
        <br />
        <span>
                 
          <span v-html="rawfo10"></span>
        </span>
        <a
          href="https://www.w3schools.com/python/python_functions.asp"
          target="_blank"
          rel="noreferrer noopener"
          class="basic-py4ai-link"
        >
          https://www.w3schools.com/python/python_functions.asp
        </a>
      </span>
    </div>
    <footer class="basic-py4ai-footer">
      <div class="basic-py4ai-container7">
        <router-link to="/strace" class="basic-py4ai-navlink7">
          STRACE
        </router-link>
      </div>
      <span class="basic-py4ai-text57">
        &quot;Making System Calls Cool Again&quot;
      </span>
      <div class="basic-py4ai-icon-group">
        <svg viewBox="0 0 877.7142857142857 1024" class="basic-py4ai-icon">
          <path
            d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
          ></path>
        </svg>
      </div>
    </footer>
    <app-header></app-header>
  </div>
</template>

<script>
import AppHeader from '../components/header'

export default {
  name: 'BasicPy4ai',
  props: {},
  components: {
    AppHeader,
  },
  data() {
    return {
      rawg2kx: ' ',
      raws7i7: ' ',
      rawojhg: ' ',
      rawovnf: ' ',
      raw1i7c: ' ',
      raww5ej: ' ',
      rawygsm: ' ',
      rawvl18: ' ',
      rawjrz6: ' ',
      raw3gmc: ' ',
      rawctp0: ' ',
      rawyvbm: ' ',
      rawt7j2: ' ',
      raw6lk0: ' ',
      rawob12: ' ',
      rawfo10: ' ',
    }
  },
  metaInfo: {
    title: 'Strace | Basic Python',
    meta: [
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ],
  },
}
</script>

<style scoped>
.basic-py4ai-container {
  width: 100%;
  display: flex;
  overflow: auto;
  min-height: 100vh;
  align-items: center;
  flex-direction: column;
  justify-content: flex-start;
  background-color: #f5f5f5;
}
.basic-py4ai-banner {
  width: 100%;
  height: 275px;
  display: flex;
  transition: 0.3s;
  align-items: center;
  flex-direction: column;
  background-size: cover;
  justify-content: center;
  background-image: url('https://marketplace.canva.com/EAD2962NKnQ/2/0/1600w/canva-rainbow-gradient-pink-and-purple-virtual-background-_Tcjok-d9b4.jpg');
}

.basic-py4ai-main-content {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: flex-start;
  background-color: #ffffff;
}
.basic-py4ai-heading {
  color: #ff0000;
  font-size: 3rem;
  align-self: center;
  text-align: center;
}
.basic-py4ai-container1 {
  flex: 0 0 auto;
  width: 100%;
  height: 100px;
  display: flex;
  align-items: flex-start;
}
.basic-py4ai-navlink {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py4ai-navlink:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py4ai-navlink1 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py4ai-navlink1:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py4ai-navlink2 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py4ai-navlink2:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py4ai-navlink3 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py4ai-navlink3:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py4ai-container2 {
  flex: 0 0 auto;
  width: 100%;
  height: 100px;
  display: flex;
  align-items: flex-start;
}
.basic-py4ai-navlink4 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py4ai-navlink4:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py4ai-navlink5 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py4ai-navlink5:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py4ai-navlink6 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py4ai-navlink6:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py4ai-content-here {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.basic-py4ai-column {
  flex: 1;
  width: auto;
  height: auto;
  display: flex;
  flex-direction: column;
}
.basic-py4ai-container3 {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.basic-py4ai-text03 {
  text-align: justify;
}
.basic-py4ai-image {
  width: 200px;
  object-fit: cover;
}
.basic-py4ai-container4 {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.basic-py4ai-container5 {
  flex: 0 0 auto;
  display: flex;
  align-items: center;
  flex-direction: column;
  justify-content: center;
}
.basic-py4ai-image1 {
  width: 200px;
  object-fit: cover;
}
.basic-py4ai-container6 {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.basic-py4ai-image2 {
  width: 200px;
  object-fit: cover;
}
.basic-py4ai-reference {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #ffffff;
}
.basic-py4ai-footer {
  width: 100%;
  display: flex;
  max-width: var(--dl-size-size-maxwidth);
  align-self: center;
  align-items: center;
  padding-top: var(--dl-space-space-twounits);
  padding-left: var(--dl-space-space-threeunits);
  padding-right: var(--dl-space-space-threeunits);
  padding-bottom: var(--dl-space-space-twounits);
  justify-content: space-between;
}
.basic-py4ai-container7 {
  flex: 0 0 auto;
  width: auto;
  height: auto;
  display: flex;
  align-items: space-between;
  flex-direction: column;
}
.basic-py4ai-navlink7 {
  font-weight: 700;
  text-decoration: none;
}
.basic-py4ai-icon {
  width: 24px;
  height: 24px;
}
@media(max-width: 1600px) {
  .basic-py4ai-container {
    background-color: #f7f7f7;
  }
  .basic-py4ai-banner {
    height: auto;
    align-items: center;
    background-size: cover;
    justify-content: flex-start;
    background-image: url("/external/bgportrait-1500w.jpg");
  }
  .basic-py4ai-main-content {
    flex: 1;
    width: 1300px;
    height: auto;
    box-shadow: 0px 0px 10px 0px #d3d2d6;
    align-items: flex-start;
    padding-top: 100px;
    flex-direction: column;
    justify-content: flex-start;
    background-color: #ffffff;
  }
  .basic-py4ai-heading {
    color: rgb(255, 255, 255);
    width: 1200px;
    height: auto;
    font-size: 64px;
    font-style: normal;
    margin-top: 40px;
    font-family: Montserrat;
    font-weight: 700;
    line-height: 1.15;
    padding-top: 40px;
    border-radius: var(--dl-radius-radius-radius4);
    margin-bottom: 20px;
    padding-bottom: 40px;
    background-size: auto;
    background-image: url("/external/bglandscape-1200w.jpg");
    background-position: top left;
  }
  .basic-py4ai-container1 {
    width: 950px;
    height: auto;
    align-self: center;
    margin-left: 50px;
    padding-top: 20px;
    margin-right: 50px;
    padding-bottom: 10px;
    justify-content: center;
  }
  .basic-py4ai-navlink {
    color: #A068FF;
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    border-width: 1px;
    margin-right: 25px;
    background-color: rgb(255, 255, 255);
  }
  .basic-py4ai-navlink1 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py4ai-navlink2 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py4ai-navlink3 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py4ai-container2 {
    width: 750px;
    height: auto;
    align-self: center;
    margin-left: 50px;
    padding-top: 10px;
    margin-right: 50px;
    padding-bottom: 20px;
    justify-content: center;
  }
  .basic-py4ai-navlink4 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py4ai-navlink5 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py4ai-navlink6 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py4ai-content-here {
    width: 1200px;
    align-items: flex-end;
    margin-left: 50px;
    padding-top: 50px;
    margin-right: 50px;
    padding-bottom: 50px;
  }
  .basic-py4ai-column {
    flex: 1;
    width: 100%;
    align-items: flex-start;
  }
  .basic-py4ai-text {
    font-size: 36px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
    padding-top: 0px;
    padding-left: 0px;
    padding-right: 0px;
    padding-bottom: 30px;
  }
  .basic-py4ai-container3 {
    margin-bottom: 35px;
  }
  .basic-py4ai-text03 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-right: var(--dl-space-space-fourunits);
  }
  .basic-py4ai-text04 {
    text-transform: inherit;
  }
  .basic-py4ai-text05 {
    font-weight: 700;
    text-transform: inherit;
  }
  .basic-py4ai-text06 {
    text-transform: inherit;
  }
  .basic-py4ai-text07 {
    font-weight: 700;
    text-transform: inherit;
  }
  .basic-py4ai-text08 {
    text-transform: inherit;
  }
  .basic-py4ai-text12 {
    font-style: italic;
    font-weight: 700;
  }
  .basic-py4ai-text13 {
    font-weight: 700;
  }
  .basic-py4ai-text15 {
    font-weight: 700;
  }
  .basic-py4ai-text17 {
    font-weight: 700;
  }
  .basic-py4ai-text19 {
    font-weight: 700;
  }
  .basic-py4ai-text24 {
    font-weight: 700;
  }
  .basic-py4ai-text26 {
    font-weight: 700;
  }
  .basic-py4ai-image {
    width: 500px;
    height: 169px;
    border-radius: var(--dl-radius-radius-radius4);
  }
  .basic-py4ai-container5 {
    width: 50%;
    padding-right: var(--dl-space-space-fourunits);
  }
  .basic-py4ai-text29 {
    font-size: 25px;
    align-self: flex-start;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
    margin-bottom: 20px;
  }
  .basic-py4ai-image1 {
    width: 500px;
    height: 120px;
    align-self: flex-start;
    border-radius: var(--dl-radius-radius-radius4);
  }
  .basic-py4ai-text30 {
    font-size: 16px;
    align-self: flex-start;
    font-style: normal;
    margin-top: 25px;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
  }
  .basic-py4ai-text32 {
    font-weight: 700;
  }
  .basic-py4ai-text34 {
    font-weight: 700;
  }
  .basic-py4ai-text36 {
    font-weight: 700;
  }
  .basic-py4ai-container6 {
    width: 50%;
    padding-left: var(--dl-space-space-twounits);
  }
  .basic-py4ai-text38 {
    font-size: 24px;
    align-self: flex-start;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
    line-height: 1.15;
    margin-bottom: 20px;
  }
  .basic-py4ai-image2 {
    width: 550px;
    height: 120px;
    align-self: flex-start;
    border-radius: var(--dl-radius-radius-radius4);
  }
  .basic-py4ai-text39 {
    align-self: flex-start;
    margin-top: 25px;
  }
  .basic-py4ai-text41 {
    font-weight: 700;
  }
  .basic-py4ai-text43 {
    font-weight: 700;
  }
  .basic-py4ai-text45 {
    font-weight: 700;
  }
  .basic-py4ai-text47 {
    font-size: 18px;
    font-style: normal;
    font-family: Inter;
    font-weight: 500;
    padding-top: 25px;
  }
  .basic-py4ai-text49 {
    font-style: italic;
  }
  .basic-py4ai-reference {
    width: 1600px;
    height: auto;
    align-self: center;
    box-shadow: 0px -1px 15px 0px #ebebeb;
    align-items: flex-start;
    padding-top: 50px;
    padding-left: 200px;
    padding-right: 200px;
    flex-direction: column;
    padding-bottom: 50px;
    justify-content: flex-start;
  }
  .basic-py4ai-text50 {
    font-size: 32px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
  }
  .basic-py4ai-text51 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.25;
  }
  .basic-py4ai-text53 {
    font-style: italic;
  }
  .basic-py4ai-link {
    color: var(--dl-color-primary-300);
    font-size: 16px;
    font-family: Inter;
    font-weight: 400;
    text-decoration: underline;
  }
  .basic-py4ai-footer {
    justify-content: space-between;
  }
  .basic-py4ai-navlink7 {
    font-size: 16px;
    font-family: Montserrat;
    font-weight: 700;
    text-decoration: none;
  }
  .basic-py4ai-text57 {
    font-size: 16px;
    font-style: normal;
    font-family: Montserrat;
    font-weight: 500;
  }
  .basic-py4ai-icon {
    margin-left: 50px;
  }
}
@media(max-width: 1200px) {
  .basic-py4ai-heading {
    color: rgb(255, 255, 255);
  }
}
@media(max-width: 479px) {
  .basic-py4ai-footer {
    align-self: center;
  }
  .basic-py4ai-icon-group {
    display: none;
  }
}
</style>
