// [Angular] Website Source Code/src/app/pages/basic-py-4biii/basic-py-4biii.component.ts
import { Component } from '@angular/core'
import { Title, Meta } from '@angular/platform-browser'

@Component({
  selector: 'basic-py4biii',
  templateUrl: 'basic-py-4biii.component.html',
  styleUrls: ['basic-py-4biii.component.css'],
})
export class BasicPy4biii {
  rawrxwb: string = ' '
  rawujay: string = ' '
  rawxg2g: string = ' '
  rawatwh: string = ' '
  rawfmm1: string = ' '
  raw0jcz: string = ' '
  rawv86u: string = ' '
  rawd3iw: string = ' '
  raw1val: string = ' '
  rawpusf: string = ' '
  rawg516: string = ' '
  raw619u: string = ' '
  raw9erh: string = ' '
  rawawhq: string = ' '
  constructor(private title: Title, private meta: Meta) {
    this.title.setTitle('Strace | Basic Python')
    this.meta.addTags([
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ])
  }
}

<div class="basic-py4biii-container">
  <div class="basic-py4biii-banner">
    <div class="basic-py4biii-main-content">
      <h1 class="basic-py4biii-heading">SUBPROGRAMS</h1>
      <div class="basic-py4biii-container1">
        <a routerLink="/basic-py-4ai" class="basic-py4biii-navlink button">
          Fundamentals of Subprograms
        </a>
        <a routerLink="/basic-py-4aii" class="basic-py4biii-navlink1 button">
          Local Referencing Environments
        </a>
        <a routerLink="/basic-py-4bi" class="basic-py4biii-navlink2 button">
          Parameter-Passing Method
        </a>
        <a routerLink="/basic-py-4bii" class="basic-py4biii-navlink3 button">
          Indirect Subprograms Calling
        </a>
      </div>
      <div class="basic-py4biii-container2">
        <a routerLink="/basic-py-4biii" class="basic-py4biii-navlink4 button">
          Design Issues for Functions
        </a>
        <a routerLink="/basic-py-4biv" class="basic-py4biii-navlink5 button">
          Overloaded and Generic Subprograms
        </a>
        <a routerLink="/basic-py-4bv" class="basic-py4biii-navlink6 button">
          User-Defined Overloaded Operators
        </a>
      </div>
      <div class="basic-py4biii-content-here">
        <h1 class="basic-py4biii-text">
          <span>Design Issues for Functions</span>
          <br />
        </h1>
        <div class="basic-py4biii-container3">
          <div class="basic-py4biii-column">
            <h1 class="basic-py4biii-text03">
              <span>Python allows side effects :O</span>
              <br />
            </h1>
            <span class="basic-py4biii-text06">
              Function can exhibit side effects that will modify the original
              variable.
            </span>
            <img
              alt="image"
              src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/4b%20Subprogram_Ariff/DesignIssue1.png?raw=true"
              class="basic-py4biii-image"
            />
            <span class="basic-py4biii-text07">
              <span class="basic-py4biii-text08">itemList</span>
              <span>
                was
                <span [innerHTML]="rawrxwb"></span>
              </span>
              <span class="basic-py4biii-text10">modified</span>
              <span>
                after
                <span [innerHTML]="rawujay"></span>
              </span>
              <span class="basic-py4biii-text12">FSE function</span>
              <span><span [innerHTML]="rawxg2g"></span></span>
              <span class="basic-py4biii-text14">
                executed
                <span [innerHTML]="rawatwh"></span>
              </span>
              <span>
                due to the
                <span [innerHTML]="rawfmm1"></span>
              </span>
              <span class="basic-py4biii-text16">call by object reference</span>
              <span>
                method. For more information about side effect, we discussed
                about this before in
                <span [innerHTML]="raw0jcz"></span>
              </span>
              <a routerLink="/basic-py-2b" class="basic-py4biii-navlink7">
                Expressions and Assignment
              </a>
              <span>:D.</span>
              <br />
            </span>
          </div>
          <div class="basic-py4biii-column1">
            <h1 class="basic-py4biii-text20">
              <span>Python returns any datatype ;)</span>
              <br />
            </h1>
            <span class="basic-py4biii-text23">
              <span>
                Function can returns any datatype and it can be assigned to a
                variable.
              </span>
              <br />
            </span>
            <img
              alt="image"
              src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/4b%20Subprogram_Ariff/DesignIssue2.png?raw=true"
              loading="eager"
              class="basic-py4biii-image1"
            />
            <span class="basic-py4biii-text26">
              <span>
                Since Python is a
                <span [innerHTML]="rawv86u"></span>
              </span>
              <span class="basic-py4biii-text28">
                dynamically-typed language
              </span>
              <span>
                , it can return a string, float, list, and even an object.
                Additionally, it also can be return and
                <span [innerHTML]="rawd3iw"></span>
              </span>
              <span class="basic-py4biii-text30">assigned</span>
              <span>
                into
                <span [innerHTML]="raw1val"></span>
              </span>
              <span class="basic-py4biii-text32">
                multiple number of variables
              </span>
              <span>.</span>
              <br />
            </span>
          </div>
        </div>
      </div>
      <span class="basic-py4biii-text35">
        <span>
          -
          <span [innerHTML]="rawpusf"></span>
        </span>
        <span class="basic-py4biii-text37">Muhammad Ariff Ridzlan</span>
      </span>
    </div>
  </div>
  <div class="basic-py4biii-reference">
    <h1 class="basic-py4biii-text38">References</h1>
    <span class="basic-py4biii-text39">
      <br class="basic-py4biii-text40" />
      <span class="basic-py4biii-text41">
        Pankaj. (2022, August 3).
        <span [innerHTML]="rawg516"></span>
      </span>
      <span class="basic-py4biii-text42">Python return statement</span>
      <span class="basic-py4biii-text43">. DigitalOcean.</span>
      <br class="basic-py4biii-text44" />
      <span class="basic-py4biii-text45">
               
        <span [innerHTML]="raw619u"></span>
      </span>
      <a
        href="https://www.digitalocean.com/community/tutorials/python-return-statement"
        target="_blank"
        rel="noreferrer noopener"
        class="basic-py4biii-link"
      >
        https://www.digitalocean.com/community/tutorials/python-return-statement
      </a>
      <br class="basic-py4biii-text46" />
      <br class="basic-py4biii-text47" />
      <span class="basic-py4biii-text48">
        Srinivas, R. (2022, January 4).
        <span [innerHTML]="raw9erh"></span>
      </span>
      <span class="basic-py4biii-text49">Side-effects in Python</span>
      <span class="basic-py4biii-text50">. Medium.</span>
      <br class="basic-py4biii-text51" />
      <span class="basic-py4biii-text52">
               
        <span [innerHTML]="rawawhq"></span>
      </span>
      <a
        href="https://python.plainenglish.io/side-effects-in-python-a50caad1169"
        target="_blank"
        rel="noreferrer noopener"
        class="basic-py4biii-link1"
      >
        https://python.plainenglish.io/side-effects-in-python-a50caad1169
      </a>
      <br />
    </span>
  </div>
  <footer class="basic-py4biii-footer">
    <div class="basic-py4biii-container4">
      <a routerLink="/strace" class="basic-py4biii-navlink8">STRACE</a>
    </div>
    <span class="basic-py4biii-text54">
      &quot;Making System Calls Cool Again&quot;
    </span>
    <div class="basic-py4biii-icon-group">
      <svg viewBox="0 0 877.7142857142857 1024" class="basic-py4biii-icon">
        <path
          d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
        ></path>
      </svg>
    </div>
  </footer>
  <app-header></app-header>
</div>

// [Vue] Website Source Code/src/views/basic-py-4biii.vue
<template>
  <div class="basic-py4biii-container">
    <div class="basic-py4biii-banner">
      <div class="basic-py4biii-main-content">
        <h1 class="basic-py4biii-heading">SUBPROGRAMS</h1>
        <div class="basic-py4biii-container1">
          <router-link to="/basic-py-4ai" class="basic-py4biii-navlink button">
            Fundamentals of Subprograms
          </router-link>
          <router-link to="/basic-py-4aii" class="basic-py4biii-navlink1 button">
            Local Referencing Environments
          </router-link>
          <router-link to="/basic-py-4bi" class="basic-py4biii-navlink2 button">
            Parameter-Passing Method
          </router-link>
          <router-link to="/basic-py-4bii" class="basic-py4biii-navlink3 button">
            Indirect Subprograms Calling
          </router-link>
        </div>
        <div class="basic-py4biii-container2">
          <router-link to="/basic-py-4biii" class="basic-py4biii-navlink4 button">
            Design Issues for Functions
          </router-link>
          <router-link to="/basic-py-4biv" class="basic-py4biii-navlink5 button">
            Overloaded and Generic Subprograms
          </router-link>
          <router-link to="/basic-py-4bv" class="basic-py4biii-navlink6 button">
            User-Defined Overloaded Operators
          </router-link>
        </div>
        <div class="basic-py4biii-content-here">
          <h1 class="basic-py4biii-text">
            <span>Design Issues for Functions</span>
            <br />
          </h1>
          <div class="basic-py4biii-container3">
            <div class="basic-py4biii-column">
              <h1 class="basic-py4biii-text03">
                <span>Python allows side effects :O</span>
                <br />
              </h1>
              <span class="basic-py4biii-text06">
                Function can exhibit side effects that will modify the original
                variable.
              </span>
              <img
                alt="image"
                src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/4b%20Subprogram_Ariff/DesignIssue1.png?raw=true"
                class="basic-py4biii-image"
              />
              <span class="basic-py4biii-text07">
                <span class="basic-py4biii-text08">itemList</span>
                <span>
                  was
                  <span v-html="rawc8ev"></span>
                </span>
                <span class="basic-py4biii-text10">modified</span>
                <span>
                  after
                  <span v-html="rawkvxw"></span>
                </span>
                <span class="basic-py4biii-text12">FSE function</span>
                <span><span v-html="rawv0mb"></span></span>
                <span class="basic-py4biii-text14">
                  executed
                  <span v-html="rawpnzx"></span>
                </span>
                <span>
                  due to the
                  <span v-html="rawpjxj"></span>
                </span>
                <span class="basic-py4biii-text16">call by object reference</span>
                <span>
                  method. For more information about side effect, we discussed
                  about this before in
                  <span v-html="rawaypu"></span>
                </span>
                <router-link to="/basic-py-2b" class="basic-py4biii-navlink7">
                  Expressions and Assignment
                </router-link>
                <span>:D.</span>
                <br />
              </span>
            </div>
            <div class="basic-py4biii-column1">
              <h1 class="basic-py4biii-text20">
                <span>Python returns any datatype ;)</span>
                <br />
              </h1>
              <span class="basic-py4biii-text23">
                <span>
                  Function can returns any datatype and it can be assigned to a
                  variable.
                </span>
                <br />
              </span>
              <img
                alt="image"
                src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/4b%20Subprogram_Ariff/DesignIssue2.png?raw=true"
                loading="eager"
                class="basic-py4biii-image1"
              />
              <span class="basic-py4biii-text26">
                <span>
                  Since Python is a
                  <span v-html="raw08b8"></span>
                </span>
                <span class="basic-py4biii-text28">
                  dynamically-typed language
                </span>
                <span>
                  , it can return a string, float, list, and even an object.
                  Additionally, it also can be return and
                  <span v-html="raw7q88"></span>
                </span>
                <span class="basic-py4biii-text30">assigned</span>
                <span>
                  into
                  <span v-html="rawbyal"></span>
                </span>
                <span class="basic-py4biii-text32">
                  multiple number of variables
                </span>
                <span>.</span>
                <br />
              </span>
            </div>
          </div>
        </div>
        <span class="basic-py4biii-text35">
          <span>
            -
            <span v-html="raw2z80"></span>
          </span>
          <span class="basic-py4biii-text37">Muhammad Ariff Ridzlan</span>
        </span>
      </div>
    </div>
    <div class="basic-py4biii-reference">
      <h1 class="basic-py4biii-text38">References</h1>
      <span class="basic-py4biii-text39">
        <br class="basic-py4biii-text40" />
        <span class="basic-py4biii-text41">
          Pankaj. (2022, August 3).
          <span v-html="raw97lq"></span>
        </span>
        <span class="basic-py4biii-text42">Python return statement</span>
        <span class="basic-py4biii-text43">. DigitalOcean.</span>
        <br class="basic-py4biii-text44" />
        <span class="basic-py4biii-text45">
                 
          <span v-html="rawbaa8"></span>
        </span>
        <a
          href="https://www.digitalocean.com/community/tutorials/python-return-statement"
          target="_blank"
          rel="noreferrer noopener"
          class="basic-py4biii-link"
        >
          https://www.digitalocean.com/community/tutorials/python-return-statement
        </a>
        <br class="basic-py4biii-text46" />
        <br class="basic-py4biii-text47" />
        <span class="basic-py4biii-text48">
          Srinivas, R. (2022, January 4).
          <span v-html="rawufto"></span>
        </span>
        <span class="basic-py4biii-text49">Side-effects in Python</span>
        <span class="basic-py4biii-text50">. Medium.</span>
        <br class="basic-py4biii-text51" />
        <span class="basic-py4biii-text52">
                 
          <span v-html="rawx5d0"></span>
        </span>
        <a
          href="https://python.plainenglish.io/side-effects-in-python-a50caad1169"
          target="_blank"
          rel="noreferrer noopener"
          class="basic-py4biii-link1"
        >
          https://python.plainenglish.io/side-effects-in-python-a50caad1169
        </a>
        <br />
      </span>
    </div>
    <footer class="basic-py4biii-footer">
      <div class="basic-py4biii-container4">
        <router-link to="/strace" class="basic-py4biii-navlink8">
          STRACE
        </router-link>
      </div>
      <span class="basic-py4biii-text54">
        &quot;Making System Calls Cool Again&quot;
      </span>
      <div class="basic-py4biii-icon-group">
        <svg viewBox="0 0 877.7142857142857 1024" class="basic-py4biii-icon">
          <path
            d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
          ></path>
        </svg>
      </div>
    </footer>
    <app-header></app-header>
  </div>
</template>

<script>
import AppHeader from '../components/header'

export default {
  name: 'BasicPy4biii',
  props: {},
  components: {
    AppHeader,
  },
  data() {
    return {
      rawc8ev: ' ',
      rawkvxw: ' ',
      rawv0mb: ' ',
      rawpnzx: ' ',
      rawpjxj: ' ',
      rawaypu: ' ',
      raw08b8: ' ',
      raw7q88: ' ',
      rawbyal: ' ',
      raw2z80: ' ',
      raw97lq: ' ',
      rawbaa8: ' ',
      rawufto: ' ',
      rawx5d0: ' ',
    }
  },
  metaInfo: {
    title: 'Strace | Basic Python',
    meta: [
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ],
  },
}
</script>

<style scoped>
.basic-py4biii-container {
  width: 100%;
  display: flex;
  overflow: auto;
  min-height: 100vh;
  align-items: center;
  flex-direction: column;
  justify-content: flex-start;
  background-color: #f5f5f5;
}
.basic-py4biii-banner {
  width: 100%;
  height: 275px;
  display: flex;
  transition: 0.3s;
  align-items: center;
  flex-direction: column;
  background-size: cover;
  justify-content: center;
  background-image: url('https://marketplace.canva.com/EAD2962NKnQ/2/0/1600w/canva-rainbow-gradient-pink-and-purple-virtual-background-_Tcjok-d9b4.jpg');
}

.basic-py4biii-main-content {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: flex-start;
  background-color: #ffffff;
}
.basic-py4biii-heading {
  color: #ff0000;
  font-size: 3rem;
  align-self: center;
  text-align: center;
}
.basic-py4biii-container1 {
  flex: 0 0 auto;
  width: 100%;
  height: 100px;
  display: flex;
  align-items: flex-start;
}
.basic-py4biii-navlink {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py4biii-navlink:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py4biii-navlink1 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py4biii-navlink1:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py4biii-navlink2 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py4biii-navlink2:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py4biii-navlink3 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py4biii-navlink3:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py4biii-container2 {
  flex: 0 0 auto;
  width: 100%;
  height: 100px;
  display: flex;
  align-items: flex-start;
}
.basic-py4biii-navlink4 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py4biii-navlink4:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py4biii-navlink5 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py4biii-navlink5:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py4biii-navlink6 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py4biii-navlink6:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py4biii-content-here {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.basic-py4biii-container3 {
  flex: 0 0 auto;
  width: 100%;
  height: 100px;
  display: flex;
  align-items: flex-start;
}
.basic-py4biii-column {
  flex: 1;
  width: auto;
  height: auto;
  display: flex;
  flex-direction: column;
}
.basic-py4biii-text06 {
  text-align: justify;
}
.basic-py4biii-image {
  width: 200px;
  object-fit: cover;
}
.basic-py4biii-text07 {
  text-align: justify;
}
.basic-py4biii-column1 {
  flex: 1;
  width: auto;
  height: auto;
  display: flex;
  flex-direction: column;
}
.basic-py4biii-text23 {
  text-align: justify;
}
.basic-py4biii-image1 {
  width: 200px;
  object-fit: cover;
}
.basic-py4biii-text26 {
  text-align: justify;
}
.basic-py4biii-reference {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #ffffff;
}
.basic-py4biii-footer {
  width: 100%;
  display: flex;
  max-width: var(--dl-size-size-maxwidth);
  align-self: center;
  align-items: center;
  padding-top: var(--dl-space-space-twounits);
  padding-left: var(--dl-space-space-threeunits);
  padding-right: var(--dl-space-space-threeunits);
  padding-bottom: var(--dl-space-space-twounits);
  justify-content: space-between;
}
.basic-py4biii-container4 {
  flex: 0 0 auto;
  width: auto;
  height: auto;
  display: flex;
  align-items: space-between;
  flex-direction: column;
}
.basic-py4biii-navlink8 {
  font-weight: 700;
  text-decoration: none;
}
.basic-py4biii-icon {
  width: 24px;
  height: 24px;
}
@media(max-width: 1600px) {
  .basic-py4biii-container {
    background-color: #f7f7f7;
  }
  .basic-py4biii-banner {
    height: auto;
    align-items: center;
    background-size: cover;
    justify-content: flex-start;
    background-image: url("/external/bgportrait-1500w.jpg");
  }
  .basic-py4biii-main-content {
    flex: 1;
    width: 1300px;
    height: auto;
    box-shadow: 0px 0px 10px 0px #d3d2d6;
    align-items: flex-start;
    padding-top: 100px;
    flex-direction: column;
    justify-content: flex-start;
    background-color: #ffffff;
  }
  .basic-py4biii-heading {
    color: rgb(255, 255, 255);
    width: 1200px;
    height: auto;
    font-size: 64px;
    font-style: normal;
    margin-top: 40px;
    font-family: Montserrat;
    font-weight: 700;
    line-height: 1.15;
    padding-top: 40px;
    border-radius: var(--dl-radius-radius-radius4);
    margin-bottom: 20px;
    padding-bottom: 40px;
    background-size: auto;
    background-image: url("/external/bglandscape-1200w.jpg");
    background-position: top left;
  }
  .basic-py4biii-container1 {
    width: 950px;
    height: auto;
    align-self: center;
    margin-left: 50px;
    padding-top: 20px;
    margin-right: 50px;
    padding-bottom: 10px;
    justify-content: center;
  }
  .basic-py4biii-navlink {
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    border-width: 1px;
    margin-right: 25px;
    background-color: rgb(255, 255, 255);
  }
  .basic-py4biii-navlink1 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py4biii-navlink2 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py4biii-navlink3 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py4biii-container2 {
    width: 750px;
    height: auto;
    align-self: center;
    margin-left: 50px;
    padding-top: 10px;
    margin-right: 50px;
    padding-bottom: 20px;
    justify-content: center;
  }
  .basic-py4biii-navlink4 {
    color: #A068FF;
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py4biii-navlink5 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py4biii-navlink6 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py4biii-content-here {
    width: 1200px;
    align-items: flex-start;
    margin-left: 50px;
    padding-top: 50px;
    margin-right: 50px;
    flex-direction: column;
    padding-bottom: 15px;
  }
  .basic-py4biii-text {
    font-size: 36px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
    padding-top: 0px;
    padding-left: 0px;
    padding-right: 0px;
    padding-bottom: 30px;
  }
  .basic-py4biii-container3 {
    height: auto;
  }
  .basic-py4biii-column {
    flex: 1;
    width: 100%;
    align-self: flex-start;
    align-items: flex-start;
    padding-top: 25px;
    margin-right: var(--dl-space-space-threeunits);
    padding-bottom: 25px;
  }
  .basic-py4biii-text03 {
    font-size: 24px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
    padding-top: 0px;
    padding-left: 0px;
    padding-right: 0px;
    padding-bottom: 25px;
  }
  .basic-py4biii-text06 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-bottom: 30px;
  }
  .basic-py4biii-image {
    width: 409px;
    height: 177px;
    align-self: center;
    border-radius: var(--dl-radius-radius-radius4);
  }
  .basic-py4biii-text07 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-top: 30px;
  }
  .basic-py4biii-text08 {
    font-style: italic;
  }
  .basic-py4biii-text10 {
    font-weight: 700;
  }
  .basic-py4biii-text12 {
    font-style: italic;
  }
  .basic-py4biii-text14 {
    font-weight: 700;
  }
  .basic-py4biii-text16 {
    font-style: italic;
  }
  .basic-py4biii-navlink7 {
    color: var(--dl-color-primary-300);
    text-decoration: underline;
  }
  .basic-py4biii-column1 {
    flex: 1;
    width: 100%;
    align-self: flex-start;
    align-items: flex-start;
    margin-left: var(--dl-space-space-threeunits);
    padding-top: 25px;
    padding-bottom: 25px;
  }
  .basic-py4biii-text20 {
    font-size: 24px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
    padding-top: 0px;
    padding-left: 0px;
    padding-right: 0px;
    padding-bottom: 25px;
  }
  .basic-py4biii-text23 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-bottom: 30px;
  }
  .basic-py4biii-image1 {
    width: auto;
    align-self: center;
    border-radius: var(--dl-radius-radius-radius4);
  }
  .basic-py4biii-text26 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-top: 30px;
  }
  .basic-py4biii-text28 {
    font-style: italic;
  }
  .basic-py4biii-text30 {
    font-weight: 700;
  }
  .basic-py4biii-text32 {
    font-weight: 700;
  }
  .basic-py4biii-text35 {
    font-size: 18px;
    align-self: flex-end;
    font-style: normal;
    font-family: Inter;
    font-weight: 500;
    padding-top: 25px;
    margin-right: 50px;
    padding-bottom: 50px;
  }
  .basic-py4biii-text37 {
    font-style: italic;
  }
  .basic-py4biii-reference {
    width: 1600px;
    height: auto;
    align-self: center;
    box-shadow: 0px -1px 15px 0px #ebebeb;
    align-items: flex-start;
    padding-top: 50px;
    padding-left: 200px;
    padding-right: 200px;
    flex-direction: column;
    padding-bottom: 50px;
    justify-content: flex-start;
  }
  .basic-py4biii-text38 {
    font-size: 32px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
  }
  .basic-py4biii-text39 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.25;
  }
  .basic-py4biii-text40 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py4biii-text41 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py4biii-text42 {
    font-size: 16px;
    font-style: italic;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py4biii-text43 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py4biii-text44 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py4biii-text45 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py4biii-link {
    color: var(--dl-color-primary-300);
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    text-decoration: underline;
  }
  .basic-py4biii-text46 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py4biii-text47 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py4biii-text48 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py4biii-text49 {
    font-size: 16px;
    font-style: italic;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py4biii-text50 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py4biii-text51 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py4biii-text52 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py4biii-link1 {
    color: var(--dl-color-primary-300);
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    text-decoration: underline;
  }
  .basic-py4biii-footer {
    justify-content: space-between;
  }
  .basic-py4biii-navlink8 {
    font-size: 16px;
    font-family: Montserrat;
    font-weight: 700;
    text-decoration: none;
  }
  .basic-py4biii-text54 {
    font-size: 16px;
    font-style: normal;
    font-family: Montserrat;
    font-weight: 500;
  }
  .basic-py4biii-icon {
    margin-left: 50px;
  }
}
@media(max-width: 1200px) {
  .basic-py4biii-heading {
    color: rgb(255, 255, 255);
  }
}
@media(max-width: 479px) {
  .basic-py4biii-footer {
    align-self: center;
  }
  .basic-py4biii-icon-group {
    display: none;
  }
}
</style>
