// [Angular] Website Source Code/src/app/pages/basic-py-2d/basic-py-2d.component.ts
import { Component } from '@angular/core'
import { Title, Meta } from '@angular/platform-browser'

@Component({
  selector: 'basic-py2d',
  templateUrl: 'basic-py-2d.component.html',
  styleUrls: ['basic-py-2d.component.css'],
})
export class BasicPy2d {
  rawettu: string = ' '
  raw9mtt: string = ' '
  rawin14: string = ' '
  rawf5lb: string = ' '
  raw7q27: string = ' '
  rawzk1s: string = ' '
  rawmyiz: string = ' '
  raw00bs: string = ' '
  rawe5o5: string = ' '
  rawlosg: string = ' '
  rawwgag: string = ' '
  rawejsm: string = ' '
  raw74tx: string = ' '
  raw4szc: string = ' '
  rawali1: string = ' '
  raw9gsv: string = ' '
  rawbc2a: string = ' '
  raw4y35: string = ' '
  raw67qu: string = ' '
  raws7jb: string = ' '
  rawv3d2: string = ' '
  constructor(private title: Title, private meta: Meta) {
    this.title.setTitle('Strace | Basic Python')
    this.meta.addTags([
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ])
  }
}

<div class="basic-py2d-container">
  <div class="basic-py2d-banner">
    <div class="basic-py2d-main-content">
      <h1 class="basic-py2d-heading">EXPRESSIONS AND ASSIGNMENT</h1>
      <div class="basic-py2d-container1">
        <a routerLink="/basic-py-2a" class="basic-py2d-navlink button">
          Arithmetic Expressions
        </a>
        <a routerLink="/basic-py-2b" class="basic-py2d-navlink1 button">
          Functional Side Effects
        </a>
        <a routerLink="/basic-py-2ci" class="basic-py2d-navlink2 button">
          Overloaded Operators
        </a>
        <a routerLink="/basic-py-2cii" class="basic-py2d-navlink3 button">
          Type Conversions
        </a>
      </div>
      <div class="basic-py2d-container2">
        <a routerLink="/basic-py-2d" class="basic-py2d-navlink4 button">
          Relational and Boolean Expressions
        </a>
        <a routerLink="/basic-py-2e" class="basic-py2d-navlink5 button">
          Short-Circuit Evaluation
        </a>
        <a routerLink="/basic-py-2f" class="basic-py2d-navlink6 button">
          Assignment Statements
        </a>
        <a routerLink="/basic-py-2g" class="basic-py2d-navlink7 button">
          Mixed-Mode Assignment
        </a>
      </div>
      <div class="basic-py2d-relational-bool-expr">
        <div class="basic-py2d-row">
          <div class="basic-py2d-column">
            <h1 class="basic-py2d-text">
              <span>Relational and Boolean Expressions</span>
              <br />
            </h1>
            <span class="basic-py2d-text03">
              <span>
                As any other programming languages, Python uses the same
                relational and boolean operator for the expressions. Since
                Python is a C-based languages, it applies the same rules for
                precedence of the arithmetic, relational, and Boolean operator.
              </span>
              <br />
            </span>
          </div>
        </div>
        <div class="basic-py2d-example">
          <div class="basic-py2d-container3">
            <h2 class="basic-py2d-text06">Relational</h2>
            <span class="basic-py2d-text07">
              <span>
                There are
                <span [innerHTML]="rawettu"></span>
              </span>
              <span class="basic-py2d-text09">
                six relational operators
                <span [innerHTML]="raw9mtt"></span>
              </span>
              <span>in Python:</span>
              <br />
              <span>
                1.
                <span [innerHTML]="rawin14"></span>
              </span>
              <span class="basic-py2d-text13">
                ==
                <span [innerHTML]="rawf5lb"></span>
              </span>
              <span>(equal to)</span>
              <br />
              <span>
                2.
                <span [innerHTML]="raw7q27"></span>
              </span>
              <span class="basic-py2d-text17">!= </span>
              <span>(not equal to)</span>
              <br />
              <span>
                3.
                <span [innerHTML]="rawzk1s"></span>
              </span>
              <span class="basic-py2d-text21">&lt;</span>
              <span>   (less than)</span>
              <br />
              <span>
                4.
                <span [innerHTML]="rawmyiz"></span>
              </span>
              <span class="basic-py2d-text25">&gt;</span>
              <span>   (greater than)</span>
              <br />
              <span>
                5.
                <span [innerHTML]="raw00bs"></span>
              </span>
              <span class="basic-py2d-text29">&lt;=</span>
              <span>(less than or equal to)</span>
              <br />
              <span>
                6.
                <span [innerHTML]="rawe5o5"></span>
              </span>
              <span class="basic-py2d-text33">&gt;=</span>
              <span>(greater than or equal to)</span>
              <br />
            </span>
            <img
              alt="pastedImage"
              src="/assets/external/expr-bool1-200h.png"
              class="basic-py2d-pasted-image"
            />
            <span class="basic-py2d-text36">
              <span>
                Based on the source code above, we can see that a relational
                operator is used for conditional statement to satisfy the
                <span [innerHTML]="rawlosg"></span>
              </span>
              <span class="basic-py2d-text38">
                if
                <span [innerHTML]="rawwgag"></span>
              </span>
              <span>statement.</span>
            </span>
          </div>
          <div class="basic-py2d-container4">
            <h2 class="basic-py2d-text40">Boolean</h2>
            <span class="basic-py2d-text41">
              <span>
                There are
                <span [innerHTML]="rawejsm"></span>
              </span>
              <span class="basic-py2d-text43">three Boolean operators</span>
              <span>in Python:</span>
              <br />
              <br />
              <span class="basic-py2d-text47">AND</span>
              <span>
                ,
                <span [innerHTML]="raw74tx"></span>
              </span>
              <span class="basic-py2d-text49">OR</span>
              <span>
                , as well as
                <span [innerHTML]="raw4szc"></span>
              </span>
              <span class="basic-py2d-text51">
                NOT
                <span [innerHTML]="rawali1"></span>
              </span>
              <span>(negation)</span>
              <br />
              <br />
              <span>It used </span>
              <span class="basic-py2d-text56">
                English word
                <span [innerHTML]="raw9gsv"></span>
              </span>
              <span>
                to indicate the operator instead of using symbol character like
                other programming languages.
              </span>
              <br />
            </span>
            <img
              alt="pastedImage"
              src="/assets/external/expr-bool2-200h.png"
              class="basic-py2d-pasted-image1"
            />
            <span class="basic-py2d-text59">
              From the example given, Boolean operator can be used in lot of
              ways to satisfy multiple conditional statements.
            </span>
          </div>
        </div>
        <span class="basic-py2d-text60">
          <span>
            -
            <span [innerHTML]="rawbc2a"></span>
          </span>
          <span class="basic-py2d-text62">Muhammad Ariff Ridzlan</span>
        </span>
      </div>
    </div>
  </div>
  <div class="basic-py2d-reference">
    <h1 class="basic-py2d-text63">References</h1>
    <span class="basic-py2d-text64">
      <br />
      <span>
        Prabhu, T. N. (2020, June 5).
        <span [innerHTML]="raw4y35"></span>
      </span>
      <span class="basic-py2d-text67">
        Python Operators from Scratch!!! — A Beginner’s Guide
      </span>
      <span>. Medium.</span>
      <br />
      <span>
                 
        <span [innerHTML]="raw67qu"></span>
      </span>
      <a
        href="https://Prabhu, T. N. (2020, June 5). Python Operators from Scratch!!! — A Beginner’s Guide. Medium. https://towardsdatascience.com/python-operators-from-scratch-a-beginners-guide-8471306f4278"
        target="_blank"
        rel="noreferrer noopener"
        class="basic-py2d-link"
      >
        https://towardsdatascience.com/python-operators-from-scratch-a-beginners-guide-8471306f4278
      </a>
      <br />
      <br />
      <span>
        Datta, S. (2022, March 22).
        <span [innerHTML]="raws7jb"></span>
      </span>
      <span class="basic-py2d-text74">
        Python Operator – Logical Operators in Python
      </span>
      <span>. freeCodeCamp.org.</span>
      <br />
      <span>
                 
        <span [innerHTML]="rawv3d2"></span>
      </span>
      <a
        href="https://Datta, S. (2022, March 22). Python Operator – Logical Operators in Python. freeCodeCamp.org. Retrieved December 24, 2023, from https://www.freecodecamp.org/news/operators-in-python-how-to-use-logical-operators-in-python/"
        target="_blank"
        rel="noreferrer noopener"
        class="basic-py2d-link1"
      >
        https://www.freecodecamp.org/news/operators-in-python-how-to-use-logical-operators-in-python/
      </a>
      <br />
    </span>
  </div>
  <footer class="basic-py2d-footer">
    <div class="basic-py2d-container5">
      <a routerLink="/strace" class="basic-py2d-navlink8">STRACE</a>
    </div>
    <span class="basic-py2d-text79">
      &quot;Making System Calls Cool Again&quot;
    </span>
    <div class="basic-py2d-icon-group">
      <svg viewBox="0 0 877.7142857142857 1024" class="basic-py2d-icon">
        <path
          d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
        ></path>
      </svg>
    </div>
  </footer>
  <app-header></app-header>
</div>

// [Vue] Website Source Code/src/views/basic-py-2d.vue
<template>
  <div class="basic-py2d-container">
    <div class="basic-py2d-banner">
      <div class="basic-py2d-main-content">
        <h1 class="basic-py2d-heading">EXPRESSIONS AND ASSIGNMENT</h1>
        <div class="basic-py2d-container1">
          <router-link to="/basic-py-2a" class="basic-py2d-navlink button">
            Arithmetic Expressions
          </router-link>
          <router-link to="/basic-py-2b" class="basic-py2d-navlink1 button">
            Functional Side Effects
          </router-link>
          <router-link to="/basic-py-2ci" class="basic-py2d-navlink2 button">
            Overloaded Operators
          </router-link>
          <router-link to="/basic-py-2cii" class="basic-py2d-navlink3 button">
            Type Conversions
          </router-link>
        </div>
        <div class="basic-py2d-container2">
          <router-link to="/basic-py-2d" class="basic-py2d-navlink4 button">
            Relational and Boolean Expressions
          </router-link>
          <router-link to="/basic-py-2e" class="basic-py2d-navlink5 button">
            Short-Circuit Evaluation
          </router-link>
          <router-link to="/basic-py-2f" class="basic-py2d-navlink6 button">
            Assignment Statements
          </router-link>
          <router-link to="/basic-py-2g" class="basic-py2d-navlink7 button">
            Mixed-Mode Assignment
          </router-link>
        </div>
        <div class="basic-py2d-relational-bool-expr">
          <div class="basic-py2d-row">
            <div class="basic-py2d-column">
              <h1 class="basic-py2d-text">
                <span>Relational and Boolean Expressions</span>
                <br />
              </h1>
              <span class="basic-py2d-text03">
                <span>
                  As any other programming languages, Python uses the same
                  relational and boolean operator for the expressions. Since
                  Python is a C-based languages, it applies the same rules for
                  precedence of the arithmetic, relational, and Boolean operator.
                </span>
                <br />
              </span>
            </div>
          </div>
          <div class="basic-py2d-example">
            <div class="basic-py2d-container3">
              <h2 class="basic-py2d-text06">Relational</h2>
              <span class="basic-py2d-text07">
                <span>
                  There are
                  <span v-html="raw7czg"></span>
                </span>
                <span class="basic-py2d-text09">
                  six relational operators
                  <span v-html="rawt85w"></span>
                </span>
                <span>in Python:</span>
                <br />
                <span>
                  1.
                  <span v-html="rawqapm"></span>
                </span>
                <span class="basic-py2d-text13">
                  ==
                  <span v-html="rawnbta"></span>
                </span>
                <span>(equal to)</span>
                <br />
                <span>
                  2.
                  <span v-html="raww2m8"></span>
                </span>
                <span class="basic-py2d-text17">!= </span>
                <span>(not equal to)</span>
                <br />
                <span>
                  3.
                  <span v-html="rawebz2"></span>
                </span>
                <span class="basic-py2d-text21">&lt;</span>
                <span>   (less than)</span>
                <br />
                <span>
                  4.
                  <span v-html="rawoyi9"></span>
                </span>
                <span class="basic-py2d-text25">&gt;</span>
                <span>   (greater than)</span>
                <br />
                <span>
                  5.
                  <span v-html="rawjuf3"></span>
                </span>
                <span class="basic-py2d-text29">&lt;=</span>
                <span>(less than or equal to)</span>
                <br />
                <span>
                  6.
                  <span v-html="rawxh2j"></span>
                </span>
                <span class="basic-py2d-text33">&gt;=</span>
                <span>(greater than or equal to)</span>
                <br />
              </span>
              <img
                alt="pastedImage"
                src="/external/expr-bool1-200h.png"
                class="basic-py2d-pasted-image"
              />
              <span class="basic-py2d-text36">
                <span>
                  Based on the source code above, we can see that a relational
                  operator is used for conditional statement to satisfy the
                  <span v-html="rawcgv3"></span>
                </span>
                <span class="basic-py2d-text38">
                  if
                  <span v-html="rawf2dj"></span>
                </span>
                <span>statement.</span>
              </span>
            </div>
            <div class="basic-py2d-container4">
              <h2 class="basic-py2d-text40">Boolean</h2>
              <span class="basic-py2d-text41">
                <span>
                  There are
                  <span v-html="rawrson"></span>
                </span>
                <span class="basic-py2d-text43">three Boolean operators</span>
                <span>in Python:</span>
                <br />
                <br />
                <span class="basic-py2d-text47">AND</span>
                <span>
                  ,
                  <span v-html="raw67ts"></span>
                </span>
                <span class="basic-py2d-text49">OR</span>
                <span>
                  , as well as
                  <span v-html="rawau4d"></span>
                </span>
                <span class="basic-py2d-text51">
                  NOT
                  <span v-html="raws87u"></span>
                </span>
                <span>(negation)</span>
                <br />
                <br />
                <span>It used </span>
                <span class="basic-py2d-text56">
                  English word
                  <span v-html="raw76af"></span>
                </span>
                <span>
                  to indicate the operator instead of using symbol character like
                  other programming languages.
                </span>
                <br />
              </span>
              <img
                alt="pastedImage"
                src="/external/expr-bool2-200h.png"
                class="basic-py2d-pasted-image1"
              />
              <span class="basic-py2d-text59">
                From the example given, Boolean operator can be used in lot of
                ways to satisfy multiple conditional statements.
              </span>
            </div>
          </div>
          <span class="basic-py2d-text60">
            <span>
              -
              <span v-html="rawrerb"></span>
            </span>
            <span class="basic-py2d-text62">Muhammad Ariff Ridzlan</span>
          </span>
        </div>
      </div>
    </div>
    <div class="basic-py2d-reference">
      <h1 class="basic-py2d-text63">References</h1>
      <span class="basic-py2d-text64">
        <br />
        <span>
          Prabhu, T. N. (2020, June 5).
          <span v-html="raw542o"></span>
        </span>
        <span class="basic-py2d-text67">
          Python Operators from Scratch!!! — A Beginner’s Guide
        </span>
        <span>. Medium.</span>
        <br />
        <span>
                   
          <span v-html="rawyi04"></span>
        </span>
        <a
          href="https://Prabhu, T. N. (2020, June 5). Python Operators from Scratch!!! — A Beginner’s Guide. Medium. https://towardsdatascience.com/python-operators-from-scratch-a-beginners-guide-8471306f4278"
          target="_blank"
          rel="noreferrer noopener"
          class="basic-py2d-link"
        >
          https://towardsdatascience.com/python-operators-from-scratch-a-beginners-guide-8471306f4278
        </a>
        <br />
        <br />
        <span>
          Datta, S. (2022, March 22).
          <span v-html="rawewtc"></span>
        </span>
        <span class="basic-py2d-text74">
          Python Operator – Logical Operators in Python
        </span>
        <span>. freeCodeCamp.org.</span>
        <br />
        <span>
                   
          <span v-html="rawk4gk"></span>
        </span>
        <a
          href="https://Datta, S. (2022, March 22). Python Operator – Logical Operators in Python. freeCodeCamp.org. Retrieved December 24, 2023, from https://www.freecodecamp.org/news/operators-in-python-how-to-use-logical-operators-in-python/"
          target="_blank"
          rel="noreferrer noopener"
          class="basic-py2d-link1"
        >
          https://www.freecodecamp.org/news/operators-in-python-how-to-use-logical-operators-in-python/
        </a>
        <br />
      </span>
    </div>
    <footer class="basic-py2d-footer">
      <div class="basic-py2d-container5">
        <router-link to="/strace" class="basic-py2d-navlink8">STRACE</router-link>
      </div>
      <span class="basic-py2d-text79">
        &quot;Making System Calls Cool Again&quot;
      </span>
      <div class="basic-py2d-icon-group">
        <svg viewBox="0 0 877.7142857142857 1024" class="basic-py2d-icon">
          <path
            d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
          ></path>
        </svg>
      </div>
    </footer>
    <app-header></app-header>
  </div>
</template>

<script>
import AppHeader from '../components/header'

export default {
  name: 'BasicPy2d',
  props: {},
  components: {
    AppHeader,
  },
  data() {
    return {
      raw7czg: ' ',
      rawt85w: ' ',
      rawqapm: ' ',
      rawnbta: ' ',
      raww2m8: ' ',
      rawebz2: ' ',
      rawoyi9: ' ',
      rawjuf3: ' ',
      rawxh2j: ' ',
      rawcgv3: ' ',
      rawf2dj: ' ',
      rawrson: ' ',
      raw67ts: ' ',
      rawau4d: ' ',
      raws87u: ' ',
      raw76af: ' ',
      rawrerb: ' ',
      raw542o: ' ',
      rawyi04: ' ',
      rawewtc: ' ',
      rawk4gk: ' ',
    }
  },
  metaInfo: {
    title: 'Strace | Basic Python',
    meta: [
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ],
  },
}
</script>

<style scoped>
.basic-py2d-container {
  width: 100%;
  display: flex;
  overflow: auto;
  min-height: 100vh;
  align-items: center;
  flex-direction: column;
  justify-content: flex-start;
  background-color: #f5f5f5;
}
.basic-py2d-banner {
  width: 100%;
  height: 275px;
  display: flex;
  transition: 0.3s;
  align-items: center;
  flex-direction: column;
  background-size: cover;
  justify-content: center;
  background-image: url('https://marketplace.canva.com/EAD2962NKnQ/2/0/1600w/canva-rainbow-gradient-pink-and-purple-virtual-background-_Tcjok-d9b4.jpg');
}

.basic-py2d-main-content {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: flex-start;
  background-color: #ffffff;
}
.basic-py2d-heading {
  color: #ff0000;
  font-size: 3rem;
  align-self: center;
  text-align: center;
}
.basic-py2d-container1 {
  flex: 0 0 auto;
  width: 100%;
  height: 100px;
  display: flex;
  align-items: flex-start;
}
.basic-py2d-navlink {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2d-navlink:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2d-navlink1 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2d-navlink1:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2d-navlink2 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2d-navlink2:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2d-navlink3 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2d-navlink3:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2d-container2 {
  flex: 0 0 auto;
  width: 100%;
  height: 100px;
  display: flex;
  align-items: flex-start;
}
.basic-py2d-navlink4 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2d-navlink4:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2d-navlink5 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2d-navlink5:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2d-navlink6 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2d-navlink6:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2d-navlink7 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2d-navlink7:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2d-relational-bool-expr {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.basic-py2d-row {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.basic-py2d-column {
  flex: 1;
  width: auto;
  height: auto;
  display: flex;
  flex-direction: column;
}
.basic-py2d-text03 {
  text-align: justify;
}
.basic-py2d-example {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.basic-py2d-container3 {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.basic-py2d-text07 {
  text-align: justify;
}
.basic-py2d-container4 {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.basic-py2d-text41 {
  text-align: justify;
}
.basic-py2d-reference {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #ffffff;
}
.basic-py2d-footer {
  width: 100%;
  display: flex;
  max-width: var(--dl-size-size-maxwidth);
  align-self: center;
  align-items: center;
  padding-top: var(--dl-space-space-twounits);
  padding-left: var(--dl-space-space-threeunits);
  padding-right: var(--dl-space-space-threeunits);
  padding-bottom: var(--dl-space-space-twounits);
  justify-content: space-between;
}
.basic-py2d-container5 {
  flex: 0 0 auto;
  width: auto;
  height: auto;
  display: flex;
  align-items: space-between;
  flex-direction: column;
}
.basic-py2d-navlink8 {
  font-weight: 700;
  text-decoration: none;
}
.basic-py2d-icon {
  width: 24px;
  height: 24px;
}
@media(max-width: 1600px) {
  .basic-py2d-container {
    background-color: #f7f7f7;
  }
  .basic-py2d-banner {
    height: auto;
    align-items: center;
    background-size: cover;
    justify-content: flex-start;
    background-image: url("/external/bgportrait-1500w.jpg");
  }
  .basic-py2d-main-content {
    flex: 1;
    width: 1300px;
    height: auto;
    box-shadow: 0px 0px 10px 0px #d3d2d6;
    align-items: flex-start;
    padding-top: 100px;
    flex-direction: column;
    justify-content: flex-start;
    background-color: #ffffff;
  }
  .basic-py2d-heading {
    color: rgb(255, 255, 255);
    width: 1200px;
    height: auto;
    font-size: 64px;
    font-style: normal;
    margin-top: 40px;
    font-family: Montserrat;
    font-weight: 700;
    line-height: 1.15;
    padding-top: 40px;
    border-radius: var(--dl-radius-radius-radius4);
    margin-bottom: 20px;
    padding-bottom: 40px;
    background-size: auto;
    background-image: url("/external/bglandscape-1200w.jpg");
  }
  .basic-py2d-container1 {
    width: 700px;
    height: auto;
    align-self: center;
    margin-left: 50px;
    padding-top: 20px;
    margin-right: 50px;
    padding-bottom: 10px;
    justify-content: center;
  }
  .basic-py2d-navlink {
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2d-navlink1 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2d-navlink2 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2d-navlink3 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2d-container2 {
    width: 800px;
    height: auto;
    align-self: center;
    margin-left: 50px;
    padding-top: 10px;
    margin-right: 50px;
    padding-bottom: 20px;
    justify-content: center;
  }
  .basic-py2d-navlink4 {
    color: #A068FF;
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2d-navlink5 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2d-navlink6 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2d-navlink7 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2d-relational-bool-expr {
    width: 1200px;
    align-items: flex-end;
    margin-left: 50px;
    padding-top: 50px;
    margin-right: 50px;
    padding-bottom: 50px;
  }
  .basic-py2d-row {
    margin-bottom: 30px;
    justify-content: space-between;
  }
  .basic-py2d-column {
    flex: 1;
    align-items: flex-start;
  }
  .basic-py2d-text {
    font-size: 36px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
    padding-top: 0px;
    padding-left: 0px;
    padding-right: 0px;
    padding-bottom: 30px;
  }
  .basic-py2d-text03 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
  }
  .basic-py2d-example {
    justify-content: space-between;
  }
  .basic-py2d-container3 {
    width: 575px;
    height: auto;
  }
  .basic-py2d-text06 {
    font-size: 24px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
    margin-bottom: 20px;
  }
  .basic-py2d-text07 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.25;
  }
  .basic-py2d-text09 {
    font-weight: 700;
  }
  .basic-py2d-text13 {
    font-weight: 700;
  }
  .basic-py2d-text17 {
    font-weight: 700;
  }
  .basic-py2d-text21 {
    font-weight: 700;
  }
  .basic-py2d-text25 {
    font-weight: 700;
  }
  .basic-py2d-text29 {
    font-weight: 700;
  }
  .basic-py2d-text33 {
    font-weight: 700;
  }
  .basic-py2d-pasted-image {
    width: 369px;
    height: 54px;
    margin-top: 25px;
    border-radius: var(--dl-radius-radius-radius4);
    margin-bottom: 25px;
  }
  .basic-py2d-text36 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py2d-text38 {
    font-style: italic;
  }
  .basic-py2d-container4 {
    width: 575px;
    height: auto;
  }
  .basic-py2d-text40 {
    font-size: 24px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
    margin-bottom: 20px;
  }
  .basic-py2d-text41 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.25;
  }
  .basic-py2d-text43 {
    font-weight: 700;
  }
  .basic-py2d-text47 {
    font-weight: 700;
  }
  .basic-py2d-text49 {
    font-weight: 700;
  }
  .basic-py2d-text51 {
    font-weight: 700;
  }
  .basic-py2d-text56 {
    font-weight: 700;
  }
  .basic-py2d-pasted-image1 {
    width: 468px;
    height: 80px;
    margin-top: 25px;
    border-radius: var(--dl-radius-radius-radius4);
    margin-bottom: 25px;
  }
  .basic-py2d-text59 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py2d-text60 {
    font-size: 18px;
    font-style: normal;
    font-family: Inter;
    font-weight: 500;
    padding-top: 25px;
  }
  .basic-py2d-text62 {
    font-style: italic;
  }
  .basic-py2d-reference {
    width: 1600px;
    height: auto;
    align-self: center;
    box-shadow: 0px -1px 15px 0px #ebebeb;
    align-items: flex-start;
    padding-top: 50px;
    padding-left: 200px;
    padding-right: 200px;
    flex-direction: column;
    padding-bottom: 50px;
    justify-content: flex-start;
  }
  .basic-py2d-text63 {
    font-size: 32px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
  }
  .basic-py2d-text64 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.25;
  }
  .basic-py2d-text67 {
    font-style: italic;
  }
  .basic-py2d-link {
    color: var(--dl-color-primary-300);
    text-decoration: underline;
  }
  .basic-py2d-text74 {
    font-style: italic;
  }
  .basic-py2d-link1 {
    color: var(--dl-color-primary-300);
    text-decoration: underline;
  }
  .basic-py2d-footer {
    justify-content: space-between;
  }
  .basic-py2d-navlink8 {
    font-size: 16px;
    font-family: Montserrat;
    font-weight: 700;
    text-decoration: none;
  }
  .basic-py2d-text79 {
    font-size: 16px;
    font-style: normal;
    font-family: Montserrat;
    font-weight: 500;
  }
  .basic-py2d-icon {
    margin-left: 50px;
  }
}
@media(max-width: 1200px) {
  .basic-py2d-heading {
    color: rgb(255, 255, 255);
  }
}
@media(max-width: 479px) {
  .basic-py2d-footer {
    align-self: center;
  }
  .basic-py2d-icon-group {
    display: none;
  }
}
</style>
