// [Angular] Website Source Code/src/app/pages/basic-py-2ci/basic-py-2ci.component.ts
import { Component } from '@angular/core'
import { Title, Meta } from '@angular/platform-browser'

@Component({
  selector: 'basic-py2ci',
  templateUrl: 'basic-py-2ci.component.html',
  styleUrls: ['basic-py-2ci.component.css'],
})
export class BasicPy2ci {
  raw6mhs: string = ' '
  raw88n2: string = ' '
  rawhfus: string = ' '
  constructor(private title: Title, private meta: Meta) {
    this.title.setTitle('Strace | Basic Python')
    this.meta.addTags([
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ])
  }
}

<div class="basic-py2ci-container">
  <div class="basic-py2ci-banner">
    <div class="basic-py2ci-main-content">
      <h1 class="basic-py2ci-heading">EXPRESSIONS AND ASSIGNMENT</h1>
      <div class="basic-py2ci-container1">
        <a routerLink="/basic-py-2a" class="basic-py2ci-navlink button">
          Arithmetic Expressions
        </a>
        <a routerLink="/basic-py-2b" class="basic-py2ci-navlink1 button">
          Functional Side Effects
        </a>
        <a routerLink="/basic-py-2ci" class="basic-py2ci-navlink2 button">
          Overloaded Operators
        </a>
        <a routerLink="/basic-py-2cii" class="basic-py2ci-navlink3 button">
          Type Conversions
        </a>
      </div>
      <div class="basic-py2ci-container2">
        <a routerLink="/basic-py-2d" class="basic-py2ci-navlink4 button">
          Relational and Boolean Expressions
        </a>
        <a routerLink="/basic-py-2e" class="basic-py2ci-navlink5 button">
          Short-Circuit Evaluation
        </a>
        <a routerLink="/basic-py-2f" class="basic-py2ci-navlink6 button">
          Assignment Statements
        </a>
        <a routerLink="/basic-py-2g" class="basic-py2ci-navlink7 button">
          Mixed-Mode Assignment
        </a>
      </div>
      <div class="basic-py2ci-hapih">
        <h1 class="basic-py2ci-text">
          <span class="basic-py2ci-text01">Overloaded Operators</span>
          <br />
        </h1>
        <span class="basic-py2ci-text03">
          <span class="basic-py2ci-text04">
            Operator Overloading means giving extended meaning beyond their
            predefined operational meaning. For example operator + is used to
            add two integers as well as join two strings and merge two lists. It
            is achievable because ‘+’ operator is overloaded by int class and
            str class. You might have noticed that the same
          </span>
          <br class="basic-py2ci-text05" />
          <span class="basic-py2ci-text06">
            built-in operator or function shows different behavior for objects
            of different classes, this is called Operator Overloading.
          </span>
          <br />
          <br />
          <span><span [innerHTML]="raw6mhs"></span></span>
        </span>
        <span class="basic-py2ci-text10">
          <span class="basic-py2ci-text11">
            Python has a special function, often known as a magic function, that
            is automatically called when it is associated with a specific
            operator in order to conduct operator overloading. For instance, the
            magic method __add__, which defines the action for the + operator,
            is automatically called when we use the + operator.
          </span>
          <br />
          <br />
          <br />
        </span>
        <span class="basic-py2ci-text15">
          <span>
            -
            <span [innerHTML]="raw88n2"></span>
          </span>
          <span>Muhammad Hafiz</span>
        </span>
        <form class="basic-py2ci-form"></form>
        <img
          alt="image"
          src="https://raw.githubusercontent.com/rydzze/TPL6213-Project/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/2a%20Expressions%20and%20Assignment/binary%20table.png"
          class="basic-py2ci-image"
        />
        <img
          alt="image"
          src="https://raw.githubusercontent.com/rydzze/TPL6213-Project/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/2a%20Expressions%20and%20Assignment/assignment%20table.png"
          class="basic-py2ci-image1"
        />
        <img
          alt="image"
          src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/2a%20Expressions%20and%20Assignment/Comparison%20table.png?raw=true"
          class="basic-py2ci-image2"
        />
        <img
          alt="image"
          src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/2a%20Expressions%20and%20Assignment/unary%20table.png?raw=true"
          class="basic-py2ci-image3"
        />
        <span class="basic-py2ci-text18">Binary Operator</span>
        <span class="basic-py2ci-text19">Assignment Operator</span>
        <span class="basic-py2ci-text20">Comparison Operator</span>
        <span class="basic-py2ci-text21">Unary Operator</span>
      </div>
    </div>
  </div>
  <div class="basic-py2ci-reference">
    <h1 class="basic-py2ci-text22">References</h1>
    <span class="basic-py2ci-text23">
      <br class="basic-py2ci-text24" />
      <span class="basic-py2ci-text25">Operator Overloading in Python</span>
      <span class="basic-py2ci-text26">
        . (2018, December 10). GeeksforGeeks.
      </span>
      <br class="basic-py2ci-text27" />
      <span class="basic-py2ci-text28">
               
        <span [innerHTML]="rawhfus"></span>
      </span>
      <a
        href="https://www.geeksforgeeks.org/operator-overloading-in-python/"
        target="_blank"
        rel="noreferrer noopener"
        class="basic-py2ci-link"
      >
        https://www.geeksforgeeks.org/operator-overloading-in-python/
      </a>
    </span>
  </div>
  <footer class="basic-py2ci-footer">
    <div class="basic-py2ci-container3">
      <a routerLink="/strace" class="basic-py2ci-navlink8">STRACE</a>
    </div>
    <span class="basic-py2ci-text29">
      &quot;Making System Calls Cool Again&quot;
    </span>
    <div class="basic-py2ci-icon-group">
      <svg viewBox="0 0 877.7142857142857 1024" class="basic-py2ci-icon">
        <path
          d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
        ></path>
      </svg>
    </div>
  </footer>
  <app-header></app-header>
</div>

// [Vue] Website Source Code/src/views/basic-py-2ci.vue
<template>
  <div class="basic-py2ci-container">
    <div class="basic-py2ci-banner">
      <div class="basic-py2ci-main-content">
        <h1 class="basic-py2ci-heading">EXPRESSIONS AND ASSIGNMENT</h1>
        <div class="basic-py2ci-container1">
          <router-link to="/basic-py-2a" class="basic-py2ci-navlink button">
            Arithmetic Expressions
          </router-link>
          <router-link to="/basic-py-2b" class="basic-py2ci-navlink1 button">
            Functional Side Effects
          </router-link>
          <router-link to="/basic-py-2ci" class="basic-py2ci-navlink2 button">
            Overloaded Operators
          </router-link>
          <router-link to="/basic-py-2cii" class="basic-py2ci-navlink3 button">
            Type Conversions
          </router-link>
        </div>
        <div class="basic-py2ci-container2">
          <router-link to="/basic-py-2d" class="basic-py2ci-navlink4 button">
            Relational and Boolean Expressions
          </router-link>
          <router-link to="/basic-py-2e" class="basic-py2ci-navlink5 button">
            Short-Circuit Evaluation
          </router-link>
          <router-link to="/basic-py-2f" class="basic-py2ci-navlink6 button">
            Assignment Statements
          </router-link>
          <router-link to="/basic-py-2g" class="basic-py2ci-navlink7 button">
            Mixed-Mode Assignment
          </router-link>
        </div>
        <div class="basic-py2ci-hapih">
          <h1 class="basic-py2ci-text">
            <span class="basic-py2ci-text01">Overloaded Operators</span>
            <br />
          </h1>
          <span class="basic-py2ci-text03">
            <span class="basic-py2ci-text04">
              Operator Overloading means giving extended meaning beyond their
              predefined operational meaning. For example operator + is used to
              add two integers as well as join two strings and merge two lists. It
              is achievable because ‘+’ operator is overloaded by int class and
              str class. You might have noticed that the same
            </span>
            <br class="basic-py2ci-text05" />
            <span class="basic-py2ci-text06">
              built-in operator or function shows different behavior for objects
              of different classes, this is called Operator Overloading.
            </span>
            <br />
            <br />
            <span><span v-html="rawca3v"></span></span>
          </span>
          <span class="basic-py2ci-text10">
            <span class="basic-py2ci-text11">
              Python has a special function, often known as a magic function, that
              is automatically called when it is associated with a specific
              operator in order to conduct operator overloading. For instance, the
              magic method __add__, which defines the action for the + operator,
              is automatically called when we use the + operator.
            </span>
            <br />
            <br />
            <br />
          </span>
          <span class="basic-py2ci-text15">
            <span>
              -
              <span v-html="rawvaxe"></span>
            </span>
            <span>Muhammad Hafiz</span>
          </span>
          <form class="basic-py2ci-form"></form>
          <img
            alt="image"
            src="https://raw.githubusercontent.com/rydzze/TPL6213-Project/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/2a%20Expressions%20and%20Assignment/binary%20table.png"
            class="basic-py2ci-image"
          />
          <img
            alt="image"
            src="https://raw.githubusercontent.com/rydzze/TPL6213-Project/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/2a%20Expressions%20and%20Assignment/assignment%20table.png"
            class="basic-py2ci-image1"
          />
          <img
            alt="image"
            src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/2a%20Expressions%20and%20Assignment/Comparison%20table.png?raw=true"
            class="basic-py2ci-image2"
          />
          <img
            alt="image"
            src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/2a%20Expressions%20and%20Assignment/unary%20table.png?raw=true"
            class="basic-py2ci-image3"
          />
          <span class="basic-py2ci-text18">Binary Operator</span>
          <span class="basic-py2ci-text19">Assignment Operator</span>
          <span class="basic-py2ci-text20">Comparison Operator</span>
          <span class="basic-py2ci-text21">Unary Operator</span>
        </div>
      </div>
    </div>
    <div class="basic-py2ci-reference">
      <h1 class="basic-py2ci-text22">References</h1>
      <span class="basic-py2ci-text23">
        <br class="basic-py2ci-text24" />
        <span class="basic-py2ci-text25">Operator Overloading in Python</span>
        <span class="basic-py2ci-text26">
          . (2018, December 10). GeeksforGeeks.
        </span>
        <br class="basic-py2ci-text27" />
        <span class="basic-py2ci-text28">
                 
          <span v-html="rawwb9e"></span>
        </span>
        <a
          href="https://www.geeksforgeeks.org/operator-overloading-in-python/"
          target="_blank"
          rel="noreferrer noopener"
          class="basic-py2ci-link"
        >
          https://www.geeksforgeeks.org/operator-overloading-in-python/
        </a>
      </span>
    </div>
    <footer class="basic-py2ci-footer">
      <div class="basic-py2ci-container3">
        <router-link to="/strace" class="basic-py2ci-navlink8">
          STRACE
        </router-link>
      </div>
      <span class="basic-py2ci-text29">
        &quot;Making System Calls Cool Again&quot;
      </span>
      <div class="basic-py2ci-icon-group">
        <svg viewBox="0 0 877.7142857142857 1024" class="basic-py2ci-icon">
          <path
            d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
          ></path>
        </svg>
      </div>
    </footer>
    <app-header></app-header>
  </div>
</template>

<script>
import AppHeader from '../components/header'

export default {
  name: 'BasicPy2ci',
  props: {},
  components: {
    AppHeader,
  },
  data() {
    return {
      rawca3v: ' ',
      rawvaxe: ' ',
      rawwb9e: ' ',
    }
  },
  metaInfo: {
    title: 'Strace | Basic Python',
    meta: [
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ],
  },
}
</script>

<style scoped>
.basic-py2ci-container {
  width: 100%;
  display: flex;
  overflow: auto;
  min-height: 100vh;
  align-items: center;
  flex-direction: column;
  justify-content: flex-start;
  background-color: #f5f5f5;
}
.basic-py2ci-banner {
  width: 100%;
  height: 275px;
  display: flex;
  transition: 0.3s;
  align-items: center;
  flex-direction: column;
  background-size: cover;
  justify-content: center;
  background-image: url('https://marketplace.canva.com/EAD2962NKnQ/2/0/1600w/canva-rainbow-gradient-pink-and-purple-virtual-background-_Tcjok-d9b4.jpg');
}

.basic-py2ci-main-content {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: flex-start;
  background-color: #ffffff;
}
.basic-py2ci-heading {
  color: #ff0000;
  font-size: 3rem;
  align-self: center;
  text-align: center;
}
.basic-py2ci-container1 {
  flex: 0 0 auto;
  width: 100%;
  height: 100px;
  display: flex;
  align-items: flex-start;
}
.basic-py2ci-navlink {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2ci-navlink:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2ci-navlink1 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2ci-navlink1:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2ci-navlink2 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2ci-navlink2:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2ci-navlink3 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2ci-navlink3:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2ci-container2 {
  flex: 0 0 auto;
  width: 100%;
  height: 100px;
  display: flex;
  align-items: flex-start;
}
.basic-py2ci-navlink4 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2ci-navlink4:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2ci-navlink5 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2ci-navlink5:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2ci-navlink6 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2ci-navlink6:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2ci-navlink7 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2ci-navlink7:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2ci-hapih {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.basic-py2ci-form {
  width: 200px;
  height: 100px;
  display: flex;
  align-items: center;
  justify-content: center;
}
.basic-py2ci-image {
  width: 200px;
  object-fit: cover;
}
.basic-py2ci-image1 {
  width: 200px;
  object-fit: cover;
}
.basic-py2ci-image2 {
  width: 200px;
  object-fit: cover;
}
.basic-py2ci-image3 {
  width: 200px;
  object-fit: cover;
}
.basic-py2ci-reference {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #ffffff;
}
.basic-py2ci-footer {
  width: 100%;
  display: flex;
  max-width: var(--dl-size-size-maxwidth);
  align-self: center;
  align-items: center;
  padding-top: var(--dl-space-space-twounits);
  padding-left: var(--dl-space-space-threeunits);
  padding-right: var(--dl-space-space-threeunits);
  padding-bottom: var(--dl-space-space-twounits);
  justify-content: space-between;
}
.basic-py2ci-container3 {
  flex: 0 0 auto;
  width: auto;
  height: auto;
  display: flex;
  align-items: space-between;
  flex-direction: column;
}
.basic-py2ci-navlink8 {
  font-weight: 700;
  text-decoration: none;
}
.basic-py2ci-icon {
  width: 24px;
  height: 24px;
}
@media(max-width: 1600px) {
  .basic-py2ci-container {
    background-color: #f7f7f7;
  }
  .basic-py2ci-banner {
    height: auto;
    align-items: center;
    background-size: cover;
    justify-content: flex-start;
    background-image: url("/external/bgportrait-1500w.jpg");
  }
  .basic-py2ci-main-content {
    flex: 1;
    width: 1300px;
    height: auto;
    box-shadow: 0px 0px 10px 0px #d3d2d6;
    align-items: flex-start;
    padding-top: 100px;
    flex-direction: column;
    justify-content: flex-start;
    background-color: #ffffff;
  }
  .basic-py2ci-heading {
    color: rgb(255, 255, 255);
    width: 1200px;
    height: auto;
    font-size: 64px;
    font-style: normal;
    margin-top: 40px;
    font-family: Montserrat;
    font-weight: 700;
    line-height: 1.15;
    padding-top: 40px;
    border-radius: var(--dl-radius-radius-radius4);
    margin-bottom: 20px;
    padding-bottom: 40px;
    background-size: auto;
    background-image: url("/external/bglandscape-1200w.jpg");
  }
  .basic-py2ci-container1 {
    width: 700px;
    height: auto;
    align-self: center;
    margin-left: 50px;
    padding-top: 20px;
    margin-right: 50px;
    padding-bottom: 10px;
    justify-content: center;
  }
  .basic-py2ci-navlink {
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2ci-navlink1 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2ci-navlink2 {
    color: #A068FF;
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2ci-navlink3 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2ci-container2 {
    width: 800px;
    height: auto;
    align-self: center;
    margin-left: 50px;
    padding-top: 10px;
    margin-right: 50px;
    padding-bottom: 20px;
    justify-content: center;
  }
  .basic-py2ci-navlink4 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2ci-navlink5 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2ci-navlink6 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2ci-navlink7 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2ci-hapih {
    width: 1200px;
    height: 750px;
    position: relative;
    margin-left: 50px;
    padding-top: 50px;
    margin-right: 50px;
    padding-bottom: 50px;
  }
  .basic-py2ci-text {
    font-size: 36px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
    margin-bottom: 10px;
  }
  .basic-py2ci-text01 {
    margin-bottom: 10px;
  }
  .basic-py2ci-text03 {
    font-size: 25px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
  }
  .basic-py2ci-text04 {
    font-size: 16px;
  }
  .basic-py2ci-text05 {
    font-size: 16px;
  }
  .basic-py2ci-text06 {
    font-size: 16px;
  }
  .basic-py2ci-text10 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
  }
  .basic-py2ci-text11 {
    text-align: justify;
  }
  .basic-py2ci-text15 {
    font-size: 18px;
    align-self: flex-end;
    font-style: italic;
    font-family: Inter;
    font-weight: 500;
    padding-top: 25px;
  }
  .basic-py2ci-image {
    top: 293px;
    left: 0px;
    width: 228px;
    height: 312px;
    position: absolute;
  }
  .basic-py2ci-image1 {
    top: 294px;
    left: 283px;
    width: 228px;
    height: 312px;
    position: absolute;
  }
  .basic-py2ci-image2 {
    top: 352px;
    left: 585px;
    width: 263px;
    height: 194px;
    position: absolute;
  }
  .basic-py2ci-image3 {
    top: 397px;
    right: 67px;
    width: 266px;
    height: 111px;
    position: absolute;
  }
  .basic-py2ci-text18 {
    left: 52px;
    bottom: 99px;
    position: absolute;
  }
  .basic-py2ci-text19 {
    left: 318px;
    bottom: 99px;
    position: absolute;
  }
  .basic-py2ci-text20 {
    top: 569px;
    left: 632px;
    position: absolute;
  }
  .basic-py2ci-text21 {
    top: 540px;
    right: 137px;
    position: absolute;
  }
  .basic-py2ci-reference {
    width: 1600px;
    height: auto;
    align-self: center;
    box-shadow: 0px -1px 15px 0px #ebebeb;
    align-items: flex-start;
    padding-top: 50px;
    padding-left: 200px;
    padding-right: 200px;
    flex-direction: column;
    padding-bottom: 50px;
    justify-content: flex-start;
  }
  .basic-py2ci-text22 {
    font-size: 32px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
  }
  .basic-py2ci-text23 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.25;
  }
  .basic-py2ci-text24 {
    font-style: normal;
  }
  .basic-py2ci-text25 {
    font-style: italic;
  }
  .basic-py2ci-text26 {
    font-style: normal;
  }
  .basic-py2ci-text27 {
    font-style: normal;
  }
  .basic-py2ci-text28 {
    font-style: normal;
  }
  .basic-py2ci-link {
    color: var(--dl-color-primary-300);
    font-style: normal;
    text-decoration: underline;
  }
  .basic-py2ci-footer {
    justify-content: space-between;
  }
  .basic-py2ci-navlink8 {
    font-size: 16px;
    font-family: Montserrat;
    font-weight: 700;
    text-decoration: none;
  }
  .basic-py2ci-text29 {
    font-size: 16px;
    font-style: normal;
    font-family: Montserrat;
    font-weight: 500;
  }
  .basic-py2ci-icon {
    margin-left: 50px;
  }
}
@media(max-width: 1200px) {
  .basic-py2ci-heading {
    color: rgb(255, 255, 255);
  }
}
@media(max-width: 479px) {
  .basic-py2ci-footer {
    align-self: center;
  }
  .basic-py2ci-icon-group {
    display: none;
  }
}
</style>
