// [Angular] Website Source Code/src/app/pages/basic-py-2a/basic-py-2a.component.ts
import { Component } from '@angular/core'
import { Title, Meta } from '@angular/platform-browser'

@Component({
  selector: 'basic-py2a',
  templateUrl: 'basic-py-2a.component.html',
  styleUrls: ['basic-py-2a.component.css'],
})
export class BasicPy2a {
  rawp871: string = ' '
  rawo4gt: string = ' '
  raw90g2: string = ' '
  raw1jpc: string = ' '
  rawmxig: string = ' '
  rawvzbt: string = ' '
  raw8f9i: string = ' '
  constructor(private title: Title, private meta: Meta) {
    this.title.setTitle('Strace | Basic Python')
    this.meta.addTags([
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ])
  }
}

<div class="basic-py2a-container">
  <div class="basic-py2a-banner">
    <div class="basic-py2a-main-content">
      <h1 class="basic-py2a-heading">EXPRESSIONS AND ASSIGNMENT</h1>
      <div class="basic-py2a-container1">
        <a routerLink="/basic-py-2a" class="basic-py2a-navlink button">
          Arithmetic Expressions
        </a>
        <a routerLink="/basic-py-2b" class="basic-py2a-navlink1 button">
          Functional Side Effects
        </a>
        <a routerLink="/basic-py-2ci" class="basic-py2a-navlink2 button">
          Overloaded Operators
        </a>
        <a routerLink="/basic-py-2cii" class="basic-py2a-navlink3 button">
          Type Conversions
        </a>
      </div>
      <div class="basic-py2a-container2">
        <a routerLink="/basic-py-2d" class="basic-py2a-navlink4 button">
          Relational and Boolean Expressions
        </a>
        <a routerLink="/basic-py-2e" class="basic-py2a-navlink5 button">
          Short-Circuit Evaluation
        </a>
        <a routerLink="/basic-py-2f" class="basic-py2a-navlink6 button">
          Assignment Statements
        </a>
        <a routerLink="/basic-py-2g" class="basic-py2a-navlink7 button">
          Mixed-Mode Assignment
        </a>
      </div>
      <div class="basic-py2a-alia">
        <div class="basic-py2a-arithmetic">
          <h1 class="basic-py2a-text">
            <span>Arithmetic Expressions</span>
            <br />
          </h1>
          <div class="basic-py2a-container3">
            <div class="basic-py2a-container4">
              <span class="basic-py2a-text03">
                <span class="basic-py2a-text04">
                  Precedence
                  <span [innerHTML]="rawp871"></span>
                </span>
                <span>
                  and
                  <span [innerHTML]="rawo4gt"></span>
                </span>
                <span class="basic-py2a-text06">
                  associativity rule
                  <span [innerHTML]="raw90g2"></span>
                </span>
                <span>for Python.</span>
              </span>
              <img
                alt="image"
                src="/assets/external/screenshot%202023-12-29%20142936-900h-900h.png"
                class="basic-py2a-image"
              />
            </div>
            <div class="basic-py2a-conditional-exp">
              <img
                alt="image"
                src="/assets/external/screenshot%202023-12-28%20205424-200h-200h.png"
                class="basic-py2a-image1"
              />
              <span class="basic-py2a-text08">
                Given example is the arithmetic operator multiplication (*) that
                is being used by the program to find totalprice.
              </span>
              <span class="basic-py2a-text09">Conditional Expression</span>
              <div class="basic-py2a-container5">
                <span class="basic-py2a-text10">
                  <span>
                    Like in C++ languages, Python also have the conditional
                    expression that can be written in one line. They have
                    ternary operators but instead of using ‘?’ and ‘:’, python
                    use ‘if’ and ‘else’ keyword.
                  </span>
                  <br />
                  <br />
                  <span>
                    The code above means that if expression_1 is true, so the
                    output will be expression_2, otherwise, it is go to
                    expression_3.
                  </span>
                </span>
                <img
                  alt="image"
                  src="/assets/external/screenshot%202023-12-29%20104022-600w-600w.png"
                  class="basic-py2a-image2"
                />
              </div>
            </div>
          </div>
        </div>
        <span class="basic-py2a-text15">- Noor Alia Alisa</span>
      </div>
    </div>
  </div>
  <div class="basic-py2a-reference">
    <h1 class="basic-py2a-text16">References</h1>
    <span class="basic-py2a-text17">
      <br class="basic-py2a-text18" />
      <span class="basic-py2a-text19">
        Singh, A. (2023, August 3).
        <span [innerHTML]="raw1jpc"></span>
      </span>
      <span class="basic-py2a-text20">
        This article will teach you about operator precedence and associativity
        in Python
      </span>
      <span class="basic-py2a-text21">. Medium.</span>
      <br class="basic-py2a-text22" />
      <span class="basic-py2a-text23">
               
        <span [innerHTML]="rawmxig"></span>
      </span>
      <a
        href="https://medium.com/@rishu__2701/this-article-will-teach-you-about-operator-precedence-and-associativity-in-python-ee455c7fbfee"
        target="_blank"
        rel="noreferrer noopener"
        class="basic-py2a-link"
      >
        https://medium.com/@rishu__2701/this-article-will-teach-you-about-operator-precedence-and-associativity-in-python-ee455c7fbfee
      </a>
      <br class="basic-py2a-text24" />
      <br class="basic-py2a-text25" />
      <span class="basic-py2a-text26">
        Conditional expression (ternary operator) in Python
        <span [innerHTML]="rawvzbt"></span>
      </span>
      <span class="basic-py2a-text27">(2023, August 18). note.nkmk.me.</span>
      <br class="basic-py2a-text28" />
      <span class="basic-py2a-text29">
               
        <span [innerHTML]="raw8f9i"></span>
      </span>
      <a
        href="https://note.nkmk.me/en/python-if-conditional-expressions/"
        target="_blank"
        rel="noreferrer noopener"
        class="basic-py2a-link1"
      >
        https://note.nkmk.me/en/python-if-conditional-expressions/
      </a>
      <br />
    </span>
  </div>
  <footer class="basic-py2a-footer">
    <div class="basic-py2a-container6">
      <a routerLink="/strace" class="basic-py2a-navlink8">STRACE</a>
    </div>
    <span class="basic-py2a-text31">
      &quot;Making System Calls Cool Again&quot;
    </span>
    <div class="basic-py2a-icon-group">
      <svg viewBox="0 0 877.7142857142857 1024" class="basic-py2a-icon">
        <path
          d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
        ></path>
      </svg>
    </div>
  </footer>
  <app-header></app-header>
</div>

// [Vue] Website Source Code/src/views/basic-py-2a.vue
<template>
  <div class="basic-py2a-container">
    <div class="basic-py2a-banner">
      <div class="basic-py2a-main-content">
        <h1 class="basic-py2a-heading">EXPRESSIONS AND ASSIGNMENT</h1>
        <div class="basic-py2a-container1">
          <router-link to="/basic-py-2a" class="basic-py2a-navlink button">
            Arithmetic Expressions
          </router-link>
          <router-link to="/basic-py-2b" class="basic-py2a-navlink1 button">
            Functional Side Effects
          </router-link>
          <router-link to="/basic-py-2ci" class="basic-py2a-navlink2 button">
            Overloaded Operators
          </router-link>
          <router-link to="/basic-py-2cii" class="basic-py2a-navlink3 button">
            Type Conversions
          </router-link>
        </div>
        <div class="basic-py2a-container2">
          <router-link to="/basic-py-2d" class="basic-py2a-navlink4 button">
            Relational and Boolean Expressions
          </router-link>
          <router-link to="/basic-py-2e" class="basic-py2a-navlink5 button">
            Short-Circuit Evaluation
          </router-link>
          <router-link to="/basic-py-2f" class="basic-py2a-navlink6 button">
            Assignment Statements
          </router-link>
          <router-link to="/basic-py-2g" class="basic-py2a-navlink7 button">
            Mixed-Mode Assignment
          </router-link>
        </div>
        <div class="basic-py2a-alia">
          <div class="basic-py2a-arithmetic">
            <h1 class="basic-py2a-text">
              <span>Arithmetic Expressions</span>
              <br />
            </h1>
            <div class="basic-py2a-container3">
              <div class="basic-py2a-container4">
                <span class="basic-py2a-text03">
                  <span class="basic-py2a-text04">
                    Precedence
                    <span v-html="raw2595"></span>
                  </span>
                  <span>
                    and
                    <span v-html="rawgwst"></span>
                  </span>
                  <span class="basic-py2a-text06">
                    associativity rule
                    <span v-html="raw6ifz"></span>
                  </span>
                  <span>for Python.</span>
                </span>
                <img
                  alt="image"
                  src="/external/screenshot%202023-12-29%20142936-900h-900h.png"
                  class="basic-py2a-image"
                />
              </div>
              <div class="basic-py2a-conditional-exp">
                <img
                  alt="image"
                  src="/external/screenshot%202023-12-28%20205424-200h-200h.png"
                  class="basic-py2a-image1"
                />
                <span class="basic-py2a-text08">
                  Given example is the arithmetic operator multiplication (*) that
                  is being used by the program to find totalprice.
                </span>
                <span class="basic-py2a-text09">Conditional Expression</span>
                <div class="basic-py2a-container5">
                  <span class="basic-py2a-text10">
                    <span>
                      Like in C++ languages, Python also have the conditional
                      expression that can be written in one line. They have
                      ternary operators but instead of using ‘?’ and ‘:’, python
                      use ‘if’ and ‘else’ keyword.
                    </span>
                    <br />
                    <br />
                    <span>
                      The code above means that if expression_1 is true, so the
                      output will be expression_2, otherwise, it is go to
                      expression_3.
                    </span>
                  </span>
                  <img
                    alt="image"
                    src="/external/screenshot%202023-12-29%20104022-600w-600w.png"
                    class="basic-py2a-image2"
                  />
                </div>
              </div>
            </div>
          </div>
          <span class="basic-py2a-text15">- Noor Alia Alisa</span>
        </div>
      </div>
    </div>
    <div class="basic-py2a-reference">
      <h1 class="basic-py2a-text16">References</h1>
      <span class="basic-py2a-text17">
        <br class="basic-py2a-text18" />
        <span class="basic-py2a-text19">
          Singh, A. (2023, August 3).
          <span v-html="rawfr95"></span>
        </span>
        <span class="basic-py2a-text20">
          This article will teach you about operator precedence and associativity
          in Python
        </span>
        <span class="basic-py2a-text21">. Medium.</span>
        <br class="basic-py2a-text22" />
        <span class="basic-py2a-text23">
                 
          <span v-html="raw6t2m"></span>
        </span>
        <a
          href="https://medium.com/@rishu__2701/this-article-will-teach-you-about-operator-precedence-and-associativity-in-python-ee455c7fbfee"
          target="_blank"
          rel="noreferrer noopener"
          class="basic-py2a-link"
        >
          https://medium.com/@rishu__2701/this-article-will-teach-you-about-operator-precedence-and-associativity-in-python-ee455c7fbfee
        </a>
        <br class="basic-py2a-text24" />
        <br class="basic-py2a-text25" />
        <span class="basic-py2a-text26">
          Conditional expression (ternary operator) in Python
          <span v-html="rawbq50"></span>
        </span>
        <span class="basic-py2a-text27">(2023, August 18). note.nkmk.me.</span>
        <br class="basic-py2a-text28" />
        <span class="basic-py2a-text29">
                 
          <span v-html="raw5xau"></span>
        </span>
        <a
          href="https://note.nkmk.me/en/python-if-conditional-expressions/"
          target="_blank"
          rel="noreferrer noopener"
          class="basic-py2a-link1"
        >
          https://note.nkmk.me/en/python-if-conditional-expressions/
        </a>
        <br />
      </span>
    </div>
    <footer class="basic-py2a-footer">
      <div class="basic-py2a-container6">
        <router-link to="/strace" class="basic-py2a-navlink8">STRACE</router-link>
      </div>
      <span class="basic-py2a-text31">
        &quot;Making System Calls Cool Again&quot;
      </span>
      <div class="basic-py2a-icon-group">
        <svg viewBox="0 0 877.7142857142857 1024" class="basic-py2a-icon">
          <path
            d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
          ></path>
        </svg>
      </div>
    </footer>
    <app-header></app-header>
  </div>
</template>

<script>
import AppHeader from '../components/header'

export default {
  name: 'BasicPy2a',
  props: {},
  components: {
    AppHeader,
  },
  data() {
    return {
      raw2595: ' ',
      rawgwst: ' ',
      raw6ifz: ' ',
      rawfr95: ' ',
      raw6t2m: ' ',
      rawbq50: ' ',
      raw5xau: ' ',
    }
  },
  metaInfo: {
    title: 'Strace | Basic Python',
    meta: [
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ],
  },
}
</script>

<style scoped>
.basic-py2a-container {
  width: 100%;
  display: flex;
  overflow: auto;
  min-height: 100vh;
  align-items: center;
  flex-direction: column;
  justify-content: flex-start;
  background-color: #f5f5f5;
}
.basic-py2a-banner {
  width: 100%;
  height: 275px;
  display: flex;
  transition: 0.3s;
  align-items: center;
  flex-direction: column;
  background-size: cover;
  justify-content: center;
  background-image: url('https://marketplace.canva.com/EAD2962NKnQ/2/0/1600w/canva-rainbow-gradient-pink-and-purple-virtual-background-_Tcjok-d9b4.jpg');
}

.basic-py2a-main-content {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: flex-start;
  background-color: #ffffff;
}
.basic-py2a-heading {
  color: #ff0000;
  font-size: 3rem;
  align-self: center;
  text-align: center;
}
.basic-py2a-container1 {
  flex: 0 0 auto;
  width: 100%;
  height: 100px;
  display: flex;
  align-items: flex-start;
}
.basic-py2a-navlink {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2a-navlink:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2a-navlink1 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2a-navlink1:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2a-navlink2 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2a-navlink2:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2a-navlink3 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2a-navlink3:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2a-container2 {
  flex: 0 0 auto;
  width: 100%;
  height: 100px;
  display: flex;
  align-items: flex-start;
}
.basic-py2a-navlink4 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2a-navlink4:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2a-navlink5 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2a-navlink5:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2a-navlink6 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2a-navlink6:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2a-navlink7 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2a-navlink7:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2a-alia {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.basic-py2a-arithmetic {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.basic-py2a-container3 {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.basic-py2a-container4 {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.basic-py2a-text03 {
  align-self: center;
  padding-bottom: 10px;
}
.basic-py2a-image {
  width: 865px;
  height: 830px;
  object-fit: cover;
}
.basic-py2a-conditional-exp {
  flex: 0 0 auto;
  width: 642px;
  height: 579px;
  display: flex;
  align-items: flex-start;
  padding-right: 15px;
  flex-direction: column;
}
.basic-py2a-image1 {
  width: 650px;
  height: 57px;
  margin-top: 20px;
  object-fit: cover;
}
.basic-py2a-text08 {
  margin-top: 10px;
}
.basic-py2a-text09 {
  margin-top: 10px;
  text-align: justify;
}
.basic-py2a-container5 {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.basic-py2a-text10 {
  margin-top: 10px;
}
.basic-py2a-image2 {
  width: 508px;
  height: 388px;
  align-self: flex-start;
  object-fit: cover;
}
.basic-py2a-reference {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #ffffff;
}
.basic-py2a-footer {
  width: 100%;
  display: flex;
  max-width: var(--dl-size-size-maxwidth);
  align-self: center;
  align-items: center;
  padding-top: var(--dl-space-space-twounits);
  padding-left: var(--dl-space-space-threeunits);
  padding-right: var(--dl-space-space-threeunits);
  padding-bottom: var(--dl-space-space-twounits);
  justify-content: space-between;
}
.basic-py2a-container6 {
  flex: 0 0 auto;
  width: auto;
  height: auto;
  display: flex;
  align-items: space-between;
  flex-direction: column;
}
.basic-py2a-navlink8 {
  font-weight: 700;
  text-decoration: none;
}
.basic-py2a-icon {
  width: 24px;
  height: 24px;
}
@media(max-width: 1600px) {
  .basic-py2a-container {
    background-color: #f7f7f7;
  }
  .basic-py2a-banner {
    height: auto;
    align-items: center;
    background-size: cover;
    justify-content: flex-start;
    background-image: url("/external/bgportrait-1500w.jpg");
  }
  .basic-py2a-main-content {
    flex: 1;
    width: 1300px;
    height: auto;
    box-shadow: 0px 0px 10px 0px #d3d2d6;
    align-items: flex-start;
    padding-top: 100px;
    flex-direction: column;
    justify-content: flex-start;
    background-color: #ffffff;
  }
  .basic-py2a-heading {
    color: rgb(255, 255, 255);
    width: 1200px;
    height: auto;
    font-size: 64px;
    font-style: normal;
    margin-top: 40px;
    font-family: Montserrat;
    font-weight: 700;
    line-height: 1.15;
    padding-top: 40px;
    border-radius: var(--dl-radius-radius-radius4);
    margin-bottom: 20px;
    padding-bottom: 40px;
    background-size: auto;
    background-image: url("/external/bglandscape-1200w.jpg");
  }
  .basic-py2a-container1 {
    width: 700px;
    height: auto;
    align-self: center;
    margin-left: 50px;
    padding-top: 20px;
    margin-right: 50px;
    padding-bottom: 10px;
    justify-content: center;
  }
  .basic-py2a-navlink {
    color: #A068FF;
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2a-navlink1 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2a-navlink2 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2a-navlink3 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2a-container2 {
    width: 800px;
    height: auto;
    align-self: center;
    margin-left: 50px;
    padding-top: 10px;
    margin-right: 50px;
    padding-bottom: 20px;
    justify-content: center;
  }
  .basic-py2a-navlink4 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2a-navlink5 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2a-navlink6 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2a-navlink7 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2a-alia {
    width: 1200px;
    height: auto;
    position: relative;
    align-items: flex-end;
    margin-left: 50px;
    padding-top: 50px;
    margin-right: 50px;
    padding-bottom: 50px;
  }
  .basic-py2a-arithmetic {
    height: auto;
    align-self: flex-start;
    flex-direction: column;
    padding-bottom: 10px;
    justify-content: space-between;
  }
  .basic-py2a-text {
    font-size: 36px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
    padding-top: 0px;
    padding-left: 0px;
    padding-right: 0px;
    padding-bottom: 30px;
  }
  .basic-py2a-container3 {
    height: auto;
  }
  .basic-py2a-container4 {
    margin-right: 25px;
  }
  .basic-py2a-text03 {
    font-size: 16px;
    align-self: flex-start;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py2a-text04 {
    font-weight: 700;
  }
  .basic-py2a-text06 {
    font-weight: 700;
  }
  .basic-py2a-image {
    width: 500px;
    height: 477px;
    align-self: flex-start;
  }
  .basic-py2a-conditional-exp {
    width: 650px;
    height: auto;
    margin-top: 30px;
    align-items: flex-start;
    margin-left: 25px;
    padding-right: 0px;
    flex-direction: column;
    justify-content: space-between;
  }
  .basic-py2a-image1 {
    width: 565px;
    height: auto;
    align-self: flex-start;
    margin-top: 0px;
    margin-bottom: 0px;
  }
  .basic-py2a-text08 {
    font-size: 16px;
    align-self: flex-start;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-right: 86px;
  }
  .basic-py2a-text09 {
    font-size: 24px;
    align-self: flex-start;
    margin-top: 40px;
    font-family: Inter;
    font-weight: 700;
    line-height: 1.15;
    padding-bottom: 15px;
  }
  .basic-py2a-container5 {
    align-items: flex-start;
  }
  .basic-py2a-text10 {
    font-size: 16px;
    margin-top: 0px;
    text-align: justify;
    font-family: Inter;
    line-height: 1.15;
    padding-right: var(--dl-space-space-fourunits);
  }
  .basic-py2a-image2 {
    width: 316px;
    height: 242px;
  }
  .basic-py2a-text15 {
    font-size: 18px;
    align-self: flex-end;
    font-style: italic;
    font-family: Inter;
    font-weight: 500;
    padding-top: 25px;
  }
  .basic-py2a-reference {
    width: 1600px;
    height: auto;
    align-self: center;
    box-shadow: 0px -1px 15px 0px #ebebeb;
    align-items: flex-start;
    padding-top: 50px;
    padding-left: 200px;
    padding-right: 200px;
    flex-direction: column;
    padding-bottom: 50px;
    justify-content: flex-start;
  }
  .basic-py2a-text16 {
    font-size: 32px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
  }
  .basic-py2a-text17 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.25;
  }
  .basic-py2a-text18 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py2a-text19 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py2a-text20 {
    font-size: 16px;
    font-style: italic;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py2a-text21 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py2a-text22 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py2a-text23 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py2a-link {
    color: var(--dl-color-primary-300);
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    text-decoration: underline;
  }
  .basic-py2a-text24 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py2a-text25 {
    font-size: 16px;
    font-style: italic;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py2a-text26 {
    font-size: 16px;
    font-style: italic;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py2a-text27 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py2a-text28 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py2a-text29 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py2a-link1 {
    color: var(--dl-color-primary-300);
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    text-decoration: underline;
  }
  .basic-py2a-footer {
    justify-content: space-between;
  }
  .basic-py2a-navlink8 {
    font-size: 16px;
    font-family: Montserrat;
    font-weight: 700;
    text-decoration: none;
  }
  .basic-py2a-text31 {
    font-size: 16px;
    font-style: normal;
    font-family: Montserrat;
    font-weight: 500;
  }
  .basic-py2a-icon {
    margin-left: 50px;
  }
}
@media(max-width: 1200px) {
  .basic-py2a-heading {
    color: rgb(255, 255, 255);
  }
}
@media(max-width: 479px) {
  .basic-py2a-footer {
    align-self: center;
  }
  .basic-py2a-icon-group {
    display: none;
  }
}
</style>
