// [Angular] Website Source Code/src/app/pages/basic-py-2f/basic-py-2f.component.ts
import { Component } from '@angular/core'
import { Title, Meta } from '@angular/platform-browser'

@Component({
  selector: 'basic-py2f',
  templateUrl: 'basic-py-2f.component.html',
  styleUrls: ['basic-py-2f.component.css'],
})
export class BasicPy2f {
  rawsf9h: string = ' '
  rawnih8: string = ' '
  raw54kf: string = ' '
  rawrgub: string = ' '
  rawqrge: string = ' '
  constructor(private title: Title, private meta: Meta) {
    this.title.setTitle('Strace | Basic Python')
    this.meta.addTags([
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ])
  }
}

<div class="basic-py2f-container">
  <div class="basic-py2f-banner">
    <div class="basic-py2f-main-content">
      <h1 class="basic-py2f-heading">EXPRESSIONS AND ASSIGNMENT</h1>
      <div class="basic-py2f-container01">
        <a routerLink="/basic-py-2a" class="basic-py2f-navlink button">
          Arithmetic Expressions
        </a>
        <a routerLink="/basic-py-2b" class="basic-py2f-navlink1 button">
          Functional Side Effects
        </a>
        <a routerLink="/basic-py-2ci" class="basic-py2f-navlink2 button">
          Overloaded Operators
        </a>
        <a routerLink="/basic-py-2cii" class="basic-py2f-navlink3 button">
          Type Conversions
        </a>
      </div>
      <div class="basic-py2f-container02">
        <a routerLink="/basic-py-2d" class="basic-py2f-navlink4 button">
          Relational and Boolean Expressions
        </a>
        <a routerLink="/basic-py-2e" class="basic-py2f-navlink5 button">
          Short-Circuit Evaluation
        </a>
        <a routerLink="/basic-py-2f" class="basic-py2f-navlink6 button">
          Assignment Statements
        </a>
        <a routerLink="/basic-py-2g" class="basic-py2f-navlink7 button">
          Mixed-Mode Assignment
        </a>
      </div>
      <div class="basic-py2f-container03">
        <div class="basic-py2f-nabil">
          <h1 class="basic-py2f-text">
            <span>Assignment Statements</span>
            <br />
          </h1>
          <span class="basic-py2f-text03">
            <span class="basic-py2f-text04">
              In Python, an assignment statement is used to assign a value to a
              variable. The basic syntax is:      &lt;
            </span>
            <span class="basic-py2f-text05">variable</span>
            <span class="basic-py2f-text06">&gt; = &lt;</span>
            <span class="basic-py2f-text07">value</span>
            <span class="basic-py2f-text08">&gt;</span>
            <br />
          </span>
          <div class="basic-py2f-container04">
            <div class="basic-py2f-container05">
              <span class="basic-py2f-text10">
                <span>Conditional Target</span>
                <br />
                <br />
              </span>
              <span class="basic-py2f-text14">
                Python provides a concise way to perform an assignment based on
                a condition. The syntax for a conditional expression is as
                follows:
              </span>
              <img
                alt="image"
                src="https://raw.githubusercontent.com/rydzze/TPL6213-Project/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/2b%20Expressions%20and%20Assignment/Screenshot%202024-01-04%20212506.png"
                class="basic-py2f-image"
              />
            </div>
            <div class="basic-py2f-container06">
              <span class="basic-py2f-text15">
                <span class="basic-py2f-text16">
                  Compound Assignment Operator
                </span>
                <br />
                <br />
              </span>
              <span class="basic-py2f-text19">
                It is a combination of an arithmetic operator with an
                assignment.
              </span>
              <img
                alt="image"
                src="https://raw.githubusercontent.com/rydzze/TPL6213-Project/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/2b%20Expressions%20and%20Assignment/Screenshot%202024-01-04%20213829.png"
                class="basic-py2f-image1"
              />
            </div>
          </div>
          <div class="basic-py2f-container07">
            <div class="basic-py2f-container08">
              <span class="basic-py2f-text20">
                <span class="basic-py2f-text21">Unary Assignment Operator</span>
                <br />
                <br />
              </span>
              <span class="basic-py2f-text24">
                Combination of a unary operation (an operation on a single
                operand) with an assignment.
              </span>
              <img
                alt="image"
                src="https://raw.githubusercontent.com/rydzze/TPL6213-Project/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/2b%20Expressions%20and%20Assignment/Screenshot%202024-01-04%20215038.png"
                class="basic-py2f-image2"
              />
            </div>
            <div class="basic-py2f-container09">
              <span class="basic-py2f-text25">
                <span class="basic-py2f-text26">
                  Assignment as an Expression
                </span>
                <br />
                <br />
              </span>
              <span class="basic-py2f-text29">
                Assignment expressions  can  assign a value to a variable as
                part of an expression. 
              </span>
              <img
                alt="image"
                src="https://raw.githubusercontent.com/rydzze/TPL6213-Project/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/2b%20Expressions%20and%20Assignment/Screenshot%202024-01-04%20220619.png"
                class="basic-py2f-image3"
              />
            </div>
          </div>
          <div class="basic-py2f-container10">
            <span class="basic-py2f-text30">
              <span class="basic-py2f-text31">Multiple Assignment</span>
              <br />
              <br />
            </span>
            <span class="basic-py2f-text34">
              It allows to assign values to multiple variables in a single line.
            </span>
            <img
              alt="image"
              src="https://raw.githubusercontent.com/rydzze/TPL6213-Project/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/2b%20Expressions%20and%20Assignment/Screenshot%202024-01-04%20221634.png"
              class="basic-py2f-image4"
            />
          </div>
          <span class="basic-py2f-text35">
            <span class="basic-py2f-text36">
              -
              <span [innerHTML]="rawsf9h"></span>
            </span>
            <span class="basic-py2f-text37">Muhammad Nabil Irfan</span>
          </span>
        </div>
      </div>
    </div>
  </div>
  <div class="basic-py2f-reference">
    <h1 class="basic-py2f-text38">References</h1>
    <span class="basic-py2f-text39">
      <br />
      <span class="basic-py2f-text41">
        Expressions and Statements: Assignment Statement Forms and FAQs.
      </span>
      <span>(2021, March 19). Toppr-guides.</span>
      <br />
      <span>
               
        <span [innerHTML]="rawnih8"></span>
      </span>
      <span class="basic-py2f-text45">
        https://www.toppr.com/guides/computer-science/introduction-to-python/variables-expressions-and-statements/expressions-and-statements/
      </span>
      <br />
      <br />
      <span>
        Sturtz, J. (n.d.).
        <span [innerHTML]="raw54kf"></span>
      </span>
      <span class="basic-py2f-text49">Conditional Statements in Python</span>
      <span>. Real Python.</span>
      <br />
      <span>
               
        <span [innerHTML]="rawrgub"></span>
      </span>
      <a
        href="https://realpython.com/python-conditional-statements/"
        target="_blank"
        rel="noreferrer noopener"
        class="basic-py2f-link"
      >
        https://realpython.com/python-conditional-statements/
      </a>
      <br />
      <br class="basic-py2f-text54" />
      <span class="basic-py2f-text55">
        Mixed mode arithmetic - Learn Python in 7 Days
      </span>
      <span>. (n.d.). O’Reilly Online Learning.</span>
      <br />
      <span>
               
        <span [innerHTML]="rawqrge"></span>
      </span>
      <a
        href="https://www.oreilly.com/library/view/learn-python-in/9781787288386/d9f2bcb2-d502-4e84-8427-67c20cd3aad8.xhtml"
        target="_blank"
        rel="noreferrer noopener"
        class="basic-py2f-link1"
      >
        https://www.oreilly.com/library/view/learn-python-in/9781787288386/d9f2bcb2-d502-4e84-8427-67c20cd3aad8.xhtml
      </a>
      <br />
    </span>
  </div>
  <footer class="basic-py2f-footer">
    <div class="basic-py2f-container11">
      <a routerLink="/strace" class="basic-py2f-navlink8">STRACE</a>
    </div>
    <span class="basic-py2f-text60">
      &quot;Making System Calls Cool Again&quot;
    </span>
    <div class="basic-py2f-icon-group">
      <svg viewBox="0 0 877.7142857142857 1024" class="basic-py2f-icon">
        <path
          d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
        ></path>
      </svg>
    </div>
  </footer>
  <app-header></app-header>
</div>

// [Vue] Website Source Code/src/views/basic-py-2f.vue
<template>
  <div class="basic-py2f-container">
    <div class="basic-py2f-banner">
      <div class="basic-py2f-main-content">
        <h1 class="basic-py2f-heading">EXPRESSIONS AND ASSIGNMENT</h1>
        <div class="basic-py2f-container01">
          <router-link to="/basic-py-2a" class="basic-py2f-navlink button">
            Arithmetic Expressions
          </router-link>
          <router-link to="/basic-py-2b" class="basic-py2f-navlink1 button">
            Functional Side Effects
          </router-link>
          <router-link to="/basic-py-2ci" class="basic-py2f-navlink2 button">
            Overloaded Operators
          </router-link>
          <router-link to="/basic-py-2cii" class="basic-py2f-navlink3 button">
            Type Conversions
          </router-link>
        </div>
        <div class="basic-py2f-container02">
          <router-link to="/basic-py-2d" class="basic-py2f-navlink4 button">
            Relational and Boolean Expressions
          </router-link>
          <router-link to="/basic-py-2e" class="basic-py2f-navlink5 button">
            Short-Circuit Evaluation
          </router-link>
          <router-link to="/basic-py-2f" class="basic-py2f-navlink6 button">
            Assignment Statements
          </router-link>
          <router-link to="/basic-py-2g" class="basic-py2f-navlink7 button">
            Mixed-Mode Assignment
          </router-link>
        </div>
        <div class="basic-py2f-container03">
          <div class="basic-py2f-nabil">
            <h1 class="basic-py2f-text">
              <span>Assignment Statements</span>
              <br />
            </h1>
            <span class="basic-py2f-text03">
              <span class="basic-py2f-text04">
                In Python, an assignment statement is used to assign a value to a
                variable. The basic syntax is:      &lt;
              </span>
              <span class="basic-py2f-text05">variable</span>
              <span class="basic-py2f-text06">&gt; = &lt;</span>
              <span class="basic-py2f-text07">value</span>
              <span class="basic-py2f-text08">&gt;</span>
              <br />
            </span>
            <div class="basic-py2f-container04">
              <div class="basic-py2f-container05">
                <span class="basic-py2f-text10">
                  <span>Conditional Target</span>
                  <br />
                  <br />
                </span>
                <span class="basic-py2f-text14">
                  Python provides a concise way to perform an assignment based on
                  a condition. The syntax for a conditional expression is as
                  follows:
                </span>
                <img
                  alt="image"
                  src="https://raw.githubusercontent.com/rydzze/TPL6213-Project/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/2b%20Expressions%20and%20Assignment/Screenshot%202024-01-04%20212506.png"
                  class="basic-py2f-image"
                />
              </div>
              <div class="basic-py2f-container06">
                <span class="basic-py2f-text15">
                  <span class="basic-py2f-text16">
                    Compound Assignment Operator
                  </span>
                  <br />
                  <br />
                </span>
                <span class="basic-py2f-text19">
                  It is a combination of an arithmetic operator with an
                  assignment.
                </span>
                <img
                  alt="image"
                  src="https://raw.githubusercontent.com/rydzze/TPL6213-Project/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/2b%20Expressions%20and%20Assignment/Screenshot%202024-01-04%20213829.png"
                  class="basic-py2f-image1"
                />
              </div>
            </div>
            <div class="basic-py2f-container07">
              <div class="basic-py2f-container08">
                <span class="basic-py2f-text20">
                  <span class="basic-py2f-text21">Unary Assignment Operator</span>
                  <br />
                  <br />
                </span>
                <span class="basic-py2f-text24">
                  Combination of a unary operation (an operation on a single
                  operand) with an assignment.
                </span>
                <img
                  alt="image"
                  src="https://raw.githubusercontent.com/rydzze/TPL6213-Project/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/2b%20Expressions%20and%20Assignment/Screenshot%202024-01-04%20215038.png"
                  class="basic-py2f-image2"
                />
              </div>
              <div class="basic-py2f-container09">
                <span class="basic-py2f-text25">
                  <span class="basic-py2f-text26">
                    Assignment as an Expression
                  </span>
                  <br />
                  <br />
                </span>
                <span class="basic-py2f-text29">
                  Assignment expressions  can  assign a value to a variable as
                  part of an expression. 
                </span>
                <img
                  alt="image"
                  src="https://raw.githubusercontent.com/rydzze/TPL6213-Project/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/2b%20Expressions%20and%20Assignment/Screenshot%202024-01-04%20220619.png"
                  class="basic-py2f-image3"
                />
              </div>
            </div>
            <div class="basic-py2f-container10">
              <span class="basic-py2f-text30">
                <span class="basic-py2f-text31">Multiple Assignment</span>
                <br />
                <br />
              </span>
              <span class="basic-py2f-text34">
                It allows to assign values to multiple variables in a single line.
              </span>
              <img
                alt="image"
                src="https://raw.githubusercontent.com/rydzze/TPL6213-Project/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/2b%20Expressions%20and%20Assignment/Screenshot%202024-01-04%20221634.png"
                class="basic-py2f-image4"
              />
            </div>
            <span class="basic-py2f-text35">
              <span class="basic-py2f-text36">
                -
                <span v-html="rawxp4b"></span>
              </span>
              <span class="basic-py2f-text37">Muhammad Nabil Irfan</span>
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class="basic-py2f-reference">
      <h1 class="basic-py2f-text38">References</h1>
      <span class="basic-py2f-text39">
        <br />
        <span class="basic-py2f-text41">
          Expressions and Statements: Assignment Statement Forms and FAQs.
        </span>
        <span>(2021, March 19). Toppr-guides.</span>
        <br />
        <span>
                 
          <span v-html="raw4320"></span>
        </span>
        <span class="basic-py2f-text45">
          https://www.toppr.com/guides/computer-science/introduction-to-python/variables-expressions-and-statements/expressions-and-statements/
        </span>
        <br />
        <br />
        <span>
          Sturtz, J. (n.d.).
          <span v-html="rawvgml"></span>
        </span>
        <span class="basic-py2f-text49">Conditional Statements in Python</span>
        <span>. Real Python.</span>
        <br />
        <span>
                 
          <span v-html="rawfmqi"></span>
        </span>
        <a
          href="https://realpython.com/python-conditional-statements/"
          target="_blank"
          rel="noreferrer noopener"
          class="basic-py2f-link"
        >
          https://realpython.com/python-conditional-statements/
        </a>
        <br />
        <br class="basic-py2f-text54" />
        <span class="basic-py2f-text55">
          Mixed mode arithmetic - Learn Python in 7 Days
        </span>
        <span>. (n.d.). O’Reilly Online Learning.</span>
        <br />
        <span>
                 
          <span v-html="raw89cy"></span>
        </span>
        <a
          href="https://www.oreilly.com/library/view/learn-python-in/9781787288386/d9f2bcb2-d502-4e84-8427-67c20cd3aad8.xhtml"
          target="_blank"
          rel="noreferrer noopener"
          class="basic-py2f-link1"
        >
          https://www.oreilly.com/library/view/learn-python-in/9781787288386/d9f2bcb2-d502-4e84-8427-67c20cd3aad8.xhtml
        </a>
        <br />
      </span>
    </div>
    <footer class="basic-py2f-footer">
      <div class="basic-py2f-container11">
        <router-link to="/strace" class="basic-py2f-navlink8">STRACE</router-link>
      </div>
      <span class="basic-py2f-text60">
        &quot;Making System Calls Cool Again&quot;
      </span>
      <div class="basic-py2f-icon-group">
        <svg viewBox="0 0 877.7142857142857 1024" class="basic-py2f-icon">
          <path
            d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
          ></path>
        </svg>
      </div>
    </footer>
    <app-header></app-header>
  </div>
</template>

<script>
import AppHeader from '../components/header'

export default {
  name: 'BasicPy2f',
  props: {},
  components: {
    AppHeader,
  },
  data() {
    return {
      rawxp4b: ' ',
      raw4320: ' ',
      rawvgml: ' ',
      rawfmqi: ' ',
      raw89cy: ' ',
    }
  },
  metaInfo: {
    title: 'Strace | Basic Python',
    meta: [
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ],
  },
}
</script>

<style scoped>
.basic-py2f-container {
  width: 100%;
  display: flex;
  overflow: auto;
  min-height: 100vh;
  align-items: center;
  flex-direction: column;
  justify-content: flex-start;
  background-color: #f5f5f5;
}
.basic-py2f-banner {
  width: 100%;
  height: 275px;
  display: flex;
  transition: 0.3s;
  align-items: center;
  flex-direction: column;
  background-size: cover;
  justify-content: center;
  background-image: url('https://marketplace.canva.com/EAD2962NKnQ/2/0/1600w/canva-rainbow-gradient-pink-and-purple-virtual-background-_Tcjok-d9b4.jpg');
}

.basic-py2f-main-content {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: flex-start;
  background-color: #ffffff;
}
.basic-py2f-heading {
  color: #ff0000;
  font-size: 3rem;
  align-self: center;
  text-align: center;
}
.basic-py2f-container01 {
  flex: 0 0 auto;
  width: 100%;
  height: 100px;
  display: flex;
  align-items: flex-start;
}
.basic-py2f-navlink {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2f-navlink:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2f-navlink1 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2f-navlink1:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2f-navlink2 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2f-navlink2:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2f-navlink3 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2f-navlink3:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2f-container02 {
  flex: 0 0 auto;
  width: 100%;
  height: 100px;
  display: flex;
  align-items: flex-start;
}
.basic-py2f-navlink4 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2f-navlink4:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2f-navlink5 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2f-navlink5:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2f-navlink6 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2f-navlink6:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2f-navlink7 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2f-navlink7:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2f-container03 {
  flex: 0 0 auto;
  width: auto;
  height: auto;
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
}
.basic-py2f-nabil {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.basic-py2f-text03 {
  text-align: justify;
}
.basic-py2f-container04 {
  flex: 0 0 auto;
  width: 100%;
  height: 100px;
  display: flex;
  align-items: flex-start;
}
.basic-py2f-container05 {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.basic-py2f-image {
  width: 200px;
  object-fit: cover;
}
.basic-py2f-container06 {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.basic-py2f-image1 {
  width: 200px;
  object-fit: cover;
}
.basic-py2f-container07 {
  flex: 0 0 auto;
  width: 100%;
  height: 100px;
  display: flex;
  align-items: flex-start;
}
.basic-py2f-container08 {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.basic-py2f-image2 {
  width: 200px;
  object-fit: cover;
}
.basic-py2f-container09 {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.basic-py2f-image3 {
  width: 200px;
  object-fit: cover;
}
.basic-py2f-container10 {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-end;
  justify-content: flex-start;
}
.basic-py2f-image4 {
  width: 200px;
  object-fit: cover;
}
.basic-py2f-reference {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #ffffff;
}
.basic-py2f-footer {
  width: 100%;
  display: flex;
  max-width: var(--dl-size-size-maxwidth);
  align-self: center;
  align-items: center;
  padding-top: var(--dl-space-space-twounits);
  padding-left: var(--dl-space-space-threeunits);
  padding-right: var(--dl-space-space-threeunits);
  padding-bottom: var(--dl-space-space-twounits);
  justify-content: space-between;
}
.basic-py2f-container11 {
  flex: 0 0 auto;
  width: auto;
  height: auto;
  display: flex;
  align-items: space-between;
  flex-direction: column;
}
.basic-py2f-navlink8 {
  font-weight: 700;
  text-decoration: none;
}
.basic-py2f-icon {
  width: 24px;
  height: 24px;
}
@media(max-width: 1600px) {
  .basic-py2f-container {
    background-color: #f7f7f7;
  }
  .basic-py2f-banner {
    height: auto;
    align-items: center;
    background-size: cover;
    justify-content: flex-start;
    background-image: url("/external/bgportrait-1500w.jpg");
  }
  .basic-py2f-main-content {
    flex: 1;
    width: 1300px;
    height: auto;
    box-shadow: 0px 0px 10px 0px #d3d2d6;
    align-items: flex-start;
    padding-top: 100px;
    flex-direction: column;
    justify-content: flex-start;
    background-color: #ffffff;
  }
  .basic-py2f-heading {
    color: rgb(255, 255, 255);
    width: 1200px;
    height: auto;
    font-size: 64px;
    font-style: normal;
    margin-top: 40px;
    font-family: Montserrat;
    font-weight: 700;
    line-height: 1.15;
    padding-top: 40px;
    border-radius: var(--dl-radius-radius-radius4);
    margin-bottom: 20px;
    padding-bottom: 40px;
    background-size: auto;
    background-image: url("/external/bglandscape-1200w.jpg");
  }
  .basic-py2f-container01 {
    width: 700px;
    height: auto;
    align-self: center;
    margin-left: 50px;
    padding-top: 20px;
    margin-right: 50px;
    padding-bottom: 10px;
    justify-content: center;
  }
  .basic-py2f-navlink {
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2f-navlink1 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2f-navlink2 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2f-navlink3 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2f-container02 {
    width: 800px;
    height: auto;
    align-self: center;
    margin-left: 50px;
    padding-top: 10px;
    margin-right: 50px;
    padding-bottom: 20px;
    justify-content: center;
  }
  .basic-py2f-navlink4 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2f-navlink5 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2f-navlink6 {
    color: #A068FF;
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2f-navlink7 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2f-nabil {
    width: 1200px;
    align-items: flex-start;
    margin-left: 50px;
    padding-top: 50px;
    margin-right: 50px;
    padding-bottom: 50px;
  }
  .basic-py2f-text {
    font-size: 36px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
    padding-top: 0px;
    padding-left: 0px;
    padding-right: 0px;
    padding-bottom: 30px;
  }
  .basic-py2f-text03 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.25;
    margin-bottom: 30px;
  }
  .basic-py2f-text04 {
    font-size: 20px;
  }
  .basic-py2f-text05 {
    font-size: 20px;
    font-style: italic;
    font-weight: 700;
  }
  .basic-py2f-text06 {
    font-size: 20px;
  }
  .basic-py2f-text07 {
    font-size: 20px;
    font-style: italic;
    font-weight: 700;
  }
  .basic-py2f-text08 {
    font-size: 20px;
  }
  .basic-py2f-container04 {
    height: auto;
    margin-top: 25px;
    align-items: center;
    margin-bottom: 25px;
  }
  .basic-py2f-container05 {
    width: 50%;
    height: auto;
    align-self: flex-start;
    padding-right: 25px;
    flex-direction: column;
  }
  .basic-py2f-text10 {
    font-size: 24px;
    align-self: flex-start;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 600;
    line-height: 1.15;
  }
  .basic-py2f-text14 {
    font-size: 16px;
    align-self: center;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-bottom: 20px;
  }
  .basic-py2f-image {
    width: 570px;
    height: 103px;
    align-self: center;
    border-radius: var(--dl-radius-radius-radius4);
  }
  .basic-py2f-container06 {
    width: 50%;
    height: auto;
    align-items: center;
    padding-left: 25px;
    flex-direction: column;
  }
  .basic-py2f-text15 {
    font-size: 24px;
    align-self: flex-start;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 600;
    line-height: 1.15;
  }
  .basic-py2f-text16 {
    text-align: justify;
  }
  .basic-py2f-text19 {
    font-size: 16px;
    align-self: center;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-bottom: 20px;
  }
  .basic-py2f-image1 {
    width: auto;
    height: auto;
    align-self: center;
    border-radius: var(--dl-radius-radius-radius4);
  }
  .basic-py2f-container07 {
    height: auto;
    margin-top: 25px;
    margin-bottom: 25px;
  }
  .basic-py2f-container08 {
    width: 50%;
    height: auto;
    align-self: flex-start;
    align-items: center;
    padding-right: 25px;
    flex-direction: column;
  }
  .basic-py2f-text20 {
    font-size: 24px;
    align-self: flex-start;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 600;
    line-height: 1.15;
  }
  .basic-py2f-text21 {
    text-align: justify;
  }
  .basic-py2f-text24 {
    font-size: 16px;
    align-self: center;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-bottom: 20px;
  }
  .basic-py2f-image2 {
    width: auto;
    height: auto;
    align-self: center;
    border-radius: var(--dl-radius-radius-radius4);
  }
  .basic-py2f-container09 {
    width: 50%;
    height: auto;
    align-items: center;
    padding-left: 25px;
    flex-direction: column;
  }
  .basic-py2f-text25 {
    font-size: 24px;
    align-self: flex-start;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 600;
    line-height: 1.15;
  }
  .basic-py2f-text26 {
    text-align: justify;
  }
  .basic-py2f-text29 {
    font-size: 16px;
    align-self: center;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-bottom: 20px;
  }
  .basic-py2f-image3 {
    width: auto;
    height: auto;
    align-self: center;
    border-radius: var(--dl-radius-radius-radius4);
  }
  .basic-py2f-container10 {
    width: 50%;
    height: auto;
    align-self: center;
    margin-top: 25px;
    align-items: center;
    margin-bottom: 40px;
    flex-direction: column;
  }
  .basic-py2f-text30 {
    font-size: 24px;
    align-self: flex-start;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 600;
    line-height: 1.15;
  }
  .basic-py2f-text31 {
    text-align: justify;
  }
  .basic-py2f-text34 {
    font-size: 16px;
    align-self: center;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-bottom: 20px;
  }
  .basic-py2f-image4 {
    width: auto;
    height: auto;
    align-self: center;
    border-radius: var(--dl-radius-radius-radius4);
  }
  .basic-py2f-text35 {
    font-size: 18px;
    align-self: flex-end;
    font-family: Inter;
    font-weight: 500;
    padding-top: 25px;
  }
  .basic-py2f-text36 {
    font-style: normal;
  }
  .basic-py2f-text37 {
    font-style: italic;
  }
  .basic-py2f-reference {
    width: 1600px;
    height: auto;
    align-self: center;
    box-shadow: 0px -1px 15px 0px #ebebeb;
    align-items: flex-start;
    padding-top: 50px;
    padding-left: 200px;
    padding-right: 200px;
    flex-direction: column;
    padding-bottom: 50px;
    justify-content: flex-start;
  }
  .basic-py2f-text38 {
    font-size: 32px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
  }
  .basic-py2f-text39 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.25;
  }
  .basic-py2f-text41 {
    font-style: italic;
  }
  .basic-py2f-text45 {
    color: var(--dl-color-primary-300);
    text-decoration: underline;
  }
  .basic-py2f-text49 {
    font-style: italic;
  }
  .basic-py2f-link {
    color: var(--dl-color-primary-300);
    text-decoration: underline;
  }
  .basic-py2f-text54 {
    font-style: italic;
  }
  .basic-py2f-text55 {
    font-style: italic;
  }
  .basic-py2f-link1 {
    color: var(--dl-color-primary-300);
    text-decoration: underline;
  }
  .basic-py2f-footer {
    justify-content: space-between;
  }
  .basic-py2f-navlink8 {
    font-size: 16px;
    font-family: Montserrat;
    font-weight: 700;
    text-decoration: none;
  }
  .basic-py2f-text60 {
    font-size: 16px;
    font-style: normal;
    font-family: Montserrat;
    font-weight: 500;
  }
  .basic-py2f-icon {
    margin-left: 50px;
  }
}
@media(max-width: 1200px) {
  .basic-py2f-heading {
    color: rgb(255, 255, 255);
  }
}
@media(max-width: 479px) {
  .basic-py2f-footer {
    align-self: center;
  }
  .basic-py2f-icon-group {
    display: none;
  }
}
</style>
