// [Angular] Website Source Code/src/app/pages/basic-py-3bi/basic-py-3bi.component.ts
import { Component } from '@angular/core'
import { Title, Meta } from '@angular/platform-browser'

@Component({
  selector: 'basic-py3bi',
  templateUrl: 'basic-py-3bi.component.html',
  styleUrls: ['basic-py-3bi.component.css'],
})
export class BasicPy3bi {
  raws0gu: string = ' '
  raw503a: string = ' '
  rawg8y6: string = ' '
  raw5mbc: string = ' '
  rawzshr: string = ' '
  rawzxlw: string = ' '
  constructor(private title: Title, private meta: Meta) {
    this.title.setTitle('Strace | Basic Python')
    this.meta.addTags([
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ])
  }
}

<div class="basic-py3bi-container">
  <div class="basic-py3bi-banner">
    <div class="basic-py3bi-main-content">
      <h1 class="basic-py3bi-heading">CONTROL STRUCTURE</h1>
      <div class="basic-py3bi-container01">
        <a routerLink="/basic-py-3ai" class="basic-py3bi-navlink button">
          Selection Statement
        </a>
        <a routerLink="/basic-py-3aii" class="basic-py3bi-navlink1 button">
          Two-way Selectors
        </a>
        <a routerLink="/basic-py-3aiii" class="basic-py3bi-navlink2 button">
          Multiple-way Selectors
        </a>
      </div>
      <div class="basic-py3bi-container02">
        <a routerLink="/basic-py-3bi" class="basic-py3bi-navlink3 button">
          Counter-Controlled Loops
        </a>
        <a routerLink="/basic-py-3bii" class="basic-py3bi-navlink4 button">
          Logically-Controlled Loops
        </a>
      </div>
      <div class="basic-py3bi-content-here">
        <div class="basic-py3bi-column">
          <h1 class="basic-py3bi-text">
            <span>Counter-Controlled Loop</span>
            <br />
          </h1>
          <span class="basic-py3bi-text03">
            For loop is used to iterate over a sequence (such as a list, tuple,
            or string) or other iterable objects. It is a counter-controlled
            loop that repeats a specific number of times based on a counter
            variable that is incremented or decremented with each iteration of
            the loop. Here are some examples of a for loop in Python:
          </span>
        </div>
        <div class="basic-py3bi-container03">
          <div class="basic-py3bi-container04">
            <img
              alt="image"
              src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/3b%20Control%20Structure_Hapih/20BB1A7A-7684-4736-93DD-6B1BC9721245.jpeg?raw=true"
              class="basic-py3bi-image"
            />
            <span class="basic-py3bi-text04">
              <span>
                This code is used to count the number of elements in the list.
                The numbers list contains 5 elements, and the count variable is
                initialized to 0. A for loop is used to iterate over each
                element in the numbers list, and the count variable is
                incremented by 1 for each element.When the loop is finished, the
                count variable contains the number of elements in the numbers
                list, which is 5. The print() function is used to display the
                value of the count variable.
              </span>
              <br />
            </span>
          </div>
          <div class="basic-py3bi-container05">
            <img
              alt="image"
              src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/3b%20Control%20Structure_Hapih/351C6150-3B44-4060-BF07-FEB56521E489.jpeg?raw=true"
              class="basic-py3bi-image1"
            />
            <span class="basic-py3bi-text07">
              <span>
                This code is used to calculate the sum of a list of numbers. The
                numbers list contains three elements, all of which are equal to
                1. The sum variable is initialized to 0, and a for loop is used
                to iterate over each element in the numbers list. Inside the
                loop, the value of each element is added to the sum variable
                using the += operator. When the loop is finished, the sum
                variable contains the sum of the numbers in the numbers list,
                which is 3. The print() function is used to display the value of
                the sum variable.
              </span>
              <br />
            </span>
          </div>
        </div>
        <div class="basic-py3bi-container06">
          <div class="basic-py3bi-container07">
            <div class="basic-py3bi-container08"></div>
            <span class="basic-py3bi-text10">
              <span>
                This code is used to find the maximum value in a list of
                numbers. The numbers list contains five elements, and the max
                variable is initialized to 0. A for loop is used to iterate over
                each element in the numbers list, and an if statement is used to
                check if the current element is greater than the current maximum
                value. If it is, the value of max is updated to the current
                element. When the loop is finished, the max variable contains
                the maximum value in the numbers list, which is 100. The print()
                function is used to display the value of the max variable.
              </span>
              <br />
            </span>
          </div>
          <div class="basic-py3bi-container09">
            <img
              alt="image"
              src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/3b%20Control%20Structure_Hapih/64FF4C5B-3D8C-45ED-A914-D6E19AAB9F3C.jpeg?raw=true"
              class="basic-py3bi-image2"
            />
            <span class="basic-py3bi-text13">
              A new list called list2 is a copy of list1. A for loop is used to
              iterate over each element in list1, and the append() method is
              used to add each element to list2. When the loop is finished,
              list2 contains the same elements as list1. The print() function is
              used to display the contents of list2.
            </span>
          </div>
        </div>
        <div class="basic-py3bi-container10">
          <div class="basic-py3bi-container11">
            <img
              alt="image"
              src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/3b%20Control%20Structure_Hapih/7901E99D-18C3-4052-A41A-ECE95F6BDC39.jpeg?raw=true"
              class="basic-py3bi-image3"
            />
          </div>
          <span class="basic-py3bi-text14">
            A simple for loop code where The fruits list contains three
            elements, and the for loop is used to iterate over each element in
            the list. Inside the loop, the value of each element is printed
            using the print() function. When the loop is finished, the program
            exits.
          </span>
        </div>
        <div class="basic-py3bi-container12">
          <img
            alt="image"
            src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/3b%20Control%20Structure_Hapih/752E90BB-8080-4050-B69D-DD686614F5FF.jpeg?raw=true"
            class="basic-py3bi-image4"
          />
          <span class="basic-py3bi-text15">
            This code is a simple example of a for loop in Python. The biodata
            dictionary contains three key-value pairs, and the for loop is used
            to iterate over each key-value pair in the dictionary. Inside the
            loop, the key and value of each pair are printed using the print()
            function. When the loop is finished, the program exits.
          </span>
        </div>
        <div class="basic-py3bi-container13">
          <img
            alt="image"
            src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/3b%20Control%20Structure_Hapih/7139BF9D-D4A6-42C6-B246-D559499E4CAE.jpeg?raw=true"
            class="basic-py3bi-image5"
          />
          <span class="basic-py3bi-text16">
            This code is an example of a nested for loop in Python. The outer
            loop uses the range() function to iterate over the values 1, 2, and
            3, and the inner loop also uses the range() function to iterate over
            the same values. Inside the inner loop, the values of i and j are
            printed using the print() function.
          </span>
        </div>
        <span class="basic-py3bi-text17">-Muhammad Hafiz</span>
      </div>
    </div>
  </div>
  <div class="basic-py3bi-reference">
    <h1 class="basic-py3bi-text18">References</h1>
    <span class="basic-py3bi-text19">
      <br />
      <span class="basic-py3bi-text21">
        Loops in Python - For, while and nested loops
        <span [innerHTML]="raws0gu"></span>
      </span>
      <span>(2023, December 21). GeeksforGeeks.</span>
      <br />
      <span>
               
        <span [innerHTML]="raw503a"></span>
      </span>
      <a
        href="https://www.geeksforgeeks.org/loops-in-python/?ref=lbp"
        target="_blank"
        rel="noreferrer noopener"
        class="basic-py3bi-link"
      >
        https://www.geeksforgeeks.org/loops-in-python/?ref=lbp
      </a>
      <br />
      <br />
      <span>
        Bonthu, H. (2023, April 26).
        <span [innerHTML]="rawg8y6"></span>
      </span>
      <span class="basic-py3bi-text28">
        Master control statements in Python with examples (Updated 2023)
      </span>
      <span>. Analytics Vidhya.</span>
      <br />
      <span>
               
        <span [innerHTML]="raw5mbc"></span>
      </span>
      <a
        href="https://www.analyticsvidhya.com/blog/2021/09/loops-and-control-statements-an-in-depth-python-tutorial/"
        target="_blank"
        rel="noreferrer noopener"
        class="basic-py3bi-link1"
      >
        https://www.analyticsvidhya.com/blog/2021/09/loops-and-control-statements-an-in-depth-python-tutorial/
      </a>
      <br />
      <br />
      <span class="basic-py3bi-text34">Python iterative statements.</span>
      <span>
        (2018, December 15). Python Class Room Diary.
        <span [innerHTML]="rawzshr"></span>
      </span>
      <br />
      <span>
               
        <span [innerHTML]="rawzxlw"></span>
      </span>
      <a
        href="https://pythonclassroomdiary.in/python-notes-printed/python-iterative-statements/"
        target="_blank"
        rel="noreferrer noopener"
        class="basic-py3bi-link2"
      >
        https://pythonclassroomdiary.in/python-notes-printed/python-iterative-statements/
      </a>
      <br />
    </span>
  </div>
  <footer class="basic-py3bi-footer">
    <div class="basic-py3bi-container14">
      <a routerLink="/strace" class="basic-py3bi-navlink5">STRACE</a>
    </div>
    <span class="basic-py3bi-text39">
      &quot;Making System Calls Cool Again&quot;
    </span>
    <div class="basic-py3bi-icon-group">
      <svg viewBox="0 0 877.7142857142857 1024" class="basic-py3bi-icon">
        <path
          d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
        ></path>
      </svg>
    </div>
  </footer>
  <app-header></app-header>
</div>

// [Vue] Website Source Code/src/views/basic-py-3bi.vue
<template>
  <div class="basic-py3bi-container">
    <div class="basic-py3bi-banner">
      <div class="basic-py3bi-main-content">
        <h1 class="basic-py3bi-heading">CONTROL STRUCTURE</h1>
        <div class="basic-py3bi-container01">
          <router-link to="/basic-py-3ai" class="basic-py3bi-navlink button">
            Selection Statement
          </router-link>
          <router-link to="/basic-py-3aii" class="basic-py3bi-navlink1 button">
            Two-way Selectors
          </router-link>
          <router-link to="/basic-py-3aiii" class="basic-py3bi-navlink2 button">
            Multiple-way Selectors
          </router-link>
        </div>
        <div class="basic-py3bi-container02">
          <router-link to="/basic-py-3bi" class="basic-py3bi-navlink3 button">
            Counter-Controlled Loops
          </router-link>
          <router-link to="/basic-py-3bii" class="basic-py3bi-navlink4 button">
            Logically-Controlled Loops
          </router-link>
        </div>
        <div class="basic-py3bi-content-here">
          <div class="basic-py3bi-column">
            <h1 class="basic-py3bi-text">
              <span>Counter-Controlled Loop</span>
              <br />
            </h1>
            <span class="basic-py3bi-text03">
              For loop is used to iterate over a sequence (such as a list, tuple,
              or string) or other iterable objects. It is a counter-controlled
              loop that repeats a specific number of times based on a counter
              variable that is incremented or decremented with each iteration of
              the loop. Here are some examples of a for loop in Python:
            </span>
          </div>
          <div class="basic-py3bi-container03">
            <div class="basic-py3bi-container04">
              <img
                alt="image"
                src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/3b%20Control%20Structure_Hapih/20BB1A7A-7684-4736-93DD-6B1BC9721245.jpeg?raw=true"
                class="basic-py3bi-image"
              />
              <span class="basic-py3bi-text04">
                <span>
                  This code is used to count the number of elements in the list.
                  The numbers list contains 5 elements, and the count variable is
                  initialized to 0. A for loop is used to iterate over each
                  element in the numbers list, and the count variable is
                  incremented by 1 for each element.When the loop is finished, the
                  count variable contains the number of elements in the numbers
                  list, which is 5. The print() function is used to display the
                  value of the count variable.
                </span>
                <br />
              </span>
            </div>
            <div class="basic-py3bi-container05">
              <img
                alt="image"
                src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/3b%20Control%20Structure_Hapih/351C6150-3B44-4060-BF07-FEB56521E489.jpeg?raw=true"
                class="basic-py3bi-image1"
              />
              <span class="basic-py3bi-text07">
                <span>
                  This code is used to calculate the sum of a list of numbers. The
                  numbers list contains three elements, all of which are equal to
                  1. The sum variable is initialized to 0, and a for loop is used
                  to iterate over each element in the numbers list. Inside the
                  loop, the value of each element is added to the sum variable
                  using the += operator. When the loop is finished, the sum
                  variable contains the sum of the numbers in the numbers list,
                  which is 3. The print() function is used to display the value of
                  the sum variable.
                </span>
                <br />
              </span>
            </div>
          </div>
          <div class="basic-py3bi-container06">
            <div class="basic-py3bi-container07">
              <div class="basic-py3bi-container08"></div>
              <span class="basic-py3bi-text10">
                <span>
                  This code is used to find the maximum value in a list of
                  numbers. The numbers list contains five elements, and the max
                  variable is initialized to 0. A for loop is used to iterate over
                  each element in the numbers list, and an if statement is used to
                  check if the current element is greater than the current maximum
                  value. If it is, the value of max is updated to the current
                  element. When the loop is finished, the max variable contains
                  the maximum value in the numbers list, which is 100. The print()
                  function is used to display the value of the max variable.
                </span>
                <br />
              </span>
            </div>
            <div class="basic-py3bi-container09">
              <img
                alt="image"
                src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/3b%20Control%20Structure_Hapih/64FF4C5B-3D8C-45ED-A914-D6E19AAB9F3C.jpeg?raw=true"
                class="basic-py3bi-image2"
              />
              <span class="basic-py3bi-text13">
                A new list called list2 is a copy of list1. A for loop is used to
                iterate over each element in list1, and the append() method is
                used to add each element to list2. When the loop is finished,
                list2 contains the same elements as list1. The print() function is
                used to display the contents of list2.
              </span>
            </div>
          </div>
          <div class="basic-py3bi-container10">
            <div class="basic-py3bi-container11">
              <img
                alt="image"
                src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/3b%20Control%20Structure_Hapih/7901E99D-18C3-4052-A41A-ECE95F6BDC39.jpeg?raw=true"
                class="basic-py3bi-image3"
              />
            </div>
            <span class="basic-py3bi-text14">
              A simple for loop code where The fruits list contains three
              elements, and the for loop is used to iterate over each element in
              the list. Inside the loop, the value of each element is printed
              using the print() function. When the loop is finished, the program
              exits.
            </span>
          </div>
          <div class="basic-py3bi-container12">
            <img
              alt="image"
              src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/3b%20Control%20Structure_Hapih/752E90BB-8080-4050-B69D-DD686614F5FF.jpeg?raw=true"
              class="basic-py3bi-image4"
            />
            <span class="basic-py3bi-text15">
              This code is a simple example of a for loop in Python. The biodata
              dictionary contains three key-value pairs, and the for loop is used
              to iterate over each key-value pair in the dictionary. Inside the
              loop, the key and value of each pair are printed using the print()
              function. When the loop is finished, the program exits.
            </span>
          </div>
          <div class="basic-py3bi-container13">
            <img
              alt="image"
              src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/3b%20Control%20Structure_Hapih/7139BF9D-D4A6-42C6-B246-D559499E4CAE.jpeg?raw=true"
              class="basic-py3bi-image5"
            />
            <span class="basic-py3bi-text16">
              This code is an example of a nested for loop in Python. The outer
              loop uses the range() function to iterate over the values 1, 2, and
              3, and the inner loop also uses the range() function to iterate over
              the same values. Inside the inner loop, the values of i and j are
              printed using the print() function.
            </span>
          </div>
          <span class="basic-py3bi-text17">-Muhammad Hafiz</span>
        </div>
      </div>
    </div>
    <div class="basic-py3bi-reference">
      <h1 class="basic-py3bi-text18">References</h1>
      <span class="basic-py3bi-text19">
        <br />
        <span class="basic-py3bi-text21">
          Loops in Python - For, while and nested loops
          <span v-html="rawcoy3"></span>
        </span>
        <span>(2023, December 21). GeeksforGeeks.</span>
        <br />
        <span>
                 
          <span v-html="raw2zyb"></span>
        </span>
        <a
          href="https://www.geeksforgeeks.org/loops-in-python/?ref=lbp"
          target="_blank"
          rel="noreferrer noopener"
          class="basic-py3bi-link"
        >
          https://www.geeksforgeeks.org/loops-in-python/?ref=lbp
        </a>
        <br />
        <br />
        <span>
          Bonthu, H. (2023, April 26).
          <span v-html="rawaf0e"></span>
        </span>
        <span class="basic-py3bi-text28">
          Master control statements in Python with examples (Updated 2023)
        </span>
        <span>. Analytics Vidhya.</span>
        <br />
        <span>
                 
          <span v-html="rawf9v8"></span>
        </span>
        <a
          href="https://www.analyticsvidhya.com/blog/2021/09/loops-and-control-statements-an-in-depth-python-tutorial/"
          target="_blank"
          rel="noreferrer noopener"
          class="basic-py3bi-link1"
        >
          https://www.analyticsvidhya.com/blog/2021/09/loops-and-control-statements-an-in-depth-python-tutorial/
        </a>
        <br />
        <br />
        <span class="basic-py3bi-text34">Python iterative statements.</span>
        <span>
          (2018, December 15). Python Class Room Diary.
          <span v-html="rawac0p"></span>
        </span>
        <br />
        <span>
                 
          <span v-html="rawyjsa"></span>
        </span>
        <a
          href="https://pythonclassroomdiary.in/python-notes-printed/python-iterative-statements/"
          target="_blank"
          rel="noreferrer noopener"
          class="basic-py3bi-link2"
        >
          https://pythonclassroomdiary.in/python-notes-printed/python-iterative-statements/
        </a>
        <br />
      </span>
    </div>
    <footer class="basic-py3bi-footer">
      <div class="basic-py3bi-container14">
        <router-link to="/strace" class="basic-py3bi-navlink5">
          STRACE
        </router-link>
      </div>
      <span class="basic-py3bi-text39">
        &quot;Making System Calls Cool Again&quot;
      </span>
      <div class="basic-py3bi-icon-group">
        <svg viewBox="0 0 877.7142857142857 1024" class="basic-py3bi-icon">
          <path
            d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
          ></path>
        </svg>
      </div>
    </footer>
    <app-header></app-header>
  </div>
</template>

<script>
import AppHeader from '../components/header'

export default {
  name: 'BasicPy3bi',
  props: {},
  components: {
    AppHeader,
  },
  data() {
    return {
      rawcoy3: ' ',
      raw2zyb: ' ',
      rawaf0e: ' ',
      rawf9v8: ' ',
      rawac0p: ' ',
      rawyjsa: ' ',
    }
  },
  metaInfo: {
    title: 'Strace | Basic Python',
    meta: [
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ],
  },
}
</script>

<style scoped>
.basic-py3bi-container {
  width: 100%;
  display: flex;
  overflow: auto;
  min-height: 100vh;
  align-items: center;
  flex-direction: column;
  justify-content: flex-start;
  background-color: #f5f5f5;
}
.basic-py3bi-banner {
  width: 100%;
  height: 275px;
  display: flex;
  transition: 0.3s;
  align-items: center;
  flex-direction: column;
  background-size: cover;
  justify-content: center;
  background-image: url('https://marketplace.canva.com/EAD2962NKnQ/2/0/1600w/canva-rainbow-gradient-pink-and-purple-virtual-background-_Tcjok-d9b4.jpg');
}

.basic-py3bi-main-content {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: flex-start;
  background-color: #ffffff;
}
.basic-py3bi-heading {
  color: #ff0000;
  font-size: 3rem;
  align-self: center;
  text-align: center;
}
.basic-py3bi-container01 {
  flex: 0 0 auto;
  width: 100%;
  height: 100px;
  display: flex;
  align-items: flex-start;
}
.basic-py3bi-navlink {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py3bi-navlink:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py3bi-navlink1 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py3bi-navlink1:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py3bi-navlink2 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py3bi-navlink2:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py3bi-container02 {
  flex: 0 0 auto;
  width: 100%;
  height: 100px;
  display: flex;
  align-items: flex-start;
}
.basic-py3bi-navlink3 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py3bi-navlink3:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py3bi-navlink4 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py3bi-navlink4:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py3bi-content-here {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.basic-py3bi-column {
  flex: 1;
  width: auto;
  height: auto;
  display: flex;
  flex-direction: column;
}
.basic-py3bi-text03 {
  text-align: justify;
}
.basic-py3bi-container03 {
  flex: 0 0 auto;
  width: auto;
  height: auto;
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
}
.basic-py3bi-container04 {
  flex: 0 0 auto;
  width: 391px;
  height: auto;
  display: flex;
  align-items: flex-end;
  flex-direction: column;
}
.basic-py3bi-image {
  width: 200px;
  object-fit: cover;
}
.basic-py3bi-container05 {
  flex: 0 0 auto;
  width: 333px;
  height: auto;
  display: flex;
  align-items: flex-end;
  flex-direction: column;
}
.basic-py3bi-image1 {
  width: 200px;
  object-fit: cover;
}
.basic-py3bi-container06 {
  flex: 0 0 auto;
  width: auto;
  height: auto;
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
}
.basic-py3bi-container07 {
  flex: 0 0 auto;
  width: 399px;
  height: auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.basic-py3bi-container08 {
  width: 200px;
  border: 2px dashed rgba(120, 120, 120, 0.4);
  height: 230px;
  display: flex;
  align-items: flex-end;
  background-size: cover;
  justify-content: flex-start;
  background-image: url('https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/3b%20Control%20Structure_Hapih/3A884F45-F19B-44DA-A584-9455516CD32C.jpeg?raw=true');
  background-position: center;
}
.basic-py3bi-container09 {
  flex: 0 0 auto;
  width: 634px;
  height: auto;
  display: flex;
  align-items: center;
  flex-direction: column;
}
.basic-py3bi-image2 {
  width: 200px;
  object-fit: cover;
}
.basic-py3bi-container10 {
  flex: 0 0 auto;
  width: auto;
  height: 244px;
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
}
.basic-py3bi-container11 {
  flex: 0 0 auto;
  width: auto;
  height: 244px;
  display: flex;
  align-items: center;
  justify-content: center;
}
.basic-py3bi-image3 {
  width: 200px;
  object-fit: cover;
}
.basic-py3bi-container12 {
  flex: 0 0 auto;
  width: auto;
  height: 252px;
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
}
.basic-py3bi-image4 {
  width: 200px;
  object-fit: cover;
}
.basic-py3bi-container13 {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.basic-py3bi-image5 {
  width: 200px;
  object-fit: cover;
}
.basic-py3bi-reference {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #ffffff;
}
.basic-py3bi-footer {
  width: 100%;
  display: flex;
  max-width: var(--dl-size-size-maxwidth);
  align-self: center;
  align-items: center;
  padding-top: var(--dl-space-space-twounits);
  padding-left: var(--dl-space-space-threeunits);
  padding-right: var(--dl-space-space-threeunits);
  padding-bottom: var(--dl-space-space-twounits);
  justify-content: space-between;
}
.basic-py3bi-container14 {
  flex: 0 0 auto;
  width: auto;
  height: auto;
  display: flex;
  align-items: space-between;
  flex-direction: column;
}
.basic-py3bi-navlink5 {
  font-weight: 700;
  text-decoration: none;
}
.basic-py3bi-icon {
  width: 24px;
  height: 24px;
}
@media(max-width: 1600px) {
  .basic-py3bi-container {
    background-color: #f7f7f7;
  }
  .basic-py3bi-banner {
    height: auto;
    align-items: center;
    background-size: cover;
    justify-content: flex-start;
    background-image: url("/external/bgportrait-1500w.jpg");
  }
  .basic-py3bi-main-content {
    flex: 1;
    width: 1300px;
    height: auto;
    box-shadow: 0px 0px 10px 0px #d3d2d6;
    align-items: flex-start;
    padding-top: 100px;
    flex-direction: column;
    justify-content: flex-start;
    background-color: #ffffff;
  }
  .basic-py3bi-heading {
    color: rgb(255, 255, 255);
    width: 1200px;
    height: auto;
    font-size: 64px;
    font-style: normal;
    margin-top: 40px;
    font-family: Montserrat;
    font-weight: 700;
    line-height: 1.15;
    padding-top: 40px;
    border-radius: var(--dl-radius-radius-radius4);
    margin-bottom: 20px;
    padding-bottom: 40px;
    background-size: cover;
    background-image: url("/external/bglandscape-1200w.jpg");
    background-position: right;
  }
  .basic-py3bi-container01 {
    width: 700px;
    height: auto;
    align-self: center;
    margin-left: 50px;
    padding-top: 20px;
    margin-right: 50px;
    padding-bottom: 10px;
    justify-content: center;
  }
  .basic-py3bi-navlink {
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py3bi-navlink1 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py3bi-navlink2 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py3bi-container02 {
    width: 800px;
    height: auto;
    align-self: center;
    margin-left: 50px;
    padding-top: 10px;
    margin-right: 50px;
    padding-bottom: 20px;
    justify-content: center;
  }
  .basic-py3bi-navlink3 {
    color: #A068FF;
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py3bi-navlink4 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py3bi-content-here {
    width: 1200px;
    align-items: flex-end;
    margin-left: 50px;
    padding-top: 50px;
    margin-right: 50px;
    padding-bottom: 50px;
  }
  .basic-py3bi-column {
    flex: 1;
    width: 100%;
    position: relative;
    align-items: flex-start;
  }
  .basic-py3bi-text {
    font-size: 36px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
    padding-top: 0px;
    padding-left: 0px;
    padding-right: 0px;
    padding-bottom: 30px;
  }
  .basic-py3bi-text03 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    text-transform: inherit;
  }
  .basic-py3bi-container03 {
    width: 100%;
    margin-top: 25px;
    align-items: center;
    margin-bottom: 25px;
    padding-right: 0px;
    justify-content: flex-end;
  }
  .basic-py3bi-container04 {
    width: 566px;
    align-self: center;
    align-items: center;
    padding-left: 0px;
    justify-content: center;
  }
  .basic-py3bi-image {
    width: 391px;
    height: 273px;
    align-self: center;
    margin-bottom: 15px;
  }
  .basic-py3bi-text04 {
    font-size: 16px;
    align-self: center;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-left: var(--dl-space-space-fourunits);
    padding-right: var(--dl-space-space-fourunits);
  }
  .basic-py3bi-container05 {
    width: 596px;
    align-items: center;
  }
  .basic-py3bi-image1 {
    width: 333px;
    height: 281px;
    align-self: center;
    margin-bottom: 15px;
  }
  .basic-py3bi-text07 {
    font-size: 16px;
    align-self: center;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-left: var(--dl-space-space-fourunits);
    padding-right: var(--dl-space-space-fourunits);
  }
  .basic-py3bi-container06 {
    width: 100%;
    height: 531px;
    align-self: center;
    align-items: center;
    justify-content: center;
  }
  .basic-py3bi-container07 {
    width: 50%;
    align-self: center;
    align-items: center;
    justify-content: center;
  }
  .basic-py3bi-container08 {
    width: 369px;
    height: 232px;
    text-align: center;
    border-style: hidden;
    margin-bottom: 15px;
    justify-content: center;
  }
  .basic-py3bi-text10 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-left: var(--dl-space-space-fourunits);
    padding-right: var(--dl-space-space-fourunits);
  }
  .basic-py3bi-container09 {
    width: 50%;
  }
  .basic-py3bi-image2 {
    flex: 0;
    width: 481px;
    height: 235px;
    align-self: center;
    text-align: right;
    margin-bottom: 15px;
  }
  .basic-py3bi-text13 {
    font-size: 16px;
    align-self: flex-start;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-left: var(--dl-space-space-fourunits);
    padding-right: var(--dl-space-space-fourunits);
  }
  .basic-py3bi-container10 {
    margin-top: 25px;
    align-items: center;
    margin-bottom: 25px;
  }
  .basic-py3bi-container11 {
    align-self: center;
  }
  .basic-py3bi-image3 {
    width: 523px;
    height: 232px;
  }
  .basic-py3bi-text14 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-left: var(--dl-space-space-fiveunits);
  }
  .basic-py3bi-container12 {
    align-self: flex-start;
    margin-top: 25px;
    align-items: center;
    margin-bottom: 25px;
    justify-content: flex-start;
  }
  .basic-py3bi-image4 {
    width: 670px;
    align-self: stretch;
  }
  .basic-py3bi-text15 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-left: var(--dl-space-space-fiveunits);
  }
  .basic-py3bi-container13 {
    margin-top: 25px;
    align-items: center;
    margin-bottom: 25px;
  }
  .basic-py3bi-image5 {
    width: 398px;
    height: 359px;
    align-self: center;
  }
  .basic-py3bi-text16 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-left: var(--dl-space-space-fiveunits);
  }
  .basic-py3bi-text17 {
    font-size: 18px;
    font-style: italic;
    font-family: Inter;
    font-weight: 500;
    padding-top: 25px;
  }
  .basic-py3bi-reference {
    width: 1600px;
    height: auto;
    align-self: center;
    box-shadow: 0px -1px 15px 0px #ebebeb;
    margin-top: 0px;
    align-items: flex-start;
    padding-top: 50px;
    padding-left: 200px;
    padding-right: 200px;
    flex-direction: column;
    padding-bottom: 50px;
    justify-content: flex-start;
  }
  .basic-py3bi-text18 {
    font-size: 32px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
  }
  .basic-py3bi-text19 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.25;
  }
  .basic-py3bi-text21 {
    font-style: italic;
  }
  .basic-py3bi-link {
    color: var(--dl-color-primary-300);
    text-decoration: underline;
  }
  .basic-py3bi-text28 {
    font-style: italic;
  }
  .basic-py3bi-link1 {
    color: var(--dl-color-primary-300);
    text-decoration: underline;
  }
  .basic-py3bi-text34 {
    font-style: italic;
  }
  .basic-py3bi-link2 {
    color: var(--dl-color-primary-300);
    text-decoration: underline;
  }
  .basic-py3bi-footer {
    justify-content: space-between;
  }
  .basic-py3bi-navlink5 {
    font-size: 16px;
    font-family: Montserrat;
    font-weight: 700;
    text-decoration: none;
  }
  .basic-py3bi-text39 {
    font-size: 16px;
    font-style: normal;
    font-family: Montserrat;
    font-weight: 500;
  }
  .basic-py3bi-icon {
    margin-left: 50px;
  }
}
@media(max-width: 1200px) {
  .basic-py3bi-heading {
    color: rgb(255, 255, 255);
  }
}
@media(max-width: 479px) {
  .basic-py3bi-footer {
    align-self: center;
  }
  .basic-py3bi-icon-group {
    display: none;
  }
}
</style>
