// [Angular] Website Source Code/src/app/pages/basic-py-1a/basic-py-1a.component.ts
import { Component } from '@angular/core'
import { Title, Meta } from '@angular/platform-browser'

@Component({
  selector: 'basic-py1a',
  templateUrl: 'basic-py-1a.component.html',
  styleUrls: ['basic-py-1a.component.css'],
})
export class BasicPy1a {
  rawhqlr: string = ' '
  rawlips: string = ' '
  raw411w: string = ' '
  raw4oc9: string = ' '
  raw6cd0: string = ' '
  rawednj: string = ' '
  rawng2z: string = ' '
  raw92yt: string = ' '
  raw273t: string = ' '
  raw8312: string = ' '
  rawgrhb: string = ' '
  rawris8: string = ' '
  rawyhmn: string = ' '
  rawp4ww: string = ' '
  rawi0s0: string = ' '
  constructor(private title: Title, private meta: Meta) {
    this.title.setTitle('Strace | Basic Python')
    this.meta.addTags([
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ])
  }
}

<div class="basic-py1a-container">
  <div class="basic-py1a-banner">
    <div class="basic-py1a-main-content">
      <h1 class="basic-py1a-heading">NAMES AND BINDINGS</h1>
      <div class="basic-py1a-container1">
        <a routerLink="/basic-py-1a" class="basic-py1a-navlink button">Name</a>
        <a routerLink="/basic-py-1b" class="basic-py1a-navlink1 button">
          Address, Value and Type
        </a>
        <a routerLink="/basic-py-1c" class="basic-py1a-navlink2 button">
          The Concept of Binding
        </a>
        <a routerLink="/basic-py-1d" class="basic-py1a-navlink3 button">
          Scope and Lifetime
        </a>
        <a routerLink="/basic-py-1e" class="basic-py1a-navlink4 button">
          Referencing Environments
        </a>
        <a routerLink="/basic-py-1f" class="basic-py1a-navlink5 button">
          Named Constants
        </a>
      </div>
      <div class="basic-py1a-alia">
        <div class="basic-py1a-name">
          <div class="basic-py1a-length">
            <h1 class="basic-py1a-text">Name</h1>
            <strong class="basic-py1a-text01">
              <span><span [innerHTML]="rawhqlr"></span></span>
              <span class="basic-py1a-text03">Length</span>
              <span><span [innerHTML]="rawlips"></span></span>
              <br />
              <br />
              <span><span [innerHTML]="raw411w"></span></span>
              <span>
                The length of a variable name for Python can be any length which
                means it is unlimited. However, it is a good practice to keep
                variable names reasonably short, meaningful, and descriptive for
                the sake of code readability.
                <span [innerHTML]="raw4oc9"></span>
              </span>
              <span><span [innerHTML]="raw6cd0"></span></span>
            </strong>
            <div class="basic-py1a-container2">
              <img
                alt="image"
                src="/assets/external/screenshot%202023-12-23%20105803-300h-200h.png"
                class="basic-py1a-image"
              />
              <img
                alt="image"
                src="/assets/external/screenshot%202023-12-23%20105822-500h-300h.png"
                class="basic-py1a-image1"
              />
            </div>
          </div>
          <div class="basic-py1a-invalid-case-sensitive">
            <strong class="basic-py1a-text10">Valid variable name:</strong>
            <img
              alt="image"
              src="/assets/external/picture1-800w-800w.png"
              class="basic-py1a-image2"
            />
            <strong class="basic-py1a-text11">Invalid variable name:</strong>
            <img
              alt="image"
              src="/assets/external/picture2-200h-200h.png"
              class="basic-py1a-image3"
            />
            <strong class="basic-py1a-text12">
              <span class="basic-py1a-text13">Case sensitivity</span>
              <br />
              <br />
              <span>
                Case and underscore character is significant where lowercase and
                uppercase letters are not the same meaning.
              </span>
              <br />
              <br />
            </strong>
            <img
              alt="image"
              src="/assets/external/picture5-400h-400h.png"
              class="basic-py1a-image4"
            />
          </div>
        </div>
        <div class="basic-py1a-special-word">
          <strong class="basic-py1a-text19">
            <span class="basic-py1a-text20">Special Words</span>
            <br />
            <br />
            <span>
              In Python,
              <span [innerHTML]="rawednj"></span>
            </span>
            <span class="basic-py1a-text24">
              reserved words
              <span [innerHTML]="rawng2z"></span>
            </span>
            <span>
              are words that
              <span [innerHTML]="raw92yt"></span>
            </span>
            <span class="basic-py1a-text26">
              have special meanings
              <span [innerHTML]="raw273t"></span>
            </span>
            <span>
              and
              <span [innerHTML]="raw8312"></span>
            </span>
            <span class="basic-py1a-text28">
              cannot be used as identifiers
              <span [innerHTML]="rawgrhb"></span>
            </span>
            <span>
              (such as variable names, function names, or class names) because
              they are part of the Python language&apos;s syntax. While
              keywords, a subset of reserved words, are specific identifiers
              that have predefined meanings in the language.
            </span>
            <br />
            <br />
            <span>
              Note that using reserved words as variable names or identifiers
              will result in a syntax error.
            </span>
            <br />
            <br />
          </strong>
          <div class="basic-py1a-image5">
            <img
              alt="image"
              src="/assets/external/picture3-300h-300h.png"
              class="basic-py1a-image6"
            />
            <svg viewBox="0 0 1024 1024" class="basic-py1a-icon">
              <path
                d="M512 170l342 342-342 342-60-60 238-240h-520v-84h520l-238-240z"
              ></path>
            </svg>
            <img
              alt="image"
              src="/assets/external/picture4-300h-300h.png"
              class="basic-py1a-image7"
            />
          </div>
        </div>
        <span class="basic-py1a-text35">
          <span>
            -
            <span [innerHTML]="rawris8"></span>
          </span>
          <span class="basic-py1a-text37">Noor Alia Alisa</span>
        </span>
      </div>
    </div>
  </div>
  <div class="basic-py1a-reference">
    <h1 class="basic-py1a-text38">References</h1>
    <span class="basic-py1a-text39">
      <br class="basic-py1a-text40" />
      <span class="basic-py1a-text41">
        Barger, R. (2023, March 22).
        <span [innerHTML]="rawyhmn"></span>
      </span>
      <span class="basic-py1a-text42">
        Python Variables – The Complete Beginner’s Guide
      </span>
      <span class="basic-py1a-text43">. freeCodeCamp.org.</span>
      <br class="basic-py1a-text44" />
      <span class="basic-py1a-text45">
               
        <span [innerHTML]="rawp4ww"></span>
      </span>
      <a
        href="https://www.freecodecamp.org/news/python-variables/"
        target="_blank"
        rel="noreferrer noopener"
        class="basic-py1a-link"
      >
        https://www.freecodecamp.org/news/python-variables/
      </a>
      <br class="basic-py1a-text46" />
      <br class="basic-py1a-text47" />
      <span class="basic-py1a-text48">
        Python Reserved Words List - Your Complete Guide.
      </span>
      <span> (n.d.). Flexiple.</span>
      <br />
      <span>
               
        <span [innerHTML]="rawi0s0"></span>
      </span>
      <a
        href="https://flexiple.com/python/python-reserved-words"
        target="_blank"
        rel="noreferrer noopener"
        class="basic-py1a-link1"
      >
        https://flexiple.com/python/python-reserved-words
      </a>
      <br />
    </span>
  </div>
  <footer class="basic-py1a-footer">
    <div class="basic-py1a-container3">
      <a routerLink="/strace" class="basic-py1a-navlink6">STRACE</a>
    </div>
    <span class="basic-py1a-text53">
      &quot;Making System Calls Cool Again&quot;
    </span>
    <div class="basic-py1a-icon-group">
      <svg viewBox="0 0 877.7142857142857 1024" class="basic-py1a-icon2">
        <path
          d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
        ></path>
      </svg>
    </div>
  </footer>
  <app-header></app-header>
</div>

// [Vue] Website Source Code/src/views/basic-py-1a.vue
<template>
  <div class="basic-py1a-container">
    <div class="basic-py1a-banner">
      <div class="basic-py1a-main-content">
        <h1 class="basic-py1a-heading">NAMES AND BINDINGS</h1>
        <div class="basic-py1a-container1">
          <router-link to="/basic-py-1a" class="basic-py1a-navlink button">
            Name
          </router-link>
          <router-link to="/basic-py-1b" class="basic-py1a-navlink1 button">
            Address, Value and Type
          </router-link>
          <router-link to="/basic-py-1c" class="basic-py1a-navlink2 button">
            The Concept of Binding
          </router-link>
          <router-link to="/basic-py-1d" class="basic-py1a-navlink3 button">
            Scope and Lifetime
          </router-link>
          <router-link to="/basic-py-1e" class="basic-py1a-navlink4 button">
            Referencing Environments
          </router-link>
          <router-link to="/basic-py-1f" class="basic-py1a-navlink5 button">
            Named Constants
          </router-link>
        </div>
        <div class="basic-py1a-alia">
          <div class="basic-py1a-name">
            <div class="basic-py1a-length">
              <h1 class="basic-py1a-text">Name</h1>
              <strong class="basic-py1a-text01">
                <span><span v-html="raw3f4v"></span></span>
                <span class="basic-py1a-text03">Length</span>
                <span><span v-html="rawxg99"></span></span>
                <br />
                <br />
                <span><span v-html="rawdaqj"></span></span>
                <span>
                  The length of a variable name for Python can be any length which
                  means it is unlimited. However, it is a good practice to keep
                  variable names reasonably short, meaningful, and descriptive for
                  the sake of code readability.
                  <span v-html="raw54em"></span>
                </span>
                <span><span v-html="rawoidk"></span></span>
              </strong>
              <div class="basic-py1a-container2">
                <img
                  alt="image"
                  src="/external/screenshot%202023-12-23%20105803-300h-200h.png"
                  class="basic-py1a-image"
                />
                <img
                  alt="image"
                  src="/external/screenshot%202023-12-23%20105822-500h-300h.png"
                  class="basic-py1a-image1"
                />
              </div>
            </div>
            <div class="basic-py1a-invalid-case-sensitive">
              <strong class="basic-py1a-text10">Valid variable name:</strong>
              <img
                alt="image"
                src="/external/picture1-800w-800w.png"
                class="basic-py1a-image2"
              />
              <strong class="basic-py1a-text11">Invalid variable name:</strong>
              <img
                alt="image"
                src="/external/picture2-200h-200h.png"
                class="basic-py1a-image3"
              />
              <strong class="basic-py1a-text12">
                <span class="basic-py1a-text13">Case sensitivity</span>
                <br />
                <br />
                <span>
                  Case and underscore character is significant where lowercase and
                  uppercase letters are not the same meaning.
                </span>
                <br />
                <br />
              </strong>
              <img
                alt="image"
                src="/external/picture5-400h-400h.png"
                class="basic-py1a-image4"
              />
            </div>
          </div>
          <div class="basic-py1a-special-word">
            <strong class="basic-py1a-text19">
              <span class="basic-py1a-text20">Special Words</span>
              <br />
              <br />
              <span>
                In Python,
                <span v-html="rawcp5t"></span>
              </span>
              <span class="basic-py1a-text24">
                reserved words
                <span v-html="raw86w8"></span>
              </span>
              <span>
                are words that
                <span v-html="rawk33b"></span>
              </span>
              <span class="basic-py1a-text26">
                have special meanings
                <span v-html="rawaub0"></span>
              </span>
              <span>
                and
                <span v-html="raw6mhz"></span>
              </span>
              <span class="basic-py1a-text28">
                cannot be used as identifiers
                <span v-html="rawj2yh"></span>
              </span>
              <span>
                (such as variable names, function names, or class names) because
                they are part of the Python language&apos;s syntax. While
                keywords, a subset of reserved words, are specific identifiers
                that have predefined meanings in the language.
              </span>
              <br />
              <br />
              <span>
                Note that using reserved words as variable names or identifiers
                will result in a syntax error.
              </span>
              <br />
              <br />
            </strong>
            <div class="basic-py1a-image5">
              <img
                alt="image"
                src="/external/picture3-300h-300h.png"
                class="basic-py1a-image6"
              />
              <svg viewBox="0 0 1024 1024" class="basic-py1a-icon">
                <path
                  d="M512 170l342 342-342 342-60-60 238-240h-520v-84h520l-238-240z"
                ></path>
              </svg>
              <img
                alt="image"
                src="/external/picture4-300h-300h.png"
                class="basic-py1a-image7"
              />
            </div>
          </div>
          <span class="basic-py1a-text35">
            <span>
              -
              <span v-html="rawbwhs"></span>
            </span>
            <span class="basic-py1a-text37">Noor Alia Alisa</span>
          </span>
        </div>
      </div>
    </div>
    <div class="basic-py1a-reference">
      <h1 class="basic-py1a-text38">References</h1>
      <span class="basic-py1a-text39">
        <br class="basic-py1a-text40" />
        <span class="basic-py1a-text41">
          Barger, R. (2023, March 22).
          <span v-html="rawx8a8"></span>
        </span>
        <span class="basic-py1a-text42">
          Python Variables – The Complete Beginner’s Guide
        </span>
        <span class="basic-py1a-text43">. freeCodeCamp.org.</span>
        <br class="basic-py1a-text44" />
        <span class="basic-py1a-text45">
                 
          <span v-html="rawgn20"></span>
        </span>
        <a
          href="https://www.freecodecamp.org/news/python-variables/"
          target="_blank"
          rel="noreferrer noopener"
          class="basic-py1a-link"
        >
          https://www.freecodecamp.org/news/python-variables/
        </a>
        <br class="basic-py1a-text46" />
        <br class="basic-py1a-text47" />
        <span class="basic-py1a-text48">
          Python Reserved Words List - Your Complete Guide.
        </span>
        <span> (n.d.). Flexiple.</span>
        <br />
        <span>
                 
          <span v-html="rawhy51"></span>
        </span>
        <a
          href="https://flexiple.com/python/python-reserved-words"
          target="_blank"
          rel="noreferrer noopener"
          class="basic-py1a-link1"
        >
          https://flexiple.com/python/python-reserved-words
        </a>
        <br />
      </span>
    </div>
    <footer class="basic-py1a-footer">
      <div class="basic-py1a-container3">
        <router-link to="/strace" class="basic-py1a-navlink6">STRACE</router-link>
      </div>
      <span class="basic-py1a-text53">
        &quot;Making System Calls Cool Again&quot;
      </span>
      <div class="basic-py1a-icon-group">
        <svg viewBox="0 0 877.7142857142857 1024" class="basic-py1a-icon2">
          <path
            d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
          ></path>
        </svg>
      </div>
    </footer>
    <app-header></app-header>
  </div>
</template>

<script>
import AppHeader from '../components/header'

export default {
  name: 'BasicPy1a',
  props: {},
  components: {
    AppHeader,
  },
  data() {
    return {
      raw3f4v: ' ',
      rawxg99: ' ',
      rawdaqj: ' ',
      raw54em: ' ',
      rawoidk: ' ',
      rawcp5t: ' ',
      raw86w8: ' ',
      rawk33b: ' ',
      rawaub0: ' ',
      raw6mhz: ' ',
      rawj2yh: ' ',
      rawbwhs: ' ',
      rawx8a8: ' ',
      rawgn20: ' ',
      rawhy51: ' ',
    }
  },
  metaInfo: {
    title: 'Strace | Basic Python',
    meta: [
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ],
  },
}
</script>

<style scoped>
.basic-py1a-container {
  width: 100%;
  display: flex;
  overflow: auto;
  min-height: 100vh;
  align-items: center;
  flex-direction: column;
  justify-content: flex-start;
  background-color: #f5f5f5;
}
.basic-py1a-banner {
  width: 100%;
  height: 275px;
  display: flex;
  transition: 0.3s;
  align-items: center;
  flex-direction: column;
  background-size: cover;
  justify-content: center;
  background-image: url('https://marketplace.canva.com/EAD2962NKnQ/2/0/1600w/canva-rainbow-gradient-pink-and-purple-virtual-background-_Tcjok-d9b4.jpg');
}

.basic-py1a-main-content {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: flex-start;
  background-color: #ffffff;
}
.basic-py1a-heading {
  color: #ff0000;
  font-size: 3rem;
  align-self: center;
  text-align: center;
}
.basic-py1a-container1 {
  flex: 0 0 auto;
  width: 100%;
  height: 100px;
  display: flex;
  align-items: flex-start;
}
.basic-py1a-navlink {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py1a-navlink:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py1a-navlink1 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py1a-navlink1:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py1a-navlink2 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py1a-navlink2:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py1a-navlink3 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py1a-navlink3:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py1a-navlink4 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py1a-navlink4:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py1a-navlink5 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py1a-navlink5:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py1a-alia {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.basic-py1a-name {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.basic-py1a-length {
  width: 1536px;
  height: 845px;
  display: flex;
  position: relative;
  align-items: flex-start;
  flex-direction: column;
}
.basic-py1a-text01 {
  color: var(--dl-color-gray-black);
  font-size: 20px;
  margin-top: 20px;
  margin-left: 10px;
}
.basic-py1a-container2 {
  width: 1600px;
  height: 548px;
  display: flex;
  position: relative;
  align-items: center;
  flex-direction: column;
  justify-content: flex-start;
}
.basic-py1a-image {
  width: 200px;
  object-fit: cover;
}
.basic-py1a-image1 {
  width: 200px;
  object-fit: cover;
}
.basic-py1a-invalid-case-sensitive {
  width: 1454px;
  height: 258px;
  display: flex;
  margin-top: 0px;
  align-items: flex-start;
  margin-right: 0px;
  flex-direction: column;
}
.basic-py1a-text10 {
  align-self: flex-start;
  margin-left: 10px;
}
.basic-py1a-image2 {
  width: 703px;
  height: 184px;
  margin-top: 10px;
  object-fit: cover;
}
.basic-py1a-text11 {
  top: 18px;
  left: 780px;
  position: absolute;
}
.basic-py1a-image3 {
  right: -12px;
  width: 753px;
  bottom: -127px;
  height: 182px;
  position: absolute;
  align-self: flex-end;
  object-fit: cover;
}
.basic-py1a-text12 {
  font-weight: 700;
  margin-left: 10px;
}
.basic-py1a-image4 {
  width: 670px;
  height: 314px;
  object-fit: cover;
  margin-left: 10px;
}
.basic-py1a-special-word {
  width: 1327px;
  height: 821px;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.basic-py1a-text19 {
  margin-top: 0px;
  margin-left: 10px;
}
.basic-py1a-image5 {
  flex: 0 0 auto;
  width: 661px;
  height: 208px;
  display: flex;
  align-items: flex-start;
  flex-direction: row;
  justify-content: flex-start;
}
.basic-py1a-image6 {
  width: 725px;
  height: 217px;
  object-fit: cover;
  margin-left: 10px;
}
.basic-py1a-icon {
  width: 102px;
  height: 102px;
  align-self: center;
}
.basic-py1a-image7 {
  width: 434px;
  height: 223px;
  object-fit: cover;
}
.basic-py1a-reference {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #ffffff;
}
.basic-py1a-footer {
  width: 100%;
  display: flex;
  max-width: var(--dl-size-size-maxwidth);
  align-self: center;
  align-items: center;
  padding-top: var(--dl-space-space-twounits);
  padding-left: var(--dl-space-space-threeunits);
  padding-right: var(--dl-space-space-threeunits);
  padding-bottom: var(--dl-space-space-twounits);
  justify-content: space-between;
}
.basic-py1a-container3 {
  flex: 0 0 auto;
  width: auto;
  height: auto;
  display: flex;
  align-items: space-between;
  flex-direction: column;
}
.basic-py1a-navlink6 {
  font-weight: 700;
  text-decoration: none;
}
.basic-py1a-icon2 {
  width: 24px;
  height: 24px;
}
@media(max-width: 1600px) {
  .basic-py1a-container {
    background-color: #f7f7f7;
  }
  .basic-py1a-banner {
    height: auto;
    align-items: center;
    background-size: cover;
    justify-content: flex-start;
    background-image: url("/external/bgportrait-1500w.jpg");
  }
  .basic-py1a-main-content {
    flex: 1;
    width: 1300px;
    height: auto;
    box-shadow: 0px 0px 10px 0px #d3d2d6;
    align-items: flex-start;
    padding-top: 100px;
    flex-direction: column;
    justify-content: flex-start;
    background-color: #ffffff;
  }
  .basic-py1a-heading {
    color: rgb(255, 255, 255);
    width: 1200px;
    height: auto;
    font-size: 64px;
    font-style: normal;
    margin-top: 40px;
    font-family: Montserrat;
    font-weight: 700;
    line-height: 1.15;
    padding-top: 40px;
    border-radius: var(--dl-radius-radius-radius4);
    margin-bottom: 20px;
    padding-bottom: 40px;
    background-size: cover;
    background-image: url("/external/bglandscape-1200w.jpg");
    background-position: bottom left;
  }
  .basic-py1a-container1 {
    width: 1050px;
    height: auto;
    align-self: center;
    align-items: center;
    margin-left: 50px;
    padding-top: 20px;
    margin-right: 50px;
    padding-bottom: 20px;
    justify-content: space-between;
  }
  .basic-py1a-navlink {
    color: #A068FF;
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py1a-navlink1 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py1a-navlink2 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py1a-navlink3 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py1a-navlink4 {
    color: var(--dl-color-gray-black);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py1a-navlink5 {
    color: var(--dl-color-gray-black);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py1a-alia {
    width: 1200px;
    height: auto;
    align-self: flex-start;
    align-items: center;
    margin-left: 50px;
    padding-top: 50px;
    margin-right: 50px;
    padding-bottom: 50px;
  }
  .basic-py1a-name {
    height: auto;
    margin-bottom: 25px;
  }
  .basic-py1a-length {
    width: 50%;
    height: auto;
    padding-right: 25px;
  }
  .basic-py1a-text {
    font-size: 36px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
    margin-bottom: 10px;
  }
  .basic-py1a-text01 {
    color: var(--dl-color-gray-black);
    font-size: 16px;
    font-style: normal;
    margin-top: 0px;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    margin-left: 0px;
    margin-bottom: 20px;
  }
  .basic-py1a-text03 {
    font-weight: 600;
  }
  .basic-py1a-container2 {
    width: 100%;
    height: 360px;
  }
  .basic-py1a-image {
    width: 562px;
    height: 134px;
    margin-bottom: 10px;
  }
  .basic-py1a-image1 {
    width: 562px;
    height: 215px;
  }
  .basic-py1a-invalid-case-sensitive {
    width: 621px;
    height: auto;
    margin-top: 0px;
    padding-top: 10px;
    padding-left: 25px;
  }
  .basic-py1a-text10 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 600;
    margin-left: 0px;
    margin-bottom: 10px;
  }
  .basic-py1a-image2 {
    width: 450px;
    height: 116px;
    margin-top: 0px;
    border-radius: var(--dl-radius-radius-radius2);
    margin-bottom: 10px;
  }
  .basic-py1a-text11 {
    top: 16px;
    left: 741px;
    position: static;
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 600;
    margin-bottom: 10px;
  }
  .basic-py1a-image3 {
    left: 731px;
    width: 450px;
    bottom: -95px;
    height: 107px;
    position: static;
    align-self: flex-start;
    border-radius: var(--dl-radius-radius-radius2);
    margin-bottom: 10px;
  }
  .basic-py1a-text12 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    margin-left: 0px;
  }
  .basic-py1a-text13 {
    font-weight: 600;
  }
  .basic-py1a-image4 {
    width: 308px;
    height: 139px;
    margin-left: 0px;
    border-radius: var(--dl-radius-radius-radius2);
  }
  .basic-py1a-special-word {
    width: 100%;
    height: auto;
    margin-top: 25px;
    margin-left: 0px;
    border-radius: var(--dl-radius-radius-radius2);
    margin-bottom: 25px;
  }
  .basic-py1a-text19 {
    font-size: 16px;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    margin-left: 0px;
    margin-bottom: 10px;
  }
  .basic-py1a-text20 {
    font-size: 24px;
    font-style: normal;
    font-weight: 700;
  }
  .basic-py1a-text24 {
    font-weight: 700;
  }
  .basic-py1a-text26 {
    font-weight: 700;
  }
  .basic-py1a-text28 {
    font-weight: 700;
  }
  .basic-py1a-image5 {
    width: 100%;
    height: auto;
  }
  .basic-py1a-image6 {
    width: 669px;
    height: 200px;
    margin-left: 0px;
  }
  .basic-py1a-image7 {
    width: 387px;
    height: 198px;
    border-radius: var(--dl-radius-radius-radius2);
  }
  .basic-py1a-text35 {
    font-size: 18px;
    align-self: flex-end;
    font-style: normal;
    font-family: Inter;
    font-weight: 500;
    padding-top: 25px;
  }
  .basic-py1a-text37 {
    font-style: italic;
  }
  .basic-py1a-reference {
    width: 1600px;
    height: auto;
    align-self: center;
    box-shadow: 0px -1px 15px 0px #ebebeb;
    align-items: flex-start;
    padding-top: 50px;
    padding-left: 200px;
    padding-right: 200px;
    flex-direction: column;
    padding-bottom: 50px;
    justify-content: flex-start;
  }
  .basic-py1a-text38 {
    font-size: 32px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
  }
  .basic-py1a-text39 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.25;
  }
  .basic-py1a-text40 {
    font-style: italic;
  }
  .basic-py1a-text41 {
    font-size: 16px;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py1a-text42 {
    font-size: 16px;
    font-style: italic;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py1a-text43 {
    font-size: 16px;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py1a-text44 {
    font-size: 16px;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py1a-text45 {
    font-size: 16px;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py1a-link {
    color: var(--dl-color-primary-300);
    font-size: 16px;
    font-family: Inter;
    font-weight: 400;
    text-decoration: underline;
  }
  .basic-py1a-text46 {
    font-size: 16px;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py1a-text47 {
    font-size: 16px;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py1a-text48 {
    font-style: italic;
  }
  .basic-py1a-link1 {
    color: var(--dl-color-primary-300);
    text-decoration: underline;
  }
  .basic-py1a-footer {
    justify-content: space-between;
  }
  .basic-py1a-navlink6 {
    font-size: 16px;
    font-family: Montserrat;
    font-weight: 700;
    text-decoration: none;
  }
  .basic-py1a-text53 {
    font-size: 16px;
    font-style: normal;
    font-family: Montserrat;
    font-weight: 500;
  }
  .basic-py1a-icon2 {
    margin-left: 50px;
  }
}
@media(max-width: 1200px) {
  .basic-py1a-heading {
    color: rgb(255, 255, 255);
  }
}
@media(max-width: 479px) {
  .basic-py1a-footer {
    align-self: center;
  }
  .basic-py1a-icon-group {
    display: none;
  }
}
</style>
