// [Angular] Website Source Code/src/app/pages/bg-2/bg-2.component.ts
import { Component } from '@angular/core'
import { Title, Meta } from '@angular/platform-browser'

@Component({
  selector: 'app-bg2',
  templateUrl: 'bg-2.component.html',
  styleUrls: ['bg-2.component.css'],
})
export class Bg2 {
  rawlhqf: string = ' '
  rawy8ij: string = ' '
  rawbk2x: string = ' '
  raw345b: string = ' '
  rawnrtf: string = ' '
  rawx0eb: string = ' '
  raw4se0: string = ' '
  rawn7pu: string = ' '
  rawgi00: string = ' '
  rawl50t: string = ' '
  rawwccs: string = ' '
  rawxygp: string = ' '
  constructor(private title: Title, private meta: Meta) {
    this.title.setTitle('Strace | Background')
    this.meta.addTags([
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ])
  }
}

<div class="bg2-container">
  <div class="bg2-banner">
    <div class="bg2-main-content">
      <h1 class="bg2-heading">PROCEDURAL + FUNCTIONAL + OOP = PYTHON !</h1>
      <div class="bg2-num2">
        <div class="bg2-row">
          <div class="bg2-column">
            <span class="bg2-text">
              <span class="bg2-text01">
                Python supported
                <span [innerHTML]="rawlhqf"></span>
              </span>
              <span class="bg2-text02">
                MORE THAN ONE
                <span [innerHTML]="rawy8ij"></span>
              </span>
              <span class="bg2-text03">programming styles</span>
              <span class="bg2-text04">
                !
                <span [innerHTML]="rawbk2x"></span>
              </span>
            </span>
            <span class="bg2-text05">
              <span>
                Python source code can be written mainly in three styles:
                <span [innerHTML]="raw345b"></span>
              </span>
              <span class="bg2-text07">Procedural</span>
              <span>
                ,
                <span [innerHTML]="rawnrtf"></span>
              </span>
              <span class="bg2-text09">Functional</span>
              <span>, and </span>
              <span class="bg2-text11">Object-Oriented</span>
              <br />
              <br />
              <span>
                As any other programming languages, you can write your source in
                a sequence from top to bottom and Python will execute the code
                line by line based on the principal of
                <span [innerHTML]="rawx0eb"></span>
              </span>
              <span class="bg2-text15">procedural programming</span>
              <span>
                . Next, Python also supported some
                <span [innerHTML]="raw4se0"></span>
              </span>
              <span class="bg2-text17">
                functional programming
                <span [innerHTML]="rawn7pu"></span>
              </span>
              <span>
                where you can use the built-in functions like sum, ord, map, and
                many more. The concepts of
                <span [innerHTML]="rawgi00"></span>
              </span>
              <span class="bg2-text19">
                object-oriented programming
                <span [innerHTML]="rawl50t"></span>
              </span>
              <span>
                such as classes, inheritance, and encapsulation can implemented
                in Python.
              </span>
            </span>
          </div>
          <img
            alt="image"
            src="https://i.pinimg.com/564x/77/66/32/7766328a08a8e1311b2f1f909dea3d79.jpg"
            class="bg2-image"
          />
        </div>
        <div class="bg2-code-example">
          <div class="bg2-container1">
            <img
              alt="image"
              src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/1%20-%20Background%20of%20Language%20and%20Framework/ariff_proc.png?raw=true"
              loading="eager"
              class="bg2-image1"
            />
            <span class="bg2-text21">
              Code Snippet of Procedural Programming
            </span>
          </div>
          <div class="bg2-container2">
            <img
              alt="image"
              src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/1%20-%20Background%20of%20Language%20and%20Framework/ariff_func.png?raw=true"
              loading="eager"
              class="bg2-image2"
            />
            <span class="bg2-text22">
              Code Snippet of Functional Programming
            </span>
          </div>
          <div class="bg2-container3">
            <img
              alt="image"
              src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/1%20-%20Background%20of%20Language%20and%20Framework/ariff_oop.png?raw=true"
              loading="eager"
              class="bg2-image3"
            />
            <span class="bg2-text23">
              Code Snippet of Object-Oriented Programming
            </span>
          </div>
        </div>
        <span class="bg2-text24">
          <span>
            -
            <span [innerHTML]="rawwccs"></span>
          </span>
          <span class="bg2-text26">Muhammad Ariff Ridzlan</span>
        </span>
      </div>
    </div>
  </div>
  <div class="bg2-reference">
    <h1 class="bg2-text27">References</h1>
    <span class="bg2-text28">
      <br />
      <span>
        Perera, M. (2020, June 13).
        <span [innerHTML]="rawxygp"></span>
      </span>
      <span class="bg2-text31">
        Let’s start with Python  -  Different Programming Styles
      </span>
      <span>. Medium.</span>
      <br />
      <span>             </span>
      <a
        href="https://madhawacperera.medium.com/lets-start-with-python-different-programming-styles-f13f516ce28f"
        target="_blank"
        rel="noreferrer noopener"
        class="bg2-link"
      >
        https://madhawacperera.medium.com/lets-start-with-python-different-programming-styles-f13f516ce28f
      </a>
      <br />
    </span>
  </div>
  <footer class="bg2-footer">
    <div class="bg2-container4">
      <a routerLink="/strace" class="bg2-navlink">STRACE</a>
    </div>
    <span class="bg2-text36">&quot;Making System Calls Cool Again&quot;</span>
    <div class="bg2-icon-group">
      <svg viewBox="0 0 877.7142857142857 1024" class="bg2-icon">
        <path
          d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
        ></path>
      </svg>
    </div>
  </footer>
  <app-header></app-header>
</div>

// [Vue] Website Source Code/src/views/bg-2.vue
<template>
  <div class="bg2-container">
    <div class="bg2-banner">
      <div class="bg2-main-content">
        <h1 class="bg2-heading">PROCEDURAL + FUNCTIONAL + OOP = PYTHON !</h1>
        <div class="bg2-num2">
          <div class="bg2-row">
            <div class="bg2-column">
              <span class="bg2-text">
                <span class="bg2-text01">
                  Python supported
                  <span v-html="rawdffk"></span>
                </span>
                <span class="bg2-text02">
                  MORE THAN ONE
                  <span v-html="rawapu3"></span>
                </span>
                <span class="bg2-text03">programming styles</span>
                <span class="bg2-text04">
                  !
                  <span v-html="rawo4t6"></span>
                </span>
              </span>
              <span class="bg2-text05">
                <span>
                  Python source code can be written mainly in three styles:
                  <span v-html="rawx5dp"></span>
                </span>
                <span class="bg2-text07">Procedural</span>
                <span>
                  ,
                  <span v-html="rawftfd"></span>
                </span>
                <span class="bg2-text09">Functional</span>
                <span>, and </span>
                <span class="bg2-text11">Object-Oriented</span>
                <br />
                <br />
                <span>
                  As any other programming languages, you can write your source in
                  a sequence from top to bottom and Python will execute the code
                  line by line based on the principal of
                  <span v-html="raw7hm0"></span>
                </span>
                <span class="bg2-text15">procedural programming</span>
                <span>
                  . Next, Python also supported some
                  <span v-html="rawtlw9"></span>
                </span>
                <span class="bg2-text17">
                  functional programming
                  <span v-html="raw6n3e"></span>
                </span>
                <span>
                  where you can use the built-in functions like sum, ord, map, and
                  many more. The concepts of
                  <span v-html="rawmqo2"></span>
                </span>
                <span class="bg2-text19">
                  object-oriented programming
                  <span v-html="rawmz11"></span>
                </span>
                <span>
                  such as classes, inheritance, and encapsulation can implemented
                  in Python.
                </span>
              </span>
            </div>
            <img
              alt="image"
              src="https://i.pinimg.com/564x/77/66/32/7766328a08a8e1311b2f1f909dea3d79.jpg"
              class="bg2-image"
            />
          </div>
          <div class="bg2-code-example">
            <div class="bg2-container1">
              <img
                alt="image"
                src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/1%20-%20Background%20of%20Language%20and%20Framework/ariff_proc.png?raw=true"
                loading="eager"
                class="bg2-image1"
              />
              <span class="bg2-text21">
                Code Snippet of Procedural Programming
              </span>
            </div>
            <div class="bg2-container2">
              <img
                alt="image"
                src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/1%20-%20Background%20of%20Language%20and%20Framework/ariff_func.png?raw=true"
                loading="eager"
                class="bg2-image2"
              />
              <span class="bg2-text22">
                Code Snippet of Functional Programming
              </span>
            </div>
            <div class="bg2-container3">
              <img
                alt="image"
                src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/1%20-%20Background%20of%20Language%20and%20Framework/ariff_oop.png?raw=true"
                loading="eager"
                class="bg2-image3"
              />
              <span class="bg2-text23">
                Code Snippet of Object-Oriented Programming
              </span>
            </div>
          </div>
          <span class="bg2-text24">
            <span>
              -
              <span v-html="rawj3j5"></span>
            </span>
            <span class="bg2-text26">Muhammad Ariff Ridzlan</span>
          </span>
        </div>
      </div>
    </div>
    <div class="bg2-reference">
      <h1 class="bg2-text27">References</h1>
      <span class="bg2-text28">
        <br />
        <span>
          Perera, M. (2020, June 13).
          <span v-html="raw8zwv"></span>
        </span>
        <span class="bg2-text31">
          Let’s start with Python  -  Different Programming Styles
        </span>
        <span>. Medium.</span>
        <br />
        <span>             </span>
        <a
          href="https://madhawacperera.medium.com/lets-start-with-python-different-programming-styles-f13f516ce28f"
          target="_blank"
          rel="noreferrer noopener"
          class="bg2-link"
        >
          https://madhawacperera.medium.com/lets-start-with-python-different-programming-styles-f13f516ce28f
        </a>
        <br />
      </span>
    </div>
    <footer class="bg2-footer">
      <div class="bg2-container4">
        <router-link to="/strace" class="bg2-navlink">STRACE</router-link>
      </div>
      <span class="bg2-text36">&quot;Making System Calls Cool Again&quot;</span>
      <div class="bg2-icon-group">
        <svg viewBox="0 0 877.7142857142857 1024" class="bg2-icon">
          <path
            d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
          ></path>
        </svg>
      </div>
    </footer>
    <app-header></app-header>
  </div>
</template>

<script>
import AppHeader from '../components/header'

export default {
  name: 'Bg2',
  props: {},
  components: {
    AppHeader,
  },
  data() {
    return {
      rawdffk: ' ',
      rawapu3: ' ',
      rawo4t6: ' ',
      rawx5dp: ' ',
      rawftfd: ' ',
      raw7hm0: ' ',
      rawtlw9: ' ',
      raw6n3e: ' ',
      rawmqo2: ' ',
      rawmz11: ' ',
      rawj3j5: ' ',
      raw8zwv: ' ',
    }
  },
  metaInfo: {
    title: 'Strace | Background',
    meta: [
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ],
  },
}
</script>

<style scoped>
.bg2-container {
  width: 100%;
  display: flex;
  overflow: auto;
  min-height: 100vh;
  align-items: center;
  flex-direction: column;
  justify-content: flex-start;
  background-color: #f5f5f5;
}
.bg2-banner {
  width: 100%;
  height: 275px;
  display: flex;
  transition: 0.3s;
  align-items: center;
  flex-direction: column;
  background-size: cover;
  justify-content: center;
  background-image: url('https://marketplace.canva.com/EAD2962NKnQ/2/0/1600w/canva-rainbow-gradient-pink-and-purple-virtual-background-_Tcjok-d9b4.jpg');
}

.bg2-main-content {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: flex-start;
  background-color: #ffffff;
}
.bg2-heading {
  color: #ff0000;
  font-size: 3rem;
  align-self: center;
  text-align: center;
}
.bg2-num2 {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.bg2-row {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.bg2-column {
  flex: 1;
  width: auto;
  height: auto;
  display: flex;
  flex-direction: column;
}
.bg2-text {
  text-align: justify;
}
.bg2-text05 {
  text-align: justify;
}
.bg2-image {
  width: 200px;
  object-fit: cover;
}
.bg2-code-example {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
}
.bg2-container1 {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.bg2-image1 {
  width: 200px;
  object-fit: cover;
}
.bg2-container2 {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.bg2-image2 {
  width: 200px;
  object-fit: cover;
}
.bg2-container3 {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.bg2-image3 {
  width: 200px;
  object-fit: cover;
}
.bg2-reference {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #ffffff;
}
.bg2-footer {
  width: 100%;
  display: flex;
  max-width: var(--dl-size-size-maxwidth);
  align-self: center;
  align-items: center;
  padding-top: var(--dl-space-space-twounits);
  padding-left: var(--dl-space-space-threeunits);
  padding-right: var(--dl-space-space-threeunits);
  padding-bottom: var(--dl-space-space-twounits);
  justify-content: space-between;
}
.bg2-container4 {
  flex: 0 0 auto;
  width: auto;
  height: auto;
  display: flex;
  align-items: space-between;
  flex-direction: column;
}
.bg2-navlink {
  font-weight: 700;
  text-decoration: none;
}
.bg2-icon {
  width: 24px;
  height: 24px;
}
@media(max-width: 1600px) {
  .bg2-container {
    background-color: #f7f7f7;
  }
  .bg2-banner {
    height: auto;
    align-items: center;
    background-size: cover;
    justify-content: flex-start;
    background-image: url("/external/bgportrait-1500w.jpg");
  }
  .bg2-main-content {
    flex: 1;
    width: 1300px;
    height: auto;
    box-shadow: 0px 0px 10px 0px #d3d2d6;
    align-items: flex-start;
    padding-top: 100px;
    flex-direction: column;
    justify-content: flex-start;
    background-color: #ffffff;
  }
  .bg2-heading {
    color: rgb(255, 255, 255);
    width: 1200px;
    height: auto;
    font-size: 64px;
    font-style: normal;
    margin-top: 25px;
    font-family: Montserrat;
    font-weight: 700;
    line-height: 1.15;
    padding-top: 40px;
    border-radius: var(--dl-radius-radius-radius4);
    padding-bottom: 40px;
    background-image: url("/external/bglandscape-1200w.jpg");
    background-position: bottom right;
  }
  .bg2-num2 {
    width: 1200px;
    height: auto;
    align-items: flex-end;
    margin-left: 50px;
    padding-top: 50px;
    margin-right: 50px;
    padding-bottom: 50px;
  }
  .bg2-row {
    align-items: center;
    margin-bottom: 50px;
    justify-content: space-between;
  }
  .bg2-column {
    flex: 1;
    align-items: flex-start;
    justify-content: center;
  }
  .bg2-text {
    font-size: 24px;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.25;
    padding-bottom: var(--dl-space-space-oneandhalfunits);
  }
  .bg2-text01 {
    font-style: normal;
  }
  .bg2-text02 {
    font-style: normal;
    font-weight: 700;
  }
  .bg2-text03 {
    font-style: inherit;
    font-weight: 400;
  }
  .bg2-text04 {
    font-style: normal;
  }
  .bg2-text05 {
    font-size: 16px;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.25;
    padding-right: var(--dl-space-space-fourunits);
  }
  .bg2-text07 {
    font-weight: 700;
  }
  .bg2-text09 {
    font-weight: 700;
  }
  .bg2-text11 {
    font-weight: 700;
  }
  .bg2-text15 {
    font-weight: 600;
  }
  .bg2-text17 {
    font-weight: 600;
  }
  .bg2-text19 {
    font-weight: 600;
  }
  .bg2-code-example {
    align-self: center;
    flex-direction: row;
    padding-bottom: 25px;
    justify-content: space-between;
  }
  .bg2-container1 {
    align-items: center;
    justify-content: center;
  }
  .bg2-image1 {
    width: 371px;
    height: 301px;
    margin-bottom: 25px;
  }
  .bg2-text21 {
    font-size: 16px;
  }
  .bg2-container2 {
    align-items: center;
    justify-content: center;
  }
  .bg2-image2 {
    width: 371px;
    height: 301px;
    margin-bottom: 25px;
  }
  .bg2-text22 {
    font-size: 16px;
  }
  .bg2-container3 {
    align-items: center;
    justify-content: center;
  }
  .bg2-image3 {
    width: 371px;
    height: 301px;
    margin-bottom: 25px;
  }
  .bg2-text23 {
    font-size: 16px;
  }
  .bg2-text24 {
    font-size: 18px;
    font-style: normal;
    font-family: Inter;
    font-weight: 500;
    padding-top: 25px;
  }
  .bg2-text26 {
    font-style: italic;
  }
  .bg2-reference {
    width: 1600px;
    height: auto;
    align-self: center;
    box-shadow: 0px -1px 15px 0px #ebebeb;
    align-items: flex-start;
    padding-top: 50px;
    padding-left: 200px;
    padding-right: 200px;
    flex-direction: column;
    padding-bottom: 50px;
    justify-content: flex-start;
  }
  .bg2-text27 {
    font-size: 32px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
  }
  .bg2-text28 {
    line-height: 1.25;
  }
  .bg2-text31 {
    font-style: italic;
  }
  .bg2-link {
    color: var(--dl-color-primary-300);
    text-decoration: underline;
  }
  .bg2-footer {
    justify-content: space-between;
  }
  .bg2-navlink {
    font-size: 16px;
    font-family: Montserrat;
    font-weight: 700;
    text-decoration: none;
  }
  .bg2-text36 {
    font-size: 16px;
    font-style: normal;
    font-family: Montserrat;
    font-weight: 500;
  }
  .bg2-icon {
    margin-left: 50px;
  }
}
@media(max-width: 1200px) {
  .bg2-heading {
    color: rgb(255, 255, 255);
  }
}
@media(max-width: 479px) {
  .bg2-footer {
    align-self: center;
  }
  .bg2-icon-group {
    display: none;
  }
}
</style>
