// [Angular] Website Source Code/src/app/pages/bg-3/bg-3.component.ts
import { Component } from '@angular/core'
import { Title, Meta } from '@angular/platform-browser'

@Component({
  selector: 'app-bg3',
  templateUrl: 'bg-3.component.html',
  styleUrls: ['bg-3.component.css'],
})
export class Bg3 {
  rawx6ri: string = ' '
  rawux6f: string = ' '
  rawalmp: string = ' '
  rawon0o: string = ' '
  raw5o7p: string = ' '
  raw9tty: string = ' '
  rawg78p: string = ' '
  rawop5o: string = ' '
  rawaq78: string = ' '
  raw9vej: string = ' '
  rawrgt2: string = ' '
  rawlm3v: string = ' '
  rawrunm: string = ' '
  rawihqd: string = ' '
  rawnfnm: string = ' '
  rawis0w: string = ' '
  rawv1yt: string = ' '
  raw13iu: string = ' '
  rawidhi: string = ' '
  raw51zt: string = ' '
  constructor(private title: Title, private meta: Meta) {
    this.title.setTitle('Strace | Background')
    this.meta.addTags([
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ])
  }
}

<div class="bg3-container">
  <div class="bg3-banner">
    <div class="bg3-main-content">
      <h1 class="bg3-heading">PYTHON AND DJANGO CAN BE EVERYWHERE</h1>
      <div class="bg3-num3-piz-punya">
        <div class="bg3-container01">
          <div class="bg3-container02">
            <h1 class="bg3-text">
              <span class="bg3-text01">
                Believe it or not,
                <span [innerHTML]="rawx6ri"></span>
              </span>
              <span class="bg3-text02">Python</span>
              <span class="bg3-text03">(</span>
              <span class="bg3-text04">especially</span>
              <span class="bg3-text05">
                ) and
                <span [innerHTML]="rawux6f"></span>
              </span>
              <span class="bg3-text06">
                Django
                <span [innerHTML]="rawalmp"></span>
              </span>
              <span class="bg3-text07">
                are used in
                <span [innerHTML]="rawon0o"></span>
              </span>
              <span class="bg3-text08">many programming domains.</span>
              <br class="bg3-text09" />
            </h1>
            <span class="bg3-text10">
              <span>
                Python and Django framework is very reliable as it was the
                <span [innerHTML]="raw5o7p"></span>
              </span>
              <span class="bg3-text12">
                backbone
                <span [innerHTML]="raw9tty"></span>
              </span>
              <span>
                for some of the most used applications out there. You might be
                suprised! Some of the applications created using Python and
                Django could be something that you used daily.
              </span>
              <br />
              <br />
              <span>
                Let&apos;s take a look at some of the example of the programming
                domains first.
              </span>
              <br />
            </span>
          </div>
          <img
            alt="image"
            src="https://i.pinimg.com/564x/19/cb/58/19cb586efd110d935c935d1fe3dd3448.jpg"
            class="bg3-image"
          />
        </div>
        <div class="bg3-container03">
          <div class="bg3-container04">
            <span class="bg3-text18">Data Science</span>
            <span class="bg3-text19">
              <span>
                Python can help the data scientist to do some
                <span [innerHTML]="rawg78p"></span>
              </span>
              <span class="bg3-text21">
                scientific calculations
                <span [innerHTML]="rawop5o"></span>
              </span>
              <span>
                with third-party packages such as Sci-Kit, NumPy, and SciPi.
                With these packages, it enhances the performance to analyse big
                dataset and shorten the time.
              </span>
            </span>
          </div>
          <div class="bg3-container05">
            <span class="bg3-text23">AI &amp; ML</span>
            <span class="bg3-text24">
              <span>
                Since Python can be used for scientific calculations, it also
                can handle the
                <span [innerHTML]="rawaq78"></span>
              </span>
              <span class="bg3-text26">
                development of AI and Machine Learning
                <span [innerHTML]="raw9vej"></span>
              </span>
              <span>
                using its pre-built library. For example, pyDatalog, SimpleAI,
                and EasyAI.  
              </span>
            </span>
          </div>
          <div class="bg3-container06">
            <span class="bg3-text28">Web Development</span>
            <span class="bg3-text29">
              <span>
                The integration of Python and Django able to create a
                <span [innerHTML]="rawrgt2"></span>
              </span>
              <span class="bg3-text31">
                website application
                <span [innerHTML]="rawlm3v"></span>
              </span>
              <span>
                for public uses. The framework, Django, simplified the typical
                backend logic thus reducing the developers&apos; workload.
              </span>
            </span>
          </div>
          <div class="bg3-container07">
            <span class="bg3-text33">Audio/Video Apps</span>
            <span class="bg3-text34">
              <span>
                Yes, you heard me right. Python and Django also can create a
                <span [innerHTML]="rawrunm"></span>
              </span>
              <span class="bg3-text36">
                media streaming application
                <span [innerHTML]="rawihqd"></span>
              </span>
              <span>
                since the Python&apos;s libraries supported it with the
                functionality of high-level.
              </span>
            </span>
          </div>
        </div>
        <div class="bg3-container08">
          <span class="bg3-text38">
            <span>
              To name a few, Instagram created in 2010 by American computer
              programmer
            </span>
            <br />
            <span>
              Kevin Systrom and Mike Krieger, and Spotify created in 2006 by
              Swedish
              <span [innerHTML]="rawnfnm"></span>
            </span>
            <br />
            <span>entrepreuner Daniel Ek and Martin Lorentzon.</span>
            <br />
          </span>
          <img
            alt="image"
            src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/1%20-%20Background%20of%20Language%20and%20Framework/med_IGLogo.png?raw=true"
            loading="eager"
            class="bg3-image1"
          />
          <img
            alt="image"
            src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/1%20-%20Background%20of%20Language%20and%20Framework/med_SpotifyLogo.png?raw=true"
            loading="eager"
            class="bg3-image2"
          />
        </div>
        <div class="bg3-container09">
          <span class="bg3-text45">
            <span>
              Now we&apos;ll go to the final bosses. Leading streaming platform,
              <span [innerHTML]="rawis0w"></span>
            </span>
            <span>Youtube believe it or not created using Python Django.</span>
            <br />
            <span>Created by Steve Chen, Chad Hurley, and Jawed Karim</span>
            <br />
            <span>
              in 2005 later acquired by Google in 2006 is the leading
              <span [innerHTML]="rawv1yt"></span>
            </span>
            <br />
            <span>streaming platform, second after Google Search</span>
            <br />
            <span> on most visited website in the world.</span>
            <br />
          </span>
          <img
            alt="image"
            src="https://raw.githubusercontent.com/rydzze/TPL6213-Project/main/IMG_SRC_WebReport/1%20-%20Background%20of%20Language%20and%20Framework/med_YouTube_Logo.webp"
            loading="eager"
            class="bg3-image3"
          />
        </div>
        <div class="bg3-container10">
          <span class="bg3-text57">
            <span>
              The most visited website in the world, Google Search is a search
              engine provided and operated by Google. Handling more than 3.5
              billion searches per day, it has a 92% share of the global search
              engine market is also created using Python Django.
            </span>
            <br />
          </span>
          <img
            alt="image"
            src="https://raw.githubusercontent.com/rydzze/TPL6213-Project/main/IMG_SRC_WebReport/1%20-%20Background%20of%20Language%20and%20Framework/med_Google_logo.png"
            loading="eager"
            class="bg3-image4"
          />
        </div>
        <span class="bg3-text60">
          <span>
            -
            <span [innerHTML]="raw13iu"></span>
          </span>
          <span class="bg3-text62">Muhammad Hafiz</span>
        </span>
      </div>
    </div>
  </div>
  <div class="bg3-reference">
    <h1 class="bg3-text63">References</h1>
    <span class="bg3-text64">
      <br class="bg3-text65" />
      <span class="bg3-text66">
        Oberoi, A. (2020, February 26).
        <span [innerHTML]="rawidhi"></span>
      </span>
      <span class="bg3-text67">
        7 Application Areas of Python Programming Language
      </span>
      <span class="bg3-text68">. daffodil.</span>
      <br class="bg3-text69" />
      <span class="bg3-text70">
               
        <span [innerHTML]="raw51zt"></span>
      </span>
      <a
        href="https://insights.daffodilsw.com/blog/7-application-areas-of-python-programming-language"
        target="_blank"
        rel="noreferrer noopener"
        class="bg3-link"
      >
        https://insights.daffodilsw.com/blog/7-application-areas-of-python-programming-language
      </a>
      <br />
    </span>
  </div>
  <footer class="bg3-footer">
    <div class="bg3-container11">
      <a routerLink="/strace" class="bg3-navlink">STRACE</a>
    </div>
    <span class="bg3-text72">&quot;Making System Calls Cool Again&quot;</span>
    <div class="bg3-icon-group">
      <svg viewBox="0 0 877.7142857142857 1024" class="bg3-icon">
        <path
          d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
        ></path>
      </svg>
    </div>
  </footer>
  <app-header></app-header>
</div>

// [Vue] Website Source Code/src/views/bg-3.vue
<template>
  <div class="bg3-container">
    <div class="bg3-banner">
      <div class="bg3-main-content">
        <h1 class="bg3-heading">PYTHON AND DJANGO CAN BE EVERYWHERE</h1>
        <div class="bg3-num3-piz-punya">
          <div class="bg3-container01">
            <div class="bg3-container02">
              <h1 class="bg3-text">
                <span class="bg3-text01">
                  Believe it or not,
                  <span v-html="rawoujp"></span>
                </span>
                <span class="bg3-text02">Python</span>
                <span class="bg3-text03">(</span>
                <span class="bg3-text04">especially</span>
                <span class="bg3-text05">
                  ) and
                  <span v-html="raw0zjd"></span>
                </span>
                <span class="bg3-text06">
                  Django
                  <span v-html="rawxpmy"></span>
                </span>
                <span class="bg3-text07">
                  are used in
                  <span v-html="rawgl0j"></span>
                </span>
                <span class="bg3-text08">many programming domains.</span>
                <br class="bg3-text09" />
              </h1>
              <span class="bg3-text10">
                <span>
                  Python and Django framework is very reliable as it was the
                  <span v-html="rawoyco"></span>
                </span>
                <span class="bg3-text12">
                  backbone
                  <span v-html="rawb0ey"></span>
                </span>
                <span>
                  for some of the most used applications out there. You might be
                  suprised! Some of the applications created using Python and
                  Django could be something that you used daily.
                </span>
                <br />
                <br />
                <span>
                  Let&apos;s take a look at some of the example of the programming
                  domains first.
                </span>
                <br />
              </span>
            </div>
            <img
              alt="image"
              src="https://i.pinimg.com/564x/19/cb/58/19cb586efd110d935c935d1fe3dd3448.jpg"
              class="bg3-image"
            />
          </div>
          <div class="bg3-container03">
            <div class="bg3-container04">
              <span class="bg3-text18">Data Science</span>
              <span class="bg3-text19">
                <span>
                  Python can help the data scientist to do some
                  <span v-html="rawhbio"></span>
                </span>
                <span class="bg3-text21">
                  scientific calculations
                  <span v-html="rawe5ap"></span>
                </span>
                <span>
                  with third-party packages such as Sci-Kit, NumPy, and SciPi.
                  With these packages, it enhances the performance to analyse big
                  dataset and shorten the time.
                </span>
              </span>
            </div>
            <div class="bg3-container05">
              <span class="bg3-text23">AI &amp; ML</span>
              <span class="bg3-text24">
                <span>
                  Since Python can be used for scientific calculations, it also
                  can handle the
                  <span v-html="rawc193"></span>
                </span>
                <span class="bg3-text26">
                  development of AI and Machine Learning
                  <span v-html="rawofsd"></span>
                </span>
                <span>
                  using its pre-built library. For example, pyDatalog, SimpleAI,
                  and EasyAI.  
                </span>
              </span>
            </div>
            <div class="bg3-container06">
              <span class="bg3-text28">Web Development</span>
              <span class="bg3-text29">
                <span>
                  The integration of Python and Django able to create a
                  <span v-html="raw0m5y"></span>
                </span>
                <span class="bg3-text31">
                  website application
                  <span v-html="raw8y4p"></span>
                </span>
                <span>
                  for public uses. The framework, Django, simplified the typical
                  backend logic thus reducing the developers&apos; workload.
                </span>
              </span>
            </div>
            <div class="bg3-container07">
              <span class="bg3-text33">Audio/Video Apps</span>
              <span class="bg3-text34">
                <span>
                  Yes, you heard me right. Python and Django also can create a
                  <span v-html="rawsl3g"></span>
                </span>
                <span class="bg3-text36">
                  media streaming application
                  <span v-html="rawekqh"></span>
                </span>
                <span>
                  since the Python&apos;s libraries supported it with the
                  functionality of high-level.
                </span>
              </span>
            </div>
          </div>
          <div class="bg3-container08">
            <span class="bg3-text38">
              <span>
                To name a few, Instagram created in 2010 by American computer
                programmer
              </span>
              <br />
              <span>
                Kevin Systrom and Mike Krieger, and Spotify created in 2006 by
                Swedish
                <span v-html="raws491"></span>
              </span>
              <br />
              <span>entrepreuner Daniel Ek and Martin Lorentzon.</span>
              <br />
            </span>
            <img
              alt="image"
              src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/1%20-%20Background%20of%20Language%20and%20Framework/med_IGLogo.png?raw=true"
              loading="eager"
              class="bg3-image1"
            />
            <img
              alt="image"
              src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/1%20-%20Background%20of%20Language%20and%20Framework/med_SpotifyLogo.png?raw=true"
              loading="eager"
              class="bg3-image2"
            />
          </div>
          <div class="bg3-container09">
            <span class="bg3-text45">
              <span>
                Now we&apos;ll go to the final bosses. Leading streaming platform,
                <span v-html="raw4icd"></span>
              </span>
              <span>Youtube believe it or not created using Python Django.</span>
              <br />
              <span>Created by Steve Chen, Chad Hurley, and Jawed Karim</span>
              <br />
              <span>
                in 2005 later acquired by Google in 2006 is the leading
                <span v-html="raw6b2s"></span>
              </span>
              <br />
              <span>streaming platform, second after Google Search</span>
              <br />
              <span> on most visited website in the world.</span>
              <br />
            </span>
            <img
              alt="image"
              src="https://raw.githubusercontent.com/rydzze/TPL6213-Project/main/IMG_SRC_WebReport/1%20-%20Background%20of%20Language%20and%20Framework/med_YouTube_Logo.webp"
              loading="eager"
              class="bg3-image3"
            />
          </div>
          <div class="bg3-container10">
            <span class="bg3-text57">
              <span>
                The most visited website in the world, Google Search is a search
                engine provided and operated by Google. Handling more than 3.5
                billion searches per day, it has a 92% share of the global search
                engine market is also created using Python Django.
              </span>
              <br />
            </span>
            <img
              alt="image"
              src="https://raw.githubusercontent.com/rydzze/TPL6213-Project/main/IMG_SRC_WebReport/1%20-%20Background%20of%20Language%20and%20Framework/med_Google_logo.png"
              loading="eager"
              class="bg3-image4"
            />
          </div>
          <span class="bg3-text60">
            <span>
              -
              <span v-html="rawma7e"></span>
            </span>
            <span class="bg3-text62">Muhammad Hafiz</span>
          </span>
        </div>
      </div>
    </div>
    <div class="bg3-reference">
      <h1 class="bg3-text63">References</h1>
      <span class="bg3-text64">
        <br class="bg3-text65" />
        <span class="bg3-text66">
          Oberoi, A. (2020, February 26).
          <span v-html="rawpot2"></span>
        </span>
        <span class="bg3-text67">
          7 Application Areas of Python Programming Language
        </span>
        <span class="bg3-text68">. daffodil.</span>
        <br class="bg3-text69" />
        <span class="bg3-text70">
                 
          <span v-html="rawlszi"></span>
        </span>
        <a
          href="https://insights.daffodilsw.com/blog/7-application-areas-of-python-programming-language"
          target="_blank"
          rel="noreferrer noopener"
          class="bg3-link"
        >
          https://insights.daffodilsw.com/blog/7-application-areas-of-python-programming-language
        </a>
        <br />
      </span>
    </div>
    <footer class="bg3-footer">
      <div class="bg3-container11">
        <router-link to="/strace" class="bg3-navlink">STRACE</router-link>
      </div>
      <span class="bg3-text72">&quot;Making System Calls Cool Again&quot;</span>
      <div class="bg3-icon-group">
        <svg viewBox="0 0 877.7142857142857 1024" class="bg3-icon">
          <path
            d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
          ></path>
        </svg>
      </div>
    </footer>
    <app-header></app-header>
  </div>
</template>

<script>
import AppHeader from '../components/header'

export default {
  name: 'Bg3',
  props: {},
  components: {
    AppHeader,
  },
  data() {
    return {
      rawoujp: ' ',
      raw0zjd: ' ',
      rawxpmy: ' ',
      rawgl0j: ' ',
      rawoyco: ' ',
      rawb0ey: ' ',
      rawhbio: ' ',
      rawe5ap: ' ',
      rawc193: ' ',
      rawofsd: ' ',
      raw0m5y: ' ',
      raw8y4p: ' ',
      rawsl3g: ' ',
      rawekqh: ' ',
      raws491: ' ',
      raw4icd: ' ',
      raw6b2s: ' ',
      rawma7e: ' ',
      rawpot2: ' ',
      rawlszi: ' ',
    }
  },
  metaInfo: {
    title: 'Strace | Background',
    meta: [
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ],
  },
}
</script>

<style scoped>
.bg3-container {
  width: 100%;
  display: flex;
  overflow: auto;
  min-height: 100vh;
  align-items: center;
  flex-direction: column;
  justify-content: flex-start;
  background-color: #f5f5f5;
}
.bg3-banner {
  width: 100%;
  height: 275px;
  display: flex;
  transition: 0.3s;
  align-items: center;
  flex-direction: column;
  background-size: cover;
  justify-content: center;
  background-image: url('https://marketplace.canva.com/EAD2962NKnQ/2/0/1600w/canva-rainbow-gradient-pink-and-purple-virtual-background-_Tcjok-d9b4.jpg');
}

.bg3-main-content {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: flex-start;
  background-color: #ffffff;
}
.bg3-heading {
  color: #ff0000;
  font-size: 3rem;
  align-self: center;
  text-align: center;
}
.bg3-num3-piz-punya {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.bg3-container01 {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.bg3-container02 {
  flex: 0 0 auto;
  width: 200px;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.bg3-text10 {
  text-align: justify;
}
.bg3-image {
  width: 200px;
  transform: scaleX(-1);
  object-fit: cover;
}
.bg3-container03 {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.bg3-container04 {
  flex: 0 0 auto;
  width: 200px;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.bg3-container05 {
  flex: 0 0 auto;
  width: 200px;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.bg3-container06 {
  flex: 0 0 auto;
  width: 200px;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.bg3-container07 {
  flex: 0 0 auto;
  width: 200px;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.bg3-container08 {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.bg3-text38 {
  text-align: justify;
}
.bg3-image1 {
  width: 200px;
  object-fit: cover;
}
.bg3-image2 {
  width: 200px;
  object-fit: cover;
}
.bg3-container09 {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.bg3-text45 {
  text-align: justify;
}
.bg3-image3 {
  width: 200px;
  object-fit: cover;
}
.bg3-container10 {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.bg3-text57 {
  text-align: justify;
}
.bg3-image4 {
  width: 200px;
  object-fit: cover;
}
.bg3-reference {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #ffffff;
}
.bg3-footer {
  width: 100%;
  display: flex;
  max-width: var(--dl-size-size-maxwidth);
  align-self: center;
  align-items: center;
  padding-top: var(--dl-space-space-twounits);
  padding-left: var(--dl-space-space-threeunits);
  padding-right: var(--dl-space-space-threeunits);
  padding-bottom: var(--dl-space-space-twounits);
  justify-content: space-between;
}
.bg3-container11 {
  flex: 0 0 auto;
  width: auto;
  height: auto;
  display: flex;
  align-items: space-between;
  flex-direction: column;
}
.bg3-navlink {
  font-weight: 700;
  text-decoration: none;
}
.bg3-icon {
  width: 24px;
  height: 24px;
}
@media(max-width: 1600px) {
  .bg3-container {
    background-color: #f7f7f7;
  }
  .bg3-banner {
    height: auto;
    align-items: center;
    background-size: cover;
    justify-content: flex-start;
    background-image: url("/external/bgportrait-1500w.jpg");
  }
  .bg3-main-content {
    flex: 1;
    width: 1300px;
    height: auto;
    box-shadow: 0px 0px 10px 0px #d3d2d6;
    align-items: flex-start;
    padding-top: 100px;
    flex-direction: column;
    justify-content: flex-start;
    background-color: #ffffff;
  }
  .bg3-heading {
    color: rgb(255, 255, 255);
    width: 1200px;
    height: auto;
    font-size: 64px;
    font-style: normal;
    margin-top: 25px;
    font-family: Montserrat;
    font-weight: 700;
    line-height: 1.15;
    padding-top: 40px;
    border-radius: var(--dl-radius-radius-radius4);
    padding-bottom: 40px;
    background-image: url("/external/bglandscape-1200w.jpg");
    background-position: bottom left;
  }
  .bg3-num3-piz-punya {
    width: 1209px;
    height: auto;
    position: relative;
    margin-left: 45px;
    padding-top: 50px;
    margin-right: 45px;
    padding-bottom: 50px;
  }
  .bg3-container01 {
    align-self: flex-start;
    padding-bottom: 15px;
    justify-content: space-between;
  }
  .bg3-container02 {
    width: 1000px;
    padding-right: var(--dl-space-space-fourunits);
  }
  .bg3-text {
    font-size: 16px;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    padding-top: 0px;
    padding-left: 0px;
    padding-right: 0px;
    padding-bottom: 30px;
  }
  .bg3-text01 {
    font-style: normal;
  }
  .bg3-text02 {
    font-weight: 700;
  }
  .bg3-text03 {
    font-style: normal;
  }
  .bg3-text04 {
    font-style: italic;
    font-weight: 700;
  }
  .bg3-text05 {
    font-style: normal;
  }
  .bg3-text06 {
    font-weight: 700;
  }
  .bg3-text07 {
    font-style: normal;
  }
  .bg3-text08 {
    font-style: inherit;
    font-weight: 700;
  }
  .bg3-text09 {
    font-style: normal;
  }
  .bg3-text10 {
    font-size: 16px;
    font-style: normal;
    text-align: left;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.5;
  }
  .bg3-text12 {
    font-weight: 700;
  }
  .bg3-image {
    width: 150px;
  }
  .bg3-container03 {
    margin-top: 30px;
    margin-bottom: 30px;
    justify-content: space-between;
  }
  .bg3-container04 {
    width: 25%;
    padding-right: 30px;
  }
  .bg3-text18 {
    font-size: 24px;
    font-style: normal;
    font-family: Inter;
    font-weight: 600;
    line-height: 1.15;
    padding-bottom: 20px;
  }
  .bg3-text19 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
  }
  .bg3-text21 {
    font-weight: 700;
  }
  .bg3-container05 {
    width: 25%;
    padding-right: 30px;
  }
  .bg3-text23 {
    font-size: 24px;
    font-style: normal;
    font-family: Inter;
    font-weight: 600;
    line-height: 1.15;
    padding-bottom: 20px;
  }
  .bg3-text24 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
  }
  .bg3-text26 {
    font-weight: 700;
  }
  .bg3-container06 {
    width: 25%;
    padding-right: 30px;
  }
  .bg3-text28 {
    font-size: 24px;
    font-style: normal;
    font-family: Inter;
    font-weight: 600;
    line-height: 1.15;
    padding-bottom: 20px;
  }
  .bg3-text29 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
  }
  .bg3-text31 {
    font-weight: 700;
  }
  .bg3-container07 {
    width: 25%;
    padding-right: 30px;
  }
  .bg3-text33 {
    font-size: 24px;
    font-style: normal;
    font-family: Inter;
    font-weight: 600;
    line-height: 1.15;
    padding-bottom: 20px;
  }
  .bg3-text34 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
  }
  .bg3-text36 {
    font-weight: 700;
  }
  .bg3-container08 {
    width: auto;
    height: 122px;
    position: relative;
    align-self: stretch;
    margin-top: 15px;
    margin-bottom: 15px;
  }
  .bg3-text38 {
    font-size: 16px;
    align-self: center;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.5;
  }
  .bg3-image1 {
    top: 8px;
    left: 836px;
    width: 111px;
    height: 111px;
    position: absolute;
  }
  .bg3-image2 {
    top: 27px;
    right: -3px;
    width: 248px;
    height: 74px;
    position: absolute;
    align-self: center;
  }
  .bg3-container09 {
    height: 169px;
    position: relative;
    margin-top: 15px;
    margin-bottom: 15px;
  }
  .bg3-text45 {
    width: 100%;
    font-size: 16px;
    font-style: normal;
    text-align: right;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.5;
  }
  .bg3-image3 {
    left: 58px;
    width: auto;
    bottom: 14px;
    height: 111px;
    position: absolute;
  }
  .bg3-container10 {
    height: 201px;
    position: relative;
    margin-top: 15px;
    margin-bottom: 15px;
  }
  .bg3-text57 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.5;
  }
  .bg3-image4 {
    left: 220px;
    width: auto;
    bottom: 1px;
    height: 111px;
    position: absolute;
  }
  .bg3-text60 {
    font-size: 18px;
    align-self: flex-end;
    font-style: normal;
    font-family: Inter;
    font-weight: 500;
    padding-top: 25px;
  }
  .bg3-text62 {
    font-style: italic;
  }
  .bg3-reference {
    width: 1600px;
    height: auto;
    align-self: center;
    box-shadow: 0px -1px 15px 0px #ebebeb;
    align-items: flex-start;
    padding-top: 50px;
    padding-left: 200px;
    padding-right: 200px;
    flex-direction: column;
    padding-bottom: 50px;
    justify-content: flex-start;
  }
  .bg3-text63 {
    font-size: 32px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
  }
  .bg3-text64 {
    line-height: 1.25;
  }
  .bg3-text65 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .bg3-text66 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .bg3-text67 {
    font-size: 16px;
    font-style: italic;
    font-family: Inter;
    font-weight: 400;
  }
  .bg3-text68 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .bg3-text69 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .bg3-text70 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .bg3-link {
    color: var(--dl-color-primary-300);
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    text-decoration: underline;
  }
  .bg3-footer {
    justify-content: space-between;
  }
  .bg3-navlink {
    font-size: 16px;
    font-family: Montserrat;
    font-weight: 700;
    text-decoration: none;
  }
  .bg3-text72 {
    font-size: 16px;
    font-style: normal;
    font-family: Montserrat;
    font-weight: 500;
  }
  .bg3-icon {
    margin-left: 50px;
  }
}
@media(max-width: 1200px) {
  .bg3-heading {
    color: rgb(255, 255, 255);
  }
}
@media(max-width: 479px) {
  .bg3-footer {
    align-self: center;
  }
  .bg3-icon-group {
    display: none;
  }
}
</style>
