// [Angular] Website Source Code/src/app/pages/bg-4/bg-4.component.ts
import { Component } from '@angular/core'
import { Title, Meta } from '@angular/platform-browser'

@Component({
  selector: 'app-bg4',
  templateUrl: 'bg-4.component.html',
  styleUrls: ['bg-4.component.css'],
})
export class Bg4 {
  rawnwjc: string = ' '
  raw1km9: string = ' '
  rawl72p: string = ' '
  raw1fx3: string = ' '
  rawskaq: string = ' '
  rawcqdn: string = ' '
  rawcgps: string = ' '
  rawgh3c: string = ' '
  rawte9i: string = ' '
  rawp0od: string = ' '
  rawns35: string = ' '
  rawop23: string = ' '
  raw58ix: string = ' '
  rawok5z: string = ' '
  rawic4b: string = ' '
  raww5lf: string = ' '
  rawgmn3: string = ' '
  rawz82m: string = ' '
  rawqq3l: string = ' '
  rawvf6r: string = ' '
  rawg613: string = ' '
  rawk9do: string = ' '
  rawprxy: string = ' '
  rawx6ii: string = ' '
  rawn4ur: string = ' '
  constructor(private title: Title, private meta: Meta) {
    this.title.setTitle('Strace | Background')
    this.meta.addTags([
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ])
  }
}

<div class="bg4-container">
  <div class="bg4-banner">
    <div class="bg4-main-content">
      <h1 class="bg4-heading">
        <span>POPULARITY OF PYTHON</span>
        <br />
        <span>AND DJANGO</span>
      </h1>
      <div class="bg4-num4">
        <div class="bg4-container1">
          <div class="bg4-container2">
            <span class="bg4-text03">
              <span class="bg4-text04">Python</span>
              <span>
                is
                <span [innerHTML]="rawnwjc"></span>
              </span>
              <span class="bg4-text06">
                currently
                <span [innerHTML]="raw1km9"></span>
              </span>
              <span>
                a
                <span [innerHTML]="rawl72p"></span>
              </span>
              <span class="bg4-text08">popular programming language</span>
              <span>
                . It consistently ranks among the top 5 most popular languages
                in various surveys and indexes. It is widely used in various
                domains such as web development, data science, artificial
                intelligence, machine learning, and scientific computing. Apart
                from that,
                <span [innerHTML]="raw1fx3"></span>
              </span>
              <span class="bg4-text10">
                Django
                <span [innerHTML]="rawskaq"></span>
              </span>
              <span>
                which is the
                <span [innerHTML]="rawcqdn"></span>
              </span>
              <span class="bg4-text12">
                framework
                <span [innerHTML]="rawcgps"></span>
              </span>
              <span class="bg4-text13">for Python</span>
              <span class="bg4-text14">
                <span [innerHTML]="rawgh3c"></span>
              </span>
              <span>
                also
                <span [innerHTML]="rawte9i"></span>
              </span>
              <span class="bg4-text16">
                popular
                <span [innerHTML]="rawp0od"></span>
              </span>
              <span>
                because it shows that they consistently ranked among the top 10
                most popular web frameworks according to the Stack Overflow
                survey. Here are some statistics that demonstrate Python and
                Django popularity:
                <span [innerHTML]="rawns35"></span>
              </span>
            </span>
          </div>
          <img
            alt="image"
            src="https://sg-res.9appsdownloading.com/sg/res/jpg/43/85/17c35def601bb8e63b432b017e50-4yv.jpg?x-oss-process=style/mq200"
            class="bg4-image"
          />
        </div>
        <div class="bg4-python-stat">
          <div class="bg4-figure-11">
            <img
              alt="image"
              src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/1%20-%20Background%20of%20Language%20and%20Framework/alia_ieee-spectrum.png?raw=true"
              loading="eager"
              class="bg4-image1"
            />
            <a
              href="https://spectrum.ieee.org/the-top-programming-languages-2023"
              target="_blank"
              rel="noreferrer noopener"
              class="bg4-link"
            >
              <span>Top 10 Programming Languages |</span>
              <br />
              <span>
                Image Source:
                <span [innerHTML]="rawop23"></span>
              </span>
              <span class="bg4-text21">IEEE Spectrum</span>
            </a>
            <span class="bg4-text22">
              Figure 1.1 indicates the top 10 programming languages from the
              IEEE Spectrum website where this ranking was created by combining
              metrics from eight sources: CareerBuilder, GitHub, Google, Hacker
              News, IEEE, Reddit, Stack Overflow, and Twitter.
              <span [innerHTML]="raw58ix"></span>
            </span>
          </div>
          <div class="bg4-figure-12">
            <img
              alt="image"
              src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/1%20-%20Background%20of%20Language%20and%20Framework/alia_pyplindex.png?raw=true"
              loading="eager"
              class="bg4-image2"
            />
            <span class="bg4-text23">
              <span>Top 10 Programming Languages |</span>
              <br />
              <span>Image Source: </span>
              <a
                href="https://pypl.github.io/PYPL.html"
                target="_blank"
                rel="noreferrer noopener"
                class="bg4-link1"
              >
                PYPL index
              </a>
            </span>
            <span class="bg4-text27">
              Figure 1.2 indicates the top 10 programming languages from the
              PYPL index website where this source is created by analyzing how
              often language tutorials are searched on Google. The more a
              language tutorial is searched, the more popular the language is
              assumed to be. It is a leading indicator. The raw data comes from
              Google Trends.
              <span [innerHTML]="rawok5z"></span>
            </span>
          </div>
          <div class="bg4-figure-13">
            <img
              alt="image"
              src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/1%20-%20Background%20of%20Language%20and%20Framework/alia_python-stackoverflow.png?raw=true"
              loading="eager"
              class="bg4-image3"
            />
            <span class="bg4-text28">
              <span>Top 10 Programming Languages | Image</span>
              <br />
              <span>Source: </span>
              <span class="bg4-text32">StackOverflow Developer Survey</span>
            </span>
            <span class="bg4-text33">
              Figure 1.3 indicates the top 10 programming languages from the
              Stack Overflow Developer website where their ranking includes
              programming, scripting, and markup languages. It makes Python the
              top 3 under JavaScript and HTML/CSS.
            </span>
          </div>
        </div>
        <div class="bg4-figure-14">
          <div class="bg4-container3">
            <img
              alt="image"
              src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/1%20-%20Background%20of%20Language%20and%20Framework/alia_django-stackoverflow.png?raw=true"
              loading="eager"
              class="bg4-image4"
            />
            <span class="bg4-text34">
              <span>Top 10 Web Frameworks | Image Source:</span>
              <a
                href="https://insights.stackoverflow.com/survey/2021#technology-most-popular-technologies"
                target="_blank"
                rel="noreferrer noopener"
              >
                <br />
              </a>
              <a
                href="https://insights.stackoverflow.com/survey/2021#technology-most-popular-technologies"
                target="_blank"
                rel="noreferrer noopener"
                class="bg4-link3"
              >
                StackOverflow Developer Survey
              </a>
            </span>
          </div>
          <div class="bg4-container4">
            <span class="bg4-text37">
              <span>
                Figure 1.4 indicates that Django is a popular Python web
                framework.
              </span>
              <br />
              <br />
              <span class="bg4-text41">
                Python&apos;s popularity
                <span [innerHTML]="rawic4b"></span>
              </span>
              <span>
                can be
                <span [innerHTML]="raww5lf"></span>
              </span>
              <span class="bg4-text43">attributed to its frameworks</span>
              <span>
                . There are numerous Python frameworks available depending on
                what we want to build. Two web development frameworks are
                available: Django, which is more robust and designed with
                microservices in mind, and Flask, which is very light and
                perfect for simple applications.
                <span [innerHTML]="rawgmn3"></span>
              </span>
              <br />
            </span>
            <div class="bg4-container5">
              <span class="bg4-text46">
                <br />
                <span>
                  Python&apos;s popularity is also incredibly strong because of
                  its use in web development. Although there&apos;s no denying
                  that JavaScript is the most widely used language on the
                  internet,
                  <span [innerHTML]="rawz82m"></span>
                </span>
                <span class="bg4-text49">
                  Python is also a popular option because of frameworks
                  <span [innerHTML]="rawqq3l"></span>
                </span>
                <span>
                  like Django and Flask for both frontend and backend
                  applications.
                </span>
                <br />
                <br />
                <span>
                  Python is
                  <span [innerHTML]="rawvf6r"></span>
                </span>
                <span class="bg4-text54">
                  becoming more and more popular
                  <span [innerHTML]="rawg613"></span>
                </span>
                <span>
                  due to its use in these software development fields, which
                  also makes it one of the most in-demand skills. Python is also
                  one of the highest-paid languages. As per a Stack Overflow
                  survey, Python developers earn an average salary of US$120k
                  annually in the US, making them the tenth highest-paid group
                  globally.
                </span>
                <br />
              </span>
              <img
                alt="image"
                src="https://i.pinimg.com/564x/8f/81/53/8f815329bd58bac86444de1b510cc3ff.jpg"
                class="bg4-image5"
              />
            </div>
          </div>
        </div>
        <span class="bg4-text57">
          However, don&apos;t be duped by Python and SQL&apos;s rankings:
          We&apos;re still a long way from having a monoculture in programming.
          In terms of combined popularity, Java and the various C-like languages
          outperform Python, particularly for high-performance or
          resource-sensitive tasks where Python&apos;s interpreter overhead is
          still too expensive (though there are several efforts to make Python
          more competitive on that front). Additionally, some software ecologies
          resist being incorporated into Python for different reasons.
        </span>
        <span class="bg4-text58">
          <span>
            -
            <span [innerHTML]="rawk9do"></span>
          </span>
          <span>Noor Alia Alisa</span>
        </span>
      </div>
    </div>
  </div>
  <div class="bg4-reference">
    <h1 class="bg4-text61">References</h1>
    <span class="bg4-text62">
      <br />
      <span>
        Cass, S. (2023, August 29).
        <span [innerHTML]="rawprxy"></span>
      </span>
      <span class="bg4-text65">The Top Programming Languages 2023</span>
      <span>. IEEE Spectrum.</span>
      <br />
      <span>
                 
        <span [innerHTML]="rawx6ii"></span>
      </span>
      <a
        href="https://spectrum.ieee.org/the-top-programming-languages-2023"
        target="_blank"
        rel="noreferrer noopener"
        class="bg4-link4"
      >
        https://spectrum.ieee.org/the-top-programming-languages-2023
      </a>
      <br />
      <br />
      <span>
        Carbonnelle, P. (2023, December).
        <span [innerHTML]="rawn4ur"></span>
      </span>
      <span class="bg4-text72">
        PYPL PopularitY of Programming Language index
      </span>
      <span>. GitHub Pages.</span>
      <br />
      <span>          </span>
      <a
        href="https://pypl.github.io/PYPL.html"
        target="_blank"
        rel="noreferrer noopener"
        class="bg4-link5"
      >
        https://pypl.github.io/PYPL.html
      </a>
      <br class="bg4-text76" />
      <br class="bg4-text77" />
      <span class="bg4-text78">Stack Overflow Developer Survey 2021</span>
      <span>. (2021). Stack Overflow.</span>
      <br />
      <span>          </span>
      <a
        href="https://insights.stackoverflow.com/survey/2021"
        target="_blank"
        rel="noreferrer noopener"
        class="bg4-link6"
      >
        https://insights.stackoverflow.com/survey/2021
      </a>
      <br />
    </span>
  </div>
  <footer class="bg4-footer">
    <div class="bg4-container6">
      <a routerLink="/strace" class="bg4-navlink">STRACE</a>
    </div>
    <span class="bg4-text83">&quot;Making System Calls Cool Again&quot;</span>
    <div class="bg4-icon-group">
      <svg viewBox="0 0 877.7142857142857 1024" class="bg4-icon">
        <path
          d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
        ></path>
      </svg>
    </div>
  </footer>
  <app-header></app-header>
</div>

// [Vue] Website Source Code/src/views/bg-4.vue
<template>
  <div class="bg4-container">
    <div class="bg4-banner">
      <div class="bg4-main-content">
        <h1 class="bg4-heading">
          <span>POPULARITY OF PYTHON</span>
          <br />
          <span>AND DJANGO</span>
        </h1>
        <div class="bg4-num4">
          <div class="bg4-container1">
            <div class="bg4-container2">
              <span class="bg4-text03">
                <span class="bg4-text04">Python</span>
                <span>
                  is
                  <span v-html="rawgpyb"></span>
                </span>
                <span class="bg4-text06">
                  currently
                  <span v-html="raw0czu"></span>
                </span>
                <span>
                  a
                  <span v-html="rawourd"></span>
                </span>
                <span class="bg4-text08">popular programming language</span>
                <span>
                  . It consistently ranks among the top 5 most popular languages
                  in various surveys and indexes. It is widely used in various
                  domains such as web development, data science, artificial
                  intelligence, machine learning, and scientific computing. Apart
                  from that,
                  <span v-html="rawznp9"></span>
                </span>
                <span class="bg4-text10">
                  Django
                  <span v-html="rawfhfz"></span>
                </span>
                <span>
                  which is the
                  <span v-html="rawqte4"></span>
                </span>
                <span class="bg4-text12">
                  framework
                  <span v-html="rawpjmi"></span>
                </span>
                <span class="bg4-text13">for Python</span>
                <span class="bg4-text14"><span v-html="raw0a0a"></span></span>
                <span>
                  also
                  <span v-html="rawi5cl"></span>
                </span>
                <span class="bg4-text16">
                  popular
                  <span v-html="rawicop"></span>
                </span>
                <span>
                  because it shows that they consistently ranked among the top 10
                  most popular web frameworks according to the Stack Overflow
                  survey. Here are some statistics that demonstrate Python and
                  Django popularity:
                  <span v-html="rawuca1"></span>
                </span>
              </span>
            </div>
            <img
              alt="image"
              src="https://sg-res.9appsdownloading.com/sg/res/jpg/43/85/17c35def601bb8e63b432b017e50-4yv.jpg?x-oss-process=style/mq200"
              class="bg4-image"
            />
          </div>
          <div class="bg4-python-stat">
            <div class="bg4-figure-11">
              <img
                alt="image"
                src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/1%20-%20Background%20of%20Language%20and%20Framework/alia_ieee-spectrum.png?raw=true"
                loading="eager"
                class="bg4-image1"
              />
              <a
                href="https://spectrum.ieee.org/the-top-programming-languages-2023"
                target="_blank"
                rel="noreferrer noopener"
                class="bg4-link"
              >
                <span>Top 10 Programming Languages |</span>
                <br />
                <span>
                  Image Source:
                  <span v-html="rawm4fl"></span>
                </span>
                <span class="bg4-text21">IEEE Spectrum</span>
              </a>
              <span class="bg4-text22">
                Figure 1.1 indicates the top 10 programming languages from the
                IEEE Spectrum website where this ranking was created by combining
                metrics from eight sources: CareerBuilder, GitHub, Google, Hacker
                News, IEEE, Reddit, Stack Overflow, and Twitter.
                <span v-html="rawgw3g"></span>
              </span>
            </div>
            <div class="bg4-figure-12">
              <img
                alt="image"
                src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/1%20-%20Background%20of%20Language%20and%20Framework/alia_pyplindex.png?raw=true"
                loading="eager"
                class="bg4-image2"
              />
              <span class="bg4-text23">
                <span>Top 10 Programming Languages |</span>
                <br />
                <span>Image Source: </span>
                <a
                  href="https://pypl.github.io/PYPL.html"
                  target="_blank"
                  rel="noreferrer noopener"
                  class="bg4-link1"
                >
                  PYPL index
                </a>
              </span>
              <span class="bg4-text27">
                Figure 1.2 indicates the top 10 programming languages from the
                PYPL index website where this source is created by analyzing how
                often language tutorials are searched on Google. The more a
                language tutorial is searched, the more popular the language is
                assumed to be. It is a leading indicator. The raw data comes from
                Google Trends.
                <span v-html="rawgj6w"></span>
              </span>
            </div>
            <div class="bg4-figure-13">
              <img
                alt="image"
                src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/1%20-%20Background%20of%20Language%20and%20Framework/alia_python-stackoverflow.png?raw=true"
                loading="eager"
                class="bg4-image3"
              />
              <span class="bg4-text28">
                <span>Top 10 Programming Languages | Image</span>
                <br />
                <span>Source: </span>
                <span class="bg4-text32">StackOverflow Developer Survey</span>
              </span>
              <span class="bg4-text33">
                Figure 1.3 indicates the top 10 programming languages from the
                Stack Overflow Developer website where their ranking includes
                programming, scripting, and markup languages. It makes Python the
                top 3 under JavaScript and HTML/CSS.
              </span>
            </div>
          </div>
          <div class="bg4-figure-14">
            <div class="bg4-container3">
              <img
                alt="image"
                src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/1%20-%20Background%20of%20Language%20and%20Framework/alia_django-stackoverflow.png?raw=true"
                loading="eager"
                class="bg4-image4"
              />
              <span class="bg4-text34">
                <span>Top 10 Web Frameworks | Image Source:</span>
                <a
                  href="https://insights.stackoverflow.com/survey/2021#technology-most-popular-technologies"
                  target="_blank"
                  rel="noreferrer noopener"
                >
                  <br />
                </a>
                <a
                  href="https://insights.stackoverflow.com/survey/2021#technology-most-popular-technologies"
                  target="_blank"
                  rel="noreferrer noopener"
                  class="bg4-link3"
                >
                  StackOverflow Developer Survey
                </a>
              </span>
            </div>
            <div class="bg4-container4">
              <span class="bg4-text37">
                <span>
                  Figure 1.4 indicates that Django is a popular Python web
                  framework.
                </span>
                <br />
                <br />
                <span class="bg4-text41">
                  Python&apos;s popularity
                  <span v-html="rawhgav"></span>
                </span>
                <span>
                  can be
                  <span v-html="rawgngw"></span>
                </span>
                <span class="bg4-text43">attributed to its frameworks</span>
                <span>
                  . There are numerous Python frameworks available depending on
                  what we want to build. Two web development frameworks are
                  available: Django, which is more robust and designed with
                  microservices in mind, and Flask, which is very light and
                  perfect for simple applications.
                  <span v-html="rawq7yn"></span>
                </span>
                <br />
              </span>
              <div class="bg4-container5">
                <span class="bg4-text46">
                  <br />
                  <span>
                    Python&apos;s popularity is also incredibly strong because of
                    its use in web development. Although there&apos;s no denying
                    that JavaScript is the most widely used language on the
                    internet,
                    <span v-html="rawanu7"></span>
                  </span>
                  <span class="bg4-text49">
                    Python is also a popular option because of frameworks
                    <span v-html="rawbz70"></span>
                  </span>
                  <span>
                    like Django and Flask for both frontend and backend
                    applications.
                  </span>
                  <br />
                  <br />
                  <span>
                    Python is
                    <span v-html="rawcmgq"></span>
                  </span>
                  <span class="bg4-text54">
                    becoming more and more popular
                    <span v-html="rawwyd1"></span>
                  </span>
                  <span>
                    due to its use in these software development fields, which
                    also makes it one of the most in-demand skills. Python is also
                    one of the highest-paid languages. As per a Stack Overflow
                    survey, Python developers earn an average salary of US$120k
                    annually in the US, making them the tenth highest-paid group
                    globally.
                  </span>
                  <br />
                </span>
                <img
                  alt="image"
                  src="https://i.pinimg.com/564x/8f/81/53/8f815329bd58bac86444de1b510cc3ff.jpg"
                  class="bg4-image5"
                />
              </div>
            </div>
          </div>
          <span class="bg4-text57">
            However, don&apos;t be duped by Python and SQL&apos;s rankings:
            We&apos;re still a long way from having a monoculture in programming.
            In terms of combined popularity, Java and the various C-like languages
            outperform Python, particularly for high-performance or
            resource-sensitive tasks where Python&apos;s interpreter overhead is
            still too expensive (though there are several efforts to make Python
            more competitive on that front). Additionally, some software ecologies
            resist being incorporated into Python for different reasons.
          </span>
          <span class="bg4-text58">
            <span>
              -
              <span v-html="rawo85n"></span>
            </span>
            <span>Noor Alia Alisa</span>
          </span>
        </div>
      </div>
    </div>
    <div class="bg4-reference">
      <h1 class="bg4-text61">References</h1>
      <span class="bg4-text62">
        <br />
        <span>
          Cass, S. (2023, August 29).
          <span v-html="rawx26u"></span>
        </span>
        <span class="bg4-text65">The Top Programming Languages 2023</span>
        <span>. IEEE Spectrum.</span>
        <br />
        <span>
                   
          <span v-html="raw07kt"></span>
        </span>
        <a
          href="https://spectrum.ieee.org/the-top-programming-languages-2023"
          target="_blank"
          rel="noreferrer noopener"
          class="bg4-link4"
        >
          https://spectrum.ieee.org/the-top-programming-languages-2023
        </a>
        <br />
        <br />
        <span>
          Carbonnelle, P. (2023, December).
          <span v-html="raweoxt"></span>
        </span>
        <span class="bg4-text72">
          PYPL PopularitY of Programming Language index
        </span>
        <span>. GitHub Pages.</span>
        <br />
        <span>          </span>
        <a
          href="https://pypl.github.io/PYPL.html"
          target="_blank"
          rel="noreferrer noopener"
          class="bg4-link5"
        >
          https://pypl.github.io/PYPL.html
        </a>
        <br class="bg4-text76" />
        <br class="bg4-text77" />
        <span class="bg4-text78">Stack Overflow Developer Survey 2021</span>
        <span>. (2021). Stack Overflow.</span>
        <br />
        <span>          </span>
        <a
          href="https://insights.stackoverflow.com/survey/2021"
          target="_blank"
          rel="noreferrer noopener"
          class="bg4-link6"
        >
          https://insights.stackoverflow.com/survey/2021
        </a>
        <br />
      </span>
    </div>
    <footer class="bg4-footer">
      <div class="bg4-container6">
        <router-link to="/strace" class="bg4-navlink">STRACE</router-link>
      </div>
      <span class="bg4-text83">&quot;Making System Calls Cool Again&quot;</span>
      <div class="bg4-icon-group">
        <svg viewBox="0 0 877.7142857142857 1024" class="bg4-icon">
          <path
            d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
          ></path>
        </svg>
      </div>
    </footer>
    <app-header></app-header>
  </div>
</template>

<script>
import AppHeader from '../components/header'

export default {
  name: 'Bg4',
  props: {},
  components: {
    AppHeader,
  },
  data() {
    return {
      rawgpyb: ' ',
      raw0czu: ' ',
      rawourd: ' ',
      rawznp9: ' ',
      rawfhfz: ' ',
      rawqte4: ' ',
      rawpjmi: ' ',
      raw0a0a: ' ',
      rawi5cl: ' ',
      rawicop: ' ',
      rawuca1: ' ',
      rawm4fl: ' ',
      rawgw3g: ' ',
      rawgj6w: ' ',
      rawhgav: ' ',
      rawgngw: ' ',
      rawq7yn: ' ',
      rawanu7: ' ',
      rawbz70: ' ',
      rawcmgq: ' ',
      rawwyd1: ' ',
      rawo85n: ' ',
      rawx26u: ' ',
      raw07kt: ' ',
      raweoxt: ' ',
    }
  },
  metaInfo: {
    title: 'Strace | Background',
    meta: [
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ],
  },
}
</script>

<style scoped>
.bg4-container {
  width: 100%;
  display: flex;
  overflow: auto;
  min-height: 100vh;
  align-items: center;
  flex-direction: column;
  justify-content: flex-start;
  background-color: #f5f5f5;
}
.bg4-banner {
  width: 100%;
  height: 275px;
  display: flex;
  transition: 0.3s;
  align-items: center;
  flex-direction: column;
  background-size: cover;
  justify-content: center;
  background-image: url('https://marketplace.canva.com/EAD2962NKnQ/2/0/1600w/canva-rainbow-gradient-pink-and-purple-virtual-background-_Tcjok-d9b4.jpg');
}

.bg4-main-content {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: flex-start;
  background-color: #ffffff;
}
.bg4-heading {
  color: #ff0000;
  font-size: 3rem;
  align-self: center;
  text-align: center;
}
.bg4-num4 {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.bg4-container1 {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.bg4-container2 {
  flex: 0 0 auto;
  width: 200px;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.bg4-image {
  width: 200px;
  transform: scaleX(-1);
  object-fit: cover;
}
.bg4-python-stat {
  flex: 0 0 auto;
  width: 100%;
  height: 100px;
  display: flex;
  align-items: flex-start;
}
.bg4-figure-11 {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.bg4-image1 {
  width: 200px;
  object-fit: cover;
}
.bg4-link {
  text-decoration: none;
}
.bg4-figure-12 {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.bg4-image2 {
  width: 200px;
  object-fit: cover;
}
.bg4-figure-13 {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.bg4-image3 {
  width: 200px;
  object-fit: cover;
}
.bg4-figure-14 {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.bg4-container3 {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.bg4-image4 {
  width: 200px;
  object-fit: cover;
}
.bg4-container4 {
  flex: 0 0 auto;
  width: 200px;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.bg4-container5 {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.bg4-image5 {
  width: 200px;
  transform: scaleX(-1);
  object-fit: cover;
}
.bg4-reference {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #ffffff;
}
.bg4-footer {
  width: 100%;
  display: flex;
  max-width: var(--dl-size-size-maxwidth);
  align-self: center;
  align-items: center;
  padding-top: var(--dl-space-space-twounits);
  padding-left: var(--dl-space-space-threeunits);
  padding-right: var(--dl-space-space-threeunits);
  padding-bottom: var(--dl-space-space-twounits);
  justify-content: space-between;
}
.bg4-container6 {
  flex: 0 0 auto;
  width: auto;
  height: auto;
  display: flex;
  align-items: space-between;
  flex-direction: column;
}
.bg4-navlink {
  font-weight: 700;
  text-decoration: none;
}
.bg4-icon {
  width: 24px;
  height: 24px;
}
@media(max-width: 1600px) {
  .bg4-container {
    background-color: #f7f7f7;
  }
  .bg4-banner {
    height: auto;
    align-items: center;
    background-size: cover;
    justify-content: flex-start;
    background-image: url("/external/bgportrait-1500w.jpg");
  }
  .bg4-main-content {
    flex: 1;
    width: 1300px;
    height: auto;
    box-shadow: 0px 0px 10px 0px #d3d2d6;
    align-items: flex-start;
    padding-top: 100px;
    flex-direction: column;
    justify-content: flex-start;
    background-color: #ffffff;
  }
  .bg4-heading {
    color: rgb(255, 255, 255);
    width: 1200px;
    height: auto;
    font-size: 64px;
    font-style: normal;
    margin-top: 25px;
    font-family: Montserrat;
    font-weight: 700;
    line-height: 1.15;
    padding-top: 40px;
    border-radius: var(--dl-radius-radius-radius4);
    padding-bottom: 40px;
    background-size: cover;
    background-image: url("/external/bgportrait-1500w.jpg");
    background-repeat: no-repeat;
    background-position: top;
  }
  .bg4-num4 {
    width: 1200px;
    height: auto;
    align-self: flex-start;
    margin-left: 50px;
    padding-top: 50px;
    margin-right: 50px;
    flex-direction: column;
    padding-bottom: 50px;
  }
  .bg4-container1 {
    align-items: center;
    margin-bottom: 50px;
  }
  .bg4-container2 {
    width: 1035px;
  }
  .bg4-text03 {
    font-size: 16px;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-right: var(--dl-space-space-fourunits);
  }
  .bg4-text04 {
    font-weight: 700;
  }
  .bg4-text06 {
    font-weight: 700;
  }
  .bg4-text08 {
    font-weight: 700;
  }
  .bg4-text10 {
    font-weight: 700;
  }
  .bg4-text12 {
    font-weight: 700;
  }
  .bg4-text13 {
    font-weight: 400;
  }
  .bg4-text14 {
    font-weight: 700;
  }
  .bg4-text16 {
    font-weight: 700;
  }
  .bg4-image {
    width: 150px;
    align-self: flex-start;
  }
  .bg4-python-stat {
    height: auto;
    margin-bottom: 50px;
  }
  .bg4-figure-11 {
    flex: 1;
    width: 403px;
    height: auto;
    align-self: flex-start;
    align-items: center;
    justify-content: flex-start;
  }
  .bg4-image1 {
    width: 100%;
    height: 240px;
    border-radius: var(--dl-radius-radius-radius8);
    margin-bottom: 15px;
  }
  .bg4-link {
    font-size: 16px;
    align-self: center;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    margin-bottom: 25px;
    text-decoration: none;
  }
  .bg4-text21 {
    color: var(--dl-color-primary-300);
  }
  .bg4-text22 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-left: 20px;
    padding-right: 20px;
  }
  .bg4-figure-12 {
    flex: 1;
    align-items: center;
    justify-content: flex-start;
  }
  .bg4-image2 {
    width: 303px;
    height: 240px;
    border-radius: var(--dl-radius-radius-radius8);
    margin-bottom: 15px;
  }
  .bg4-text23 {
    font-size: 16px;
    align-self: center;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    margin-bottom: 25px;
    text-decoration: none;
  }
  .bg4-link1 {
    color: var(--dl-color-primary-300);
  }
  .bg4-text27 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-left: 20px;
    padding-right: 20px;
  }
  .bg4-figure-13 {
    flex: 1;
    align-items: center;
    justify-content: flex-start;
  }
  .bg4-image3 {
    width: 344px;
    height: 240px;
    border-radius: var(--dl-radius-radius-radius8);
    margin-bottom: 15px;
  }
  .bg4-text28 {
    font-size: 16px;
    align-self: center;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    margin-bottom: 25px;
    text-decoration: none;
  }
  .bg4-text32 {
    color: var(--dl-color-primary-300);
  }
  .bg4-text33 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-left: 20px;
    padding-right: 20px;
  }
  .bg4-figure-14 {
    height: auto;
    margin-bottom: 50px;
  }
  .bg4-container3 {
    width: 379px;
  }
  .bg4-image4 {
    width: 258px;
    height: 344px;
    align-self: center;
    border-radius: var(--dl-radius-radius-radius8);
  }
  .bg4-text34 {
    font-size: 16px;
    align-self: center;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 400;
    padding-top: 15px;
    text-decoration: none;
  }
  .bg4-link3 {
    color: var(--dl-color-primary-300);
  }
  .bg4-container4 {
    width: 820px;
  }
  .bg4-text37 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-left: 20px;
  }
  .bg4-text41 {
    font-weight: 700;
  }
  .bg4-text43 {
    font-weight: 700;
  }
  .bg4-text46 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-left: 20px;
    padding-right: var(--dl-space-space-fourunits);
  }
  .bg4-text49 {
    font-weight: 700;
  }
  .bg4-text54 {
    font-weight: 700;
  }
  .bg4-image5 {
    align-self: center;
  }
  .bg4-text57 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-bottom: 10px;
  }
  .bg4-text58 {
    font-size: 18px;
    align-self: flex-end;
    font-style: italic;
    font-family: Inter;
    font-weight: 500;
    padding-top: 25px;
  }
  .bg4-reference {
    width: 1600px;
    height: auto;
    align-self: center;
    box-shadow: 0px -1px 15px 0px #ebebeb;
    align-items: flex-start;
    padding-top: 50px;
    padding-left: 200px;
    padding-right: 200px;
    flex-direction: column;
    padding-bottom: 50px;
    justify-content: flex-start;
  }
  .bg4-text61 {
    font-size: 32px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
  }
  .bg4-text62 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.25;
  }
  .bg4-text65 {
    font-style: italic;
  }
  .bg4-link4 {
    color: var(--dl-color-primary-300);
    text-decoration: underline;
  }
  .bg4-text72 {
    font-style: italic;
  }
  .bg4-link5 {
    color: var(--dl-color-primary-300);
    text-decoration: underline;
  }
  .bg4-text76 {
    font-style: italic;
  }
  .bg4-text77 {
    font-style: italic;
  }
  .bg4-text78 {
    font-style: italic;
  }
  .bg4-link6 {
    color: var(--dl-color-primary-300);
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    text-decoration: underline;
  }
  .bg4-footer {
    justify-content: space-between;
  }
  .bg4-navlink {
    font-size: 16px;
    font-family: Montserrat;
    font-weight: 700;
    text-decoration: none;
  }
  .bg4-text83 {
    font-size: 16px;
    font-style: normal;
    font-family: Montserrat;
    font-weight: 500;
  }
  .bg4-icon {
    margin-left: 50px;
  }
}
@media(max-width: 1200px) {
  .bg4-heading {
    color: rgb(255, 255, 255);
  }
  .bg4-link {
    align-self: center;
  }
  .bg4-image2 {
    width: 453px;
    height: 391px;
  }
  .bg4-image4 {
    width: 572px;
    height: 482px;
    align-self: center;
  }
  .bg4-text34 {
    align-self: center;
  }
  .bg4-text37 {
    text-align: justify;
    margin-bottom: 0px;
  }
  .bg4-text46 {
    text-align: justify;
    margin-bottom: 0px;
  }
}
@media(max-width: 479px) {
  .bg4-footer {
    align-self: center;
  }
  .bg4-icon-group {
    display: none;
  }
}
</style>
