// [Angular] Website Source Code/src/app/pages/bg-5/bg-5.component.ts
import { Component } from '@angular/core'
import { Title, Meta } from '@angular/platform-browser'

@Component({
  selector: 'app-bg5',
  templateUrl: 'bg-5.component.html',
  styleUrls: ['bg-5.component.css'],
})
export class Bg5 {
  rawv4f6: string = ' '
  rawgowx: string = ' '
  rawehfv: string = ' '
  rawr7ib: string = ' '
  rawz8d3: string = ' '
  rawf4xi: string = ' '
  rawvdph: string = ' '
  rawj2hq: string = ' '
  rawhklo: string = ' '
  raw5xkh: string = ' '
  rawdoeo: string = ' '
  raw89zs: string = ' '
  constructor(private title: Title, private meta: Meta) {
    this.title.setTitle('Strace | Background')
    this.meta.addTags([
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ])
  }
}

<div class="bg5-container">
  <div class="bg5-banner">
    <div class="bg5-main-content">
      <h1 class="bg5-heading">
        <span>IMPLEMENTATION OF</span>
        <br />
        <span>PYTHON IS HYBRID</span>
      </h1>
      <div class="bg5-num5">
        <div class="bg5-container1">
          <img
            alt="image"
            src="https://i.pinimg.com/564x/74/58/e2/7458e2f9ef2512a3220cf7937c743017.jpg"
            class="bg5-image"
          />
          <span class="bg5-text03">
            <span>
              Many people said that the Python is a pure interpretation language
              but this is actually not 100% true.
            </span>
            <br />
            <br />
            <span>
              Before a
              <span [innerHTML]="rawv4f6"></span>
            </span>
            <span class="bg5-text08">
              Python script
              <span [innerHTML]="rawgowx"></span>
            </span>
            <span>
              can be run, it needs to be
              <span [innerHTML]="rawehfv"></span>
            </span>
            <span class="bg5-text10">converted into bytecode</span>
            <span>
              , an intermediate form. Increasing the execution speed is the aim
              of this compilation phase. The bytecode is subsequently executed
              by the Python Virtual Machine (PVM). This compilation to bytecode
              process uses
              <span [innerHTML]="rawr7ib"></span>
            </span>
            <span class="bg5-text12">Just-In-Time (JIT) compilation</span>
            <span>.</span>
            <br />
            <br />
            <span>
              The Python interpreter typically executes each line of the
              language. This increases the interactive nature of development
              because you can test individual lines or blocks of code in an
              interactive shell.
            </span>
            <br />
          </span>
          <div class="bg5-container2">
            <img
              alt="image"
              src="https://miro.medium.com/v2/resize:fit:720/format:webp/1*CZjfRXGXNphuUL67zbEDTw.png"
              loading="eager"
              class="bg5-image1"
            />
            <span class="bg5-text18">
              <span>
                Implementation of Python | Image Source:
                <span [innerHTML]="rawz8d3"></span>
              </span>
              <a
                href="https://medium.com/swlh/understanding-python-implementations-53015a3698e5"
                target="_blank"
                rel="noreferrer noopener"
                class="bg5-link"
              >
                Medium
              </a>
            </span>
          </div>
        </div>
        <span class="bg5-text20">
          <span>
            -
            <span [innerHTML]="rawf4xi"></span>
          </span>
          <span class="bg5-text22">Muhammad Nabil Irfan</span>
        </span>
      </div>
    </div>
  </div>
  <div class="bg5-reference">
    <h1 class="bg5-text23">References</h1>
    <span class="bg5-text24">
      <br />
      <span>
        Kochar, A. (2023, March 13).
        <span [innerHTML]="rawvdph"></span>
      </span>
      <span class="bg5-text27">Why Python is Interpreted Language?</span>
      <span>PrepBytes Blog.</span>
      <br />
      <span>
               
        <span [innerHTML]="rawj2hq"></span>
      </span>
      <a
        href="https://www.prepbytes.com/blog/python/why-python-is-interpreted-language/"
        target="_blank"
        rel="noreferrer noopener"
        class="bg5-link1"
      >
        https://www.prepbytes.com/blog/python/why-python-is-interpreted-language/
      </a>
      <a
        href="https://www.prepbytes.com/blog/python/why-python-is-interpreted-language/#:~:text=A5%3A%20Yes%2C%20Python%20code%20can,both%20interpreted%20and%20compiled%20characteristics. In-Text Citation: (2023)"
        target="_blank"
        rel="noreferrer noopener"
      >
        <br class="bg5-text31" />
      </a>
      <a
        href="https://www.prepbytes.com/blog/python/why-python-is-interpreted-language/#:~:text=A5%3A%20Yes%2C%20Python%20code%20can,both%20interpreted%20and%20compiled%20characteristics. In-Text Citation: (2023)"
        target="_blank"
        rel="noreferrer noopener"
      >
        <br class="bg5-text32" />
      </a>
      <span>
        Singh, S. (2020, July 21).
        <span [innerHTML]="rawhklo"></span>
      </span>
      <span class="bg5-text34">Understanding Python Implementations</span>
      <span>. Medium.</span>
      <br />
      <span>       </span>
      <span class="bg5-text38"><span [innerHTML]="raw5xkh"></span></span>
      <a
        href="https://Singh, S. (2020, July 21). Understanding Python Implementations. Medium. https://medium.com/swlh/understanding-python-implementations-53015a3698e5"
        target="_blank"
        rel="noreferrer noopener"
        class="bg5-link4"
      >
        https://medium.com/swlh/understanding-python-implementations-53015a3698e5
      </a>
      <br class="bg5-text39" />
      <br class="bg5-text40" />
      <span class="bg5-text41">
        Is Python interpreted, or compiled, or both?
      </span>
      <span>(2011, July 31). Stack Overflow.</span>
      <br />
      <span>
               
        <span [innerHTML]="rawdoeo"></span>
      </span>
      <a
        href="https://stackoverflow.com/questions/6889747/is-python-interpreted-or-compiled-or-both"
        target="_blank"
        rel="noreferrer noopener"
        class="bg5-link5"
      >
        https://stackoverflow.com/questions/6889747/is-python-interpreted-or-compiled-or-both
      </a>
      <a
        href="https://stackoverflow.com/questions/6889747/is-python-interpreted-or-compiled-or-both"
        target="_blank"
        rel="noreferrer noopener"
        class="bg5-link6"
      >
        <span [innerHTML]="raw89zs"></span>
      </a>
      <br />
    </span>
  </div>
  <footer class="bg5-footer">
    <div class="bg5-container3">
      <a routerLink="/strace" class="bg5-navlink">STRACE</a>
    </div>
    <span class="bg5-text46">&quot;Making System Calls Cool Again&quot;</span>
    <div class="bg5-icon-group">
      <svg viewBox="0 0 877.7142857142857 1024" class="bg5-icon">
        <path
          d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
        ></path>
      </svg>
    </div>
  </footer>
  <app-header></app-header>
</div>

// [Vue] Website Source Code/src/views/bg-5.vue
<template>
  <div class="bg5-container">
    <div class="bg5-banner">
      <div class="bg5-main-content">
        <h1 class="bg5-heading">
          <span>IMPLEMENTATION OF</span>
          <br />
          <span>PYTHON IS HYBRID</span>
        </h1>
        <div class="bg5-num5">
          <div class="bg5-container1">
            <img
              alt="image"
              src="https://i.pinimg.com/564x/74/58/e2/7458e2f9ef2512a3220cf7937c743017.jpg"
              class="bg5-image"
            />
            <span class="bg5-text03">
              <span>
                Many people said that the Python is a pure interpretation language
                but this is actually not 100% true.
              </span>
              <br />
              <br />
              <span>
                Before a
                <span v-html="rawqwz1"></span>
              </span>
              <span class="bg5-text08">
                Python script
                <span v-html="rawox49"></span>
              </span>
              <span>
                can be run, it needs to be
                <span v-html="raw5iyj"></span>
              </span>
              <span class="bg5-text10">converted into bytecode</span>
              <span>
                , an intermediate form. Increasing the execution speed is the aim
                of this compilation phase. The bytecode is subsequently executed
                by the Python Virtual Machine (PVM). This compilation to bytecode
                process uses
                <span v-html="rawrh9f"></span>
              </span>
              <span class="bg5-text12">Just-In-Time (JIT) compilation</span>
              <span>.</span>
              <br />
              <br />
              <span>
                The Python interpreter typically executes each line of the
                language. This increases the interactive nature of development
                because you can test individual lines or blocks of code in an
                interactive shell.
              </span>
              <br />
            </span>
            <div class="bg5-container2">
              <img
                alt="image"
                src="https://miro.medium.com/v2/resize:fit:720/format:webp/1*CZjfRXGXNphuUL67zbEDTw.png"
                loading="eager"
                class="bg5-image1"
              />
              <span class="bg5-text18">
                <span>
                  Implementation of Python | Image Source:
                  <span v-html="raw3al2"></span>
                </span>
                <a
                  href="https://medium.com/swlh/understanding-python-implementations-53015a3698e5"
                  target="_blank"
                  rel="noreferrer noopener"
                  class="bg5-link"
                >
                  Medium
                </a>
              </span>
            </div>
          </div>
          <span class="bg5-text20">
            <span>
              -
              <span v-html="rawg0xt"></span>
            </span>
            <span class="bg5-text22">Muhammad Nabil Irfan</span>
          </span>
        </div>
      </div>
    </div>
    <div class="bg5-reference">
      <h1 class="bg5-text23">References</h1>
      <span class="bg5-text24">
        <br />
        <span>
          Kochar, A. (2023, March 13).
          <span v-html="raw2cdb"></span>
        </span>
        <span class="bg5-text27">Why Python is Interpreted Language?</span>
        <span>PrepBytes Blog.</span>
        <br />
        <span>
                 
          <span v-html="rawgzmo"></span>
        </span>
        <a
          href="https://www.prepbytes.com/blog/python/why-python-is-interpreted-language/"
          target="_blank"
          rel="noreferrer noopener"
          class="bg5-link1"
        >
          https://www.prepbytes.com/blog/python/why-python-is-interpreted-language/
        </a>
        <a
          href="https://www.prepbytes.com/blog/python/why-python-is-interpreted-language/#:~:text=A5%3A%20Yes%2C%20Python%20code%20can,both%20interpreted%20and%20compiled%20characteristics. In-Text Citation: (2023)"
          target="_blank"
          rel="noreferrer noopener"
        >
          <br class="bg5-text31" />
        </a>
        <a
          href="https://www.prepbytes.com/blog/python/why-python-is-interpreted-language/#:~:text=A5%3A%20Yes%2C%20Python%20code%20can,both%20interpreted%20and%20compiled%20characteristics. In-Text Citation: (2023)"
          target="_blank"
          rel="noreferrer noopener"
        >
          <br class="bg5-text32" />
        </a>
        <span>
          Singh, S. (2020, July 21).
          <span v-html="rawvxbb"></span>
        </span>
        <span class="bg5-text34">Understanding Python Implementations</span>
        <span>. Medium.</span>
        <br />
        <span>       </span>
        <span class="bg5-text38"><span v-html="rawouxt"></span></span>
        <a
          href="https://Singh, S. (2020, July 21). Understanding Python Implementations. Medium. https://medium.com/swlh/understanding-python-implementations-53015a3698e5"
          target="_blank"
          rel="noreferrer noopener"
          class="bg5-link4"
        >
          https://medium.com/swlh/understanding-python-implementations-53015a3698e5
        </a>
        <br class="bg5-text39" />
        <br class="bg5-text40" />
        <span class="bg5-text41">
          Is Python interpreted, or compiled, or both?
        </span>
        <span>(2011, July 31). Stack Overflow.</span>
        <br />
        <span>
                 
          <span v-html="rawdgjw"></span>
        </span>
        <a
          href="https://stackoverflow.com/questions/6889747/is-python-interpreted-or-compiled-or-both"
          target="_blank"
          rel="noreferrer noopener"
          class="bg5-link5"
        >
          https://stackoverflow.com/questions/6889747/is-python-interpreted-or-compiled-or-both
        </a>
        <a
          href="https://stackoverflow.com/questions/6889747/is-python-interpreted-or-compiled-or-both"
          target="_blank"
          rel="noreferrer noopener"
          class="bg5-link6"
        >
          <span v-html="raw82bn"></span>
        </a>
        <br />
      </span>
    </div>
    <footer class="bg5-footer">
      <div class="bg5-container3">
        <router-link to="/strace" class="bg5-navlink">STRACE</router-link>
      </div>
      <span class="bg5-text46">&quot;Making System Calls Cool Again&quot;</span>
      <div class="bg5-icon-group">
        <svg viewBox="0 0 877.7142857142857 1024" class="bg5-icon">
          <path
            d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
          ></path>
        </svg>
      </div>
    </footer>
    <app-header></app-header>
  </div>
</template>

<script>
import AppHeader from '../components/header'

export default {
  name: 'Bg5',
  props: {},
  components: {
    AppHeader,
  },
  data() {
    return {
      rawqwz1: ' ',
      rawox49: ' ',
      raw5iyj: ' ',
      rawrh9f: ' ',
      raw3al2: ' ',
      rawg0xt: ' ',
      raw2cdb: ' ',
      rawgzmo: ' ',
      rawvxbb: ' ',
      rawouxt: ' ',
      rawdgjw: ' ',
      raw82bn: ' ',
    }
  },
  metaInfo: {
    title: 'Strace | Background',
    meta: [
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ],
  },
}
</script>

<style scoped>
.bg5-container {
  width: 100%;
  display: flex;
  overflow: auto;
  min-height: 100vh;
  align-items: center;
  flex-direction: column;
  justify-content: flex-start;
  background-color: #f5f5f5;
}
.bg5-banner {
  width: 100%;
  height: 275px;
  display: flex;
  transition: 0.3s;
  align-items: center;
  flex-direction: column;
  background-size: cover;
  justify-content: center;
  background-image: url('https://marketplace.canva.com/EAD2962NKnQ/2/0/1600w/canva-rainbow-gradient-pink-and-purple-virtual-background-_Tcjok-d9b4.jpg');
}

.bg5-main-content {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: flex-start;
  background-color: #ffffff;
}
.bg5-heading {
  color: #ff0000;
  font-size: 3rem;
  align-self: center;
  text-align: center;
}
.bg5-num5 {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: flex-start;
  background-color: #ffffff;
}
.bg5-container1 {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.bg5-image {
  width: 200px;
  object-fit: cover;
}
.bg5-container2 {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.bg5-image1 {
  width: 200px;
  object-fit: cover;
}
.bg5-reference {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #ffffff;
}
.bg5-footer {
  width: 100%;
  display: flex;
  max-width: var(--dl-size-size-maxwidth);
  align-self: center;
  align-items: center;
  padding-top: var(--dl-space-space-twounits);
  padding-left: var(--dl-space-space-threeunits);
  padding-right: var(--dl-space-space-threeunits);
  padding-bottom: var(--dl-space-space-twounits);
  justify-content: space-between;
}
.bg5-container3 {
  flex: 0 0 auto;
  width: auto;
  height: auto;
  display: flex;
  align-items: space-between;
  flex-direction: column;
}
.bg5-navlink {
  font-weight: 700;
  text-decoration: none;
}
.bg5-icon {
  width: 24px;
  height: 24px;
}
@media(max-width: 1600px) {
  .bg5-container {
    background-color: #f7f7f7;
  }
  .bg5-banner {
    height: auto;
    align-items: center;
    background-size: cover;
    justify-content: flex-start;
    background-image: url("/external/bgportrait-1500w.jpg");
  }
  .bg5-main-content {
    flex: 1;
    width: 1300px;
    height: auto;
    box-shadow: 0px 0px 10px 0px #d3d2d6;
    align-items: flex-start;
    padding-top: 100px;
    flex-direction: column;
    justify-content: flex-start;
    background-color: #ffffff;
  }
  .bg5-heading {
    color: rgb(255, 255, 255);
    width: 1200px;
    height: auto;
    font-size: 64px;
    font-style: normal;
    margin-top: 25px;
    font-family: Montserrat;
    font-weight: 700;
    line-height: 1.15;
    padding-top: 40px;
    border-radius: var(--dl-radius-radius-radius4);
    margin-bottom: 15px;
    padding-bottom: 40px;
    background-image: url("/external/bglandscape-1200w.jpg");
    background-position: top;
  }
  .bg5-num5 {
    width: 1200px;
    height: auto;
    margin-top: 0px;
    margin-left: 50px;
    padding-top: 50px;
    margin-right: 50px;
    flex-direction: column;
    padding-bottom: 50px;
  }
  .bg5-container1 {
    align-items: center;
    margin-bottom: 25px;
    justify-content: flex-start;
  }
  .bg5-image {
    width: 180px;
  }
  .bg5-text03 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-left: var(--dl-space-space-fourunits);
    padding-right: var(--dl-space-space-fourunits);
  }
  .bg5-text08 {
    font-weight: 700;
  }
  .bg5-text10 {
    font-weight: 700;
  }
  .bg5-text12 {
    font-weight: 700;
  }
  .bg5-image1 {
    width: 412px;
    height: 226px;
    margin-bottom: 15px;
  }
  .bg5-text18 {
    align-self: center;
    text-align: center;
  }
  .bg5-link {
    color: var(--dl-color-primary-300);
    text-decoration: underline;
  }
  .bg5-text20 {
    font-size: 18px;
    align-self: flex-end;
    font-style: normal;
    font-family: Inter;
    font-weight: 500;
    padding-top: 25px;
  }
  .bg5-text22 {
    font-style: italic;
  }
  .bg5-reference {
    width: 1600px;
    height: auto;
    align-self: center;
    box-shadow: 0px -1px 15px 0px #ebebeb;
    align-items: flex-start;
    padding-top: 50px;
    padding-left: 200px;
    padding-right: 200px;
    flex-direction: column;
    padding-bottom: 50px;
    justify-content: flex-start;
  }
  .bg5-text23 {
    font-size: 32px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
  }
  .bg5-text24 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.25;
  }
  .bg5-text27 {
    font-style: italic;
  }
  .bg5-link1 {
    color: var(--dl-color-primary-300);
    text-decoration: underline;
  }
  .bg5-text31 {
    line-height: 1.25;
    text-decoration: underline;
  }
  .bg5-text32 {
    line-height: 1.25;
    text-decoration: underline;
  }
  .bg5-text34 {
    font-style: italic;
  }
  .bg5-text38 {
    color: var(--dl-color-primary-300);
  }
  .bg5-link4 {
    color: var(--dl-color-primary-300);
    text-decoration: underline;
  }
  .bg5-text39 {
    line-height: 1.25;
    text-decoration: underline;
  }
  .bg5-text40 {
    font-style: italic;
  }
  .bg5-text41 {
    font-style: italic;
  }
  .bg5-link5 {
    color: var(--dl-color-primary-300);
    text-decoration: underline;
  }
  .bg5-link6 {
    text-decoration: underline;
  }
  .bg5-footer {
    justify-content: space-between;
  }
  .bg5-navlink {
    font-size: 16px;
    font-family: Montserrat;
    font-weight: 700;
    text-decoration: none;
  }
  .bg5-text46 {
    font-size: 16px;
    font-style: normal;
    font-family: Montserrat;
    font-weight: 500;
  }
  .bg5-icon {
    margin-left: 50px;
  }
}
@media(max-width: 1200px) {
  .bg5-heading {
    color: rgb(255, 255, 255);
  }
  .bg5-num5 {
    align-items: flex-start;
    flex-direction: column;
    justify-content: center;
  }
}
@media(max-width: 479px) {
  .bg5-footer {
    align-self: center;
  }
  .bg5-icon-group {
    display: none;
  }
}
</style>
