// [Angular] Website Source Code/src/app/pages/bg-6/bg-6.component.ts
import { Component } from '@angular/core'
import { Title, Meta } from '@angular/platform-browser'

@Component({
  selector: 'app-bg6',
  templateUrl: 'bg-6.component.html',
  styleUrls: ['bg-6.component.css'],
})
export class Bg6 {
  raw4fjy: string = ' '
  rawjb0f: string = ' '
  constructor(private title: Title, private meta: Meta) {
    this.title.setTitle('Strace | Background')
    this.meta.addTags([
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ])
  }
}

<div class="bg6-container">
  <div class="bg6-banner">
    <div class="bg6-main-content">
      <h1 class="bg6-heading">Programming Environment for Python and Django</h1>
      <div class="bg6-container1">
        <span class="bg6-text">
          <span>
            There are several Integrated Development Environments (IDEs) for
            Python, and the best one for you depends on your preferences and
            requirements.
          </span>
          <br />
          <span> </span>
          <br />
          <br />
        </span>
        <img
          alt="image"
          src="https://s3.getstickerpack.com/storage/uploads/sticker-pack/stickthing/sticker_28.png?afb1beab15bc92190c4fa8ec58960f76&amp;d=200x200"
          loading="eager"
          class="bg6-image"
        />
      </div>
      <div class="bg6-container2">
        <div class="bg6-py-charm">
          <h1 class="bg6-text06">
            <span class="bg6-text07">1. PyCharm</span>
            <br />
          </h1>
          <img
            alt="pastedImage"
            src="https://storage.caktusgroup.com/media/blog-images/logo.png"
            class="bg6-pasted-image"
          />
          <span class="bg6-text09">
            <span>
              Developed by JetBrains, PyCharm is a powerful and feature-rich IDE
              for Python development.
            </span>
            <br />
            <br />
            <span>
              It provides smart code completion, code analysis, a powerful
              debugger, and integrated testing support.
            </span>
            <br />
            <br />
            <span>
              PyCharm is available in both a free, open-source community edition
              and a paid professional edition with additional features.
            </span>
          </span>
        </div>
        <div class="bg6-idle">
          <h1 class="bg6-text17">2. IDLE</h1>
          <img
            alt="pastedImage"
            src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/1200px-Python-logo-notext.svg.png"
            loading="eager"
            class="bg6-pasted-image1"
          />
          <span class="bg6-text18">
            <span>
              TextKey Features: Simple and lightweight with an interactive
              shell, basic code editor, debugger, and integrated help.
              Particularly suitable for beginners and small projects.
            </span>
            <br />
            <br />
            <span>
              Bundled with Python: IDLE comes bundled with the standard Python
              distribution, making it readily available without the need for
              additional installations.
            </span>
          </span>
        </div>
        <div class="bg6-idle1">
          <h1 class="bg6-text23">3. Visual Studio Code</h1>
          <img
            alt="pastedImage"
            src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/1200px-Visual_Studio_Code_1.35_icon.svg.png"
            loading="eager"
            class="bg6-pasted-image2"
          />
          <span class="bg6-text24">
            <span class="bg6-text25">
              Visual Studio Code also known as VS Code, is a text editor
              developed by the Microsoft and it is available for Windows, macOS,
              as well as Linux.
            </span>
            <br />
            <br />
            <span>
              VS Code provide the programmers with interesting features such as
              IntelliSense for faster coding experience, debugger, and Git
              integration which can help the developers to collaborate their web
              development project using Python and Django.
            </span>
            <br />
          </span>
        </div>
      </div>
      <span class="bg6-text30">
        <span class="bg6-text31">- Muhammad Nabil Irfan</span>
        <br />
      </span>
    </div>
  </div>
  <div class="bg6-reference">
    <h1 class="bg6-text33">References</h1>
    <span class="bg6-text34">
      <br class="bg6-text35" />
      <span class="bg6-text36"><span [innerHTML]="raw4fjy"></span></span>
      <span class="bg6-text37">
        Gupta, A. (2023, October 19).
        <span [innerHTML]="rawjb0f"></span>
      </span>
      <span class="bg6-text38">
        15+ Popular Python IDEs in 2023: Choosing The Best One
      </span>
      <span class="bg6-text39">. Simplilearn.com.</span>
      <br class="bg6-text40" />
      <span class="bg6-text41">             </span>
      <span class="bg6-text42">
        https://www.simplilearn.com/tutorials/python-tutorial/python-ide
      </span>
      <br />
    </span>
  </div>
  <footer class="bg6-footer">
    <div class="bg6-container3">
      <a routerLink="/strace" class="bg6-navlink">STRACE</a>
    </div>
    <span class="bg6-text44">&quot;Making System Calls Cool Again&quot;</span>
    <div class="bg6-icon-group">
      <svg viewBox="0 0 877.7142857142857 1024" class="bg6-icon">
        <path
          d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
        ></path>
      </svg>
    </div>
  </footer>
  <app-header></app-header>
</div>

// [Vue] Website Source Code/src/views/bg-6.vue
<template>
  <div class="bg6-container">
    <div class="bg6-banner">
      <div class="bg6-main-content">
        <h1 class="bg6-heading">Programming Environment for Python and Django</h1>
        <div class="bg6-container1">
          <span class="bg6-text">
            <span>
              There are several Integrated Development Environments (IDEs) for
              Python, and the best one for you depends on your preferences and
              requirements.
            </span>
            <br />
            <span> </span>
            <br />
            <br />
          </span>
          <img
            alt="image"
            src="https://s3.getstickerpack.com/storage/uploads/sticker-pack/stickthing/sticker_28.png?afb1beab15bc92190c4fa8ec58960f76&amp;d=200x200"
            loading="eager"
            class="bg6-image"
          />
        </div>
        <div class="bg6-container2">
          <div class="bg6-py-charm">
            <h1 class="bg6-text06">
              <span class="bg6-text07">1. PyCharm</span>
              <br />
            </h1>
            <img
              alt="pastedImage"
              src="https://storage.caktusgroup.com/media/blog-images/logo.png"
              class="bg6-pasted-image"
            />
            <span class="bg6-text09">
              <span>
                Developed by JetBrains, PyCharm is a powerful and feature-rich IDE
                for Python development.
              </span>
              <br />
              <br />
              <span>
                It provides smart code completion, code analysis, a powerful
                debugger, and integrated testing support.
              </span>
              <br />
              <br />
              <span>
                PyCharm is available in both a free, open-source community edition
                and a paid professional edition with additional features.
              </span>
            </span>
          </div>
          <div class="bg6-idle">
            <h1 class="bg6-text17">2. IDLE</h1>
            <img
              alt="pastedImage"
              src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/1200px-Python-logo-notext.svg.png"
              loading="eager"
              class="bg6-pasted-image1"
            />
            <span class="bg6-text18">
              <span>
                TextKey Features: Simple and lightweight with an interactive
                shell, basic code editor, debugger, and integrated help.
                Particularly suitable for beginners and small projects.
              </span>
              <br />
              <br />
              <span>
                Bundled with Python: IDLE comes bundled with the standard Python
                distribution, making it readily available without the need for
                additional installations.
              </span>
            </span>
          </div>
          <div class="bg6-idle1">
            <h1 class="bg6-text23">3. Visual Studio Code</h1>
            <img
              alt="pastedImage"
              src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/1200px-Visual_Studio_Code_1.35_icon.svg.png"
              loading="eager"
              class="bg6-pasted-image2"
            />
            <span class="bg6-text24">
              <span class="bg6-text25">
                Visual Studio Code also known as VS Code, is a text editor
                developed by the Microsoft and it is available for Windows, macOS,
                as well as Linux.
              </span>
              <br />
              <br />
              <span>
                VS Code provide the programmers with interesting features such as
                IntelliSense for faster coding experience, debugger, and Git
                integration which can help the developers to collaborate their web
                development project using Python and Django.
              </span>
              <br />
            </span>
          </div>
        </div>
        <span class="bg6-text30">
          <span class="bg6-text31">- Muhammad Nabil Irfan</span>
          <br />
        </span>
      </div>
    </div>
    <div class="bg6-reference">
      <h1 class="bg6-text33">References</h1>
      <span class="bg6-text34">
        <br class="bg6-text35" />
        <span class="bg6-text36"><span v-html="rawgp2t"></span></span>
        <span class="bg6-text37">
          Gupta, A. (2023, October 19).
          <span v-html="raw8dz0"></span>
        </span>
        <span class="bg6-text38">
          15+ Popular Python IDEs in 2023: Choosing The Best One
        </span>
        <span class="bg6-text39">. Simplilearn.com.</span>
        <br class="bg6-text40" />
        <span class="bg6-text41">             </span>
        <span class="bg6-text42">
          https://www.simplilearn.com/tutorials/python-tutorial/python-ide
        </span>
        <br />
      </span>
    </div>
    <footer class="bg6-footer">
      <div class="bg6-container3">
        <router-link to="/strace" class="bg6-navlink">STRACE</router-link>
      </div>
      <span class="bg6-text44">&quot;Making System Calls Cool Again&quot;</span>
      <div class="bg6-icon-group">
        <svg viewBox="0 0 877.7142857142857 1024" class="bg6-icon">
          <path
            d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
          ></path>
        </svg>
      </div>
    </footer>
    <app-header></app-header>
  </div>
</template>

<script>
import AppHeader from '../components/header'

export default {
  name: 'Bg6',
  props: {},
  components: {
    AppHeader,
  },
  data() {
    return {
      rawgp2t: ' ',
      raw8dz0: ' ',
    }
  },
  metaInfo: {
    title: 'Strace | Background',
    meta: [
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ],
  },
}
</script>

<style scoped>
.bg6-container {
  width: 100%;
  display: flex;
  overflow: auto;
  min-height: 100vh;
  align-items: center;
  flex-direction: column;
  justify-content: flex-start;
  background-color: #f5f5f5;
}
.bg6-banner {
  width: 100%;
  height: 275px;
  display: flex;
  transition: 0.3s;
  align-items: center;
  flex-direction: column;
  background-size: cover;
  justify-content: center;
  background-image: url('https://marketplace.canva.com/EAD2962NKnQ/2/0/1600w/canva-rainbow-gradient-pink-and-purple-virtual-background-_Tcjok-d9b4.jpg');
}

.bg6-main-content {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: flex-start;
  background-color: #ffffff;
}
.bg6-heading {
  color: #ff0000;
  font-size: 3rem;
  align-self: center;
  text-align: center;
}
.bg6-container1 {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.bg6-image {
  width: 200px;
  transform: scaleX(-1);
  object-fit: cover;
}
.bg6-container2 {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.bg6-py-charm {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.bg6-idle {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.bg6-idle1 {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.bg6-reference {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #ffffff;
}
.bg6-footer {
  width: 100%;
  display: flex;
  max-width: var(--dl-size-size-maxwidth);
  align-self: center;
  align-items: center;
  padding-top: var(--dl-space-space-twounits);
  padding-left: var(--dl-space-space-threeunits);
  padding-right: var(--dl-space-space-threeunits);
  padding-bottom: var(--dl-space-space-twounits);
  justify-content: space-between;
}
.bg6-container3 {
  flex: 0 0 auto;
  width: auto;
  height: auto;
  display: flex;
  align-items: space-between;
  flex-direction: column;
}
.bg6-navlink {
  font-weight: 700;
  text-decoration: none;
}
.bg6-icon {
  width: 24px;
  height: 24px;
}
@media(max-width: 1600px) {
  .bg6-container {
    background-color: #f7f7f7;
  }
  .bg6-banner {
    width: 1600px;
    height: auto;
    align-items: center;
    background-size: cover;
    justify-content: flex-start;
    background-image: url("/external/bgportrait-1600w.jpg");
  }
  .bg6-main-content {
    flex: 1;
    width: 1300px;
    height: auto;
    box-shadow: 0px 0px 10px 0px #d3d2d6;
    align-items: flex-start;
    padding-top: 100px;
    flex-direction: column;
    padding-bottom: 50px;
    justify-content: flex-start;
    background-color: #ffffff;
  }
  .bg6-heading {
    color: rgb(255, 255, 255);
    width: 1200px;
    height: auto;
    font-size: 56px;
    font-style: normal;
    margin-top: 25px;
    font-family: Montserrat;
    font-weight: 700;
    line-height: 1.15;
    padding-top: 40px;
    border-radius: var(--dl-radius-radius-radius4);
    margin-bottom: 15px;
    padding-bottom: 40px;
    text-transform: uppercase;
    background-size: cover;
    background-image: url("/external/bgportrait-1600w.jpg");
    background-position: center;
  }
  .bg6-container1 {
    width: 50%;
    align-self: center;
    align-items: center;
    margin-left: 50px;
    padding-top: 50px;
    margin-right: 50px;
    flex-direction: row;
    padding-bottom: 25px;
    justify-content: space-between;
  }
  .bg6-text {
    width: 50%;
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
  }
  .bg6-container2 {
    width: 1200px;
    height: auto;
    align-items: flex-start;
    margin-left: 50px;
    padding-top: 25px;
    margin-right: 50px;
    flex-direction: row;
    padding-bottom: 50px;
    justify-content: flex-start;
  }
  .bg6-py-charm {
    width: 400px;
    align-self: flex-start;
    align-items: center;
    padding-left: 30px;
    padding-right: 30px;
    flex-direction: column;
    justify-content: flex-start;
  }
  .bg6-text06 {
    width: auto;
    height: auto;
    font-size: 32px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
    margin-bottom: 25px;
  }
  .bg6-text07 {
    width: 240px;
  }
  .bg6-pasted-image {
    width: 201px;
    height: 201px;
    align-self: center;
    margin-bottom: 35px;
  }
  .bg6-text09 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
  }
  .bg6-idle {
    width: 400px;
    align-self: flex-start;
    align-items: center;
    padding-left: 30px;
    padding-right: 30px;
    flex-direction: column;
    justify-content: flex-start;
  }
  .bg6-text17 {
    width: auto;
    height: auto;
    font-size: 32px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
    margin-bottom: 25px;
  }
  .bg6-pasted-image1 {
    width: 187px;
    height: 203px;
    align-self: center;
    margin-bottom: 35px;
  }
  .bg6-text18 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
  }
  .bg6-idle1 {
    width: 400px;
    align-self: flex-start;
    align-items: center;
    padding-left: 30px;
    padding-right: 30px;
    flex-direction: column;
    justify-content: flex-start;
  }
  .bg6-text23 {
    width: auto;
    height: auto;
    font-size: 32px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
    margin-bottom: 25px;
  }
  .bg6-pasted-image2 {
    width: 203px;
    height: 203px;
    align-self: center;
    margin-bottom: 35px;
  }
  .bg6-text24 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
  }
  .bg6-text25 {
    text-align: justify;
  }
  .bg6-text30 {
    font-size: 18px;
    align-self: flex-end;
    font-style: italic;
    text-align: justify;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-right: 50px;
  }
  .bg6-text31 {
    text-align: justify;
    font-family: Inter;
  }
  .bg6-reference {
    width: 1600px;
    height: auto;
    align-self: center;
    box-shadow: 0px -1px 15px 0px #d4d4d4;
    align-items: flex-start;
    padding-top: 50px;
    padding-left: 200px;
    padding-right: 200px;
    flex-direction: column;
    padding-bottom: 50px;
    justify-content: flex-start;
  }
  .bg6-text33 {
    font-size: 32px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
  }
  .bg6-text34 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.25;
  }
  .bg6-text35 {
    font-size: 18px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .bg6-text36 {
    font-size: 18px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .bg6-text37 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .bg6-text38 {
    font-size: 16px;
    font-style: italic;
    font-family: Inter;
    font-weight: 400;
  }
  .bg6-text39 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .bg6-text40 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .bg6-text41 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .bg6-text42 {
    color: var(--dl-color-primary-300);
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    text-decoration: underline;
  }
  .bg6-footer {
    justify-content: space-between;
  }
  .bg6-navlink {
    font-size: 16px;
    font-family: Montserrat;
    font-weight: 700;
    text-decoration: none;
  }
  .bg6-text44 {
    font-size: 16px;
    font-style: normal;
    font-family: Montserrat;
    font-weight: 500;
  }
  .bg6-icon {
    margin-left: 50px;
  }
}
@media(max-width: 1200px) {
  .bg6-heading {
    color: rgb(255, 255, 255);
  }
}
@media(max-width: 479px) {
  .bg6-footer {
    align-self: center;
  }
  .bg6-icon-group {
    display: none;
  }
}
</style>
