// [Angular] Website Source Code/src/app/components/feature-card1/feature-card1.component.ts
import { Component, Input } from '@angular/core'

@Component({
  selector: 'feature-card1',
  templateUrl: 'feature-card1.component.html',
  styleUrls: ['feature-card1.component.css'],
})
export class FeatureCard1 {
  @Input()
  imageSrc: string =
    'https://images.unsplash.com/photo-1512295767273-ac109ac3acfa?ixid=Mnw5MTMyMXwwfDF8c2VhcmNofDF8fHllbGxvdyUyMHRlY2h8ZW58MHx8fHwxNjI2MjU1NDk0&ixlib=rb-1.2.1&w=1000'
  @Input()
  imageAlt: string = 'image'
  @Input()
  title: string = 'Names and Binding'
  @Input()
  rootClassName: string = ''
  constructor() {}
}

<div class="feature-card1-feature-card" [ngClass]="rootClassName">
  <h2 class="feature-card1-text">{{ title }}</h2>
  <img
    [attr.alt]="imageAlt"
    [attr.src]="imageSrc"
    class="feature-card1-image"
  />
</div>

// [Vue] Website Source Code/src/components/feature-card1.vue
<template>
  <div class="feature-card1-feature-card" v-bind:class="rootClassName">
    <h2 class="feature-card1-text">{{ title }}</h2>
    <img :alt="imageAlt" :src="imageSrc" class="feature-card1-image" />
  </div>
</template>

<script>
export default {
  name: 'FeatureCard1',
  props: {
    imageSrc: {
      type: String,
      default:
        'https://images.unsplash.com/photo-1512295767273-ac109ac3acfa?ixid=Mnw5MTMyMXwwfDF8c2VhcmNofDF8fHllbGxvdyUyMHRlY2h8ZW58MHx8fHwxNjI2MjU1NDk0&ixlib=rb-1.2.1&w=1000',
    },
    imageAlt: {
      type: String,
      default: 'image',
    },
    title: {
      type: String,
      default: 'Names and Binding',
    },
    rootClassName: String,
  },
}
</script>

<style scoped>
.feature-card1-feature-card {
  width: 100%;
  display: flex;
  padding: var(--dl-space-space-unit);
  max-width: var(--dl-size-size-maxwidth);
  box-shadow: 5px 5px 10px 0px rgba(18, 18, 18, 0.1);
  transition: 0.3s;
  align-items: flex-start;
  flex-direction: column;
  justify-content: flex-start;
}
.feature-card1-feature-card:hover {
  transform: scale(1.02);
}
.feature-card1-text {
  margin-bottom: var(--dl-space-space-twounits);
}
.feature-card1-image {
  width: var(--dl-size-size-medium);
  height: var(--dl-size-size-medium);
  object-fit: cover;
  border-radius: var(--dl-radius-radius-radius4);
}
</style>
