// [Vue] Website Source Code/src/views/basic-py-3bii.vue
<template>
  <div class="basic-py3bii-container">
    <div class="basic-py3bii-banner">
      <div class="basic-py3bii-main-content">
        <h1 class="basic-py3bii-heading">CONTROL STRUCTURE</h1>
        <div class="basic-py3bii-container1">
          <router-link to="/basic-py-3ai" class="basic-py3bii-navlink button">
            Selection Statement
          </router-link>
          <router-link to="/basic-py-3aii" class="basic-py3bii-navlink1 button">
            Two-way Selectors
          </router-link>
          <router-link to="/basic-py-3aiii" class="basic-py3bii-navlink2 button">
            Multiple-way Selectors
          </router-link>
        </div>
        <div class="basic-py3bii-container2">
          <router-link to="/basic-py-3bi" class="basic-py3bii-navlink3 button">
            Counter-Controlled Loops
          </router-link>
          <router-link to="/basic-py-3bii" class="basic-py3bii-navlink4 button">
            Logically-Controlled Loops
          </router-link>
        </div>
        <div class="basic-py3bii-content-here">
          <h1 class="basic-py3bii-text">
            <span>Logically-Controlled Loop</span>
            <br />
          </h1>
          <span class="basic-py3bii-text03">
            <span class="basic-py3bii-text04">
              While loop is a control flow statement that allows code to be
              executed repeatedly based on a given Boolean condition. It is a
              logically-controlled loop that repeats until a specific condition is
              met. The condition is usually expressed as a Boolean expression that
              is evaluated at the beginning of each iteration of the loop.
            </span>
            <br class="basic-py3bii-text05" />
            <span class="basic-py3bii-text06">
              Here is an example of a while loop in Python:
            </span>
            <br class="basic-py3bii-text07" />
            <br class="basic-py3bii-text08" />
          </span>
          <div class="basic-py3bii-container3">
            <img
              alt="image"
              src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/3b%20Control%20Structure_Hapih/120EA66C-DEFC-40DA-9B87-D13BCDCC7220.jpeg?raw=true"
              class="basic-py3bii-image"
            />
            <div class="basic-py3bii-column">
              <span class="basic-py3bii-text09">
                This code is a simple program that prompts the user to enter their
                age and checks if the input is a valid number. A while loop is
                used to repeatedly prompt the user to enter their age until they
                enter a valid number. Inside the loop, the isdigit() method is
                used to check if the user’s input is a valid number. When the user
                enters a valid number, the loop is exited and the user’s age is
                printed.
              </span>
              <span class="basic-py3bii-text10">
                <span>
                  This code is a simple number guessing game that generates a
                  random number between 1 and 10 and prompts the user to guess the
                  number. The guess variable is initialized to 0 and a while loop
                  is used to repeatedly prompt the user to guess the number until
                  they guess correctly.
                  <span v-html="rawx0r4"></span>
                </span>
                <span>
                  Inside the loop, an if statement is used to check if the user’s
                  guess is too low or too high compared to the randomly generated
                  number. When the user guesses the correct number, the loop is
                  exited and a congratulatory message is printed. 
                </span>
                <br />
                <br />
                <br />
              </span>
            </div>
          </div>
          <span class="basic-py3bii-text16">
            <span>
              -
              <span v-html="rawpziz"></span>
            </span>
            <span class="basic-py3bii-text18">Muhammad Hafiz</span>
          </span>
        </div>
      </div>
    </div>
    <div class="basic-py3bii-reference">
      <h1 class="basic-py3bii-text19">References</h1>
      <span class="basic-py3bii-text20">
        <br class="basic-py3bii-text21" />
        <span class="basic-py3bii-text22">
          Python while loop (With examples).
        </span>
        <span class="basic-py3bii-text23">
          (n.d.). Programiz: Learn to Code for Free.
        </span>
        <br class="basic-py3bii-text24" />
        <span class="basic-py3bii-text25">
                 
          <span v-html="rawpbeg"></span>
        </span>
        <a
          href="https://www.programiz.com/python-programming/while-loop"
          target="_blank"
          rel="noreferrer noopener"
          class="basic-py3bii-link"
        >
          https://www.programiz.com/python-programming/while-loop
        </a>
        <br class="basic-py3bii-text26" />
        <br class="basic-py3bii-text27" />
        <span class="basic-py3bii-text28">
          Bonthu, H. (2023, April 26).
          <span v-html="rawvqmw"></span>
        </span>
        <span class="basic-py3bii-text29">
          Master control statements in Python with examples (Updated 2023).
        </span>
        <span class="basic-py3bii-text30">Analytics Vidhya.</span>
        <br class="basic-py3bii-text31" />
        <span class="basic-py3bii-text32">
                 
          <span v-html="rawvtn5"></span>
        </span>
        <a
          href="https://www.analyticsvidhya.com/blog/2021/09/loops-and-control-statements-an-in-depth-python-tutorial/"
          target="_blank"
          rel="noreferrer noopener"
          class="basic-py3bii-link1"
        >
          https://www.analyticsvidhya.com/blog/2021/09/loops-and-control-statements-an-in-depth-python-tutorial/
        </a>
        <br class="basic-py3bii-text33" />
        <br class="basic-py3bii-text34" />
        <span class="basic-py3bii-text35">Python iterative statements.</span>
        <span class="basic-py3bii-text36">
          (2018, December 15). Python Class Room Diary.
        </span>
        <br class="basic-py3bii-text37" />
        <span class="basic-py3bii-text38">
                 
          <span v-html="raw5cpl"></span>
        </span>
        <a
          href="https://pythonclassroomdiary.in/python-notes-printed/python-iterative-statements/"
          target="_blank"
          rel="noreferrer noopener"
          class="basic-py3bii-link2"
        >
          https://pythonclassroomdiary.in/python-notes-printed/python-iterative-statements/
        </a>
        <br />
      </span>
    </div>
    <footer class="basic-py3bii-footer">
      <div class="basic-py3bii-container4">
        <router-link to="/strace" class="basic-py3bii-navlink5">
          STRACE
        </router-link>
      </div>
      <span class="basic-py3bii-text40">
        &quot;Making System Calls Cool Again&quot;
      </span>
      <div class="basic-py3bii-icon-group">
        <svg viewBox="0 0 877.7142857142857 1024" class="basic-py3bii-icon">
          <path
            d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
          ></path>
        </svg>
      </div>
    </footer>
    <app-header></app-header>
  </div>
</template>

<script>
import AppHeader from '../components/header'

export default {
  name: 'BasicPy3bii',
  props: {},
  components: {
    AppHeader,
  },
  data() {
    return {
      rawx0r4: ' ',
      rawpziz: ' ',
      rawpbeg: ' ',
      rawvqmw: ' ',
      rawvtn5: ' ',
      raw5cpl: ' ',
    }
  },
  metaInfo: {
    title: 'Strace | Basic Python',
    meta: [
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ],
  },
}
</script>

<style scoped>
.basic-py3bii-container {
  width: 100%;
  display: flex;
  overflow: auto;
  min-height: 100vh;
  align-items: center;
  flex-direction: column;
  justify-content: flex-start;
  background-color: #f5f5f5;
}
.basic-py3bii-banner {
  width: 100%;
  height: 275px;
  display: flex;
  transition: 0.3s;
  align-items: center;
  flex-direction: column;
  background-size: cover;
  justify-content: center;
  background-image: url('https://marketplace.canva.com/EAD2962NKnQ/2/0/1600w/canva-rainbow-gradient-pink-and-purple-virtual-background-_Tcjok-d9b4.jpg');
}

.basic-py3bii-main-content {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: flex-start;
  background-color: #ffffff;
}
.basic-py3bii-heading {
  color: #ff0000;
  font-size: 3rem;
  align-self: center;
  text-align: center;
}
.basic-py3bii-container1 {
  flex: 0 0 auto;
  width: 100%;
  height: 100px;
  display: flex;
  align-items: flex-start;
}
.basic-py3bii-navlink {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py3bii-navlink:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py3bii-navlink1 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py3bii-navlink1:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py3bii-navlink2 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py3bii-navlink2:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py3bii-container2 {
  flex: 0 0 auto;
  width: 100%;
  height: 100px;
  display: flex;
  align-items: flex-start;
}
.basic-py3bii-navlink3 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py3bii-navlink3:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py3bii-navlink4 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py3bii-navlink4:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py3bii-content-here {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.basic-py3bii-text03 {
  text-align: justify;
}
.basic-py3bii-container3 {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.basic-py3bii-image {
  width: 200px;
  object-fit: cover;
}
.basic-py3bii-column {
  flex: 1;
  width: auto;
  height: auto;
  display: flex;
  flex-direction: column;
}
.basic-py3bii-reference {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #ffffff;
}
.basic-py3bii-footer {
  width: 100%;
  display: flex;
  max-width: var(--dl-size-size-maxwidth);
  align-self: center;
  align-items: center;
  padding-top: var(--dl-space-space-twounits);
  padding-left: var(--dl-space-space-threeunits);
  padding-right: var(--dl-space-space-threeunits);
  padding-bottom: var(--dl-space-space-twounits);
  justify-content: space-between;
}
.basic-py3bii-container4 {
  flex: 0 0 auto;
  width: auto;
  height: auto;
  display: flex;
  align-items: space-between;
  flex-direction: column;
}
.basic-py3bii-navlink5 {
  font-weight: 700;
  text-decoration: none;
}
.basic-py3bii-icon {
  width: 24px;
  height: 24px;
}
@media(max-width: 1600px) {
  .basic-py3bii-container {
    background-color: #f7f7f7;
  }
  .basic-py3bii-banner {
    height: auto;
    align-items: center;
    background-size: cover;
    justify-content: flex-start;
    background-image: url("/external/bgportrait-1500w.jpg");
  }
  .basic-py3bii-main-content {
    flex: 1;
    width: 1300px;
    height: auto;
    box-shadow: 0px 0px 10px 0px #d3d2d6;
    align-items: flex-start;
    padding-top: 100px;
    flex-direction: column;
    justify-content: flex-start;
    background-color: #ffffff;
  }
  .basic-py3bii-heading {
    color: rgb(255, 255, 255);
    width: 1200px;
    height: auto;
    font-size: 64px;
    font-style: normal;
    margin-top: 40px;
    font-family: Montserrat;
    font-weight: 700;
    line-height: 1.15;
    padding-top: 40px;
    border-radius: var(--dl-radius-radius-radius4);
    margin-bottom: 20px;
    padding-bottom: 40px;
    background-size: cover;
    background-image: url("/external/bglandscape-1200w.jpg");
    background-position: right;
  }
  .basic-py3bii-container1 {
    width: 700px;
    height: auto;
    align-self: center;
    margin-left: 50px;
    padding-top: 20px;
    margin-right: 50px;
    padding-bottom: 10px;
    justify-content: center;
  }
  .basic-py3bii-navlink {
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py3bii-navlink1 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py3bii-navlink2 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py3bii-container2 {
    width: 800px;
    height: auto;
    align-self: center;
    margin-left: 50px;
    padding-top: 10px;
    margin-right: 50px;
    padding-bottom: 20px;
    justify-content: center;
  }
  .basic-py3bii-navlink3 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py3bii-navlink4 {
    color: #A068FF;
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py3bii-content-here {
    width: 1200px;
    height: auto;
    align-self: flex-start;
    align-items: flex-end;
    margin-left: 50px;
    padding-top: 50px;
    margin-right: 50px;
    padding-bottom: 50px;
  }
  .basic-py3bii-text {
    font-size: 36px;
    align-self: flex-start;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
    padding-top: 0px;
    padding-left: 0px;
    padding-right: 0px;
    padding-bottom: 30px;
  }
  .basic-py3bii-text03 {
    font-size: 16px;
    align-self: flex-start;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
  }
  .basic-py3bii-text04 {
    text-transform: inherit;
  }
  .basic-py3bii-text05 {
    text-transform: inherit;
  }
  .basic-py3bii-text06 {
    text-transform: inherit;
  }
  .basic-py3bii-text07 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    text-transform: inherit;
  }
  .basic-py3bii-text08 {
    text-transform: uppercase;
  }
  .basic-py3bii-container3 {
    align-self: flex-start;
    align-items: flex-end;
    justify-content: flex-start;
  }
  .basic-py3bii-image {
    width: 438px;
    height: 423px;
    align-self: flex-start;
    margin-left: 0px;
    margin-right: 0px;
  }
  .basic-py3bii-column {
    flex: 1;
    width: 100%;
    align-items: flex-start;
  }
  .basic-py3bii-text09 {
    font-size: 16px;
    align-self: center;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-left: var(--dl-space-space-fourunits);
    margin-bottom: 75px;
  }
  .basic-py3bii-text10 {
    font-size: 16px;
    align-self: stretch;
    font-style: normal;
    margin-top: 50px;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    margin-left: 0px;
    padding-left: var(--dl-space-space-fourunits);
  }
  .basic-py3bii-text16 {
    font-size: 18px;
    font-style: normal;
    font-family: Inter;
    font-weight: 500;
    padding-top: 25px;
  }
  .basic-py3bii-text18 {
    font-style: italic;
  }
  .basic-py3bii-reference {
    width: 1600px;
    height: auto;
    align-self: center;
    box-shadow: 0px -1px 15px 0px #ebebeb;
    align-items: flex-start;
    padding-top: 50px;
    padding-left: 200px;
    padding-right: 200px;
    flex-direction: column;
    padding-bottom: 50px;
    justify-content: flex-start;
  }
  .basic-py3bii-text19 {
    font-size: 32px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
  }
  .basic-py3bii-text20 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.25;
  }
  .basic-py3bii-text21 {
    font-size: 16px;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py3bii-text22 {
    font-size: 16px;
    font-style: italic;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py3bii-text23 {
    font-size: 16px;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py3bii-text24 {
    font-size: 16px;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py3bii-text25 {
    font-size: 16px;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py3bii-link {
    color: var(--dl-color-primary-300);
    font-size: 16px;
    font-family: Inter;
    font-weight: 400;
    text-decoration: underline;
  }
  .basic-py3bii-text26 {
    font-size: 16px;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py3bii-text27 {
    font-size: 16px;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py3bii-text28 {
    font-size: 16px;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py3bii-text29 {
    font-size: 16px;
    font-style: italic;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py3bii-text30 {
    font-size: 16px;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py3bii-text31 {
    font-size: 16px;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py3bii-text32 {
    font-size: 16px;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py3bii-link1 {
    color: var(--dl-color-primary-300);
    font-size: 16px;
    font-family: Inter;
    font-weight: 400;
    text-decoration: underline;
  }
  .basic-py3bii-text33 {
    font-size: 16px;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py3bii-text34 {
    font-size: 16px;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py3bii-text35 {
    font-size: 16px;
    font-style: italic;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py3bii-text36 {
    font-size: 16px;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py3bii-text37 {
    font-size: 16px;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py3bii-text38 {
    font-size: 16px;
    font-family: Inter;
    font-weight: 400;
  }
  .basic-py3bii-link2 {
    color: var(--dl-color-primary-300);
    font-size: 16px;
    font-family: Inter;
    font-weight: 400;
    text-decoration: underline;
  }
  .basic-py3bii-footer {
    justify-content: space-between;
  }
  .basic-py3bii-navlink5 {
    font-size: 16px;
    font-family: Montserrat;
    font-weight: 700;
    text-decoration: none;
  }
  .basic-py3bii-text40 {
    font-size: 16px;
    font-style: normal;
    font-family: Montserrat;
    font-weight: 500;
  }
  .basic-py3bii-icon {
    margin-left: 50px;
  }
}
@media(max-width: 1200px) {
  .basic-py3bii-heading {
    color: rgb(255, 255, 255);
  }
}
@media(max-width: 479px) {
  .basic-py3bii-footer {
    align-self: center;
  }
  .basic-py3bii-icon-group {
    display: none;
  }
}
</style>

// [Angular] Website Source Code/src/app/pages/basic-py-3bii/basic-py-3bii.component.ts
import { Component } from '@angular/core'
import { Title, Meta } from '@angular/platform-browser'

@Component({
  selector: 'basic-py3bii',
  templateUrl: 'basic-py-3bii.component.html',
  styleUrls: ['basic-py-3bii.component.css'],
})
export class BasicPy3bii {
  rawk8n8: string = ' '
  rawtv20: string = ' '
  rawpadj: string = ' '
  rawsw66: string = ' '
  rawstxa: string = ' '
  rawnxiu: string = ' '
  constructor(private title: Title, private meta: Meta) {
    this.title.setTitle('Strace | Basic Python')
    this.meta.addTags([
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ])
  }
}

<div class="basic-py3bii-container">
  <div class="basic-py3bii-banner">
    <div class="basic-py3bii-main-content">
      <h1 class="basic-py3bii-heading">CONTROL STRUCTURE</h1>
      <div class="basic-py3bii-container1">
        <a routerLink="/basic-py-3ai" class="basic-py3bii-navlink button">
          Selection Statement
        </a>
        <a routerLink="/basic-py-3aii" class="basic-py3bii-navlink1 button">
          Two-way Selectors
        </a>
        <a routerLink="/basic-py-3aiii" class="basic-py3bii-navlink2 button">
          Multiple-way Selectors
        </a>
      </div>
      <div class="basic-py3bii-container2">
        <a routerLink="/basic-py-3bi" class="basic-py3bii-navlink3 button">
          Counter-Controlled Loops
        </a>
        <a routerLink="/basic-py-3bii" class="basic-py3bii-navlink4 button">
          Logically-Controlled Loops
        </a>
      </div>
      <div class="basic-py3bii-content-here">
        <h1 class="basic-py3bii-text">
          <span>Logically-Controlled Loop</span>
          <br />
        </h1>
        <span class="basic-py3bii-text03">
          <span class="basic-py3bii-text04">
            While loop is a control flow statement that allows code to be
            executed repeatedly based on a given Boolean condition. It is a
            logically-controlled loop that repeats until a specific condition is
            met. The condition is usually expressed as a Boolean expression that
            is evaluated at the beginning of each iteration of the loop.
          </span>
          <br class="basic-py3bii-text05" />
          <span class="basic-py3bii-text06">
            Here is an example of a while loop in Python:
          </span>
          <br class="basic-py3bii-text07" />
          <br class="basic-py3bii-text08" />
        </span>
        <div class="basic-py3bii-container3">
          <img
            alt="image"
            src="https://github.com/rydzze/TPL6213-Project/blob/main/IMG_SRC_WebReport/2%20-%20Basic%20Element%20of%20Python/3b%20Control%20Structure_Hapih/120EA66C-DEFC-40DA-9B87-D13BCDCC7220.jpeg?raw=true"
            class="basic-py3bii-image"
          />
          <div class="basic-py3bii-column">
            <span class="basic-py3bii-text09">
              This code is a simple program that prompts the user to enter their
              age and checks if the input is a valid number. A while loop is
              used to repeatedly prompt the user to enter their age until they
              enter a valid number. Inside the loop, the isdigit() method is
              used to check if the user’s input is a valid number. When the user
              enters a valid number, the loop is exited and the user’s age is
              printed.
            </span>
            <span class="basic-py3bii-text10">
              <span>
                This code is a simple number guessing game that generates a
                random number between 1 and 10 and prompts the user to guess the
                number. The guess variable is initialized to 0 and a while loop
                is used to repeatedly prompt the user to guess the number until
                they guess correctly.
                <span [innerHTML]="rawk8n8"></span>
              </span>
              <span>
                Inside the loop, an if statement is used to check if the user’s
                guess is too low or too high compared to the randomly generated
                number. When the user guesses the correct number, the loop is
                exited and a congratulatory message is printed. 
              </span>
              <br />
              <br />
              <br />
            </span>
          </div>
        </div>
        <span class="basic-py3bii-text16">
          <span>
            -
            <span [innerHTML]="rawtv20"></span>
          </span>
          <span class="basic-py3bii-text18">Muhammad Hafiz</span>
        </span>
      </div>
    </div>
  </div>
  <div class="basic-py3bii-reference">
    <h1 class="basic-py3bii-text19">References</h1>
    <span class="basic-py3bii-text20">
      <br class="basic-py3bii-text21" />
      <span class="basic-py3bii-text22">
        Python while loop (With examples).
      </span>
      <span class="basic-py3bii-text23">
        (n.d.). Programiz: Learn to Code for Free.
      </span>
      <br class="basic-py3bii-text24" />
      <span class="basic-py3bii-text25">
               
        <span [innerHTML]="rawpadj"></span>
      </span>
      <a
        href="https://www.programiz.com/python-programming/while-loop"
        target="_blank"
        rel="noreferrer noopener"
        class="basic-py3bii-link"
      >
        https://www.programiz.com/python-programming/while-loop
      </a>
      <br class="basic-py3bii-text26" />
      <br class="basic-py3bii-text27" />
      <span class="basic-py3bii-text28">
        Bonthu, H. (2023, April 26).
        <span [innerHTML]="rawsw66"></span>
      </span>
      <span class="basic-py3bii-text29">
        Master control statements in Python with examples (Updated 2023).
      </span>
      <span class="basic-py3bii-text30">Analytics Vidhya.</span>
      <br class="basic-py3bii-text31" />
      <span class="basic-py3bii-text32">
               
        <span [innerHTML]="rawstxa"></span>
      </span>
      <a
        href="https://www.analyticsvidhya.com/blog/2021/09/loops-and-control-statements-an-in-depth-python-tutorial/"
        target="_blank"
        rel="noreferrer noopener"
        class="basic-py3bii-link1"
      >
        https://www.analyticsvidhya.com/blog/2021/09/loops-and-control-statements-an-in-depth-python-tutorial/
      </a>
      <br class="basic-py3bii-text33" />
      <br class="basic-py3bii-text34" />
      <span class="basic-py3bii-text35">Python iterative statements.</span>
      <span class="basic-py3bii-text36">
        (2018, December 15). Python Class Room Diary.
      </span>
      <br class="basic-py3bii-text37" />
      <span class="basic-py3bii-text38">
               
        <span [innerHTML]="rawnxiu"></span>
      </span>
      <a
        href="https://pythonclassroomdiary.in/python-notes-printed/python-iterative-statements/"
        target="_blank"
        rel="noreferrer noopener"
        class="basic-py3bii-link2"
      >
        https://pythonclassroomdiary.in/python-notes-printed/python-iterative-statements/
      </a>
      <br />
    </span>
  </div>
  <footer class="basic-py3bii-footer">
    <div class="basic-py3bii-container4">
      <a routerLink="/strace" class="basic-py3bii-navlink5">STRACE</a>
    </div>
    <span class="basic-py3bii-text40">
      &quot;Making System Calls Cool Again&quot;
    </span>
    <div class="basic-py3bii-icon-group">
      <svg viewBox="0 0 877.7142857142857 1024" class="basic-py3bii-icon">
        <path
          d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
        ></path>
      </svg>
    </div>
  </footer>
  <app-header></app-header>
</div>
