// [Vue] Website Source Code/src/views/bg-1.vue
<template>
  <div class="bg1-container">
    <div class="bg1-banner">
      <div class="bg1-main-content">
        <h1 class="bg1-heading">ORIGIN OF PYTHON AND DJANGO</h1>
        <div class="bg1-num1-hafiz-punya">
          <div class="bg1-python">
            <div class="bg1-container1">
              <div class="bg1-container2">
                <img
                  alt="image"
                  src="https://i.pinimg.com/564x/04/4f/72/044f7201f7b3c5fb1520c07ae3566988.jpg"
                  loading="eager"
                  class="bg1-image"
                />
                <span class="bg1-text">
                  <span class="bg1-text01">Python</span>
                  <span>
                    , whose name taken from BBC&apos;s Monty Python&apos;s Flying
                    Circus TV show started as a hobby project during Christmas. It
                    was created by
                    <span v-html="rawxh00"></span>
                  </span>
                  <span class="bg1-text03">
                    Guido van Rossum
                    <span v-html="raw2nub"></span>
                  </span>
                  <span>
                    at the Centrum Wiskunde &amp; Informatica (CWI) as a successor
                    to ABC with exception capabilities and interfacing with the
                    Amoeba OS which he help created.
                  </span>
                  <br />
                  <br />
                  <span>
                    Taking the syntax of ABC and some of its good features. He
                    created a good scripting language.
                  </span>
                </span>
              </div>
            </div>
            <div class="bg1-container3">
              <img
                alt="image"
                src="https://aem.dropbox.com/cms/content/dam/dropbox/blog/files/2019/11/guido_hero.jpg"
                loading="eager"
                class="bg1-image1"
              />
              <span class="bg1-text08">
                <span>The Creator of Pythom, Guido van Rossum, </span>
                <span>Illustration</span>
                <br />
                <span>by </span>
                <span>Fanny Luor | Image </span>
                <span>
                  Source:
                  <span v-html="rawqsym"></span>
                </span>
                <a
                  href="https://blog.dropbox.com/topics/work-culture/-the-mind-at-work--guido-van-rossum-on-how-python-makes-thinking"
                  target="_blank"
                  rel="noreferrer noopener"
                  class="bg1-link"
                >
                  Dropbox Blog
                </a>
                <br />
              </span>
            </div>
          </div>
          <div class="bg1-container4"></div>
          <div class="bg1-django">
            <div class="bg1-container5">
              <img
                alt="image"
                src="https://i.pinimg.com/564x/47/dd/d4/47ddd4f77693d99357d9bc2816d9b3cb.jpg"
                loading="eager"
                class="bg1-image2"
              />
              <span class="bg1-text16">
                <span class="bg1-text17">
                  Django
                  <span v-html="rawimao"></span>
                </span>
                <span>
                  stylised as Django is a free and open-source, high-level
                  Python-based web framework.
                </span>
                <br />
                <br class="bg1-text20" />
                <span>
                  Created in 2003 by
                  <span v-html="rawtv4k"></span>
                </span>
                <span class="bg1-text22">
                  a group of web programmers
                  <span v-html="rawe4hj"></span>
                </span>
                <span>
                  responsible for creating and maintaining newspaper websites at
                  the
                  <span v-html="raw5adn"></span>
                </span>
                <span class="bg1-text24">
                  Lawrence Journal-World
                  <span v-html="rawtr9z"></span>
                </span>
                <span>newspaper.</span>
                <br />
                <br class="bg1-text27" />
                <span>
                  The web framework for perfectionists with deadlines. As the
                  Django&apos;s tagline suggests, the framework is built to be
                  more efficient so you can build your powerful websites
                  hassle-free.
                </span>
                <br />
              </span>
            </div>
            <div class="bg1-container6">
              <div class="bg1-container7">
                <img
                  alt="image"
                  src="https://pbs.twimg.com/profile_images/643261843054555136/IK7URL7S_200x200.png"
                  loading="lazy"
                  class="bg1-image3"
                />
                <img
                  alt="image"
                  src="https://upload.wikimedia.org/wikipedia/commons/6/6c/Simon_Willison_%282929211382%29_%28cropped%29.jpg"
                  loading="lazy"
                  class="bg1-image4"
                />
              </div>
              <span class="bg1-text30">
                <span>Adrian Holovaty and Simon Willison, </span>
                <span>Django&apos;s</span>
                <br />
                <span>Creators </span>
                <span>
                  | Image Source:
                  <span v-html="rawdyym"></span>
                </span>
                <a
                  href="https://twitter.com/adrianholovaty"
                  target="_blank"
                  rel="noreferrer noopener"
                  class="bg1-link1"
                >
                  X
                </a>
                <span>
                  and
                  <span v-html="rawl5ez"></span>
                </span>
                <a
                  href="https://en.wikipedia.org/wiki/Simon_Willison"
                  target="_blank"
                  rel="noreferrer noopener"
                  class="bg1-link2"
                >
                  Wikipedia
                </a>
              </span>
            </div>
          </div>
          <span class="bg1-text37">
            Django was designed to encourage rapid development and clean,
            pragmatic design. Its primary goal is to ease the creation of complex,
            database-driven websites. The framework emphasizes reusability and
            &quot;pluggability&quot; of components, less code, low coupling, rapid
            development, and the principle of don&apos;t repeat yourself.
          </span>
          <span class="bg1-text38">
            <span>
              -
              <span v-html="rawse9s"></span>
            </span>
            <span class="bg1-text40">Muhammad Hafiz</span>
          </span>
        </div>
      </div>
    </div>
    <div class="bg1-reference">
      <h1 class="bg1-text41">References</h1>
      <span class="bg1-text42">
        <br class="bg1-text43" />
        <span class="bg1-text44">
          Stieg, C. (2023, February 20).
          <span v-html="rawgveh"></span>
        </span>
        <span class="bg1-text45">
          When Was Python Created? History of Python Programming Language
        </span>
        <span class="bg1-text46">. Codecademy Blog.</span>
        <br class="bg1-text47" />
        <span class="bg1-text48">
                 
          <span v-html="raw4d32"></span>
        </span>
        <a
          href="https://Stieg, C. (2023, February 20). When Was Python Created? History of Python Programming Language. Codecademy Blog. https://www.codecademy.com/resources/blog/history-of-python-coding-language/"
          target="_blank"
          rel="noreferrer noopener"
          class="bg1-link3"
        >
          https://www.codecademy.com/resources/blog/history-of-python-coding-language/
        </a>
        <br class="bg1-text49" />
        <br class="bg1-text50" />
        <span class="bg1-text51">
          Silva, P. A. (2023, June 8).
          <span v-html="rawlprr"></span>
        </span>
        <span class="bg1-text52">
          Understanding Django: A Journey Through Its History
        </span>
        <span class="bg1-text53">. Medium.</span>
        <br class="bg1-text54" />
        <span class="bg1-text55">
                 
          <span v-html="rawxurx"></span>
        </span>
        <a
          href="https://Silva, P. A. (2023, June 8). Understanding Django: A Journey Through Its History. Medium. https://medium.com/@pedroanisio_80550/understanding-django-a-journey-through-its-history-23c8ce4350a3"
          target="_blank"
          rel="noreferrer noopener"
          class="bg1-link4"
        >
          https://medium.com/@pedroanisio_80550/understanding-django-a-journey-through-its-history-23c8ce4350a3
        </a>
        <br />
      </span>
    </div>
    <footer class="bg1-footer">
      <div class="bg1-container8">
        <router-link to="/strace" class="bg1-navlink">STRACE</router-link>
      </div>
      <span class="bg1-text57">&quot;Making System Calls Cool Again&quot;</span>
      <div class="bg1-icon-group">
        <svg viewBox="0 0 877.7142857142857 1024" class="bg1-icon">
          <path
            d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
          ></path>
        </svg>
      </div>
    </footer>
    <app-header rootClassName="header-root-class-name"></app-header>
  </div>
</template>

<script>
import AppHeader from '../components/header'

export default {
  name: 'Bg1',
  props: {},
  components: {
    AppHeader,
  },
  data() {
    return {
      rawxh00: ' ',
      raw2nub: ' ',
      rawqsym: ' ',
      rawimao: ' ',
      rawtv4k: ' ',
      rawe4hj: ' ',
      raw5adn: ' ',
      rawtr9z: ' ',
      rawdyym: ' ',
      rawl5ez: ' ',
      rawse9s: ' ',
      rawgveh: ' ',
      raw4d32: ' ',
      rawlprr: ' ',
      rawxurx: ' ',
    }
  },
  metaInfo: {
    title: 'Strace | Background',
    meta: [
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ],
  },
}
</script>

<style scoped>
.bg1-container {
  width: 100%;
  display: flex;
  overflow: auto;
  min-height: 100vh;
  align-items: center;
  flex-direction: column;
  justify-content: flex-start;
  background-color: #f5f5f5;
}
.bg1-banner {
  width: 100%;
  height: 275px;
  display: flex;
  transition: 0.3s;
  align-items: center;
  flex-direction: column;
  background-size: cover;
  justify-content: center;
  background-image: url('https://marketplace.canva.com/EAD2962NKnQ/2/0/1600w/canva-rainbow-gradient-pink-and-purple-virtual-background-_Tcjok-d9b4.jpg');
}

.bg1-main-content {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: flex-start;
  background-color: #ffffff;
}
.bg1-heading {
  color: #ff0000;
  font-size: 3rem;
  align-self: center;
  text-align: center;
}
.bg1-num1-hafiz-punya {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.bg1-python {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.bg1-container1 {
  flex: 0 0 auto;
  width: 200px;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.bg1-container2 {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.bg1-image {
  width: 200px;
  object-fit: cover;
}
.bg1-container3 {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.bg1-image1 {
  width: 200px;
  object-fit: cover;
}
.bg1-container4 {
  flex: 0 0 auto;
  width: 100%;
  border: 2px dashed rgba(120, 120, 120, 0.4);
  height: 100px;
  display: flex;
  align-items: flex-start;
}
.bg1-django {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.bg1-container5 {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.bg1-image2 {
  width: 200px;
  object-fit: cover;
}
.bg1-text16 {
  font-size: 16px;
  font-style: normal;
  text-align: justify;
  font-family: "Inter";
  font-weight: 400;
  line-height: 1.15;
}
.bg1-container6 {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.bg1-container7 {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.bg1-image3 {
  width: 200px;
  object-fit: cover;
}
.bg1-image4 {
  width: 200px;
  object-fit: cover;
}
.bg1-reference {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #ffffff;
}
.bg1-footer {
  width: 100%;
  display: flex;
  max-width: var(--dl-size-size-maxwidth);
  align-self: center;
  align-items: center;
  padding-top: var(--dl-space-space-twounits);
  padding-left: var(--dl-space-space-threeunits);
  padding-right: var(--dl-space-space-threeunits);
  padding-bottom: var(--dl-space-space-twounits);
  justify-content: space-between;
}
.bg1-container8 {
  flex: 0 0 auto;
  width: auto;
  height: auto;
  display: flex;
  align-items: space-between;
  flex-direction: column;
}
.bg1-navlink {
  font-weight: 700;
  text-decoration: none;
}
.bg1-icon {
  width: 24px;
  height: 24px;
}
@media(max-width: 1600px) {
  .bg1-container {
    background-color: #f7f7f7;
  }
  .bg1-banner {
    height: auto;
    align-items: center;
    background-size: cover;
    justify-content: flex-start;
    background-image: url("/external/bgportrait-1500w.jpg");
  }
  .bg1-main-content {
    flex: 1;
    width: 1300px;
    height: auto;
    box-shadow: 0px 0px 10px 0px #d3d2d6;
    align-items: flex-start;
    padding-top: 100px;
    border-radius: var(--dl-radius-radius-radius8);
    flex-direction: column;
    justify-content: flex-start;
    background-color: #ffffff;
    border-bottom-left-radius: 0;
    border-bottom-right-radius: 0;
  }
  .bg1-heading {
    color: rgb(255, 255, 255);
    width: 1200px;
    height: auto;
    font-size: 64px;
    font-style: normal;
    margin-top: 25px;
    font-family: Montserrat;
    font-weight: 700;
    line-height: 1.15;
    padding-top: 40px;
    border-radius: var(--dl-radius-radius-radius4);
    margin-bottom: 15px;
    padding-bottom: 40px;
    background-image: url("/external/bglandscape-1200w.jpg");
    background-position: top;
  }
  .bg1-num1-hafiz-punya {
    width: 1200px;
    align-items: flex-end;
    margin-left: 50px;
    padding-top: 50px;
    margin-right: 50px;
    padding-bottom: 50px;
  }
  .bg1-python {
    align-items: center;
  }
  .bg1-container1 {
    flex: 1;
  }
  .bg1-container2 {
    height: auto;
    align-items: center;
  }
  .bg1-image {
    width: 210px;
    height: 210px;
  }
  .bg1-text {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.25;
    padding-left: var(--dl-space-space-fourunits);
    padding-right: var(--dl-space-space-fourunits);
  }
  .bg1-text01 {
    font-weight: 700;
  }
  .bg1-text03 {
    font-weight: 700;
  }
  .bg1-container3 {
    align-items: center;
  }
  .bg1-image1 {
    width: 250px;
    height: 204px;
    border-radius: var(--dl-radius-radius-radius8);
    margin-bottom: 10px;
  }
  .bg1-text08 {
    font-size: 14px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.25;
  }
  .bg1-link {
    color: #004eff;
  }
  .bg1-container4 {
    height: 100px;
    border-style: hidden;
  }
  .bg1-django {
    align-items: center;
  }
  .bg1-container5 {
    flex: 1;
    width: auto;
    height: auto;
    flex-direction: row;
    justify-content: flex-start;
  }
  .bg1-image2 {
    width: 210px;
    height: 210px;
  }
  .bg1-text16 {
    width: 100%;
    height: 100%;
    font-size: 16px;
    align-self: center;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
    padding-left: var(--dl-space-space-fourunits);
    padding-right: var(--dl-space-space-fourunits);
  }
  .bg1-text17 {
    font-weight: 700;
  }
  .bg1-text20 {
    text-align: justify;
    padding-right: 50px;
  }
  .bg1-text22 {
    font-weight: 700;
  }
  .bg1-text24 {
    font-weight: 700;
  }
  .bg1-text27 {
    text-align: justify;
    padding-right: 50px;
  }
  .bg1-container6 {
    align-items: center;
  }
  .bg1-container7 {
    margin-bottom: 10px;
    justify-content: center;
  }
  .bg1-image3 {
    width: 180px;
    height: 190px;
    border-top-left-radius: var(--dl-radius-radius-radius8);
    border-bottom-left-radius: var(--dl-radius-radius-radius8);
  }
  .bg1-image4 {
    width: 170px;
    height: 190px;
    border-top-right-radius: var(--dl-radius-radius-radius8);
    border-bottom-right-radius: var(--dl-radius-radius-radius8);
  }
  .bg1-text30 {
    font-size: 14px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.25;
  }
  .bg1-link1 {
    color: var(--dl-color-primary-100);
  }
  .bg1-link2 {
    color: var(--dl-color-primary-100);
  }
  .bg1-text37 {
    font-size: 16px;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.25;
    padding-top: 40px;
    padding-bottom: 10px;
  }
  .bg1-text38 {
    font-size: 18px;
    font-style: normal;
    font-family: Inter;
    font-weight: 500;
    padding-top: 25px;
  }
  .bg1-text40 {
    font-style: italic;
  }
  .bg1-reference {
    width: 1600px;
    height: auto;
    align-self: center;
    box-shadow: 0px -1px 15px 0px #ebebeb;
    align-items: flex-start;
    padding-top: 50px;
    padding-left: 200px;
    padding-right: 200px;
    flex-direction: column;
    padding-bottom: 50px;
    justify-content: flex-start;
  }
  .bg1-text41 {
    font-size: 32px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
  }
  .bg1-text42 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.25;
  }
  .bg1-text43 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .bg1-text44 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .bg1-text45 {
    font-size: 16px;
    font-style: italic;
    font-family: Inter;
    font-weight: 400;
  }
  .bg1-text46 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .bg1-text47 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .bg1-text48 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .bg1-link3 {
    color: var(--dl-color-primary-300);
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    text-decoration: underline;
  }
  .bg1-text49 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .bg1-text50 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .bg1-text51 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .bg1-text52 {
    font-size: 16px;
    font-style: italic;
    font-family: Inter;
    font-weight: 400;
  }
  .bg1-text53 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .bg1-text54 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .bg1-text55 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
  }
  .bg1-link4 {
    color: var(--dl-color-primary-300);
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    text-decoration: underline;
  }
  .bg1-footer {
    justify-content: space-between;
  }
  .bg1-navlink {
    font-size: 16px;
    font-family: Montserrat;
    font-weight: 700;
    text-decoration: none;
  }
  .bg1-text57 {
    font-size: 16px;
    font-style: normal;
    font-family: Montserrat;
    font-weight: 500;
  }
  .bg1-icon {
    margin-left: 50px;
  }
}
@media(max-width: 1200px) {
  .bg1-heading {
    color: rgb(255, 255, 255);
  }
  .bg1-text16 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
  }
}
@media(max-width: 479px) {
  .bg1-footer {
    align-self: center;
  }
  .bg1-icon-group {
    display: none;
  }
}
</style>

// [Angular] Website Source Code/src/app/pages/bg-1/bg-1.component.ts
import { Component } from '@angular/core'
import { Title, Meta } from '@angular/platform-browser'

@Component({
  selector: 'app-bg1',
  templateUrl: 'bg-1.component.html',
  styleUrls: ['bg-1.component.css'],
})
export class Bg1 {
  rawqztp: string = ' '
  rawbce7: string = ' '
  rawpu5a: string = ' '
  raw4ud8: string = ' '
  rawcx5x: string = ' '
  rawd3uf: string = ' '
  rawhhdh: string = ' '
  rawduf8: string = ' '
  rawyzwz: string = ' '
  rawa8ps: string = ' '
  rawnr8c: string = ' '
  rawc640: string = ' '
  rawvnf2: string = ' '
  raw3eny: string = ' '
  raw34wz: string = ' '
  constructor(private title: Title, private meta: Meta) {
    this.title.setTitle('Strace | Background')
    this.meta.addTags([
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ])
  }
}

<div class="bg1-container">
  <div class="bg1-banner">
    <div class="bg1-main-content">
      <h1 class="bg1-heading">ORIGIN OF PYTHON AND DJANGO</h1>
      <div class="bg1-num1-hafiz-punya">
        <div class="bg1-python">
          <div class="bg1-container1">
            <div class="bg1-container2">
              <img
                alt="image"
                src="https://i.pinimg.com/564x/04/4f/72/044f7201f7b3c5fb1520c07ae3566988.jpg"
                loading="eager"
                class="bg1-image"
              />
              <span class="bg1-text">
                <span class="bg1-text01">Python</span>
                <span>
                  , whose name taken from BBC&apos;s Monty Python&apos;s Flying
                  Circus TV show started as a hobby project during Christmas. It
                  was created by
                  <span [innerHTML]="rawqztp"></span>
                </span>
                <span class="bg1-text03">
                  Guido van Rossum
                  <span [innerHTML]="rawbce7"></span>
                </span>
                <span>
                  at the Centrum Wiskunde &amp; Informatica (CWI) as a successor
                  to ABC with exception capabilities and interfacing with the
                  Amoeba OS which he help created.
                </span>
                <br />
                <br />
                <span>
                  Taking the syntax of ABC and some of its good features. He
                  created a good scripting language.
                </span>
              </span>
            </div>
          </div>
          <div class="bg1-container3">
            <img
              alt="image"
              src="https://aem.dropbox.com/cms/content/dam/dropbox/blog/files/2019/11/guido_hero.jpg"
              loading="eager"
              class="bg1-image1"
            />
            <span class="bg1-text08">
              <span>The Creator of Pythom, Guido van Rossum, </span>
              <span>Illustration</span>
              <br />
              <span>by </span>
              <span>Fanny Luor | Image </span>
              <span>
                Source:
                <span [innerHTML]="rawpu5a"></span>
              </span>
              <a
                href="https://blog.dropbox.com/topics/work-culture/-the-mind-at-work--guido-van-rossum-on-how-python-makes-thinking"
                target="_blank"
                rel="noreferrer noopener"
                class="bg1-link"
              >
                Dropbox Blog
              </a>
              <br />
            </span>
          </div>
        </div>
        <div class="bg1-container4"></div>
        <div class="bg1-django">
          <div class="bg1-container5">
            <img
              alt="image"
              src="https://i.pinimg.com/564x/47/dd/d4/47ddd4f77693d99357d9bc2816d9b3cb.jpg"
              loading="eager"
              class="bg1-image2"
            />
            <span class="bg1-text16">
              <span class="bg1-text17">
                Django
                <span [innerHTML]="raw4ud8"></span>
              </span>
              <span>
                stylised as Django is a free and open-source, high-level
                Python-based web framework.
              </span>
              <br />
              <br class="bg1-text20" />
              <span>
                Created in 2003 by
                <span [innerHTML]="rawcx5x"></span>
              </span>
              <span class="bg1-text22">
                a group of web programmers
                <span [innerHTML]="rawd3uf"></span>
              </span>
              <span>
                responsible for creating and maintaining newspaper websites at
                the
                <span [innerHTML]="rawhhdh"></span>
              </span>
              <span class="bg1-text24">
                Lawrence Journal-World
                <span [innerHTML]="rawduf8"></span>
              </span>
              <span>newspaper.</span>
              <br />
              <br class="bg1-text27" />
              <span>
                The web framework for perfectionists with deadlines. As the
                Django&apos;s tagline suggests, the framework is built to be
                more efficient so you can build your powerful websites
                hassle-free.
              </span>
              <br />
            </span>
          </div>
          <div class="bg1-container6">
            <div class="bg1-container7">
              <img
                alt="image"
                src="https://pbs.twimg.com/profile_images/643261843054555136/IK7URL7S_200x200.png"
                loading="lazy"
                class="bg1-image3"
              />
              <img
                alt="image"
                src="https://upload.wikimedia.org/wikipedia/commons/6/6c/Simon_Willison_%282929211382%29_%28cropped%29.jpg"
                loading="lazy"
                class="bg1-image4"
              />
            </div>
            <span class="bg1-text30">
              <span>Adrian Holovaty and Simon Willison, </span>
              <span>Django&apos;s</span>
              <br />
              <span>Creators </span>
              <span>
                | Image Source:
                <span [innerHTML]="rawyzwz"></span>
              </span>
              <a
                href="https://twitter.com/adrianholovaty"
                target="_blank"
                rel="noreferrer noopener"
                class="bg1-link1"
              >
                X
              </a>
              <span>
                and
                <span [innerHTML]="rawa8ps"></span>
              </span>
              <a
                href="https://en.wikipedia.org/wiki/Simon_Willison"
                target="_blank"
                rel="noreferrer noopener"
                class="bg1-link2"
              >
                Wikipedia
              </a>
            </span>
          </div>
        </div>
        <span class="bg1-text37">
          Django was designed to encourage rapid development and clean,
          pragmatic design. Its primary goal is to ease the creation of complex,
          database-driven websites. The framework emphasizes reusability and
          &quot;pluggability&quot; of components, less code, low coupling, rapid
          development, and the principle of don&apos;t repeat yourself.
        </span>
        <span class="bg1-text38">
          <span>
            -
            <span [innerHTML]="rawnr8c"></span>
          </span>
          <span class="bg1-text40">Muhammad Hafiz</span>
        </span>
      </div>
    </div>
  </div>
  <div class="bg1-reference">
    <h1 class="bg1-text41">References</h1>
    <span class="bg1-text42">
      <br class="bg1-text43" />
      <span class="bg1-text44">
        Stieg, C. (2023, February 20).
        <span [innerHTML]="rawc640"></span>
      </span>
      <span class="bg1-text45">
        When Was Python Created? History of Python Programming Language
      </span>
      <span class="bg1-text46">. Codecademy Blog.</span>
      <br class="bg1-text47" />
      <span class="bg1-text48">
               
        <span [innerHTML]="rawvnf2"></span>
      </span>
      <a
        href="https://Stieg, C. (2023, February 20). When Was Python Created? History of Python Programming Language. Codecademy Blog. https://www.codecademy.com/resources/blog/history-of-python-coding-language/"
        target="_blank"
        rel="noreferrer noopener"
        class="bg1-link3"
      >
        https://www.codecademy.com/resources/blog/history-of-python-coding-language/
      </a>
      <br class="bg1-text49" />
      <br class="bg1-text50" />
      <span class="bg1-text51">
        Silva, P. A. (2023, June 8).
        <span [innerHTML]="raw3eny"></span>
      </span>
      <span class="bg1-text52">
        Understanding Django: A Journey Through Its History
      </span>
      <span class="bg1-text53">. Medium.</span>
      <br class="bg1-text54" />
      <span class="bg1-text55">
               
        <span [innerHTML]="raw34wz"></span>
      </span>
      <a
        href="https://Silva, P. A. (2023, June 8). Understanding Django: A Journey Through Its History. Medium. https://medium.com/@pedroanisio_80550/understanding-django-a-journey-through-its-history-23c8ce4350a3"
        target="_blank"
        rel="noreferrer noopener"
        class="bg1-link4"
      >
        https://medium.com/@pedroanisio_80550/understanding-django-a-journey-through-its-history-23c8ce4350a3
      </a>
      <br />
    </span>
  </div>
  <footer class="bg1-footer">
    <div class="bg1-container8">
      <a routerLink="/strace" class="bg1-navlink">STRACE</a>
    </div>
    <span class="bg1-text57">&quot;Making System Calls Cool Again&quot;</span>
    <div class="bg1-icon-group">
      <svg viewBox="0 0 877.7142857142857 1024" class="bg1-icon">
        <path
          d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
        ></path>
      </svg>
    </div>
  </footer>
  <app-header rootClassName="header-root-class-name"></app-header>
</div>
