// [Vue] Website Source Code/src/views/home.vue
<template>
  <div class="home-container">
    <div class="home-banner">
      <div class="home-container1">
        <div class="home-container2">
          <div class="home-container3">
            <header class="home-testimonial-card">
              <h1 class="home-text">STRACE</h1>
              <svg viewBox="0 0 1024 1024" class="home-icon">
                <path
                  d="M800 640c-123.712 0-224-100.29-224-224 0-123.712 100.288-224 224-224s224 100.288 224 224l1 32c0 247.424-200.576 448-448 448v-128c85.474 0 165.834-33.286 226.274-93.726 11.634-11.636 22.252-24.016 31.83-37.020-11.438 1.8-23.16 2.746-35.104 2.746zM224 640c-123.71 0-224-100.29-224-224 0-123.712 100.29-224 224-224s224 100.288 224 224l1 32c0 247.424-200.576 448-448 448v-128c85.474 0 165.834-33.286 226.274-93.726 11.636-11.636 22.254-24.016 31.832-37.020-11.44 1.8-23.16 2.746-35.106 2.746z"
                ></path>
              </svg>
              <span class="home-text01">
                <span class="home-text02">Making System Calls Cool Again</span>
                <br />
              </span>
            </header>
            <span class="home-text04">
              <span>
                Ever wondered about the name &quot;Strace&quot;? It&apos;s an
                abbreviation for &quot;system call trace,&quot; functioning like a
                digital detective that tracks a program&apos;s journey through the
                operating system.
              </span>
              <br />
              <br />
              <span>
                Why &quot;Strace&quot;? It signals our interest in understanding
                how machines communicate, providing insight into the realm of tech
                processes. So, when you encounter &quot;Strace,&quot; think of our
                commitment to unravel the language of software, exploring the
                intricacies of technology one step at a time.
              </span>
            </span>
            <h1 class="home-text09">Member of Strace</h1>
            <div class="home-members">
              <div class="home-ariff">
                <img
                  alt="GIF"
                  src="https://media.tenor.com/HXB5IotN6TcAAAAM/cat-war.gif"
                  class="home-image"
                />
                <span class="home-text10">
                  <span class="home-text11">Muhammad Ariff Ridzlan</span>
                  <br />
                  <span>1234001234</span>
                  <br />
                </span>
              </div>
              <div class="home-nabil">
                <img
                  alt="image"
                  src="https://media.tenor.com/HXB5IotN6TcAAAAM/cat-war.gif"
                  class="home-image1"
                />
                <span class="home-text15">
                  <span class="home-text16">Muhammad Nabil Irfan</span>
                  <br />
                  <span>1234001234</span>
                </span>
              </div>
              <div class="home-med">
                <img
                  alt="image"
                  src="https://media.tenor.com/HXB5IotN6TcAAAAM/cat-war.gif"
                  class="home-image2"
                />
                <span class="home-text19">
                  <span class="home-text20">Muhammad Hafiz</span>
                  <br />
                  <span>1234001234</span>
                </span>
              </div>
              <div class="home-alia">
                <img
                  alt="image"
                  src="https://media.tenor.com/HXB5IotN6TcAAAAM/cat-war.gif"
                  class="home-image3"
                />
                <span class="home-text23">
                  <span class="home-text24">Noor Alia Alisa</span>
                  <br />
                  <span>1234001234</span>
                  <br />
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <footer class="home-footer">
      <div class="home-container4">
        <router-link to="/strace" class="home-navlink">STRACE</router-link>
      </div>
      <span class="home-text28">&quot;Making System Calls Cool Again&quot;</span>
      <div class="home-icon-group">
        <svg viewBox="0 0 877.7142857142857 1024" class="home-icon2">
          <path
            d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
          ></path>
        </svg>
      </div>
    </footer>
    <app-header></app-header>
  </div>
</template>

<script>
import AppHeader from '../components/header'

export default {
  name: 'Home',
  props: {},
  components: {
    AppHeader,
  },
  metaInfo: {
    title: 'Strace | Home',
    meta: [
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ],
  },
}
</script>

<style scoped>
.home-container {
  width: 100%;
  display: flex;
  overflow: auto;
  min-height: 100vh;
  align-items: center;
  flex-direction: column;
  justify-content: flex-start;
  background-color: #f5f5f5;
}
.home-banner {
  width: 100%;
  height: 275px;
  display: flex;
  align-items: center;
  flex-direction: column;
  background-size: cover;
  justify-content: center;
  background-image: url('https://marketplace.canva.com/EAD2962NKnQ/2/0/1600w/canva-rainbow-gradient-pink-and-purple-virtual-background-_Tcjok-d9b4.jpg');
}
.home-container1 {
  flex: 0 0 auto;
  width: 200px;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.home-container2 {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.home-container3 {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.home-testimonial-card {
  display: flex;
  padding: var(--dl-space-space-twounits);
  max-width: var(--dl-size-size-maxwidth);
  align-items: center;
  flex-direction: column;
}
.home-text {
  color: #ffffff;
  font-size: 3rem;
  align-self: center;
  margin-top: 15px;
  text-align: center;
}
.home-icon {
  width: var(--dl-size-size-small);
  margin-bottom: var(--dl-space-space-twounits);
}
.home-text01 {
  color: var(--dl-color-gray-500);
  font-size: 1.25rem;
  text-align: center;
  margin-bottom: var(--dl-space-space-threeunits);
}
.home-text02 {
  text-align: center;
}
.home-members {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
}
.home-ariff {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.home-image {
  width: 200px;
  object-fit: cover;
}
.home-nabil {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.home-image1 {
  width: 200px;
  object-fit: cover;
}
.home-med {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.home-image2 {
  width: 200px;
  object-fit: cover;
}
.home-alia {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.home-image3 {
  width: 200px;
  object-fit: cover;
}
.home-footer {
  width: 100%;
  display: flex;
  max-width: var(--dl-size-size-maxwidth);
  align-self: center;
  align-items: center;
  padding-top: var(--dl-space-space-twounits);
  padding-left: var(--dl-space-space-threeunits);
  padding-right: var(--dl-space-space-threeunits);
  padding-bottom: var(--dl-space-space-twounits);
  justify-content: space-between;
}
.home-container4 {
  flex: 0 0 auto;
  width: auto;
  height: auto;
  display: flex;
  align-items: space-between;
  flex-direction: column;
}
.home-navlink {
  font-weight: 700;
  text-decoration: none;
}
.home-icon2 {
  width: 24px;
  height: 24px;
}
@media(max-width: 1600px) {
  .home-container {
    background-color: #ffffff;
  }
  .home-banner {
    height: 1325px;
    opacity: 1;
    position: relative;
    background-size: cover;
    justify-content: center;
    background-image: url("/external/bglandscape-1100w.jpg");
  }
  .home-container1 {
    flex: 1;
    width: 1200px;
    height: auto;
    padding-bottom: 0px;
    justify-content: center;
  }
  .home-container2 {
    flex: 1;
    height: auto;
    align-items: center;
    justify-content: center;
  }
  .home-container3 {
    flex: 1;
    width: 1200px;
    height: auto;
    align-self: flex-start;
    box-shadow: 0px 0px 10px 0px #d3d2d6;
    margin-top: 150px;
    align-items: flex-start;
    border-radius: var(--dl-radius-radius-radius8);
    justify-content: center;
    background-color: #ffffff;
    border-top-left-radius: var(--dl-radius-radius-radius8);
    border-top-right-radius: var(--dl-radius-radius-radius8);
  }
  .home-testimonial-card {
    width: 100%;
  }
  .home-text {
    color: #ffffff;
    width: 1050px;
    height: auto;
    opacity: 1;
    font-size: 5rem;
    align-self: center;
    font-style: normal;
    margin-top: 10px;
    font-family: Montserrat;
    font-weight: 700;
    line-height: 1;
    padding-top: 40px;
    border-radius: var(--dl-radius-radius-radius4);
    margin-bottom: 50px;
    padding-bottom: 40px;
    background-size: cover;
    background-image: url("/external/bglandscape-1100w.jpg");
    background-repeat: no-repeat;
    background-position: bottom left;
  }
  .home-text01 {
    color: var(--dl-color-gray-500);
    font-size: 2rem;
    font-style: italic;
    font-family: Inter;
    font-weight: 400;
    margin-bottom: var(--dl-space-space-unit);
  }
  .home-text04 {
    color: #000000;
    font-size: 20px;
    font-style: normal;
    margin-top: 30px;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 100px;
    margin-right: 100px;
    margin-bottom: 30px;
  }
  .home-text09 {
    font-size: 3em;
    align-self: center;
    font-style: normal;
    margin-top: 50px;
    font-family: Montserrat;
    font-weight: 700;
    margin-bottom: 50px;
  }
  .home-members {
    margin-bottom: 30px;
    padding-bottom: 25px;
  }
  .home-ariff {
    margin-bottom: 0px;
  }
  .home-image {
    margin-left: 25px;
    margin-right: 25px;
    border-radius: var(--dl-radius-radius-round);
    margin-bottom: 25px;
  }
  .home-text10 {
    font-size: 16px;
    align-self: center;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    line-height: 1.15;
  }
  .home-text11 {
    align-self: center;
    font-weight: 700;
  }
  .home-nabil {
    margin-bottom: 0px;
  }
  .home-image1 {
    margin-left: 25px;
    margin-right: 25px;
    border-radius: var(--dl-radius-radius-round);
    margin-bottom: 25px;
  }
  .home-text15 {
    font-size: 16px;
    align-self: center;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
  }
  .home-text16 {
    font-weight: 700;
  }
  .home-med {
    margin-bottom: 0px;
  }
  .home-image2 {
    margin-left: 25px;
    margin-right: 25px;
    border-radius: var(--dl-radius-radius-round);
    margin-bottom: 25px;
  }
  .home-text19 {
    font-size: 16px;
    align-self: center;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
  }
  .home-text20 {
    font-weight: 700;
  }
  .home-alia {
    margin-bottom: 0px;
  }
  .home-image3 {
    margin-left: 25px;
    margin-right: 25px;
    border-radius: var(--dl-radius-radius-round);
    margin-bottom: 25px;
  }
  .home-text23 {
    font-size: 16px;
    align-self: center;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.15;
  }
  .home-text24 {
    align-self: center;
    font-weight: 700;
  }
  .home-footer {
    justify-content: space-between;
  }
  .home-navlink {
    font-size: 16px;
    font-family: Montserrat;
    font-weight: 700;
    text-decoration: none;
  }
  .home-text28 {
    font-size: 16px;
    font-style: normal;
    font-family: Montserrat;
    font-weight: 500;
  }
  .home-icon2 {
    margin-left: 50px;
  }
}
@media(max-width: 1200px) {
  .home-banner {
    position: relative;
  }
  .home-text {
    font-size: 4rem;
  }
}
@media(max-width: 767px) {
  .home-icon {
    height: var(--dl-size-size-small);
  }
}
@media(max-width: 479px) {
  .home-testimonial-card {
    padding-left: var(--dl-space-space-unit);
    padding-right: var(--dl-space-space-unit);
  }
  .home-footer {
    align-self: center;
  }
  .home-icon-group {
    display: none;
  }
}
</style>

// [Angular] Website Source Code/src/app/pages/home/home.component.ts
import { Component } from '@angular/core'
import { Title, Meta } from '@angular/platform-browser'

@Component({
  selector: 'app-home',
  templateUrl: 'home.component.html',
  styleUrls: ['home.component.css'],
})
export class Home {
  constructor(private title: Title, private meta: Meta) {
    this.title.setTitle('Strace | Home')
    this.meta.addTags([
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ])
  }
}

<div class="home-container">
  <div class="home-banner">
    <div class="home-container1">
      <div class="home-container2">
        <div class="home-container3">
          <header class="home-testimonial-card">
            <h1 class="home-text">STRACE</h1>
            <svg viewBox="0 0 1024 1024" class="home-icon">
              <path
                d="M800 640c-123.712 0-224-100.29-224-224 0-123.712 100.288-224 224-224s224 100.288 224 224l1 32c0 247.424-200.576 448-448 448v-128c85.474 0 165.834-33.286 226.274-93.726 11.634-11.636 22.252-24.016 31.83-37.020-11.438 1.8-23.16 2.746-35.104 2.746zM224 640c-123.71 0-224-100.29-224-224 0-123.712 100.29-224 224-224s224 100.288 224 224l1 32c0 247.424-200.576 448-448 448v-128c85.474 0 165.834-33.286 226.274-93.726 11.636-11.636 22.254-24.016 31.832-37.020-11.44 1.8-23.16 2.746-35.106 2.746z"
              ></path>
            </svg>
            <span class="home-text01">
              <span class="home-text02">Making System Calls Cool Again</span>
              <br />
            </span>
          </header>
          <span class="home-text04">
            <span>
              Ever wondered about the name &quot;Strace&quot;? It&apos;s an
              abbreviation for &quot;system call trace,&quot; functioning like a
              digital detective that tracks a program&apos;s journey through the
              operating system.
            </span>
            <br />
            <br />
            <span>
              Why &quot;Strace&quot;? It signals our interest in understanding
              how machines communicate, providing insight into the realm of tech
              processes. So, when you encounter &quot;Strace,&quot; think of our
              commitment to unravel the language of software, exploring the
              intricacies of technology one step at a time.
            </span>
          </span>
          <h1 class="home-text09">Member of Strace</h1>
          <div class="home-members">
            <div class="home-ariff">
              <img
                alt="GIF"
                src="https://media.tenor.com/HXB5IotN6TcAAAAM/cat-war.gif"
                class="home-image"
              />
              <span class="home-text10">
                <span class="home-text11">Muhammad Ariff Ridzlan</span>
                <br />
                <span>1234001234</span>
                <br />
              </span>
            </div>
            <div class="home-nabil">
              <img
                alt="image"
                src="https://media.tenor.com/HXB5IotN6TcAAAAM/cat-war.gif"
                class="home-image1"
              />
              <span class="home-text15">
                <span class="home-text16">Muhammad Nabil Irfan</span>
                <br />
                <span>1234001234</span>
              </span>
            </div>
            <div class="home-med">
              <img
                alt="image"
                src="https://media.tenor.com/HXB5IotN6TcAAAAM/cat-war.gif"
                class="home-image2"
              />
              <span class="home-text19">
                <span class="home-text20">Muhammad Hafiz</span>
                <br />
                <span>1234001234</span>
              </span>
            </div>
            <div class="home-alia">
              <img
                alt="image"
                src="https://media.tenor.com/HXB5IotN6TcAAAAM/cat-war.gif"
                class="home-image3"
              />
              <span class="home-text23">
                <span class="home-text24">Noor Alia Alisa</span>
                <br />
                <span>1234001234</span>
                <br />
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <footer class="home-footer">
    <div class="home-container4">
      <a routerLink="/strace" class="home-navlink">STRACE</a>
    </div>
    <span class="home-text28">&quot;Making System Calls Cool Again&quot;</span>
    <div class="home-icon-group">
      <svg viewBox="0 0 877.7142857142857 1024" class="home-icon2">
        <path
          d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
        ></path>
      </svg>
    </div>
  </footer>
  <app-header></app-header>
</div>
