// [Vue] Website Source Code/src/views/basic-py-2e.vue
<template>
  <div class="basic-py2e-container">
    <div class="basic-py2e-banner">
      <div class="basic-py2e-main-content">
        <h1 class="basic-py2e-heading">EXPRESSIONS AND ASSIGNMENT</h1>
        <div class="basic-py2e-container1">
          <router-link to="/basic-py-2a" class="basic-py2e-navlink button">
            Arithmetic Expressions
          </router-link>
          <router-link to="/basic-py-2b" class="basic-py2e-navlink1 button">
            Functional Side Effects
          </router-link>
          <router-link to="/basic-py-2ci" class="basic-py2e-navlink2 button">
            Overloaded Operators
          </router-link>
          <router-link to="/basic-py-2cii" class="basic-py2e-navlink3 button">
            Type Conversions
          </router-link>
        </div>
        <div class="basic-py2e-container2">
          <router-link to="/basic-py-2d" class="basic-py2e-navlink4 button">
            Relational and Boolean Expressions
          </router-link>
          <router-link to="/basic-py-2e" class="basic-py2e-navlink5 button">
            Short-Circuit Evaluation
          </router-link>
          <router-link to="/basic-py-2f" class="basic-py2e-navlink6 button">
            Assignment Statements
          </router-link>
          <router-link to="/basic-py-2g" class="basic-py2e-navlink7 button">
            Mixed-Mode Assignment
          </router-link>
        </div>
        <div class="basic-py2e-short-circuit">
          <h1 class="basic-py2e-text">
            <span>Short-Circuit Evaluation</span>
            <br />
          </h1>
          <div class="basic-py2e-row">
            <span class="basic-py2e-text03">
              <span>
                For
                <span v-html="rawrbk9"></span>
              </span>
              <span class="basic-py2e-text05">all logical operators</span>
              <span>
                in Python,
                <span v-html="rawsi1q"></span>
              </span>
              <span class="basic-py2e-text07">short-circuit is evaluated</span>
              <span>
                if the outcomes has been determined. The reason is to avoid
                unnecessary evaluations if the final result of the Boolean
                expression has been decided at the beginning.
              </span>
              <br />
              <br />
              <span>
                Referring to the source code given, short-circuit can be executed.
              </span>
              <br />
              <br />
              <span class="basic-py2e-text14">Logical AND operator</span>
              <br />
              <span>
                In the
                <span v-html="rawzynf"></span>
              </span>
              <span class="basic-py2e-text17">
                if
                <span v-html="raw0lyx"></span>
              </span>
              <span>
                statement,
                <span v-html="raw7cyv"></span>
              </span>
              <span class="basic-py2e-text19">formset.is_valid()</span>
              <span>
                will not execute if
                <span v-html="raw8x73"></span>
              </span>
              <span class="basic-py2e-text21">form.is_valid()</span>
              <span>is FALSE.</span>
              <br />
              <br />
              <span class="basic-py2e-text25">Logical OR operator</span>
              <br />
              <span>
                For assigning variable
                <span v-html="rawicdo"></span>
              </span>
              <span class="basic-py2e-text28">
                form
                <span v-html="raw70sp"></span>
              </span>
              <span>
                after
                <span v-html="raw1c3o"></span>
              </span>
              <span class="basic-py2e-text30">
                if
                <span v-html="raw12cc"></span>
              </span>
              <span>
                statement,
                <span v-html="rawnng3"></span>
              </span>
              <span class="basic-py2e-text32">
                None
                <span v-html="raws6kx"></span>
              </span>
              <span>
                will not evaluated if
                <span v-html="rawgn5d"></span>
              </span>
              <span class="basic-py2e-text34">request.GET</span>
              <span>is TRUE.</span>
              <br />
            </span>
            <img
              alt="pastedImage"
              src="/external/expr-short-circuit-700w.png"
              class="basic-py2e-pasted-image"
            />
          </div>
          <span class="basic-py2e-text37">
            <span>
              -
              <span v-html="rawvazc"></span>
            </span>
            <span class="basic-py2e-text39">Muhammad Ariff Ridzlan</span>
          </span>
        </div>
      </div>
    </div>
    <div class="basic-py2e-reference">
      <h1 class="basic-py2e-text40">References</h1>
      <span class="basic-py2e-text41">
        <br />
        <span>
          Prabhu, T. N. (2020, June 5).
          <span v-html="rawdxis"></span>
        </span>
        <span class="basic-py2e-text44">
          Python Operators from Scratch!!! — A Beginner’s Guide
        </span>
        <span>. Medium.</span>
        <br />
        <span>
                   
          <span v-html="rawuihq"></span>
        </span>
        <a
          href="https://Prabhu, T. N. (2020, June 5). Python Operators from Scratch!!! — A Beginner’s Guide. Medium. https://towardsdatascience.com/python-operators-from-scratch-a-beginners-guide-8471306f4278"
          target="_blank"
          rel="noreferrer noopener"
          class="basic-py2e-link"
        >
          https://towardsdatascience.com/python-operators-from-scratch-a-beginners-guide-8471306f4278
        </a>
        <br />
        <br />
        <span>
          Datta, S. (2022, March 22).
          <span v-html="raw6grv"></span>
        </span>
        <span class="basic-py2e-text51">
          Python Operator – Logical Operators in Python
        </span>
        <span>. freeCodeCamp.org.</span>
        <br />
        <span>
                   
          <span v-html="raw6wt0"></span>
        </span>
        <a
          href="https://Datta, S. (2022, March 22). Python Operator – Logical Operators in Python. freeCodeCamp.org. Retrieved December 24, 2023, from https://www.freecodecamp.org/news/operators-in-python-how-to-use-logical-operators-in-python/"
          target="_blank"
          rel="noreferrer noopener"
          class="basic-py2e-link1"
        >
          https://www.freecodecamp.org/news/operators-in-python-how-to-use-logical-operators-in-python/
        </a>
        <br />
      </span>
    </div>
    <footer class="basic-py2e-footer">
      <div class="basic-py2e-container3">
        <router-link to="/strace" class="basic-py2e-navlink8">STRACE</router-link>
      </div>
      <span class="basic-py2e-text56">
        &quot;Making System Calls Cool Again&quot;
      </span>
      <div class="basic-py2e-icon-group">
        <svg viewBox="0 0 877.7142857142857 1024" class="basic-py2e-icon">
          <path
            d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
          ></path>
        </svg>
      </div>
    </footer>
    <app-header></app-header>
  </div>
</template>

<script>
import AppHeader from '../components/header'

export default {
  name: 'BasicPy2e',
  props: {},
  components: {
    AppHeader,
  },
  data() {
    return {
      rawrbk9: ' ',
      rawsi1q: ' ',
      rawzynf: ' ',
      raw0lyx: ' ',
      raw7cyv: ' ',
      raw8x73: ' ',
      rawicdo: ' ',
      raw70sp: ' ',
      raw1c3o: ' ',
      raw12cc: ' ',
      rawnng3: ' ',
      raws6kx: ' ',
      rawgn5d: ' ',
      rawvazc: ' ',
      rawdxis: ' ',
      rawuihq: ' ',
      raw6grv: ' ',
      raw6wt0: ' ',
    }
  },
  metaInfo: {
    title: 'Strace | Basic Python',
    meta: [
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ],
  },
}
</script>

<style scoped>
.basic-py2e-container {
  width: 100%;
  display: flex;
  overflow: auto;
  min-height: 100vh;
  align-items: center;
  flex-direction: column;
  justify-content: flex-start;
  background-color: #f5f5f5;
}
.basic-py2e-banner {
  width: 100%;
  height: 275px;
  display: flex;
  transition: 0.3s;
  align-items: center;
  flex-direction: column;
  background-size: cover;
  justify-content: center;
  background-image: url('https://marketplace.canva.com/EAD2962NKnQ/2/0/1600w/canva-rainbow-gradient-pink-and-purple-virtual-background-_Tcjok-d9b4.jpg');
}

.basic-py2e-main-content {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: flex-start;
  background-color: #ffffff;
}
.basic-py2e-heading {
  color: #ff0000;
  font-size: 3rem;
  align-self: center;
  text-align: center;
}
.basic-py2e-container1 {
  flex: 0 0 auto;
  width: 100%;
  height: 100px;
  display: flex;
  align-items: flex-start;
}
.basic-py2e-navlink {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2e-navlink:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2e-navlink1 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2e-navlink1:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2e-navlink2 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2e-navlink2:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2e-navlink3 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2e-navlink3:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2e-container2 {
  flex: 0 0 auto;
  width: 100%;
  height: 100px;
  display: flex;
  align-items: flex-start;
}
.basic-py2e-navlink4 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2e-navlink4:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2e-navlink5 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2e-navlink5:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2e-navlink6 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2e-navlink6:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2e-navlink7 {
  transition: 0.3s;
  text-decoration: none;
}
.basic-py2e-navlink7:hover {
  color: #a068ff;
  font-style: normal;
  font-weight: 500;
  background-color: rgba(0, 0, 0, 0.75);
}
.basic-py2e-short-circuit {
  flex: 0 0 auto;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
}
.basic-py2e-row {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: flex-start;
}
.basic-py2e-text03 {
  text-align: justify;
}
.basic-py2e-reference {
  flex: 0 0 auto;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #ffffff;
}
.basic-py2e-footer {
  width: 100%;
  display: flex;
  max-width: var(--dl-size-size-maxwidth);
  align-self: center;
  align-items: center;
  padding-top: var(--dl-space-space-twounits);
  padding-left: var(--dl-space-space-threeunits);
  padding-right: var(--dl-space-space-threeunits);
  padding-bottom: var(--dl-space-space-twounits);
  justify-content: space-between;
}
.basic-py2e-container3 {
  flex: 0 0 auto;
  width: auto;
  height: auto;
  display: flex;
  align-items: space-between;
  flex-direction: column;
}
.basic-py2e-navlink8 {
  font-weight: 700;
  text-decoration: none;
}
.basic-py2e-icon {
  width: 24px;
  height: 24px;
}
@media(max-width: 1600px) {
  .basic-py2e-container {
    background-color: #f7f7f7;
  }
  .basic-py2e-banner {
    height: auto;
    align-items: center;
    background-size: cover;
    justify-content: flex-start;
    background-image: url("/external/bgportrait-1500w.jpg");
  }
  .basic-py2e-main-content {
    flex: 1;
    width: 1300px;
    height: auto;
    box-shadow: 0px 0px 10px 0px #d3d2d6;
    align-items: flex-start;
    padding-top: 100px;
    flex-direction: column;
    justify-content: flex-start;
    background-color: #ffffff;
  }
  .basic-py2e-heading {
    color: rgb(255, 255, 255);
    width: 1200px;
    height: auto;
    font-size: 64px;
    font-style: normal;
    margin-top: 40px;
    font-family: Montserrat;
    font-weight: 700;
    line-height: 1.15;
    padding-top: 40px;
    border-radius: var(--dl-radius-radius-radius4);
    margin-bottom: 20px;
    padding-bottom: 40px;
    background-size: auto;
    background-image: url("/external/bglandscape-1200w.jpg");
  }
  .basic-py2e-container1 {
    width: 700px;
    height: auto;
    align-self: center;
    margin-left: 50px;
    padding-top: 20px;
    margin-right: 50px;
    padding-bottom: 10px;
    justify-content: center;
  }
  .basic-py2e-navlink {
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2e-navlink1 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2e-navlink2 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2e-navlink3 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2e-container2 {
    width: 800px;
    height: auto;
    align-self: center;
    margin-left: 50px;
    padding-top: 10px;
    margin-right: 50px;
    padding-bottom: 20px;
    justify-content: center;
  }
  .basic-py2e-navlink4 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2e-navlink5 {
    color: #A068FF;
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2e-navlink6 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    margin-right: 25px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2e-navlink7 {
    color: rgb(0, 0, 0);
    font-size: 16px;
    font-style: normal;
    text-align: center;
    font-family: Inter;
    font-weight: 500;
    line-height: 1.15;
    margin-left: 25px;
    border-width: 1px;
    text-decoration: none;
    background-color: rgb(255, 255, 255);
  }
  .basic-py2e-short-circuit {
    width: 1200px;
    align-items: flex-end;
    margin-left: 50px;
    padding-top: 50px;
    margin-right: 50px;
    padding-bottom: 50px;
  }
  .basic-py2e-text {
    font-size: 36px;
    align-self: flex-start;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
    padding-top: 0px;
    padding-left: 0px;
    padding-right: 0px;
    padding-bottom: 30px;
  }
  .basic-py2e-row {
    margin-bottom: 30px;
    justify-content: space-between;
  }
  .basic-py2e-text03 {
    font-size: 16px;
    align-self: center;
    font-style: normal;
    text-align: justify;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.25;
    padding-right: var(--dl-space-space-fourunits);
  }
  .basic-py2e-text05 {
    font-weight: 700;
  }
  .basic-py2e-text07 {
    font-weight: 700;
  }
  .basic-py2e-text14 {
    font-weight: 700;
  }
  .basic-py2e-text17 {
    font-style: italic;
  }
  .basic-py2e-text19 {
    font-style: italic;
  }
  .basic-py2e-text21 {
    font-style: italic;
  }
  .basic-py2e-text25 {
    font-weight: 700;
  }
  .basic-py2e-text28 {
    font-style: italic;
  }
  .basic-py2e-text30 {
    font-style: italic;
  }
  .basic-py2e-text32 {
    font-style: italic;
  }
  .basic-py2e-text34 {
    font-style: italic;
  }
  .basic-py2e-pasted-image {
    width: 611px;
    height: 365px;
    border-radius: var(--dl-radius-radius-radius4);
  }
  .basic-py2e-text37 {
    font-size: 18px;
    font-style: normal;
    font-family: Inter;
    font-weight: 500;
    padding-top: 25px;
  }
  .basic-py2e-text39 {
    font-style: italic;
  }
  .basic-py2e-reference {
    width: 1600px;
    height: auto;
    align-self: center;
    box-shadow: 0px -1px 15px 0px #ebebeb;
    align-items: flex-start;
    padding-top: 50px;
    padding-left: 200px;
    padding-right: 200px;
    flex-direction: column;
    padding-bottom: 50px;
    justify-content: flex-start;
  }
  .basic-py2e-text40 {
    font-size: 32px;
    font-style: normal;
    font-family: Inter;
    font-weight: 700;
  }
  .basic-py2e-text41 {
    font-size: 16px;
    font-style: normal;
    font-family: Inter;
    font-weight: 400;
    line-height: 1.25;
  }
  .basic-py2e-text44 {
    font-style: italic;
  }
  .basic-py2e-link {
    color: var(--dl-color-primary-300);
    text-decoration: underline;
  }
  .basic-py2e-text51 {
    font-style: italic;
  }
  .basic-py2e-link1 {
    color: var(--dl-color-primary-300);
    text-decoration: underline;
  }
  .basic-py2e-footer {
    justify-content: space-between;
  }
  .basic-py2e-navlink8 {
    font-size: 16px;
    font-family: Montserrat;
    font-weight: 700;
    text-decoration: none;
  }
  .basic-py2e-text56 {
    font-size: 16px;
    font-style: normal;
    font-family: Montserrat;
    font-weight: 500;
  }
  .basic-py2e-icon {
    margin-left: 50px;
  }
}
@media(max-width: 1200px) {
  .basic-py2e-heading {
    color: rgb(255, 255, 255);
  }
}
@media(max-width: 479px) {
  .basic-py2e-footer {
    align-self: center;
  }
  .basic-py2e-icon-group {
    display: none;
  }
}
</style>

// [Angular] Website Source Code/src/app/pages/basic-py-2e/basic-py-2e.component.ts
import { Component } from '@angular/core'
import { Title, Meta } from '@angular/platform-browser'

@Component({
  selector: 'basic-py2e',
  templateUrl: 'basic-py-2e.component.html',
  styleUrls: ['basic-py-2e.component.css'],
})
export class BasicPy2e {
  rawr15c: string = ' '
  rawqfny: string = ' '
  rawnpql: string = ' '
  rawico4: string = ' '
  rawyl07: string = ' '
  raw9avz: string = ' '
  rawklt8: string = ' '
  rawoxp8: string = ' '
  rawdru0: string = ' '
  rawpddo: string = ' '
  rawyxdx: string = ' '
  rawe4lk: string = ' '
  raw6iet: string = ' '
  rawr9ym: string = ' '
  rawvgrk: string = ' '
  rawngjc: string = ' '
  raw29v6: string = ' '
  rawh6nr: string = ' '
  constructor(private title: Title, private meta: Meta) {
    this.title.setTitle('Strace | Basic Python')
    this.meta.addTags([
      {
        name: 'description',
        content: 'TPL6213 Project',
      },
      {
        property: 'og:title',
        content: 'Strace',
      },
      {
        property: 'og:description',
        content: 'TPL6213 Project',
      },
    ])
  }
}

<div class="basic-py2e-container">
  <div class="basic-py2e-banner">
    <div class="basic-py2e-main-content">
      <h1 class="basic-py2e-heading">EXPRESSIONS AND ASSIGNMENT</h1>
      <div class="basic-py2e-container1">
        <a routerLink="/basic-py-2a" class="basic-py2e-navlink button">
          Arithmetic Expressions
        </a>
        <a routerLink="/basic-py-2b" class="basic-py2e-navlink1 button">
          Functional Side Effects
        </a>
        <a routerLink="/basic-py-2ci" class="basic-py2e-navlink2 button">
          Overloaded Operators
        </a>
        <a routerLink="/basic-py-2cii" class="basic-py2e-navlink3 button">
          Type Conversions
        </a>
      </div>
      <div class="basic-py2e-container2">
        <a routerLink="/basic-py-2d" class="basic-py2e-navlink4 button">
          Relational and Boolean Expressions
        </a>
        <a routerLink="/basic-py-2e" class="basic-py2e-navlink5 button">
          Short-Circuit Evaluation
        </a>
        <a routerLink="/basic-py-2f" class="basic-py2e-navlink6 button">
          Assignment Statements
        </a>
        <a routerLink="/basic-py-2g" class="basic-py2e-navlink7 button">
          Mixed-Mode Assignment
        </a>
      </div>
      <div class="basic-py2e-short-circuit">
        <h1 class="basic-py2e-text">
          <span>Short-Circuit Evaluation</span>
          <br />
        </h1>
        <div class="basic-py2e-row">
          <span class="basic-py2e-text03">
            <span>
              For
              <span [innerHTML]="rawr15c"></span>
            </span>
            <span class="basic-py2e-text05">all logical operators</span>
            <span>
              in Python,
              <span [innerHTML]="rawqfny"></span>
            </span>
            <span class="basic-py2e-text07">short-circuit is evaluated</span>
            <span>
              if the outcomes has been determined. The reason is to avoid
              unnecessary evaluations if the final result of the Boolean
              expression has been decided at the beginning.
            </span>
            <br />
            <br />
            <span>
              Referring to the source code given, short-circuit can be executed.
            </span>
            <br />
            <br />
            <span class="basic-py2e-text14">Logical AND operator</span>
            <br />
            <span>
              In the
              <span [innerHTML]="rawnpql"></span>
            </span>
            <span class="basic-py2e-text17">
              if
              <span [innerHTML]="rawico4"></span>
            </span>
            <span>
              statement,
              <span [innerHTML]="rawyl07"></span>
            </span>
            <span class="basic-py2e-text19">formset.is_valid()</span>
            <span>
              will not execute if
              <span [innerHTML]="raw9avz"></span>
            </span>
            <span class="basic-py2e-text21">form.is_valid()</span>
            <span>is FALSE.</span>
            <br />
            <br />
            <span class="basic-py2e-text25">Logical OR operator</span>
            <br />
            <span>
              For assigning variable
              <span [innerHTML]="rawklt8"></span>
            </span>
            <span class="basic-py2e-text28">
              form
              <span [innerHTML]="rawoxp8"></span>
            </span>
            <span>
              after
              <span [innerHTML]="rawdru0"></span>
            </span>
            <span class="basic-py2e-text30">
              if
              <span [innerHTML]="rawpddo"></span>
            </span>
            <span>
              statement,
              <span [innerHTML]="rawyxdx"></span>
            </span>
            <span class="basic-py2e-text32">
              None
              <span [innerHTML]="rawe4lk"></span>
            </span>
            <span>
              will not evaluated if
              <span [innerHTML]="raw6iet"></span>
            </span>
            <span class="basic-py2e-text34">request.GET</span>
            <span>is TRUE.</span>
            <br />
          </span>
          <img
            alt="pastedImage"
            src="/assets/external/expr-short-circuit-700w.png"
            class="basic-py2e-pasted-image"
          />
        </div>
        <span class="basic-py2e-text37">
          <span>
            -
            <span [innerHTML]="rawr9ym"></span>
          </span>
          <span class="basic-py2e-text39">Muhammad Ariff Ridzlan</span>
        </span>
      </div>
    </div>
  </div>
  <div class="basic-py2e-reference">
    <h1 class="basic-py2e-text40">References</h1>
    <span class="basic-py2e-text41">
      <br />
      <span>
        Prabhu, T. N. (2020, June 5).
        <span [innerHTML]="rawvgrk"></span>
      </span>
      <span class="basic-py2e-text44">
        Python Operators from Scratch!!! — A Beginner’s Guide
      </span>
      <span>. Medium.</span>
      <br />
      <span>
                 
        <span [innerHTML]="rawngjc"></span>
      </span>
      <a
        href="https://Prabhu, T. N. (2020, June 5). Python Operators from Scratch!!! — A Beginner’s Guide. Medium. https://towardsdatascience.com/python-operators-from-scratch-a-beginners-guide-8471306f4278"
        target="_blank"
        rel="noreferrer noopener"
        class="basic-py2e-link"
      >
        https://towardsdatascience.com/python-operators-from-scratch-a-beginners-guide-8471306f4278
      </a>
      <br />
      <br />
      <span>
        Datta, S. (2022, March 22).
        <span [innerHTML]="raw29v6"></span>
      </span>
      <span class="basic-py2e-text51">
        Python Operator – Logical Operators in Python
      </span>
      <span>. freeCodeCamp.org.</span>
      <br />
      <span>
                 
        <span [innerHTML]="rawh6nr"></span>
      </span>
      <a
        href="https://Datta, S. (2022, March 22). Python Operator – Logical Operators in Python. freeCodeCamp.org. Retrieved December 24, 2023, from https://www.freecodecamp.org/news/operators-in-python-how-to-use-logical-operators-in-python/"
        target="_blank"
        rel="noreferrer noopener"
        class="basic-py2e-link1"
      >
        https://www.freecodecamp.org/news/operators-in-python-how-to-use-logical-operators-in-python/
      </a>
      <br />
    </span>
  </div>
  <footer class="basic-py2e-footer">
    <div class="basic-py2e-container3">
      <a routerLink="/strace" class="basic-py2e-navlink8">STRACE</a>
    </div>
    <span class="basic-py2e-text56">
      &quot;Making System Calls Cool Again&quot;
    </span>
    <div class="basic-py2e-icon-group">
      <svg viewBox="0 0 877.7142857142857 1024" class="basic-py2e-icon">
        <path
          d="M438.857 73.143c242.286 0 438.857 196.571 438.857 438.857 0 193.714-125.714 358.286-300 416.571-22.286 4-30.286-9.714-30.286-21.143 0-14.286 0.571-61.714 0.571-120.571 0-41.143-13.714-67.429-29.714-81.143 97.714-10.857 200.571-48 200.571-216.571 0-48-17.143-86.857-45.143-117.714 4.571-11.429 19.429-56-4.571-116.571-36.571-11.429-120.571 45.143-120.571 45.143-34.857-9.714-72.571-14.857-109.714-14.857s-74.857 5.143-109.714 14.857c0 0-84-56.571-120.571-45.143-24 60.571-9.143 105.143-4.571 116.571-28 30.857-45.143 69.714-45.143 117.714 0 168 102.286 205.714 200 216.571-12.571 11.429-24 30.857-28 58.857-25.143 11.429-89.143 30.857-127.429-36.571-24-41.714-67.429-45.143-67.429-45.143-42.857-0.571-2.857 26.857-2.857 26.857 28.571 13.143 48.571 64 48.571 64 25.714 78.286 148 52 148 52 0 36.571 0.571 70.857 0.571 81.714 0 11.429-8 25.143-30.286 21.143-174.286-58.286-300-222.857-300-416.571 0-242.286 196.571-438.857 438.857-438.857zM166.286 703.429c1.143-2.286-0.571-5.143-4-6.857-3.429-1.143-6.286-0.571-7.429 1.143-1.143 2.286 0.571 5.143 4 6.857 2.857 1.714 6.286 1.143 7.429-1.143zM184 722.857c2.286-1.714 1.714-5.714-1.143-9.143-2.857-2.857-6.857-4-9.143-1.714-2.286 1.714-1.714 5.714 1.143 9.143 2.857 2.857 6.857 4 9.143 1.714zM201.143 748.571c2.857-2.286 2.857-6.857 0-10.857-2.286-4-6.857-5.714-9.714-3.429-2.857 1.714-2.857 6.286 0 10.286s7.429 5.714 9.714 4zM225.143 772.571c2.286-2.286 1.143-7.429-2.286-10.857-4-4-9.143-4.571-11.429-1.714-2.857 2.286-1.714 7.429 2.286 10.857 4 4 9.143 4.571 11.429 1.714zM257.714 786.857c1.143-3.429-2.286-7.429-7.429-9.143-4.571-1.143-9.714 0.571-10.857 4s2.286 7.429 7.429 8.571c4.571 1.714 9.714 0 10.857-3.429zM293.714 789.714c0-4-4.571-6.857-9.714-6.286-5.143 0-9.143 2.857-9.143 6.286 0 4 4 6.857 9.714 6.286 5.143 0 9.143-2.857 9.143-6.286zM326.857 784c-0.571-3.429-5.143-5.714-10.286-5.143-5.143 1.143-8.571 4.571-8 8.571 0.571 3.429 5.143 5.714 10.286 4.571s8.571-4.571 8-8z"
        ></path>
      </svg>
    </div>
  </footer>
  <app-header></app-header>
</div>
